---
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook: default
  pdf_document:
    toc: yes
---

```{r, echo=FALSE}
library(knitr)
options(scipen = F)
#This code automatically tidies code so that it does not reach over the page
opts_chunk$set(tidy.opts=list(width.cutoff=50),tidy=TRUE, rownames.print = FALSE, rows.print = 10)
```

# (PART) Lecture notes {-}

# Preliminaries

In this chapter you will learn:

* Why marketing research is important
* The marketing research process
* What type of research design is appropriate in which situation
* The difference between causality and correlation
* The primary scales of measurement
* The difference between measurement validity and reliability

## The marketing research process

* Primary vs. secondary data
* Qualitative vs. quantitative data
* Longitudinal vs. cross-sectional data
* Exploratory vs. conclusive research
* Focus on quantitative conclusive studies

## Choosing a research designs

* Determine the research objective
* Descriptive, predictive, prescriptive

### Descriptive research

### Predictive research

### Causal inference

* A.k.a. explanatory; prescriptive; counter-factual
* Role of theory ...
* Examples for spurious correlation
* Shmueli

#### Experimentation

> "To find out what happens when you change something, 
> it is necessary to change it."
>
> `r tufte::quote_footer('--- Box, Hunter, and Hunter 1978')`

* Systematic vs. unsystematic variation (the signal and the noise)
* Within vs. between subject 
* Control groups --> within vs. between

#### Observational research

* Longitudinal research; 
* Difference-in-Differences Design

## Measurement and scaling

### Levels of measurement

### Measurement accuracy

### Scaling techniques

#### Single vs. multi-item scales

#### Formative vs. reflective scales


## References {-}
