<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>07-introStatTests</title>
  <meta name="description" content="07-introStatTests">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="07-introStatTests" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="07-introStatTests" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  


<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">MRDA 2018</a></strong></li>
<li class="divider"></li>
<li class="chapter" data-level="1" data-path=""><a href="#introduction-to-statistical-inference"><i class="fa fa-check"></i><b>1</b> Introduction to Statistical Inference</a><ul>
<li class="chapter" data-level="1.1" data-path=""><a href="#if-we-knew-it-all"><i class="fa fa-check"></i><b>1.1</b> If we knew it all</a><ul>
<li class="chapter" data-level="1.1.1" data-path=""><a href="#sampling-from-a-known-population"><i class="fa fa-check"></i><b>1.1.1</b> Sampling from a known population</a></li>
<li class="chapter" data-level="1.1.2" data-path=""><a href="#standard-error-of-the-mean"><i class="fa fa-check"></i><b>1.1.2</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path=""><a href="#the-central-limit-theorem"><i class="fa fa-check"></i><b>1.2</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="1.3" data-path=""><a href="#using-what-we-actually-know"><i class="fa fa-check"></i><b>1.3</b> Using what we actually know</a><ul>
<li class="chapter" data-level="1.3.1" data-path=""><a href="#confidence-intervals-for-the-sample-mean"><i class="fa fa-check"></i><b>1.3.1</b> Confidence Intervals for the Sample Mean</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path=""><a href="#summary"><i class="fa fa-check"></i><b>1.4</b> Summary</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">07-introStatTests</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">07-introStatTests</h1>
</div>
<div id="introduction-to-statistical-inference" class="section level1">
<h1><span class="header-section-number">1</span> Introduction to Statistical Inference</h1>
<p>This chapter will provide you with a basic intuition on statistical inference. As marketing researchers we are usually faced with “imperfect” data in the sense that we cannot collect <strong>all</strong> the data we would like. Imagine you are interested in the average amount of time WU students spend listening to music every month. Ideally, we could force all WU students to fill out our survey. Realistically we will only be able to observe a small fraction of students (maybe 500 out of the <span class="math inline">\(25.000+\)</span>). With the data from this small fraction at hand, we want to make an inference about the true average listening time of all WU students. We are going to start with the assumption that we know everything. That is, we first assume that we know all WU students’ listening times and analyze the distribution of the listening time in the entire population. Subsequently, we are going to look at the uncertainty that is introduced by only knowing some of the students’ listening times (i.e., a sample from the population) and how that influences our analysis.</p>
<p><a href="./Code/06-statistical_inference%20(2).R">You can download the corresponding R-Code here</a></p>
<div id="if-we-knew-it-all" class="section level2">
<h2><span class="header-section-number">1.1</span> If we knew it all</h2>
<p>Assume there are <span class="math inline">\(25,000\)</span> students at WU and every single one has kindly provided us with the hours they listened to music in the past month. In this case, we know the true mean (<span class="math inline">\(49.93\)</span> hours) and the true standard deviation (SD = <span class="math inline">\(10.02\)</span>) and thus we can easily summarize the entire distribution. Since the data follows a normal distribution, roughly 95% of the values lie within 2 standard deviations from the mean, as the following plot shows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(latex2exp)
<span class="kw">set.seed</span>(<span class="dv">321</span>)
hours &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">25000</span>, <span class="dv">50</span>, <span class="dv">10</span>)

<span class="kw">ggplot</span>(<span class="kw">data.frame</span>(hours)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(hours), <span class="dt">bins =</span> <span class="dv">50</span>, <span class="dt">fill =</span> <span class="st">&#39;white&#39;</span>, <span class="dt">color =</span> <span class="st">&#39;black&#39;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Histogram of listening times&quot;</span>,
       <span class="dt">subtitle =</span> <span class="kw">TeX</span>(<span class="kw">sprintf</span>(<span class="st">&quot;Population mean ($</span><span class="ch">\\</span><span class="st">mu$) = %.2f; population standard deviation ($</span><span class="ch">\\</span><span class="st">sigma$) = %.2f&quot;</span>,<span class="kw">round</span>(<span class="kw">mean</span>(hours),<span class="dv">2</span>),<span class="kw">round</span>(<span class="kw">sd</span>(hours),<span class="dv">2</span>))),
       <span class="dt">y =</span> <span class="st">&#39;Number of students&#39;</span>, 
       <span class="dt">x =</span> <span class="st">&#39;Hours&#39;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="kw">mean</span>(hours), <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="kw">mean</span>(hours)<span class="op">+</span><span class="dv">2</span><span class="op">*</span><span class="kw">sd</span>(hours), <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="kw">mean</span>(hours)<span class="op">-</span><span class="dv">2</span><span class="op">*</span><span class="kw">sd</span>(hours), <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_segment</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">mean</span>(hours), <span class="dt">y =</span> <span class="dv">1100</span>, <span class="dt">yend =</span> <span class="dv">1100</span>, <span class="dt">xend =</span> (<span class="kw">mean</span>(hours) <span class="op">-</span><span class="st"> </span><span class="dv">2</span><span class="op">*</span><span class="kw">sd</span>(hours))), <span class="dt">lineend =</span> <span class="st">&quot;butt&quot;</span>, <span class="dt">linejoin =</span> <span class="st">&quot;round&quot;</span>,
     <span class="dt">size =</span> <span class="fl">0.5</span>, <span class="dt">arrow =</span> <span class="kw">arrow</span>(<span class="dt">length =</span> <span class="kw">unit</span>(<span class="fl">0.2</span>, <span class="st">&quot;inches&quot;</span>))) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_segment</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">mean</span>(hours), <span class="dt">y =</span> <span class="dv">1100</span>, <span class="dt">yend =</span> <span class="dv">1100</span>, <span class="dt">xend =</span> (<span class="kw">mean</span>(hours) <span class="op">+</span><span class="st"> </span><span class="dv">2</span><span class="op">*</span><span class="kw">sd</span>(hours))), <span class="dt">lineend =</span> <span class="st">&quot;butt&quot;</span>, <span class="dt">linejoin =</span> <span class="st">&quot;round&quot;</span>,
     <span class="dt">size =</span> <span class="fl">0.5</span>, <span class="dt">arrow =</span> <span class="kw">arrow</span>(<span class="dt">length =</span> <span class="kw">unit</span>(<span class="fl">0.2</span>, <span class="st">&quot;inches&quot;</span>))) <span class="op">+</span>
<span class="st">  </span><span class="kw">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="dt">x =</span> <span class="kw">mean</span>(hours) <span class="op">+</span><span class="st"> </span><span class="dv">28</span>, <span class="dt">y =</span> <span class="dv">1100</span>, <span class="dt">label =</span> <span class="st">&quot;Mean + 2 * SD&quot;</span> )<span class="op">+</span>
<span class="st">  </span><span class="kw">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="dt">x =</span> <span class="kw">mean</span>(hours) <span class="dv">-28</span>, <span class="dt">y =</span> <span class="dv">1100</span>, <span class="dt">label =</span> <span class="st">&quot;Mean - 2 * SD&quot;</span> )</code></pre></div>
<p><img src="07-statistical_inference_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>In this case, we refere to all WU students as <strong>the population</strong>. In general, the population is the entire group we are interested in. This group does not have to necessarily consist of people, but could also be companies, stores, animals, etc.. The parameters of the distribution of population values (in hour case: “hours”) are called population parameters. As already mentioned, we do not usually know population parameters but use inferential statistics to infer them based on our sample from the population, i.e., we measure statistics from a sample (e.g., the sample mean <span class="math inline">\(\bar x\)</span>) to estimate population parameters (the population mean <span class="math inline">\(\mu\)</span>). Here, we will use the following notation to refer to either the population parameters or the sample statistic:</p>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Sample statistic</th>
<th>Population parameter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Size</td>
<td>N</td>
<td>n</td>
</tr>
<tr class="even">
<td>Mean</td>
<td><span class="math inline">\(\bar{x} = {1 \over n}\sum_{i=1}^n x_i\)</span></td>
<td><span class="math inline">\(\mu = {1 \over N}\sum_{i=1}^N x_i\)</span></td>
</tr>
<tr class="odd">
<td>Variance</td>
<td><span class="math inline">\(s^2 = {1 \over n-1}\sum_{i=1}^n (x_i-\bar{x})^2\)</span></td>
<td><span class="math inline">\(\sigma^2 = {1 \over N}\sum_{i=1}^N (x_i-\mu)^2\)</span></td>
</tr>
<tr class="even">
<td>Standard deviation</td>
<td><span class="math inline">\(s = \sqrt{s^2}\)</span></td>
<td><span class="math inline">\(\sigma = \sqrt{\sigma^2}\)</span></td>
</tr>
<tr class="odd">
<td>Standard error</td>
<td><span class="math inline">\(SE_{\bar x} = {s \over \sqrt{n}}\)</span></td>
<td><span class="math inline">\(\sigma_{\bar x} = {\sigma \over \sqrt{n}}\)</span></td>
</tr>
</tbody>
</table>
<div id="sampling-from-a-known-population" class="section level3">
<h3><span class="header-section-number">1.1.1</span> Sampling from a known population</h3>
<p>In the first step towards a realistic research setting, let us take one sample from this population and calculate the mean listening time. We can simply sample the row numbers of students and then subset the <code>hours</code> vector with the sampled rownumbers. The <code>sample()</code> function will be used to draw a sample of size 100 from the population of 25,000 students, and one student can only be drawn once (i.e., <code>replace = FALSE</code>). The following plot shows the distribution of listening times for our sample.</p>
<p><img src="07-statistical_inference_files/figure-html/unnamed-chunk-3-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Observe that in this first draw the mean (<span class="math inline">\(\bar x =\)</span> 50.28) is quite close to the actual mean ($= $ 49.93). It seems like the sample mean is a decent estimate of the population mean. However, we could just be lucky this time and the next sample could turn out to have a different mean. Let us continue by looking at four additional random samples, consisting of 100 students each. The following plot shows the distribution of listening times for the four different samples from the population.</p>
<p><img src="07-statistical_inference_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>It becomes clear that the mean is slightly different for each sample. This is referred to as <strong>sampling variation</strong> and it is completely fine to get a slightly different mean every time we take a sample. We just need to find a way of expressing the uncertainty associated with the fact that we only have data from one sample, because in a realistic setting you are most likely only going to have access to a single sample.</p>
<p>So in order to make sure that the first draw is not just pure luck and the sample mean is in fact a good estimate for the population mean, let us take <strong>many</strong> (e.g., <span class="math inline">\(20,000\)</span>) different samples from the population. That is, we repeatedly draw 100 students randomly from the population without replacement (that is, once a student has been drawn she or he is removed from the pool and cannot be drawn again) and calculate the mean of each sample. This will show us a range within which the sample mean of any sample we take is likely going to be. We are going to store the means of all the samples in a matrix and then plot a histogram of the means to observe the likely values.</p>
<p><img src="07-statistical_inference_files/figure-html/unnamed-chunk-5-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>As you can see, on average the sample mean (“mean of sample means”) is extremely close to the population mean, despite only sampling <span class="math inline">\(100\)</span> people at a time. This distribution of sample means is also referred to as <strong>sampling distribution</strong> of the sample mean. However, there is some uncertainty, and the means are slightly different for the different samples and range from 46 to 54.64.</p>
</div>
<div id="standard-error-of-the-mean" class="section level3">
<h3><span class="header-section-number">1.1.2</span> Standard error of the mean</h3>
<p>Due to the variation in the sample means shown in our simulation, it is never possible to say exactly what the population mean is based on a single sample. However, even with a single sample we can infer a range of values within which the population mean is likely contained. In order to do so, notice that the sample means are approximately normally distributed. Another interesting fact is that the mean of sample means (i.e., 49.94) is roughly equal to the population mean (i.e., 49.93). This tells us already that generally the sample mean is a good approximation of the population mean. However, in order to make statements about the expected range of possible values, we would need to know the standard deviation of the sampling distribution. The formal representation of the standard deviation of the sample means is</p>
<p><span class="math display">\[
\sigma_{\bar x} = {\sigma \over \sqrt{n}}
\]</span></p>
<p>where <span class="math inline">\(\sigma\)</span> is the population SD and <span class="math inline">\(n\)</span> is the sample size. <span class="math inline">\(\sigma_{\bar{x}}\)</span> is referred to as the <strong>Standard Error</strong> of the mean and it expresses the variation in sample means we should expect given the number of observations in our sample and the population SD. That is, it provides a measure of how precisely we can estimate the population mean from the sample mean.</p>
<div id="sample-size" class="section level4">
<h4><span class="header-section-number">1.1.2.1</span> Sample size</h4>
<p>The first thing to notice here is that an increase in the <strong>number of observations per sample</strong> <span class="math inline">\(n\)</span> decreases the range of possible sample means (i.e., the standard error). This makes intuitive sense. Think of the two extremes: sample size <span class="math inline">\(1\)</span> and sample size <span class="math inline">\(25,000\)</span>. With a single person in the sample we do not gain a lot of information and our estimate is very uncertain, which is expressed through a larger standard deviation. Looking at the histogram at the beginning of this chapter showing the number of students for each of the listening times, clearly we would get values below <span class="math inline">\(25\)</span> or above <span class="math inline">\(75\)</span> for some samples. This is way farther away from the population mean than the minimum and the maximum of our <span class="math inline">\(100\)</span> person samples. On the other hand, if we sample every student we get the population mean every time and thus we do not have any uncertainty (assuming the population does not change). Even if we only sample, say <span class="math inline">\(24,000\)</span> people every time, we gain a lot of information about the population and the sample means would not be very different from each other since only up to <span class="math inline">\(1,000\)</span> people are potentially different in any given sample. Thus, with larger (smaller) samples, there is less (more) uncertainty that the sample is a good approximation of the entire population. The following plot shows the relationship between the sample size and the standard error. Samples of increasing size are randomly drawn from the population of WU students. You can see that the standard error is decreasing with the number of observations.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-6"></span>
<img src="07-statistical_inference_files/figure-html/unnamed-chunk-6-1.png" alt="Relationship between the sample size and the standard error" width="672" />
<p class="caption">
Figure 1.1: Relationship between the sample size and the standard error
</p>
</div>
<p>The following plots show the relationship between the sample size and the standard error in a slightly different way. The plots show the range of sample means resulting from the repeated sampling process for different sample sizes. Notice that the more students are contained in the individual samples, the less uncertainty there is when estimating the population mean from a sample (i.e., the possible values are more closely centered around the mean). So when the sample size is small, the sample mean can expected to be very different the next time we take a sample. When the sample size is large, we can expect the sample means to be more similar every time we take a sample.</p>
<p><img src="07-statistical_inference_files/figure-html/unnamed-chunk-7-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>As you can see, the standard deviation of the sample means (<span class="math inline">\(\sigma_{\bar x}\)</span>) decreases as the sample size increases as a consequence of the reduced uncertainty about the true sample mean when we take larger samples.</p>
</div>
<div id="population-standard-deviation" class="section level4">
<h4><span class="header-section-number">1.1.2.2</span> Population standard deviation</h4>
<p>A second factor determining the standard deviation of the distribution of sample means (<span class="math inline">\(\sigma_{\bar x}\)</span>) is the standard deviation associated with the population parameter (<span class="math inline">\(\sigma\)</span>). Again, looking at the extremes illustrates this well. If all WU students listened to music for approximately the same amount of time, the samples would not differ much from each other. In other words, if the standard deviation in the population is lower, we expect the standard deviation of the sample means to be lower as well. This is illustrated by the following plots.</p>
<p><img src="07-statistical_inference_files/figure-html/unnamed-chunk-8-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>In the first plot (panel A), we assume a much smaller population standard deviation (e.g., <span class="math inline">\(\sigma\)</span> = 1 instead of <span class="math inline">\(\sigma\)</span> = 10). Notice how the smaller (larger) the population standard deviation, the less (more) uncertainty there is when estimating the population mean from a sample (i.e., the possible values are more closely centered around the mean). So when the population SD is large, the sample mean can expected to be very different the next time we take a sample. When the population SD is small, we can expect the sample means to be more similar.</p>
</div>
</div>
</div>
<div id="the-central-limit-theorem" class="section level2">
<h2><span class="header-section-number">1.2</span> The Central Limit Theorem</h2>
<p>The attentive reader might have noticed that the population above was generated using a normal distribution function. It would be very restrictive if we could only analyze populations whose values are normally distributed. Furthermore, we are unable in reality to check whether the population values are normally distributed since we do not know the entire population. However, it turns out that the results generalize to many other distributions. This is described by the <strong>Central Limit Theorem</strong>.</p>
<p>The central limit theorem states that if <strong>(1)</strong> the population distribution has a mean (there are examples of distributions that don’t have a mean , but we will ignore these here), and <strong>(2)</strong> we take a large enough sample, then the sampling distribution of the sample mean is approximately normally distributed. What exactly “large enough” means depends on the setting, but the interactive element at the end of this chapter illustrates how the sample size influences how accurately we can estimate the population parameters from the sample statistics.</p>
<p>To illustrate this, let’s repeat the analysis above with a population from a gamma distribution. In the previous example, we assumed a normal distribution so it was more likely for a given student to spend around 50 hours per week listening to music. The following example depicts the case in which most students spend a similar amount of time listening to music, but there are a few students who very rarely listen to music, and some music enthusiasts with a very high level of listening time. Here is a histogram of the listening times in the population:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">321</span>)
hours &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="dv">2</span>, <span class="dt">scale =</span> <span class="dv">10</span>)
<span class="kw">ggplot</span>(<span class="kw">data.frame</span>(hours)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> hours), <span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">fill=</span><span class="st">&#39;white&#39;</span>, <span class="dt">color=</span><span class="st">&#39;black&#39;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="kw">mean</span>(hours), <span class="dt">size =</span> <span class="dv">1</span>)  <span class="op">+</span><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Histogram of listening times&quot;</span>,
       <span class="dt">subtitle =</span> <span class="kw">TeX</span>(<span class="kw">sprintf</span>(<span class="st">&quot;Population mean ($</span><span class="ch">\\</span><span class="st">mu$) = %.2f; population standard deviation ($</span><span class="ch">\\</span><span class="st">sigma$) = %.2f&quot;</span>,<span class="kw">round</span>(<span class="kw">mean</span>(hours),<span class="dv">2</span>),<span class="kw">round</span>(<span class="kw">sd</span>(hours),<span class="dv">2</span>))),
       <span class="dt">y =</span> <span class="st">&#39;Number of students&#39;</span>, 
       <span class="dt">x =</span> <span class="st">&#39;Hours&#39;</span>) </code></pre></div>
<p><img src="07-statistical_inference_files/figure-html/unnamed-chunk-9-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>The vertical black line represents the population mean (<span class="math inline">\(\mu\)</span>), which is 19.98 hours. The following plot depicts the histogram of listening times of four random samples from the population, each consisting of 100 students:</p>
<p><img src="07-statistical_inference_files/figure-html/unnamed-chunk-10-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>As in the previous example, the mean is slightly different every time we take a sample due to sampling variation. Also note that the distribution of listening times no longer follows a normal distribution as a result of the fact that we now assume a gamma distribution for the population with a positive skew (i.e., lower values more likely, higher values less likely).</p>
<p>Let’s see what happens to the distribution of sample means if we take an increasing number of samples, each drawn from the same gamma population:</p>
<p><img src="07-statistical_inference_files/figure-html/unnamed-chunk-11-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>Two things are worth noting: <strong>(1)</strong> The more (hypothetical) samples we take, the more the sampling distribution approaches a normal distribution. <strong>(2)</strong> The mean of the sampling distribution of the sample mean (<span class="math inline">\(\mu_{\bar x}\)</span>) is very similar to the population mean (<span class="math inline">\(\mu\)</span>). From this we can see that the mean of a sample is a good estimate of the population mean.</p>
<p>In summary, it is important to distinguish two types of variation: <strong>(1)</strong> For each individual sample that we may take in real life, the standard deviation (<span class="math inline">\(s\)</span>) is used to describe the <strong>natural variation</strong> in the data and the data may follow a non-normal distribution. <strong>(2)</strong> If we would (hypothetically!) repeat the study many times, the sampling distribution of the sample mean follows a normal distribution for large samples sizes (even if data from each individual study are non-normal), and the standard error (<span class="math inline">\(\sigma_{\bar x}\)</span>) is used to describe the <strong>variation between study results</strong>. This is an important feature, since many statistical tests assume that the sampling distribution is normally distributed. As we have seen, this does <strong>not</strong> mean that the data from one particular sample needs to follow a normal distribution.</p>
</div>
<div id="using-what-we-actually-know" class="section level2">
<h2><span class="header-section-number">1.3</span> Using what we actually know</h2>
<p>So far we have assumed to know the population standard deviation (<span class="math inline">\(\sigma\)</span>). This an unrealistic assumption since we do not know the entire population. The best guess for the population standard deviation we have is the sample standard deviation, denoted <span class="math inline">\(s\)</span>. Thus, the standard error of the mean is usually estimated from the sample standard deviation:</p>
<p><span class="math display">\[
\sigma_{\bar x} \approx SE_{\bar x}={s \over \sqrt{n}}
\]</span></p>
<p>Note that <span class="math inline">\(s\)</span> itself is a sample estimate of the population parameter <span class="math inline">\(\sigma\)</span>. This additional estimation introduces further uncertainty. You can see in the interactive element below that the sample SD, on average, provides a good estimate of the population SD. That is, the distribution of sample SDs that we get by drawing many samples is centered around the population value. Again, the larger the sample, the closer any given sample SD is going to be to the population parameter and we introduce less uncertainty. One conclusion is that your sample needs to be large enough to provide a reliable estimate of the population parameters. What exactly “large enough” means depends on the setting, but the interactive element illustrates how the remaining values change as a function of the sample size.</p>
<p>We will not go into detail about the importance of random samples but basically the correctness of your estimate depends crucially on having a sample at hand that actually represents the population. Unfortunately, we will usually not notice if the sample is non-random. Our statistics are still a good approximation of “a” population parameter, namely the one for the population that we actually sampled but not the one we are interested in. To illustrate this uncheck the “Random Sample” box below. The new sample will be only from the top <span class="math inline">\(50\%\)</span> music listeners (but this generalizes to different types of non-random samples).</p>
<iframe src="https://learn.wu.ac.at/shiny/imsm/clt/" style="border: none; width: 800px; height: 1265px">
</iframe>
<div id="confidence-intervals-for-the-sample-mean" class="section level3">
<h3><span class="header-section-number">1.3.1</span> Confidence Intervals for the Sample Mean</h3>
<p>When we try to estimate parameters of populations (e.g., the population mean <span class="math inline">\(\mu\)</span>) from a sample, the average value from a sample (e.g., the sample mean <span class="math inline">\(\bar x\)</span>) only provides an estimate of what the real population parameter is. The next time you collect a sample of the same size, you could get a different average. This is sampling variation and it is completely fine to get a slightly different sample mean every time we take a sample as we have see above. However, this inherent uncertainty about the true population parameter means that coming up with an exact estimate (i.e., a <strong>point estimate</strong>) for a particular population parameter is really difficult. That is why it is often informative to construct a range around that statistic (i.e., an <strong>interval estimate</strong>) that likely contains the population parameter with a certain level of confidence. That is, we construct an interval such that for a large share (say 95%) of the sample means we could potentially get, the population mean is within that interval.</p>
<p>Let us consider one random sample of 100 students from our population above.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">321</span>)
hours &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="dv">2</span>, <span class="dt">scale =</span> <span class="dv">10</span>)

<span class="kw">set.seed</span>(<span class="dv">6789</span>)
sample_size &lt;-<span class="st"> </span><span class="dv">100</span>
student_sample &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">25000</span>, <span class="dt">size =</span> sample_size, <span class="dt">replace =</span> <span class="ot">FALSE</span>)
hours_s &lt;-<span class="st"> </span>hours[student_sample]

plot2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(hours_s)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> hours_s), <span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">fill=</span><span class="st">&#39;white&#39;</span>, <span class="dt">color=</span><span class="st">&#39;black&#39;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;Hours&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="kw">aes</span>(<span class="dt">xintercept =</span> <span class="kw">mean</span>(hours_s)), <span class="dt">size=</span><span class="dv">1</span>) <span class="op">+</span>
<span class="st"> </span><span class="kw">ggtitle</span>(<span class="kw">TeX</span>(<span class="kw">sprintf</span>(<span class="st">&quot;Random sample; $n$ = %d; $</span><span class="ch">\\</span><span class="st">bar{x}$ = %.2f; $s$ = %.2f&quot;</span>,sample_size,<span class="kw">round</span>(<span class="kw">mean</span>(hours_s),<span class="dv">2</span>),<span class="kw">round</span>(<span class="kw">sd</span>(hours_s),<span class="dv">2</span>))))
plot2</code></pre></div>
<p><img src="07-statistical_inference_files/figure-html/unnamed-chunk-12-1.png" width="576" /></p>
<p>From the central limit theorem we know that the sampling distribution of the sample mean is approximately normal and we know that for the normal distribution, 95% of the values lie within about 2 standard deviations from the mean. Actually, it is not exactly 2 standard deviations from the mean. To get the exact number, we can use the quantile function for the normal distribution <code>qnorm()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qnorm</span>(<span class="fl">0.975</span>)</code></pre></div>
<pre><code>## [1] 1.959964</code></pre>
<p>We use <code>0.975</code> (and not <code>0.95</code>) to account for the probability at each end of the distribution (i.e., 2.5% at the lower end and 2.5% at the upper end). We can see that 95% of the values are roughly within 1.96 standard deviations from the mean. Since we know the sample mean (<span class="math inline">\(\bar x\)</span>) and we can estimate the standard deviation of the sampling distribution (<span class="math inline">\(\sigma_{\bar x} \approx {s \over \sqrt{n}}\)</span>), we can now easily calculate the lower and upper boundaries of our confidence interval as:</p>
<p><span class="math display">\[
CI_{lower} = {\bar x} - z_{1-{\alpha \over 2}} * \sigma_{\bar x} \\
CI_{upper} = {\bar x} + z_{1-{\alpha \over 2}} * \sigma_{\bar x}
\]</span></p>
<p>Here, <span class="math inline">\(\alpha\)</span> refers to the significance level. You can find a detailed discussion of this point at the end of the next chapter. For now, we will adopt the widely accepted significance level of 5% and set <span class="math inline">\(\alpha\)</span> to 0.05. Thus, <span class="math inline">\(\pm z_{1-{\alpha \over 2}}\)</span> gives us the z-scores (i.e., number of standard deviations from the mean) within which range 95% of the probability density lies.</p>
<p>Plugging in the values from our sample, we get:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sample_mean &lt;-<span class="st"> </span><span class="kw">mean</span>(hours_s)
se &lt;-<span class="st"> </span><span class="kw">sd</span>(hours_s)<span class="op">/</span><span class="kw">sqrt</span>(sample_size)
ci_lower &lt;-<span class="st"> </span>sample_mean <span class="op">-</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>)<span class="op">*</span>se
ci_upper &lt;-<span class="st"> </span>sample_mean <span class="op">+</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>)<span class="op">*</span>se
ci_lower</code></pre></div>
<pre><code>## [1] 18.5929</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ci_upper</code></pre></div>
<pre><code>## [1] 24.81597</code></pre>
<p>such that if we collected 100 samples and computed the mean and confidence interval for each of them, in <span class="math inline">\(95\%\)</span> of the cases, the true population mean is going to be within this interval between 18.59 and 24.82. This is illustrated in the plot below that shows the mean of the first 100 samples and their confidence intervals:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">12</span>)
samples &lt;-<span class="st"> </span><span class="dv">100</span>
hours &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="dv">2</span>, <span class="dt">scale =</span> <span class="dv">10</span>)
means &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="ot">NA</span>, <span class="dt">nrow =</span> samples)
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>samples){
  student_sample &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">25000</span>, <span class="dt">size =</span> <span class="dv">100</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)
  means[i,] &lt;-<span class="st"> </span><span class="kw">mean</span>(hours[student_sample])
}

means_sd &lt;-<span class="st"> </span><span class="kw">data.frame</span>(means, <span class="dt">lower =</span>  means <span class="op">-</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>) <span class="op">*</span><span class="st"> </span>(<span class="kw">sd</span>(hours)<span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">100</span>)), <span class="dt">upper =</span> means <span class="op">+</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>) <span class="op">*</span><span class="st"> </span>(<span class="kw">sd</span>(hours)<span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">100</span>)), <span class="dt">y =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">100</span>)
means_sd<span class="op">$</span>diff &lt;-<span class="st"> </span><span class="kw">factor</span>(<span class="kw">ifelse</span>(means_sd<span class="op">$</span>lower <span class="op">&gt;</span><span class="st"> </span><span class="kw">mean</span>(hours) <span class="op">|</span><span class="st"> </span>means_sd<span class="op">$</span>upper <span class="op">&lt;</span><span class="st"> </span><span class="kw">mean</span>(hours), <span class="st">&#39;No&#39;</span>, <span class="st">&#39;Yes&#39;</span>))

ggplot2<span class="op">::</span><span class="kw">ggplot</span>(means_sd, <span class="kw">aes</span>(<span class="dt">y =</span> y)) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">100</span>, <span class="dt">by =</span> <span class="dv">1</span>), <span class="dt">expand =</span> <span class="kw">c</span>(<span class="fl">0.005</span>,<span class="fl">0.005</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> means, <span class="dt">color =</span> diff)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_errorbarh</span>(<span class="kw">aes</span>(<span class="dt">xmin =</span> lower, <span class="dt">xmax =</span> upper, <span class="dt">color =</span> diff)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="kw">mean</span>(hours)) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_color_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;black&quot;</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">guides</span>(<span class="dt">color=</span><span class="kw">guide_legend</span>(<span class="dt">title=</span><span class="st">&quot;True mean in CI&quot;</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>()</code></pre></div>
<p><img src="07-statistical_inference_files/figure-html/unnamed-chunk-15-1.png" width="960" /></p>
<p>Note that this does <strong>not</strong> mean that for a specific sample there is a <span class="math inline">\(95\%\)</span> chance that the population mean lies within its confidence interval. The statement depends on the large number of samples we do not actually draw in a real setting. You can view the set of all possible confidence intervals similarly to the sides of a coin or a die. If we throw a coin many times, we are going to observe head roughly half of the times. This does not, however, exclude the possibility of observing tails for the first 10 throws. Similarly, any specific confidence interval might or might not include the population mean but if we take many samples on average <span class="math inline">\(95\%\)</span> of the confidence intervals are going to include the population mean.</p>
</div>
</div>
<div id="summary" class="section level2">
<h2><span class="header-section-number">1.4</span> Summary</h2>
<p>When conducting research, we are (almost) always faced with the problem of not having access to the entire group we are interested in. Therefore, we use sample properties that we have derived in this chapter to do statistical inference based on a single sample. We use statistics of the sample as well as the sample size to calculate the confidence interval of our choice (e.g. <span class="math inline">\(95\%\)</span>). In practice most of this is done for us, so you won’t need to do this by hand. With a sample at hand, we need to choose the appropriate test and a null hypothesis. How this is done will be discussed in the next chapter.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
},
"search": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
