<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>11 A tibble: 3 x 54 | Marketing Research Design &amp; Analysis 2020</title>
  <meta name="description" content="An Introduction to Data Analytics Using R" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="11 A tibble: 3 x 54 | Marketing Research Design &amp; Analysis 2020" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An Introduction to Data Analytics Using R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="11 A tibble: 3 x 54 | Marketing Research Design &amp; Analysis 2020" />
  
  <meta name="twitter:description" content="An Introduction to Data Analytics Using R" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="prev" href="survey-design-analysis.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="part"><span><b>I Course outline</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#course-motivation"><i class="fa fa-check"></i>Course motivation</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#course-structure"><i class="fa fa-check"></i>Course structure</a><ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#schedule"><i class="fa fa-check"></i>Schedule</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#grading"><i class="fa fa-check"></i>Grading</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#course-materials"><i class="fa fa-check"></i>Course materials</a><ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#main-reference"><i class="fa fa-check"></i>Main reference</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#further-readings"><i class="fa fa-check"></i>Further readings</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#discussion-forum"><i class="fa fa-check"></i>Discussion forum</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#datacamp"><i class="fa fa-check"></i>DataCamp</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#other-web-resources"><i class="fa fa-check"></i>Other web-resources</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#contact"><i class="fa fa-check"></i>Contact</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Lecture notes</b></span></li>
<li class="chapter" data-level="1" data-path="preliminaries.html"><a href="preliminaries.html"><i class="fa fa-check"></i><b>1</b> Preliminaries</a><ul>
<li class="chapter" data-level="1.1" data-path="preliminaries.html"><a href="preliminaries.html#marketing-foundations-recap"><i class="fa fa-check"></i><b>1.1</b> Marketing foundations (recap)</a></li>
<li class="chapter" data-level="1.2" data-path="preliminaries.html"><a href="preliminaries.html#the-research-process"><i class="fa fa-check"></i><b>1.2</b> The research process</a><ul>
<li class="chapter" data-level="1.2.1" data-path="preliminaries.html"><a href="preliminaries.html#research-question-and-hypothesis"><i class="fa fa-check"></i><b>1.2.1</b> Research question and hypothesis</a></li>
<li class="chapter" data-level="1.2.2" data-path="preliminaries.html"><a href="preliminaries.html#choosing-a-research-design"><i class="fa fa-check"></i><b>1.2.2</b> Choosing a research design</a></li>
<li class="chapter" data-level="1.2.3" data-path="preliminaries.html"><a href="preliminaries.html#collecting-data"><i class="fa fa-check"></i><b>1.2.3</b> Collecting data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="preliminaries.html"><a href="preliminaries.html#learning-check"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="preliminaries.html"><a href="preliminaries.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html"><i class="fa fa-check"></i><b>2</b> Getting started with R</a><ul>
<li class="chapter" data-level="2.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#how-to-download-and-install-r-and-rstudio"><i class="fa fa-check"></i><b>2.1</b> How to download and install R and RStudio</a></li>
<li class="chapter" data-level="2.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#the-r-studio-interface"><i class="fa fa-check"></i><b>2.2</b> The R Studio interface</a></li>
<li class="chapter" data-level="2.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#functions"><i class="fa fa-check"></i><b>2.3</b> Functions</a></li>
<li class="chapter" data-level="2.4" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#packages"><i class="fa fa-check"></i><b>2.4</b> Packages</a></li>
<li class="chapter" data-level="2.5" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#a-typical-r-session"><i class="fa fa-check"></i><b>2.5</b> A typical R session</a></li>
<li class="chapter" data-level="2.6" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#getting-help"><i class="fa fa-check"></i><b>2.6</b> Getting help</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-handling.html"><a href="data-handling.html"><i class="fa fa-check"></i><b>3</b> Data handling</a><ul>
<li class="chapter" data-level="3.1" data-path="data-handling.html"><a href="data-handling.html#basic-data-handling"><i class="fa fa-check"></i><b>3.1</b> Basic data handling</a><ul>
<li class="chapter" data-level="3.1.1" data-path="data-handling.html"><a href="data-handling.html#creating-objects"><i class="fa fa-check"></i><b>3.1.1</b> Creating objects</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-handling.html"><a href="data-handling.html#data-types"><i class="fa fa-check"></i><b>3.1.2</b> Data types</a></li>
<li class="chapter" data-level="3.1.3" data-path="data-handling.html"><a href="data-handling.html#data-structures"><i class="fa fa-check"></i><b>3.1.3</b> Data structures</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-handling.html"><a href="data-handling.html#data-import-and-export"><i class="fa fa-check"></i><b>3.2</b> Data import and export</a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-handling.html"><a href="data-handling.html#getting-data-for-this-course"><i class="fa fa-check"></i><b>3.2.1</b> Getting data for this course</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-handling.html"><a href="data-handling.html#import-data-created-by-other-software-packages"><i class="fa fa-check"></i><b>3.2.2</b> Import data created by other software packages</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-handling.html"><a href="data-handling.html#import-data-from-qualtrics"><i class="fa fa-check"></i><b>3.2.3</b> Import data from Qualtrics</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-handling.html"><a href="data-handling.html#export-data"><i class="fa fa-check"></i><b>3.2.4</b> Export data</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-handling.html"><a href="data-handling.html#import-data-from-the-web"><i class="fa fa-check"></i><b>3.2.5</b> Import data from the Web</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-handling.html"><a href="data-handling.html#learning-check-1"><i class="fa fa-check"></i>Learning check</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="summarizing-data.html"><a href="summarizing-data.html"><i class="fa fa-check"></i><b>4</b> Summarizing data</a><ul>
<li class="chapter" data-level="4.1" data-path="summarizing-data.html"><a href="summarizing-data.html#summary-statistics"><i class="fa fa-check"></i><b>4.1</b> Summary statistics</a><ul>
<li class="chapter" data-level="4.1.1" data-path="summarizing-data.html"><a href="summarizing-data.html#categorical-variables"><i class="fa fa-check"></i><b>4.1.1</b> Categorical variables</a></li>
<li class="chapter" data-level="4.1.2" data-path="summarizing-data.html"><a href="summarizing-data.html#continuous-variables"><i class="fa fa-check"></i><b>4.1.2</b> Continuous variables</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="summarizing-data.html"><a href="summarizing-data.html#data-visualization"><i class="fa fa-check"></i><b>4.2</b> Data visualization</a><ul>
<li class="chapter" data-level="4.2.1" data-path="summarizing-data.html"><a href="summarizing-data.html#categorical-variables-1"><i class="fa fa-check"></i><b>4.2.1</b> Categorical variables</a></li>
<li class="chapter" data-level="4.2.2" data-path="summarizing-data.html"><a href="summarizing-data.html#continuous-variables-1"><i class="fa fa-check"></i><b>4.2.2</b> Continuous variables</a></li>
<li class="chapter" data-level="4.2.3" data-path="summarizing-data.html"><a href="summarizing-data.html#saving-plots"><i class="fa fa-check"></i><b>4.2.3</b> Saving plots</a></li>
<li class="chapter" data-level="4.2.4" data-path="summarizing-data.html"><a href="summarizing-data.html#ggplot-extensions"><i class="fa fa-check"></i><b>4.2.4</b> ggplot extensions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="summarizing-data.html"><a href="summarizing-data.html#learning-check-2"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="summarizing-data.html"><a href="summarizing-data.html#references-1"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html"><i class="fa fa-check"></i><b>5</b> Introduction to Statistical Inference</a><ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#if-we-knew-it-all"><i class="fa fa-check"></i><b>5.1</b> If we knew it all</a><ul>
<li class="chapter" data-level="5.1.1" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#sampling-from-a-known-population"><i class="fa fa-check"></i><b>5.1.1</b> Sampling from a known population</a></li>
<li class="chapter" data-level="5.1.2" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>5.1.2</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>5.2</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="5.3" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#using-what-we-actually-know"><i class="fa fa-check"></i><b>5.3</b> Using what we actually know</a></li>
<li class="chapter" data-level="5.4" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#confidence-intervals-for-the-sample-mean"><i class="fa fa-check"></i><b>5.4</b> Confidence Intervals for the Sample Mean</a></li>
<li class="chapter" data-level="" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#learning-check-3"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#references-2"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>6</b> Hypothesis testing</a><ul>
<li class="chapter" data-level="6.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction-1"><i class="fa fa-check"></i><b>6.1</b> Introduction</a><ul>
<li class="chapter" data-level="6.1.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#the-null-hypothesis"><i class="fa fa-check"></i><b>6.1.1</b> The null hypothesis</a></li>
<li class="chapter" data-level="6.1.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#statistical-inference-on-a-sample"><i class="fa fa-check"></i><b>6.1.2</b> Statistical inference on a sample</a></li>
<li class="chapter" data-level="6.1.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#choosing-the-right-test"><i class="fa fa-check"></i><b>6.1.3</b> Choosing the right test</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-sample-t-test"><i class="fa fa-check"></i><b>6.2</b> One sample t-test</a></li>
<li class="chapter" data-level="6.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#comparing-two-means"><i class="fa fa-check"></i><b>6.3</b> Comparing two means</a><ul>
<li class="chapter" data-level="6.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#independent-means-t-test"><i class="fa fa-check"></i><b>6.3.1</b> Independent-means t-test</a></li>
<li class="chapter" data-level="6.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#dependent-means-t-test"><i class="fa fa-check"></i><b>6.3.2</b> Dependent-means t-test</a></li>
<li class="chapter" data-level="6.3.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#further-considerations"><i class="fa fa-check"></i><b>6.3.3</b> Further considerations</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#comparing-several-means"><i class="fa fa-check"></i><b>6.4</b> Comparing several means</a><ul>
<li class="chapter" data-level="6.4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction-2"><i class="fa fa-check"></i><b>6.4.1</b> Introduction</a></li>
<li class="chapter" data-level="6.4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#decomposing-variance"><i class="fa fa-check"></i><b>6.4.2</b> Decomposing variance</a></li>
<li class="chapter" data-level="6.4.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-way-anova"><i class="fa fa-check"></i><b>6.4.3</b> One-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#non-parametric-tests"><i class="fa fa-check"></i><b>6.5</b> Non-parametric tests</a><ul>
<li class="chapter" data-level="6.5.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#mann-whitney-u-test-a.k.a.-wilcoxon-rank-sum-test"><i class="fa fa-check"></i><b>6.5.1</b> Mann-Whitney U Test (a.k.a. Wilcoxon rank-sum test)</a></li>
<li class="chapter" data-level="6.5.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>6.5.2</b> Wilcoxon signed-rank test</a></li>
<li class="chapter" data-level="6.5.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#kruskal-wallis-test"><i class="fa fa-check"></i><b>6.5.3</b> Kruskal-Wallis test</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#categorical-data"><i class="fa fa-check"></i><b>6.6</b> Categorical data</a><ul>
<li class="chapter" data-level="6.6.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#confidence-intervals-for-proportions"><i class="fa fa-check"></i><b>6.6.1</b> Confidence intervals for proportions</a></li>
<li class="chapter" data-level="6.6.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#chi-square-test"><i class="fa fa-check"></i><b>6.6.2</b> Chi-square test</a></li>
<li class="chapter" data-level="6.6.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#sample-size-1"><i class="fa fa-check"></i><b>6.6.3</b> Sample size</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#learning-check-4"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#references-3"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>7</b> Regression</a><ul>
<li class="chapter" data-level="7.1" data-path="regression.html"><a href="regression.html#correlation"><i class="fa fa-check"></i><b>7.1</b> Correlation</a><ul>
<li class="chapter" data-level="7.1.1" data-path="regression.html"><a href="regression.html#correlation-coefficient"><i class="fa fa-check"></i><b>7.1.1</b> Correlation coefficient</a></li>
<li class="chapter" data-level="7.1.2" data-path="regression.html"><a href="regression.html#significance-testing"><i class="fa fa-check"></i><b>7.1.2</b> Significance testing</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="regression.html"><a href="regression.html#regression-1"><i class="fa fa-check"></i><b>7.2</b> Regression</a><ul>
<li class="chapter" data-level="7.2.1" data-path="regression.html"><a href="regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>7.2.1</b> Simple linear regression</a></li>
<li class="chapter" data-level="7.2.2" data-path="regression.html"><a href="regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>7.2.2</b> Multiple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="regression.html"><a href="regression.html#potential-problems"><i class="fa fa-check"></i><b>7.3</b> Potential problems</a><ul>
<li class="chapter" data-level="7.3.1" data-path="regression.html"><a href="regression.html#outliers"><i class="fa fa-check"></i><b>7.3.1</b> Outliers</a></li>
<li class="chapter" data-level="7.3.2" data-path="regression.html"><a href="regression.html#influential-observations"><i class="fa fa-check"></i><b>7.3.2</b> Influential observations</a></li>
<li class="chapter" data-level="7.3.3" data-path="regression.html"><a href="regression.html#non-linearity"><i class="fa fa-check"></i><b>7.3.3</b> Non-linearity</a></li>
<li class="chapter" data-level="7.3.4" data-path="regression.html"><a href="regression.html#non-constant-error-variance"><i class="fa fa-check"></i><b>7.3.4</b> Non-constant error variance</a></li>
<li class="chapter" data-level="7.3.5" data-path="regression.html"><a href="regression.html#non-normally-distributed-errors"><i class="fa fa-check"></i><b>7.3.5</b> Non-normally distributed errors</a></li>
<li class="chapter" data-level="7.3.6" data-path="regression.html"><a href="regression.html#correlation-of-errors"><i class="fa fa-check"></i><b>7.3.6</b> Correlation of errors</a></li>
<li class="chapter" data-level="7.3.7" data-path="regression.html"><a href="regression.html#collinearity"><i class="fa fa-check"></i><b>7.3.7</b> Collinearity</a></li>
<li class="chapter" data-level="7.3.8" data-path="regression.html"><a href="regression.html#omitted-variables"><i class="fa fa-check"></i><b>7.3.8</b> Omitted Variables</a></li>
<li class="chapter" data-level="7.3.9" data-path="regression.html"><a href="regression.html#overfitting"><i class="fa fa-check"></i><b>7.3.9</b> Overfitting</a></li>
<li class="chapter" data-level="7.3.10" data-path="regression.html"><a href="regression.html#variable-selection"><i class="fa fa-check"></i><b>7.3.10</b> Variable selection</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="regression.html"><a href="regression.html#categorical-predictors"><i class="fa fa-check"></i><b>7.4</b> Categorical predictors</a><ul>
<li class="chapter" data-level="7.4.1" data-path="regression.html"><a href="regression.html#two-categories"><i class="fa fa-check"></i><b>7.4.1</b> Two categories</a></li>
<li class="chapter" data-level="7.4.2" data-path="regression.html"><a href="regression.html#more-than-two-categories"><i class="fa fa-check"></i><b>7.4.2</b> More than two categories</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="regression.html"><a href="regression.html#extensions-of-the-linear-model"><i class="fa fa-check"></i><b>7.5</b> Extensions of the linear model</a><ul>
<li class="chapter" data-level="7.5.1" data-path="regression.html"><a href="regression.html#interaction-effects"><i class="fa fa-check"></i><b>7.5.1</b> Interaction effects</a></li>
<li class="chapter" data-level="7.5.2" data-path="regression.html"><a href="regression.html#non-linear-relationships"><i class="fa fa-check"></i><b>7.5.2</b> Non-linear relationships</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="regression.html"><a href="regression.html#logistic-regression"><i class="fa fa-check"></i><b>7.6</b> Logistic regression</a><ul>
<li class="chapter" data-level="7.6.1" data-path="regression.html"><a href="regression.html#motivation-and-intuition"><i class="fa fa-check"></i><b>7.6.1</b> Motivation and intuition</a></li>
<li class="chapter" data-level="7.6.2" data-path="regression.html"><a href="regression.html#technical-details-of-the-model"><i class="fa fa-check"></i><b>7.6.2</b> Technical details of the model</a></li>
<li class="chapter" data-level="7.6.3" data-path="regression.html"><a href="regression.html#estimation-in-r"><i class="fa fa-check"></i><b>7.6.3</b> Estimation in R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#learning-check-5"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#references-4"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html"><i class="fa fa-check"></i><b>8</b> Exploratory factor analysis</a><ul>
<li class="chapter" data-level="8.1" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#introduction-3"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#steps-in-factor-analysis"><i class="fa fa-check"></i><b>8.2</b> Steps in factor analysis</a><ul>
<li class="chapter" data-level="8.2.1" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#are-the-assumptions-satisfied"><i class="fa fa-check"></i><b>8.2.1</b> Are the assumptions satisfied?</a></li>
<li class="chapter" data-level="8.2.2" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#deriving-factors"><i class="fa fa-check"></i><b>8.2.2</b> Deriving factors</a></li>
<li class="chapter" data-level="8.2.3" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#factor-interpretation"><i class="fa fa-check"></i><b>8.2.3</b> Factor interpretation</a></li>
<li class="chapter" data-level="8.2.4" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#creating-new-variables"><i class="fa fa-check"></i><b>8.2.4</b> Creating new variables</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#reliability-analysis"><i class="fa fa-check"></i><b>8.3</b> Reliability analysis</a></li>
<li class="chapter" data-level="" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#learning-check-6"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#references-5"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="part"><span><b>III Assignments</b></span></li>
<li class="chapter" data-level="9" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html"><i class="fa fa-check"></i><b>9</b> R Markdown &amp; assignments</a><ul>
<li class="chapter" data-level="9.1" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#introduction-to-r-markdown"><i class="fa fa-check"></i><b>9.1</b> Introduction to R Markdown</a><ul>
<li class="chapter" data-level="" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#creating-a-new-r-markdown-document"><i class="fa fa-check"></i>Creating a new R Markdown document</a></li>
<li class="chapter" data-level="" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#text-and-equations"><i class="fa fa-check"></i>Text and Equations</a></li>
<li class="chapter" data-level="" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#r-code"><i class="fa fa-check"></i>R-Code</a></li>
<li class="chapter" data-level="" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#latex-math"><i class="fa fa-check"></i>LaTeX Math</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#solution-assignment-2"><i class="fa fa-check"></i><b>9.2</b> Solution assignment 2</a></li>
<li class="chapter" data-level="9.3" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#solution-assignment-3"><i class="fa fa-check"></i><b>9.3</b> Solution assignment 3</a></li>
<li class="chapter" data-level="9.4" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#solution-assignment-4"><i class="fa fa-check"></i><b>9.4</b> Solution assignment 4</a></li>
</ul></li>
<li class="part"><span><b>IV Group project</b></span></li>
<li class="chapter" data-level="10" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html"><i class="fa fa-check"></i><b>10</b> Survey design &amp; analysis</a><ul>
<li class="chapter" data-level="10.1" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#your-tasks"><i class="fa fa-check"></i><b>10.1</b> Your tasks</a><ul>
<li class="chapter" data-level="10.1.1" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#topics-for-the-group-project"><i class="fa fa-check"></i><b>10.1.1</b> Topics for the group project</a></li>
<li class="chapter" data-level="10.1.2" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#guidelines"><i class="fa fa-check"></i><b>10.1.2</b> Guidelines</a></li>
<li class="chapter" data-level="10.1.3" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#timeline"><i class="fa fa-check"></i><b>10.1.3</b> Timeline</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#part-1-before-collecting-data"><i class="fa fa-check"></i><b>10.2</b> Part 1: Before collecting data</a><ul>
<li class="chapter" data-level="10.2.1" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#research-design"><i class="fa fa-check"></i><b>10.2.1</b> Research design</a></li>
<li class="chapter" data-level="10.2.2" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#survey-method"><i class="fa fa-check"></i><b>10.2.2</b> Survey method</a></li>
<li class="chapter" data-level="10.2.3" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#questionnaire"><i class="fa fa-check"></i><b>10.2.3</b> Questionnaire</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#part-2-collecting-data-and-analysis"><i class="fa fa-check"></i><b>10.3</b> Part 2: Collecting data and analysis</a><ul>
<li class="chapter" data-level="10.3.1" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#collecting-data-1"><i class="fa fa-check"></i><b>10.3.1</b> Collecting data</a></li>
<li class="chapter" data-level="10.3.2" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#data-analysis"><i class="fa fa-check"></i><b>10.3.2</b> Data analysis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="a-tibble-3-x-54.html"><a href="a-tibble-3-x-54.html"><i class="fa fa-check"></i><b>11</b> A tibble: 3 x 54</a><ul>
<li class="chapter" data-level="11.0.1" data-path="a-tibble-3-x-54.html"><a href="a-tibble-3-x-54.html#reporting"><i class="fa fa-check"></i><b>11.0.1</b> Reporting</a></li>
<li class="chapter" data-level="11.1" data-path="a-tibble-3-x-54.html"><a href="a-tibble-3-x-54.html#frequently-asked-questions"><i class="fa fa-check"></i><b>11.1</b> Frequently asked questions</a><ul>
<li class="chapter" data-level="11.1.1" data-path="a-tibble-3-x-54.html"><a href="a-tibble-3-x-54.html#multiple-answers-stored-in-one-cell-in-csv"><i class="fa fa-check"></i><b>11.1.1</b> Multiple answers stored in one cell in CSV</a></li>
<li class="chapter" data-level="11.1.2" data-path="a-tibble-3-x-54.html"><a href="a-tibble-3-x-54.html#labels-for-numeric-values-in-csv-output"><i class="fa fa-check"></i><b>11.1.2</b> Labels for numeric values in CSV output</a></li>
<li class="chapter" data-level="11.1.3" data-path="a-tibble-3-x-54.html"><a href="a-tibble-3-x-54.html#bar-chart-for-multiple-choice-question-with-multiple-answers"><i class="fa fa-check"></i><b>11.1.3</b> Bar chart for multiple choice question with multiple answers</a></li>
<li class="chapter" data-level="11.1.4" data-path="a-tibble-3-x-54.html"><a href="a-tibble-3-x-54.html#how-to-create-a-radar-plot"><i class="fa fa-check"></i><b>11.1.4</b> How to create a radar plot?</a></li>
<li class="chapter" data-level="11.1.5" data-path="a-tibble-3-x-54.html"><a href="a-tibble-3-x-54.html#vertical-likert-line-chart"><i class="fa fa-check"></i><b>11.1.5</b> Vertical Likert line chart</a></li>
<li class="chapter" data-level="11.1.6" data-path="a-tibble-3-x-54.html"><a href="a-tibble-3-x-54.html#diverging-stacked-barchart"><i class="fa fa-check"></i><b>11.1.6</b> Diverging stacked barchart</a></li>
<li class="chapter" data-level="11.1.7" data-path="a-tibble-3-x-54.html"><a href="a-tibble-3-x-54.html#collapserecode-categories"><i class="fa fa-check"></i><b>11.1.7</b> Collapse/recode categories</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Marketing Research Design &amp; Analysis 2020</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="a-tibble-3-x-54" class="section level1">
<h1><span class="header-section-number">11</span> A tibble: 3 x 54</h1>
<p><code>Start Date</code> <code>End Date</code> <code>Response Type</code> <code>IP Address</code> Progress <code>Duration (in s~   &lt;chr&gt;        &lt;chr&gt;                &lt;dbl&gt; &lt;lgl&gt;           &lt;dbl&gt;            &lt;dbl&gt; 1 25- 5-2 2  ~ 25- 5-2 2~               1 NA                  1               96 2 4- 6-2 2   ~ 4- 6-2 2 ~               1 NA                  1               11 3 4- 6-2 2   ~ 4- 6-2 2 ~               1 NA                  1              173 # ... with 48 more variables: Finished &lt;dbl&gt;,</code>Recorded Date<code>&lt;chr&gt;,</code>Response
# ID<code>&lt;chr&gt;,</code>Recipient Last Name<code>&lt;lgl&gt;,</code>Recipient First Name<code>&lt;lgl&gt;, #</code>Recipient Email<code>&lt;lgl&gt;,</code>External Data Reference<code>&lt;lgl&gt;,</code>Location
# Latitude<code>&lt;chr&gt;,</code>Location Longitude<code>&lt;chr&gt;,</code>Distribution Channel<code>&lt;chr&gt;, #</code>User Language<code>&lt;chr&gt;,</code> Measuring steps<code>&lt;dbl&gt;,</code> Calories burned<code>&lt;dbl&gt;, #</code> Measuring heartbeat<code>&lt;dbl&gt;,</code> Exercise tracking<code>&lt;dbl&gt;,</code> Measuring
# distance<code>&lt;dbl&gt;,</code> Location<code>&lt;dbl&gt;,</code> Price<code>&lt;dbl&gt;,</code> Ambience<code>&lt;dbl&gt;,</code>
# Customer Service<code>&lt;dbl&gt;,</code> Active<code>&lt;dbl&gt;,</code> Cool<code>&lt;dbl&gt;,</code>
# Sophisticated<code>&lt;dbl&gt;,</code> Masculine<code>&lt;dbl&gt;,</code> Funny<code>&lt;dbl&gt;,</code>
# good:bad<code>&lt;dbl&gt;,</code> pleasant:unpleasant<code>&lt;dbl&gt;,</code> helpful:not
# helpful<code>&lt;dbl&gt;,</code> Selected Choice<code>&lt;dbl&gt;,</code> Other - Text<code>&lt;lgl&gt;,</code>During a
# typical day, in what period of the day you prefer watching movies or TV
# series on Netflix?<code>&lt;dbl&gt;,</code> ja! Natürlich.<code>&lt;dbl&gt;,</code> Clever<code>&lt;dbl&gt;,</code> Spar
# Vital<code>&lt;dbl&gt;,</code> …<code>&lt;dbl&gt;,</code> Percentage groceries<code>&lt;dbl&gt;,</code>
# Willingness-to-pay (in EUR)<code>&lt;dbl&gt;,</code>Conditional Questions Sometimes, you
# may want to ask questions that are only appropriate for a sub-group of
# respondents. In this case, you may use filters that can be used to show
# questions depending on an answer to a previous question. Say, you want to
# ask a follow-up questions only to respondents who answered “Yes” to a
# previous question. First, you would collect the response to the initial
# question: Initial question:<code>&lt;dbl&gt;,</code>This is the follow-up questions that
# is only displayed if the initial question has been answered “Yes” (see
# Option “Add Display Logic” in the question menu. Follow-up
# question:<code>&lt;dbl&gt;,</code> Willingness to pay (in EUR):<code>&lt;dbl&gt;,</code>In a
# within-subjects design, you manipulate the independent variable using the
# same participants (a.k.a. repeated-measures designs). This means, you
# collect information twice from the same respondents under the different
# experimental conditions. For example, at the beginning of the
# questionnaire, you may show respondents the current advertising of Brand X
# and ask for the purchase probability: Please consider the follwing
# advertisement: A How likely are you to purchase Brand X in the following 6
# months?<code>&lt;dbl&gt;,</code>At a later stage in the questionnaire, you may show the
# respondent the new advertisement of Brand X and ask for the purchase
# likelihood again. Please consider the follwing advertisement: B How likely
# are you to purchase Brand X in the following 6 months?<code>&lt;dbl&gt;,</code> A<code>&lt;dbl&gt;, #</code> B<code>&lt;dbl&gt;,</code> Selected Choice_1<code>&lt;dbl&gt;,</code> Text<code>&lt;lgl&gt;,</code>In a typical week,
# how many hours do you spend using fitness tracker?` <dbl>, Condition <chr></p>
<div class="infobox_orange hint">
<p>In this <a href="https://cran.csiro.au/web/packages/qualtRics/vignettes/qualtRics.html">link</a> you can find a brief, but insightful Introduction to qualtRics package and how to combine Qualtrics and R</p>
</div>
<div id="multiple-choice-with-a-single-answer" class="section level4 unnumbered">
<h4>Multiple choice with a single answer</h4>
<p>Type of data you obtain is <strong>categorical</strong>, and the output comes in the following form:</p>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:center;">
During a typical day, in what period of the day you prefer watching movies or TV series on Netflix?
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
</tr>
</tbody>
</table>
<p>What to do with this data now? First, we need to load it in R and prepare for analysis. The numbers you see in the output R recognizes <strong>as numeric</strong>. In order to conduct statistical modeling and properly visualize our results, we need to convert our data to <strong>a factor class.</strong></p>
<p>A factor (or coding variable) represents different groups of data by using numbers (integers). In fact, factors appear as numeric variables, but they hold meaning of labels/names of data groups, i.e. nominal variable. These data groups are represented in a form of ‘levels’.<br />
In our case, our multiple choice question output will contain 5 data groups after converting it to factor:</p>
<div class="sourceCode" id="cb907"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb907-1"><a href="a-tibble-3-x-54.html#cb907-1"></a><span class="co"># Convert numeric value to factors</span></span>
<span id="cb907-2"><a href="a-tibble-3-x-54.html#cb907-2"></a>qualtrics<span class="op">$</span><span class="st">`</span><span class="dt">During a typical day, in what period of the day you prefer watching movies or TV series on Netflix?</span><span class="st">`</span> &lt;-<span class="st"> </span><span class="kw">factor</span>(qualtrics<span class="op">$</span><span class="st">`</span><span class="dt">During a typical day, in what period of the day you prefer watching movies or TV series on Netflix?</span><span class="st">`</span>, </span>
<span id="cb907-3"><a href="a-tibble-3-x-54.html#cb907-3"></a>    <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>), <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Never&quot;</span>, <span class="st">&quot;Early morning(00:00-06:00)&quot;</span>, </span>
<span id="cb907-4"><a href="a-tibble-3-x-54.html#cb907-4"></a>        <span class="st">&quot;Morning(06:00-12:00)&quot;</span>, <span class="st">&quot;Afternoon(12:00-18:00&quot;</span>, </span>
<span id="cb907-5"><a href="a-tibble-3-x-54.html#cb907-5"></a>        <span class="st">&quot;Evening (18:00-22:00)&quot;</span>))</span>
<span id="cb907-6"><a href="a-tibble-3-x-54.html#cb907-6"></a><span class="co"># Table</span></span>
<span id="cb907-7"><a href="a-tibble-3-x-54.html#cb907-7"></a><span class="kw">table</span>(qualtrics<span class="op">$</span><span class="st">`</span><span class="dt">During a typical day, in what period of the day you prefer watching movies or TV series on Netflix?</span><span class="st">`</span>)</span></code></pre></div>
<pre><code>## 
##                      Never Early morning(00:00-06:00) 
##                         19                         18 
##       Morning(06:00-12:00)      Afternoon(12:00-18:00 
##                         22                         35 
##      Evening (18:00-22:00) 
##                         23</code></pre>
<div id="fischers-exact" class="section level5">
<h5><span class="header-section-number">11.0.0.0.1</span> Fischer’s exact</h5>
Fisher’s exact test is used to test a hypothesis with data obtained from multiple choice questions with single answer. Results from multiple choice questions with multiple answers are treated with different test.
<ul>
<li>
<B> Application: </B> when you have <B> 1 dependent variable and 1 independent variable with 2 or more levels/factors </B>
</ul>
</li>
<ul>
<li>
Used when frequency in at least one cell is <B> less than 5 </B>. When frequencies in each cell are greater than 5, Chi-square test should be used.
</ul>
</li>
<ul>
<li>
<B>Hypothesis:</B> Is there a significant difference in frequencies between values observed in cells and values expected in cells ?
</ul>
</li>
<ul>
<li>
<B>H0:</B> There is no relationship between the two categorical variables.Therefore, two categorical variables are <B> independent.</B> Knowing the value of one variable does not help to predict the value of the other variable.
</ul>
</li>
<ul>
<li>
<B>H1:</B> There is a relationship between the two categorical variables.Therefore, two categorical variables are <B> dependent.</B>Knowing the value of one variable helps to predict the value of the other variable.
</ul>
</li>
<ul>
<li>
Usually, this type of test is used on 2x2 contingency tables. However, it can be applicable on contingency tables of larger dimensions.
</ul>
</li>
<p><B>Example:</B> We would like to know whether the preferred period of the day for watching Netflix depends on the respondents’ country of origin.</p>
<div class="sourceCode" id="cb909"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb909-1"><a href="a-tibble-3-x-54.html#cb909-1"></a><span class="co"># Converting characters to factors</span></span>
<span id="cb909-2"><a href="a-tibble-3-x-54.html#cb909-2"></a>qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> Selected Choice_1</span><span class="st">`</span> &lt;-<span class="st"> </span><span class="kw">factor</span>(qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> Selected Choice_1</span><span class="st">`</span>, </span>
<span id="cb909-3"><a href="a-tibble-3-x-54.html#cb909-3"></a>    <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>), <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Male&quot;</span>, <span class="st">&quot;Female&quot;</span>))</span>
<span id="cb909-4"><a href="a-tibble-3-x-54.html#cb909-4"></a>qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> Selected Choice</span><span class="st">`</span> &lt;-<span class="st"> </span><span class="kw">factor</span>(qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> Selected Choice</span><span class="st">`</span>, </span>
<span id="cb909-5"><a href="a-tibble-3-x-54.html#cb909-5"></a>    <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>), <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Austria&quot;</span>, <span class="st">&quot;Germany&quot;</span>))</span>
<span id="cb909-6"><a href="a-tibble-3-x-54.html#cb909-6"></a><span class="co"># Creation of contingency table</span></span>
<span id="cb909-7"><a href="a-tibble-3-x-54.html#cb909-7"></a>fisher_test_table &lt;-<span class="st"> </span><span class="kw">table</span>(qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> Selected Choice</span><span class="st">`</span>, </span>
<span id="cb909-8"><a href="a-tibble-3-x-54.html#cb909-8"></a>    qualtrics<span class="op">$</span><span class="st">`</span><span class="dt">During a typical day, in what period of the day you prefer watching movies or TV series on Netflix?</span><span class="st">`</span>)</span>
<span id="cb909-9"><a href="a-tibble-3-x-54.html#cb909-9"></a><span class="co"># Since we have a count less than 5, we should</span></span>
<span id="cb909-10"><a href="a-tibble-3-x-54.html#cb909-10"></a><span class="co"># apply Fisher&#39;s test instead of Chi-square.</span></span>
<span id="cb909-11"><a href="a-tibble-3-x-54.html#cb909-11"></a><span class="co"># Fisher&#39;s test</span></span>
<span id="cb909-12"><a href="a-tibble-3-x-54.html#cb909-12"></a>test &lt;-<span class="st"> </span><span class="kw">fisher.test</span>(fisher_test_table)</span>
<span id="cb909-13"><a href="a-tibble-3-x-54.html#cb909-13"></a>test</span></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  fisher_test_table
## p-value = 0.575
## alternative hypothesis: two.sided</code></pre>
<p>From the output and from <code>test$p.value</code> we see that the p-value is higher than the significance level of 5%. Like any other statistical test, if the p-value is higher than the significance level, we can not reject the null hypothesis.</p>
<p>In our case, not rejecting the null hypothesis for the Fisher’s exact test of independence means that there is no significant relationship between the two categorical variables. Therefore, knowing the value of one variable does not help to predict the value of the other variable.</p>
</div>
<div id="chi-square-test-goodness-of-fit-independence-test" class="section level5 unnumbered">
<h5>Chi-square test: Goodness of fit &amp; Independence test</h5>
<ol style="list-style-type: decimal">
<li>Goodness of fit
<div>
<ul>
<li>
<B> Application: </B>when you only have <B> 1 dependent variable and none independent variables </B>
</ul>
</li>
<ul>
<li>
<B> Hypothesis:</B> Is there a significant difference in frequencies between values observed in cells and values expected in cells ?
</ul>
</li>
<ul>
<li>
<B> H0: </B> There is no significant difference between the observed and the expected frequencies.
</ul>
</li>
<ul>
<li>
<B> H1: </B> There is a significant difference between the observed and the expected frequencies.
</ul>
</li>
<ul>
<li>
If we don’t specify expected frequency per cell (see in the code below), then it is expected that all cells show an eqaul frequency.
</ul>
</li>
<ul>
<li>
<B> Example</B> :‘Do the numbers of respondents who prefer watching Netflix in different periods of a day <B> significantly differ from each other?</B>’
</ul>
</li>
</div>
<ul>
<li>
<B> Note that we did not assume any specific distribution, so we are assuming that each count will have the same or similar number.
</ul>
</li>
</B></li>
</ol>
<div class="sourceCode" id="cb911"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb911-1"><a href="a-tibble-3-x-54.html#cb911-1"></a><span class="co"># Creating table</span></span>
<span id="cb911-2"><a href="a-tibble-3-x-54.html#cb911-2"></a>mlc_chi_square &lt;-<span class="st"> </span><span class="kw">table</span>(qualtrics<span class="op">$</span><span class="st">`</span><span class="dt">During a typical day, in what period of the day you prefer watching movies or TV series on Netflix?</span><span class="st">`</span>)</span>
<span id="cb911-3"><a href="a-tibble-3-x-54.html#cb911-3"></a></span>
<span id="cb911-4"><a href="a-tibble-3-x-54.html#cb911-4"></a><span class="co"># Chi-square test (without given expected values =</span></span>
<span id="cb911-5"><a href="a-tibble-3-x-54.html#cb911-5"></a><span class="co"># equal values )</span></span>
<span id="cb911-6"><a href="a-tibble-3-x-54.html#cb911-6"></a><span class="kw">chisq.test</span>(mlc_chi_square)</span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  mlc_chi_square
## X-squared = 7.9145, df = 4, p-value = 0.09476</code></pre>
<p>The p-value of the test is higher than 0.05. We can conclude that the numbers of respondents who watch Netflix in different periods of a day are commonly distributed. Observed distribution does not differ significantly from the expected. This result does not surprise if you take a look at the values for each level in the table we created before conducting the test. There you can see that count of answers in each level is more or less not deviating too much. It is visible if you take a look at the previous visualizations as well.</p>
<p>If we are interested in testing more specific distribution, i.e. expect that 40% of our respondents are watching Netflix during evening hours, we can introduce corresponding distribution in the test.</p>
<div class="sourceCode" id="cb913"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb913-1"><a href="a-tibble-3-x-54.html#cb913-1"></a><span class="co"># Expected values in percentages for each alternative. The sum must be 1.</span></span>
<span id="cb913-2"><a href="a-tibble-3-x-54.html#cb913-2"></a>expected_values &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.10</span>, <span class="co"># We expect that 10% of our respondents do not watch Netflix at all.</span></span>
<span id="cb913-3"><a href="a-tibble-3-x-54.html#cb913-3"></a>                     <span class="fl">0.20</span>, <span class="co"># We expect that 20% of our respondents watch Netflix in early morning.</span></span>
<span id="cb913-4"><a href="a-tibble-3-x-54.html#cb913-4"></a>                     <span class="fl">0.10</span>, <span class="co"># We expect that 10% of our respondents watch Netflix in morning.</span></span>
<span id="cb913-5"><a href="a-tibble-3-x-54.html#cb913-5"></a>                     <span class="fl">0.20</span>, <span class="co"># We expect that 20% of our respondents watch Netflix in afternoon.</span></span>
<span id="cb913-6"><a href="a-tibble-3-x-54.html#cb913-6"></a>                     <span class="fl">0.40</span>  <span class="co"># We expect that 40% of our respondents watch Netflix in evening.</span></span>
<span id="cb913-7"><a href="a-tibble-3-x-54.html#cb913-7"></a>                    )</span>
<span id="cb913-8"><a href="a-tibble-3-x-54.html#cb913-8"></a><span class="co"># Chi-square test with expected values</span></span>
<span id="cb913-9"><a href="a-tibble-3-x-54.html#cb913-9"></a><span class="kw">chisq.test</span>(mlc_chi_square, <span class="dt">p=</span>expected_values)</span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  mlc_chi_square
## X-squared = 32.722, df = 4, p-value = 0.000001362</code></pre>
<p>This time the p-value of the test is lower than 0.05. We have an evidence that observed distribution does significantly differ from the expected distribution (10%/20%/10%/20%/40%).</p>
<ol start="2" style="list-style-type: decimal">
<li>Chi-Square Test of Independence
<div>
<ul>
<li>
<B> Application: </B>when you have <B> 1 dependent variable and 1 independent variable with 2 or more levels/factors </B>
</ul>
</li>
<ul>
<li>
<B> Hypothesis: </B> Is there an association between categorical variable X and categorical variable Y?
</ul>
</li>
<ul>
<li>
<B> H0: </B> There is no association between the two variables.</B>
</ul>
</li>
<ul>
<li>
<B> H1: </B> There is an association between the two variables.</B>
</ul>
</li>
<ul>
<li>
<B> Example: </B> Is there an association between gender and the preferred period of a day for watching Netflix?
</ul>
</li>
</div></li>
</ol>
<div class="sourceCode" id="cb915"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb915-1"><a href="a-tibble-3-x-54.html#cb915-1"></a><span class="co"># Creation of contingency table</span></span>
<span id="cb915-2"><a href="a-tibble-3-x-54.html#cb915-2"></a>chi_square_table &lt;-<span class="st"> </span><span class="kw">table</span>(qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> Selected Choice_1</span><span class="st">`</span>, </span>
<span id="cb915-3"><a href="a-tibble-3-x-54.html#cb915-3"></a>    qualtrics<span class="op">$</span><span class="st">&quot;During a typical day, in what period of the day you prefer watching movies or TV series on Netflix?&quot;</span>)</span>
<span id="cb915-4"><a href="a-tibble-3-x-54.html#cb915-4"></a><span class="co"># Chi-square independence test</span></span>
<span id="cb915-5"><a href="a-tibble-3-x-54.html#cb915-5"></a><span class="kw">chisq.test</span>(chi_square_table)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  chi_square_table
## X-squared = 1.5739, df = 4, p-value = 0.8135</code></pre>
<p>Since the p-value (0.8135) is higher than the significance level (0.05), we cannot reject the null hypothesis. Thus, we conclude that there is no association relationship between gender and the preferred period of a day for watching Netflix. Therefore, we can say that the hours spent is independent from the gender of participant.</p>
</div>
</div>
<div id="multiple-choice-with-multiple-answers" class="section level4 unnumbered">
<h4>Multiple choice with multiple answers</h4>
<p>In Qualtrics, multiple answers on multiple choice questions are captured in separate columns. For instance, the second respondents chose “Ja!Natürlich” and “Clever” as answers, thus, the rest of alternatives have none value in this row.</p>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:center;">
ja! Natürlich.
</th>
<th style="text-align:center;">
Clever
</th>
<th style="text-align:center;">
Spar Vital
</th>
<th style="text-align:center;">
…
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
NA
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
NA
</td>
</tr>
</tbody>
</table>
<p>Since this type of question provides multiple possible answers, one way to analyze data obtained from this question is in the following form:</p>
<div class="sourceCode" id="cb917"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb917-1"><a href="a-tibble-3-x-54.html#cb917-1"></a><span class="co"># Replacing NA with 0</span></span>
<span id="cb917-2"><a href="a-tibble-3-x-54.html#cb917-2"></a>qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> ja! Natürlich.</span><span class="st">`</span>[<span class="kw">is.na</span>(qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> ja! Natürlich.</span><span class="st">`</span>)] =<span class="st"> </span><span class="dv">0</span></span>
<span id="cb917-3"><a href="a-tibble-3-x-54.html#cb917-3"></a>qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> Clever</span><span class="st">`</span>[<span class="kw">is.na</span>(qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> Clever</span><span class="st">`</span>)] =<span class="st"> </span><span class="dv">0</span></span>
<span id="cb917-4"><a href="a-tibble-3-x-54.html#cb917-4"></a>qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> Spar Vital</span><span class="st">`</span>[<span class="kw">is.na</span>(qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> Spar Vital</span><span class="st">`</span>)] =<span class="st"> </span><span class="dv">0</span></span>
<span id="cb917-5"><a href="a-tibble-3-x-54.html#cb917-5"></a>qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> ...</span><span class="st">`</span>[<span class="kw">is.na</span>(qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> ...</span><span class="st">`</span>)] =<span class="st"> </span><span class="dv">0</span></span>
<span id="cb917-6"><a href="a-tibble-3-x-54.html#cb917-6"></a><span class="co"># qualtrics[38] accesses ja!Natürlich column</span></span>
<span id="cb917-7"><a href="a-tibble-3-x-54.html#cb917-7"></a><span class="co"># qualtrics[39] accesses Clever column</span></span>
<span id="cb917-8"><a href="a-tibble-3-x-54.html#cb917-8"></a><span class="co"># qualtrics[40] accesses Spar Vital column</span></span>
<span id="cb917-9"><a href="a-tibble-3-x-54.html#cb917-9"></a><span class="co"># qualtrics[41] accesses ... column Calculating</span></span>
<span id="cb917-10"><a href="a-tibble-3-x-54.html#cb917-10"></a><span class="co"># frequency, percentage of respondents and</span></span>
<span id="cb917-11"><a href="a-tibble-3-x-54.html#cb917-11"></a><span class="co"># percentage of cases</span></span>
<span id="cb917-12"><a href="a-tibble-3-x-54.html#cb917-12"></a>df.cochran &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Frequnecy =</span> <span class="kw">colSums</span>(qualtrics[<span class="dv">38</span><span class="op">:</span><span class="dv">41</span>]), </span>
<span id="cb917-13"><a href="a-tibble-3-x-54.html#cb917-13"></a>    <span class="dt">Share_of_respondents =</span> (<span class="kw">colSums</span>(qualtrics[<span class="dv">38</span><span class="op">:</span><span class="dv">41</span>])<span class="op">/</span><span class="kw">sum</span>(qualtrics[<span class="dv">38</span><span class="op">:</span><span class="dv">41</span>])) <span class="op">*</span><span class="st"> </span></span>
<span id="cb917-14"><a href="a-tibble-3-x-54.html#cb917-14"></a><span class="st">        </span><span class="dv">100</span>, <span class="dt">Share_of_cases =</span> ((<span class="kw">colSums</span>(qualtrics[<span class="dv">38</span><span class="op">:</span><span class="dv">41</span>]))<span class="op">/</span><span class="kw">nrow</span>(qualtrics[<span class="dv">38</span><span class="op">:</span><span class="dv">41</span>])) <span class="op">*</span><span class="st"> </span></span>
<span id="cb917-15"><a href="a-tibble-3-x-54.html#cb917-15"></a><span class="st">        </span><span class="dv">100</span>)</span>
<span id="cb917-16"><a href="a-tibble-3-x-54.html#cb917-16"></a>df.cochran <span class="op">%&gt;%</span><span class="st"> </span>kableExtra<span class="op">::</span><span class="kw">kbl</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">kable_paper</span>(<span class="st">&quot;hover&quot;</span>, </span>
<span id="cb917-17"><a href="a-tibble-3-x-54.html#cb917-17"></a>    <span class="dt">full_width =</span> F)</span></code></pre></div>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Frequnecy
</th>
<th style="text-align:center;">
Share_of_respondents
</th>
<th style="text-align:center;">
Share_of_cases
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
ja! Natürlich.
</td>
<td style="text-align:center;">
80
</td>
<td style="text-align:center;">
31.25000
</td>
<td style="text-align:center;">
68.37607
</td>
</tr>
<tr>
<td style="text-align:left;">
Clever
</td>
<td style="text-align:center;">
62
</td>
<td style="text-align:center;">
24.21875
</td>
<td style="text-align:center;">
52.99145
</td>
</tr>
<tr>
<td style="text-align:left;">
Spar Vital
</td>
<td style="text-align:center;">
71
</td>
<td style="text-align:center;">
27.73438
</td>
<td style="text-align:center;">
60.68376
</td>
</tr>
<tr>
<td style="text-align:left;">
…
</td>
<td style="text-align:center;">
43
</td>
<td style="text-align:center;">
16.79688
</td>
<td style="text-align:center;">
36.75214
</td>
</tr>
</tbody>
</table>
<p>The share of cases column suggests that, for instance, almost 70% percent of people are familiar with the brand “ja!Naturlich”.</p>
<p>For the analysis of results collected with multiple choice question with multiple possible answers, we can use <strong>Cochran’s Q test.</strong>Although we did not mention it before, it is not too different from what you have already learned about other tests.</p>
<p>The Cochran’s Q test and associated multiple comparisons require the following assumptions:</p>
<ol style="list-style-type: decimal">
<li><p>Responses are dichotomous and from k number of matched samples.</p></li>
<li><p>The subjects are independent of one another and were selected at random from a larger population.</p></li>
<li><p>The sample size is sufficiently “large”. (As a rule of thumb, the number of subjects for which the responses are not all 0’s or 1’s, n, should be ≥ 4 and nk should be ≥ 24)</p></li>
</ol>
<p>In a within-subjects experiment design with three or more observations of a dichotomous(= just two levels such as “Yes” or “No”) categorical outcome, you utilize Cochran’s Q test to assess main effects. Similarly, in a multiple choice question with multiple answers we have the same respondent going through three or more potential answers with dichotomous(=yes or no) categorical outcome, meaning that responses are <strong>not independent from each other.</strong></p>
<div class="sourceCode" id="cb918"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb918-1"><a href="a-tibble-3-x-54.html#cb918-1"></a><span class="kw">library</span>(DescTools)</span>
<span id="cb918-2"><a href="a-tibble-3-x-54.html#cb918-2"></a>list.cochran &lt;-<span class="st"> </span><span class="kw">list</span>(qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> ja! Natürlich.</span><span class="st">`</span>, qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> Clever</span><span class="st">`</span>, </span>
<span id="cb918-3"><a href="a-tibble-3-x-54.html#cb918-3"></a>    qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> Spar Vital</span><span class="st">`</span>, qualtrics<span class="op">$</span><span class="st">`</span><span class="dt"> ...</span><span class="st">`</span>)  <span class="co"># imaginary brand</span></span>
<span id="cb918-4"><a href="a-tibble-3-x-54.html#cb918-4"></a><span class="co"># Replacing NAs in the list with 0 in order to be</span></span>
<span id="cb918-5"><a href="a-tibble-3-x-54.html#cb918-5"></a><span class="co"># able to run the test</span></span>
<span id="cb918-6"><a href="a-tibble-3-x-54.html#cb918-6"></a>list.cochran &lt;-<span class="st"> </span><span class="kw">rapply</span>(list.cochran, <span class="dt">f =</span> <span class="cf">function</span>(x) <span class="kw">ifelse</span>(<span class="kw">is.na</span>(x), </span>
<span id="cb918-7"><a href="a-tibble-3-x-54.html#cb918-7"></a>    <span class="dv">0</span>, x), <span class="dt">how =</span> <span class="st">&quot;replace&quot;</span>)</span>
<span id="cb918-8"><a href="a-tibble-3-x-54.html#cb918-8"></a><span class="co"># Cochran test</span></span>
<span id="cb918-9"><a href="a-tibble-3-x-54.html#cb918-9"></a>matrix.cochran &lt;-<span class="st"> </span><span class="kw">do.call</span>(cbind, list.cochran)</span>
<span id="cb918-10"><a href="a-tibble-3-x-54.html#cb918-10"></a>DescTools<span class="op">::</span><span class="kw">CochranQTest</span>(matrix.cochran, <span class="dt">alpha =</span> <span class="fl">0.05</span>)</span></code></pre></div>
<pre><code>## 
##  Cochran&#39;s Q test
## 
## data:  y
## Q = 25.568, df = 3, p-value = 0.00001174</code></pre>
<p>The p-value less than 0.05 indicates that there is enough evidence to conclude that some of the store brands are better known among our respondents than other. In order to take a closer look at it, we need to conduct a post hoc test.</p>
<div class="sourceCode" id="cb920"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb920-1"><a href="a-tibble-3-x-54.html#cb920-1"></a><span class="co"># Post hoc test (Dunn Test)</span></span>
<span id="cb920-2"><a href="a-tibble-3-x-54.html#cb920-2"></a><span class="kw">DunnTest</span>(list.cochran, <span class="dt">method =</span> <span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Dunn&#39;s test of multiple comparisons using rank sums : bonferroni  
## 
##     mean.rank.diff      pval    
## 2-1            -36    0.1093    
## 3-1            -18    1.0000    
## 4-1            -74 0.0000073 ***
## 3-2             18    1.0000    
## 4-2            -38    0.0761 .  
## 4-3            -56    0.0014 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>From the results of the Dunn Test, we can see that there is a big difference between 1 (“ja!Natürlich”) and 4(“…”), as well as between 4(“…”) and 3(“Spar Vital”).</p>
</div>
<div id="rank-order-question-1" class="section level4">
<h4><span class="header-section-number">11.0.0.1</span> Rank order question</h4>
<p>Intuitive question to ask when it comes to this type of question is the following: which feature is the most important for respondents?</p>
<p>We can answer this question by calculating a mean rank for each feature. Before we do so, we will create a separate data frame and add columns of the response data.</p>
<div class="sourceCode" id="cb922"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb922-1"><a href="a-tibble-3-x-54.html#cb922-1"></a>rank.data &lt;-<span class="st"> </span><span class="kw">subset</span>(qualtrics, <span class="dt">select =</span> <span class="kw">c</span>(<span class="st">&quot; Measuring steps&quot;</span>, </span>
<span id="cb922-2"><a href="a-tibble-3-x-54.html#cb922-2"></a>    <span class="st">&quot; Calories burned&quot;</span>, <span class="st">&quot; Measuring heartbeat&quot;</span>, <span class="st">&quot; Exercise tracking&quot;</span>, </span>
<span id="cb922-3"><a href="a-tibble-3-x-54.html#cb922-3"></a>    <span class="st">&quot; Measuring distance&quot;</span>))</span>
<span id="cb922-4"><a href="a-tibble-3-x-54.html#cb922-4"></a><span class="kw">head</span>(rank.data) <span class="op">%&gt;%</span><span class="st"> </span>kableExtra<span class="op">::</span><span class="kw">kbl</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb922-5"><a href="a-tibble-3-x-54.html#cb922-5"></a><span class="st">    </span><span class="kw">kable_paper</span>(<span class="st">&quot;hover&quot;</span>, <span class="dt">full_width =</span> F)</span></code></pre></div>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:center;">
Measuring steps
</th>
<th style="text-align:center;">
Calories burned
</th>
<th style="text-align:center;">
Measuring heartbeat
</th>
<th style="text-align:center;">
Exercise tracking
</th>
<th style="text-align:center;">
Measuring distance
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
5
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
5
</td>
</tr>
</tbody>
</table>
<p>First information we would like to know is how many preference combinations there are, and how repetitive they are. We can obtain that information by creating a summary of the ranking data frame we created.</p>
<div class="sourceCode" id="cb923"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb923-1"><a href="a-tibble-3-x-54.html#cb923-1"></a><span class="kw">library</span>(pmr)</span>
<span id="cb923-2"><a href="a-tibble-3-x-54.html#cb923-2"></a>test &lt;-<span class="st"> </span><span class="kw">rankagg</span>(rank.data)</span>
<span id="cb923-3"><a href="a-tibble-3-x-54.html#cb923-3"></a>test</span></code></pre></div>
<pre><code>##                  n
##  [1,] 2 1 3 4 5 10
##  [2,] 1 3 2 4 5 19
##  [3,] 2 3 1 4 5 17
##  [4,] 1 2 4 3 5  4
##  [5,] 4 2 1 3 5  3
##  [6,] 3 2 1 5 4 15
##  [7,] 1 3 5 2 4 10
##  [8,] 1 2 4 5 3 10
##  [9,] 2 4 1 5 3  9
## [10,] 1 2 5 4 3  9
## [11,] 5 4 3 1 2  3
## [12,] 2 3 4 5 1  8</code></pre>
<p>The matrix we received as an output is the summary of our ranking data. It shows that, for instance, the preference combination “2,1,3,4,5” repeats 10 times in the data frame. More specifically, it means that there are 10 respondents who prefer the item 2(“Calories burned”) the most, then the item 1(“Measuring steps”), and so on.</p>
<p>Now we can calculate the mean rank for each feature and conclude which feature is the most important to our respondents:</p>
<div class="sourceCode" id="cb925"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb925-1"><a href="a-tibble-3-x-54.html#cb925-1"></a><span class="co"># Mean rank of each fitness tracker feature</span></span>
<span id="cb925-2"><a href="a-tibble-3-x-54.html#cb925-2"></a><span class="kw">destat</span>(test)<span class="op">$</span>mean.rank</span></code></pre></div>
<pre><code>## [1] 1.811966 2.581197 2.598291 4.051282 3.957265</code></pre>
<p>As we can observe from the output, the item 1(“Measuring steps”) shows the best mean rank among all items. Therefore, we can assume that the “Measuring steps” is most important for our respondents. However, in order to statistically prove it and become sure that this is not just by mere chance, we can conduct <strong>Friedman rank sum test</strong>.</p>
<p>Friedman rank sum test is used to identify whether there are any statistically significant differences between the distributions of 3 or more paired groups. It is used when the normality assumptions for using one-way repeated measures ANOVA are not met. Another case when Friedman rank rum test is used is when the dependent variable is measured on an ordinal scale, as in our case.</p>
<div class="sourceCode" id="cb927"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb927-1"><a href="a-tibble-3-x-54.html#cb927-1"></a><span class="co"># Friedman test</span></span>
<span id="cb927-2"><a href="a-tibble-3-x-54.html#cb927-2"></a><span class="kw">friedman.test</span>(<span class="kw">as.matrix</span>(rank.data))</span></code></pre></div>
<pre><code>## 
##  Friedman rank sum test
## 
## data:  as.matrix(rank.data)
## Friedman chi-squared = 176.42, df = 4, p-value &lt; 0.00000000000000022</code></pre>
<p>Friedman rank sum test has a p-value lower than 0.05, so we can conclude that here are significant differences between at least two features (what we have already seen in our visualization). Even though we have identified differences between preferences towards features in our advanced visualization, we will conduct a post hoc test in order to demonstrate traditional way of calculating pairwise comparisons.</p>
<div class="sourceCode" id="cb929"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb929-1"><a href="a-tibble-3-x-54.html#cb929-1"></a><span class="kw">library</span>(rstatix)</span>
<span id="cb929-2"><a href="a-tibble-3-x-54.html#cb929-2"></a>rank.data.long &lt;-<span class="st"> </span>reshape2<span class="op">::</span><span class="kw">melt</span>(rank.data, <span class="dt">value.name =</span> <span class="st">&quot;Rank&quot;</span>, </span>
<span id="cb929-3"><a href="a-tibble-3-x-54.html#cb929-3"></a>    <span class="dt">variable.name =</span> <span class="st">&quot;Feature&quot;</span>, <span class="dt">stringsAsFactors =</span> <span class="ot">TRUE</span>)</span>
<span id="cb929-4"><a href="a-tibble-3-x-54.html#cb929-4"></a>posthoc &lt;-<span class="st"> </span><span class="kw">wilcox_test</span>(Rank <span class="op">~</span><span class="st"> </span>Feature, <span class="dt">paired =</span> <span class="ot">TRUE</span>, </span>
<span id="cb929-5"><a href="a-tibble-3-x-54.html#cb929-5"></a>    <span class="dt">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span>, <span class="dt">data =</span> rank.data.long)</span>
<span id="cb929-6"><a href="a-tibble-3-x-54.html#cb929-6"></a>posthoc <span class="op">%&gt;%</span><span class="st"> </span>kableExtra<span class="op">::</span><span class="kw">kbl</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">kable_paper</span>(<span class="st">&quot;hover&quot;</span>, </span>
<span id="cb929-7"><a href="a-tibble-3-x-54.html#cb929-7"></a>    <span class="dt">full_width =</span> F)</span></code></pre></div>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:center;">
.y.
</th>
<th style="text-align:center;">
group1
</th>
<th style="text-align:center;">
group2
</th>
<th style="text-align:center;">
n1
</th>
<th style="text-align:center;">
n2
</th>
<th style="text-align:center;">
statistic
</th>
<th style="text-align:center;">
p
</th>
<th style="text-align:center;">
p.adj
</th>
<th style="text-align:center;">
p.adj.signif
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Rank
</td>
<td style="text-align:center;">
Measuring steps
</td>
<td style="text-align:center;">
Calories burned
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
1369.0
</td>
<td style="text-align:center;">
0.000000
</td>
<td style="text-align:center;">
0.000
</td>
<td style="text-align:center;">
****
</td>
</tr>
<tr>
<td style="text-align:center;">
Rank
</td>
<td style="text-align:center;">
Measuring steps
</td>
<td style="text-align:center;">
Measuring heartbeat
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
2231.0
</td>
<td style="text-align:center;">
0.000753
</td>
<td style="text-align:center;">
0.008
</td>
<td style="text-align:center;">
**
</td>
</tr>
<tr>
<td style="text-align:center;">
Rank
</td>
<td style="text-align:center;">
Measuring steps
</td>
<td style="text-align:center;">
Exercise tracking
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
354.0
</td>
<td style="text-align:center;">
0.000000
</td>
<td style="text-align:center;">
0.000
</td>
<td style="text-align:center;">
****
</td>
</tr>
<tr>
<td style="text-align:center;">
Rank
</td>
<td style="text-align:center;">
Measuring steps
</td>
<td style="text-align:center;">
Measuring distance
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
367.5
</td>
<td style="text-align:center;">
0.000000
</td>
<td style="text-align:center;">
0.000
</td>
<td style="text-align:center;">
****
</td>
</tr>
<tr>
<td style="text-align:center;">
Rank
</td>
<td style="text-align:center;">
Calories burned
</td>
<td style="text-align:center;">
Measuring heartbeat
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
3214.5
</td>
<td style="text-align:center;">
0.512000
</td>
<td style="text-align:center;">
1.000
</td>
<td style="text-align:center;">
ns
</td>
</tr>
<tr>
<td style="text-align:center;">
Rank
</td>
<td style="text-align:center;">
Calories burned
</td>
<td style="text-align:center;">
Exercise tracking
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
610.5
</td>
<td style="text-align:center;">
0.000000
</td>
<td style="text-align:center;">
0.000
</td>
<td style="text-align:center;">
****
</td>
</tr>
<tr>
<td style="text-align:center;">
Rank
</td>
<td style="text-align:center;">
Calories burned
</td>
<td style="text-align:center;">
Measuring distance
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
940.0
</td>
<td style="text-align:center;">
0.000000
</td>
<td style="text-align:center;">
0.000
</td>
<td style="text-align:center;">
****
</td>
</tr>
<tr>
<td style="text-align:center;">
Rank
</td>
<td style="text-align:center;">
Measuring heartbeat
</td>
<td style="text-align:center;">
Exercise tracking
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
1235.0
</td>
<td style="text-align:center;">
0.000000
</td>
<td style="text-align:center;">
0.000
</td>
<td style="text-align:center;">
****
</td>
</tr>
<tr>
<td style="text-align:center;">
Rank
</td>
<td style="text-align:center;">
Measuring heartbeat
</td>
<td style="text-align:center;">
Measuring distance
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
1307.5
</td>
<td style="text-align:center;">
0.000000
</td>
<td style="text-align:center;">
0.000
</td>
<td style="text-align:center;">
****
</td>
</tr>
<tr>
<td style="text-align:center;">
Rank
</td>
<td style="text-align:center;">
Exercise tracking
</td>
<td style="text-align:center;">
Measuring distance
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
3534.5
</td>
<td style="text-align:center;">
0.816000
</td>
<td style="text-align:center;">
1.000
</td>
<td style="text-align:center;">
ns
</td>
</tr>
</tbody>
</table>
<p>The output table provides us with p-values referring to significance of difference in mean ranks of each pair. For instance, the first 4 rows proves that the differences between the mean rank of the feature “Measuring steps” and each of the rest of features are significant. Consequently, we can conclude that this feature is by far the most important among our respondents.</p>
<p>Another question that may be interesting to explore is whether there are any complementary features ? Or features which overlap each other in its functionality? In order to have a look at that, we can investigate the correlation between ranks assigned to each feature.</p>
<div class="sourceCode" id="cb930"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb930-1"><a href="a-tibble-3-x-54.html#cb930-1"></a><span class="co"># Correlation Matrix</span></span>
<span id="cb930-2"><a href="a-tibble-3-x-54.html#cb930-2"></a>cor.matrix &lt;-<span class="st"> </span><span class="kw">cor</span>(rank.data, <span class="dt">method =</span> <span class="kw">c</span>(<span class="st">&quot;spearman&quot;</span>))</span>
<span id="cb930-3"><a href="a-tibble-3-x-54.html#cb930-3"></a>cor.matrix</span></code></pre></div>
<pre><code>##                       Measuring steps  Calories burned  Measuring heartbeat
##  Measuring steps           1.00000000      -0.04651331           -0.6569094
##  Calories burned          -0.04651331       1.00000000           -0.2221626
##  Measuring heartbeat      -0.65690943      -0.22216264            1.0000000
##  Exercise tracking         0.29633223      -0.10838758           -0.3255840
##  Measuring distance       -0.05958032      -0.11694481           -0.3817895
##                       Exercise tracking  Measuring distance
##  Measuring steps              0.2963322         -0.05958032
##  Calories burned             -0.1083876         -0.11694481
##  Measuring heartbeat         -0.3255840         -0.38178948
##  Exercise tracking            1.0000000         -0.47176821
##  Measuring distance          -0.4717682          1.00000000</code></pre>
<p>At the first glance we can observe a lot of negative values, meaning that many features correlate negatively relative to each other. In order to make the interpretation easier, we will try to visualise correlations in a form of a correlation matrix.</p>
<div class="sourceCode" id="cb932"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb932-1"><a href="a-tibble-3-x-54.html#cb932-1"></a><span class="kw">library</span>(ggcorrplot)</span>
<span id="cb932-2"><a href="a-tibble-3-x-54.html#cb932-2"></a><span class="kw">ggcorrplot</span>(cor.matrix)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-622-1.png" width="672" /></p>
<p>From the correlation matrix we can confirm that almost all features negatively correlate to each other. An exception is the relationship between feature “Measuring steps” and “Exercise tracking”, which correlates positively. This matrix can be useful for digging deeper in relationship between preferences for features. For instance, we can assume that feature “Measuring steps” and “Exercise tracking” correlate positively because users see them as complementary features. Moreover, if we say that walking is a type of exercise (in case of longer walking routes), we can assume that users, who ranked “Exercise tracking” high, ranked “Measuring steps” high as well, because they perceive it as another type of “Exercise tracking”.</p>
</div>
<div id="constant-sum-question-1" class="section level4">
<h4><span class="header-section-number">11.0.0.2</span> Constant Sum question</h4>
<p>If you wish to obtain information about how much one attribute is preferred over another one, you may use a constant sum scale. The total box should always be displayed at the bottom to make it easier for respondents. A constant sum question permits collection of ratio data type. With data obtained we would be able to express the relative importance of the options.</p>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:center;">
Location
</th>
<th style="text-align:center;">
Price
</th>
<th style="text-align:center;">
Ambience
</th>
<th style="text-align:center;">
Customer Service
</th>
<th style="text-align:center;">
id
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
32
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
32
</td>
<td style="text-align:center;">
13
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
22
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
40
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
5
</td>
</tr>
<tr>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
60
</td>
<td style="text-align:center;">
6
</td>
</tr>
</tbody>
</table>
<p>By computing descriptive statistics per column we get very useful insight in our data:</p>
<div class="sourceCode" id="cb933"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb933-1"><a href="a-tibble-3-x-54.html#cb933-1"></a><span class="co"># Compute descriptive statistics</span></span>
<span id="cb933-2"><a href="a-tibble-3-x-54.html#cb933-2"></a><span class="kw">library</span>(pastecs)</span>
<span id="cb933-3"><a href="a-tibble-3-x-54.html#cb933-3"></a>res &lt;-<span class="st"> </span><span class="kw">stat.desc</span>(constant.sum)</span>
<span id="cb933-4"><a href="a-tibble-3-x-54.html#cb933-4"></a><span class="kw">round</span>(res[, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>], <span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span>kableExtra<span class="op">::</span><span class="kw">kbl</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb933-5"><a href="a-tibble-3-x-54.html#cb933-5"></a><span class="st">    </span><span class="kw">kable_paper</span>(<span class="st">&quot;hover&quot;</span>, <span class="dt">full_width =</span> F)</span></code></pre></div>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Location
</th>
<th style="text-align:center;">
Price
</th>
<th style="text-align:center;">
Ambience
</th>
<th style="text-align:center;">
Customer Service
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
nbr.val
</td>
<td style="text-align:center;">
117.00
</td>
<td style="text-align:center;">
117.00
</td>
<td style="text-align:center;">
117.00
</td>
<td style="text-align:center;">
117.00
</td>
</tr>
<tr>
<td style="text-align:left;">
nbr.null
</td>
<td style="text-align:center;">
41.00
</td>
<td style="text-align:center;">
2.00
</td>
<td style="text-align:center;">
6.00
</td>
<td style="text-align:center;">
9.00
</td>
</tr>
<tr>
<td style="text-align:left;">
nbr.na
</td>
<td style="text-align:center;">
0.00
</td>
<td style="text-align:center;">
0.00
</td>
<td style="text-align:center;">
0.00
</td>
<td style="text-align:center;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
min
</td>
<td style="text-align:center;">
0.00
</td>
<td style="text-align:center;">
0.00
</td>
<td style="text-align:center;">
0.00
</td>
<td style="text-align:center;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
max
</td>
<td style="text-align:center;">
40.00
</td>
<td style="text-align:center;">
100.00
</td>
<td style="text-align:center;">
60.00
</td>
<td style="text-align:center;">
100.00
</td>
</tr>
<tr>
<td style="text-align:left;">
range
</td>
<td style="text-align:center;">
40.00
</td>
<td style="text-align:center;">
100.00
</td>
<td style="text-align:center;">
60.00
</td>
<td style="text-align:center;">
100.00
</td>
</tr>
<tr>
<td style="text-align:left;">
sum
</td>
<td style="text-align:center;">
1421.00
</td>
<td style="text-align:center;">
3684.00
</td>
<td style="text-align:center;">
3014.00
</td>
<td style="text-align:center;">
3581.00
</td>
</tr>
<tr>
<td style="text-align:left;">
median
</td>
<td style="text-align:center;">
10.00
</td>
<td style="text-align:center;">
30.00
</td>
<td style="text-align:center;">
20.00
</td>
<td style="text-align:center;">
30.00
</td>
</tr>
<tr>
<td style="text-align:left;">
mean
</td>
<td style="text-align:center;">
12.15
</td>
<td style="text-align:center;">
31.49
</td>
<td style="text-align:center;">
25.76
</td>
<td style="text-align:center;">
30.61
</td>
</tr>
<tr>
<td style="text-align:left;">
SE.mean
</td>
<td style="text-align:center;">
1.00
</td>
<td style="text-align:center;">
1.50
</td>
<td style="text-align:center;">
1.29
</td>
<td style="text-align:center;">
1.48
</td>
</tr>
<tr>
<td style="text-align:left;">
CI.mean.0.95
</td>
<td style="text-align:center;">
1.99
</td>
<td style="text-align:center;">
2.97
</td>
<td style="text-align:center;">
2.56
</td>
<td style="text-align:center;">
2.93
</td>
</tr>
<tr>
<td style="text-align:left;">
var
</td>
<td style="text-align:center;">
117.90
</td>
<td style="text-align:center;">
263.11
</td>
<td style="text-align:center;">
195.39
</td>
<td style="text-align:center;">
255.34
</td>
</tr>
<tr>
<td style="text-align:left;">
std.dev
</td>
<td style="text-align:center;">
10.86
</td>
<td style="text-align:center;">
16.22
</td>
<td style="text-align:center;">
13.98
</td>
<td style="text-align:center;">
15.98
</td>
</tr>
<tr>
<td style="text-align:left;">
coef.var
</td>
<td style="text-align:center;">
0.89
</td>
<td style="text-align:center;">
0.52
</td>
<td style="text-align:center;">
0.54
</td>
<td style="text-align:center;">
0.52
</td>
</tr>
</tbody>
</table>
<p>With the data collected we are able to answer the question: what factor is the most important for our respondents when they go out for a dinner?</p>
<p>In order to answer this question we need to conduct <strong>a repeated measures ANOVA</strong>.
This type of ANOVA is used for analyzing data where the same subjects are measured more than once. In our case we have every respondent measured on each of the factors (locations, price, ambiance and customer service). Repeated measures ANOVA is an extension of the paired-samples t-test. This test is also referred to as a within-subjects ANOVA. In the within-subject experimental design the same individuals are measured on the same outcome variable under different time points or conditions.</p>
<p>We need to check all assumptions that need to be fulfilled in order to deploy this type of ANOVA. There are three assumptions that need to check. The first to check that each level of the independent variable is approximately normally distributed. Since we have more than 30 observations at each level, we do not need to proceed further due to the central limit theorem. Second assumption refers to extreme outliers. Let’s have a look at potential outliers:</p>
<div class="sourceCode" id="cb934"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb934-1"><a href="a-tibble-3-x-54.html#cb934-1"></a><span class="co"># Creation of the long version of data frame</span></span>
<span id="cb934-2"><a href="a-tibble-3-x-54.html#cb934-2"></a><span class="kw">library</span>(reshape2)</span>
<span id="cb934-3"><a href="a-tibble-3-x-54.html#cb934-3"></a>constant.sum.long &lt;-<span class="st"> </span><span class="kw">melt</span>(constant.sum[, <span class="dv">-5</span>], <span class="dt">variable.name =</span> <span class="st">&quot;Factor&quot;</span>, </span>
<span id="cb934-4"><a href="a-tibble-3-x-54.html#cb934-4"></a>    <span class="dt">value.name =</span> <span class="st">&quot;Points&quot;</span>)</span>
<span id="cb934-5"><a href="a-tibble-3-x-54.html#cb934-5"></a><span class="co"># Outliers</span></span>
<span id="cb934-6"><a href="a-tibble-3-x-54.html#cb934-6"></a>constant.sum.long <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(Factor) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">identify_outliers</span>(Points) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb934-7"><a href="a-tibble-3-x-54.html#cb934-7"></a><span class="st">    </span>kableExtra<span class="op">::</span><span class="kw">kbl</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">kable_paper</span>(<span class="st">&quot;hover&quot;</span>, </span>
<span id="cb934-8"><a href="a-tibble-3-x-54.html#cb934-8"></a>    <span class="dt">full_width =</span> F)</span></code></pre></div>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:center;">
Factor
</th>
<th style="text-align:center;">
Points
</th>
<th style="text-align:center;">
is.outlier
</th>
<th style="text-align:center;">
is.extreme
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Price
</td>
<td style="text-align:center;">
80
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Price
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Price
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
60
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
60
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
60
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Ambience
</td>
<td style="text-align:center;">
50
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
<tr>
<td style="text-align:center;">
Customer Service
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
TRUE
</td>
<td style="text-align:center;">
FALSE
</td>
</tr>
</tbody>
</table>
<p>The p value seems to be significant, i.e., less than 0.05. As we cannot identify any extreme outliers, we can proceed with deploying repeated measures ANOVA.</p>
<div class="sourceCode" id="cb935"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb935-1"><a href="a-tibble-3-x-54.html#cb935-1"></a><span class="co"># Formatting data</span></span>
<span id="cb935-2"><a href="a-tibble-3-x-54.html#cb935-2"></a>constant.sum.aov &lt;-<span class="st"> </span><span class="kw">gather</span>(constant.sum, <span class="dt">key =</span> <span class="st">&quot;Factor&quot;</span>, </span>
<span id="cb935-3"><a href="a-tibble-3-x-54.html#cb935-3"></a>    <span class="dt">value =</span> <span class="st">&quot;Points&quot;</span>, <span class="st">`</span><span class="dt"> Location</span><span class="st">`</span>, <span class="st">`</span><span class="dt"> Price</span><span class="st">`</span>, <span class="st">`</span><span class="dt"> Ambience</span><span class="st">`</span>, </span>
<span id="cb935-4"><a href="a-tibble-3-x-54.html#cb935-4"></a>    <span class="st">`</span><span class="dt"> Customer Service</span><span class="st">`</span>)</span>
<span id="cb935-5"><a href="a-tibble-3-x-54.html#cb935-5"></a><span class="co"># One-way repeated measures ANOVA</span></span>
<span id="cb935-6"><a href="a-tibble-3-x-54.html#cb935-6"></a>res.aov &lt;-<span class="st"> </span><span class="kw">anova_test</span>(<span class="dt">data =</span> constant.sum.aov, <span class="dt">dv =</span> Points, </span>
<span id="cb935-7"><a href="a-tibble-3-x-54.html#cb935-7"></a>    <span class="dt">wid =</span> id, <span class="dt">within =</span> Factor)</span>
<span id="cb935-8"><a href="a-tibble-3-x-54.html#cb935-8"></a><span class="kw">get_anova_table</span>(res.aov) <span class="op">%&gt;%</span><span class="st"> </span>kableExtra<span class="op">::</span><span class="kw">kbl</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb935-9"><a href="a-tibble-3-x-54.html#cb935-9"></a><span class="st">    </span><span class="kw">kable_paper</span>(<span class="st">&quot;hover&quot;</span>, <span class="dt">full_width =</span> F)</span></code></pre></div>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:center;">
Effect
</th>
<th style="text-align:center;">
DFn
</th>
<th style="text-align:center;">
DFd
</th>
<th style="text-align:center;">
F
</th>
<th style="text-align:center;">
p
</th>
<th style="text-align:center;">
p&lt;.05
</th>
<th style="text-align:center;">
ges
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Factor
</td>
<td style="text-align:center;">
2.56
</td>
<td style="text-align:center;">
297.36
</td>
<td style="text-align:center;">
33.668
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
<ul>
<li></td>
<td style="text-align:center;">
0.225
</td>
</tr>
</tbody>
</table>
As we know that ANOVA is an omnibus test, we need to conduct post hoc test for further details:</li>
</ul>
<div class="sourceCode" id="cb936"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb936-1"><a href="a-tibble-3-x-54.html#cb936-1"></a><span class="co"># Post hoc test</span></span>
<span id="cb936-2"><a href="a-tibble-3-x-54.html#cb936-2"></a><span class="kw">pairwise.t.test</span>(constant.sum.long<span class="op">$</span>Points, constant.sum.long<span class="op">$</span>Factor, </span>
<span id="cb936-3"><a href="a-tibble-3-x-54.html#cb936-3"></a>    <span class="dt">paired =</span> T, <span class="dt">p.adjust.method =</span> <span class="st">&quot;holm&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using paired t tests 
## 
## data:  constant.sum.long$Points and constant.sum.long$Factor 
## 
##                    Location             Price  Ambience
##  Price            0.0000000000000027   -      -        
##  Ambience         0.0000000003153773   0.030  -        
##  Customer Service &lt; 0.0000000000000002 0.742  0.079    
## 
## P value adjustment method: holm</code></pre>
<p>Now we can clearly see that difference between perceived importance of price and location, or price and ambiance, are significant. On the other hand, the difference in perceived importance between customer service and price is not significant.</p>
</div>
<div id="number-entry-question-1" class="section level4">
<h4><span class="header-section-number">11.0.0.3</span> Number entry question</h4>
<p>A number entry question is a recommended type of question if you are interested in obtaining ratio data type. We will use this type of question together with a constant sum question type to collect data that can be analyzed with regression analysis.<strong>Note that in this case we treat constant sum data as ratio data and therefore assume that 0 means complete absence.</strong></p>
<p>Here is a glimpse in answers on how important is each factor to our respondents when it comes to dinning outside:</p>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:center;">
Location
</th>
<th style="text-align:center;">
Price
</th>
<th style="text-align:center;">
Ambience
</th>
<th style="text-align:center;">
Customer Service
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
32
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
32
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
22
</td>
<td style="text-align:center;">
43
</td>
</tr>
<tr>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
34
</td>
</tr>
<tr>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
46
</td>
</tr>
<tr>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
17
</td>
</tr>
<tr>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
4
</td>
</tr>
</tbody>
</table>
<p>Additionally, we asked our respondents how much are they willing to spend on dinner on average. In order to handle data easier, we will create a new data frame where we merge all the data together:</p>
<div class="sourceCode" id="cb938"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb938-1"><a href="a-tibble-3-x-54.html#cb938-1"></a>dinner &lt;-<span class="st"> </span><span class="kw">subset</span>(qualtrics, <span class="dt">select =</span> <span class="kw">c</span>(<span class="st">&quot; Location&quot;</span>, </span>
<span id="cb938-2"><a href="a-tibble-3-x-54.html#cb938-2"></a>    <span class="st">&quot; Price&quot;</span>, <span class="st">&quot; Ambience&quot;</span>, <span class="st">&quot; Customer Service&quot;</span>, <span class="st">&quot; Willingness-to-pay (in EUR)&quot;</span>))</span>
<span id="cb938-3"><a href="a-tibble-3-x-54.html#cb938-3"></a><span class="kw">head</span>(dinner) <span class="op">%&gt;%</span><span class="st"> </span>kableExtra<span class="op">::</span><span class="kw">kbl</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">kable_paper</span>(<span class="st">&quot;hover&quot;</span>, </span>
<span id="cb938-4"><a href="a-tibble-3-x-54.html#cb938-4"></a>    <span class="dt">full_width =</span> T)</span></code></pre></div>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:center;">
Location
</th>
<th style="text-align:center;">
Price
</th>
<th style="text-align:center;">
Ambience
</th>
<th style="text-align:center;">
Customer Service
</th>
<th style="text-align:center;">
Willingness-to-pay (in EUR)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
32
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
32
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
29
</td>
</tr>
<tr>
<td style="text-align:center;">
25
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
22
</td>
<td style="text-align:center;">
43
</td>
<td style="text-align:center;">
77
</td>
</tr>
<tr>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
34
</td>
<td style="text-align:center;">
52
</td>
</tr>
<tr>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
46
</td>
<td style="text-align:center;">
31
</td>
</tr>
<tr>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
17
</td>
<td style="text-align:center;">
22
</td>
</tr>
<tr>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
35
</td>
</tr>
</tbody>
</table>
<p>Before we conduct a linear regression analysis, we need to take a look at correlation matrix:</p>
<div class="sourceCode" id="cb939"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb939-1"><a href="a-tibble-3-x-54.html#cb939-1"></a>correlation &lt;-<span class="st"> </span><span class="kw">cor</span>(dinner, <span class="dt">method =</span> <span class="kw">c</span>(<span class="st">&quot;pearson&quot;</span>))</span>
<span id="cb939-2"><a href="a-tibble-3-x-54.html#cb939-2"></a>correlation</span></code></pre></div>
<pre><code>##                                Location       Price    Ambience
##  Location                     1.0000000 -0.31732620 -0.36134355
##  Price                       -0.3173262  1.00000000 -0.21962027
##  Ambience                    -0.3613436 -0.21962027  1.00000000
##  Customer Service            -0.1668810  0.08894752 -0.02405881
##  Willingness-to-pay (in EUR)  0.1414540 -0.07438388 -0.32550607
##                               Customer Service  Willingness-to-pay (in EUR)
##  Location                          -0.16688104                   0.14145397
##  Price                              0.08894752                  -0.07438388
##  Ambience                          -0.02405881                  -0.32550607
##  Customer Service                   1.00000000                   0.12125571
##  Willingness-to-pay (in EUR)        0.12125571                   1.00000000</code></pre>
<p>From our data we see, for instance, that some negative correlation between willingness to pay and importance of ambiance as well as some positive correlation between importance of customer service and willingness-to-pay. Let us observe descriptive statistics as well:</p>
<div class="sourceCode" id="cb941"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb941-1"><a href="a-tibble-3-x-54.html#cb941-1"></a>psych<span class="op">::</span><span class="kw">describe</span>(dinner) <span class="op">%&gt;%</span><span class="st"> </span>kableExtra<span class="op">::</span><span class="kw">kbl</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb941-2"><a href="a-tibble-3-x-54.html#cb941-2"></a><span class="st">    </span><span class="kw">kable_paper</span>(<span class="st">&quot;hover&quot;</span>, <span class="dt">full_width =</span> F)</span></code></pre></div>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
vars
</th>
<th style="text-align:center;">
n
</th>
<th style="text-align:center;">
mean
</th>
<th style="text-align:center;">
sd
</th>
<th style="text-align:center;">
median
</th>
<th style="text-align:center;">
trimmed
</th>
<th style="text-align:center;">
mad
</th>
<th style="text-align:center;">
min
</th>
<th style="text-align:center;">
max
</th>
<th style="text-align:center;">
range
</th>
<th style="text-align:center;">
skew
</th>
<th style="text-align:center;">
kurtosis
</th>
<th style="text-align:center;">
se
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Location
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
12.14530
</td>
<td style="text-align:center;">
10.85823
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
11.25263
</td>
<td style="text-align:center;">
14.8260
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
40
</td>
<td style="text-align:center;">
40
</td>
<td style="text-align:center;">
0.3585257
</td>
<td style="text-align:center;">
-0.8903393
</td>
<td style="text-align:center;">
1.003844
</td>
</tr>
<tr>
<td style="text-align:left;">
Price
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
31.48718
</td>
<td style="text-align:center;">
16.22079
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
29.83158
</td>
<td style="text-align:center;">
14.8260
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
1.5662904
</td>
<td style="text-align:center;">
4.1917874
</td>
<td style="text-align:center;">
1.499613
</td>
</tr>
<tr>
<td style="text-align:left;">
Ambience
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
25.76068
</td>
<td style="text-align:center;">
13.97822
</td>
<td style="text-align:center;">
20
</td>
<td style="text-align:center;">
25.09474
</td>
<td style="text-align:center;">
14.8260
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
60
</td>
<td style="text-align:center;">
60
</td>
<td style="text-align:center;">
0.3807401
</td>
<td style="text-align:center;">
-0.3100357
</td>
<td style="text-align:center;">
1.292286
</td>
</tr>
<tr>
<td style="text-align:left;">
Customer Service
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
49.35897
</td>
<td style="text-align:center;">
29.47777
</td>
<td style="text-align:center;">
47
</td>
<td style="text-align:center;">
49.29474
</td>
<td style="text-align:center;">
40.0302
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
98
</td>
<td style="text-align:center;">
98
</td>
<td style="text-align:center;">
0.0342022
</td>
<td style="text-align:center;">
-1.1897398
</td>
<td style="text-align:center;">
2.725221
</td>
</tr>
<tr>
<td style="text-align:left;">
Willingness-to-pay (in EUR)
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
32.99145
</td>
<td style="text-align:center;">
26.26801
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
30.28421
</td>
<td style="text-align:center;">
29.6520
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
110
</td>
<td style="text-align:center;">
110
</td>
<td style="text-align:center;">
0.8007002
</td>
<td style="text-align:center;">
0.0124325
</td>
<td style="text-align:center;">
2.428479
</td>
</tr>
</tbody>
</table>
<p>We see that difference between mean and median does not suggest (at the first sight) great effect of outliers.</p>
<p>Let us now do linear regression analysis:</p>
<div class="sourceCode" id="cb942"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb942-1"><a href="a-tibble-3-x-54.html#cb942-1"></a>mlr.dinner &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="st">`</span><span class="dt"> Willingness-to-pay (in EUR)</span><span class="st">`</span> <span class="op">~</span><span class="st"> `</span><span class="dt"> Location</span><span class="st">`</span> <span class="op">+</span><span class="st"> </span></span>
<span id="cb942-2"><a href="a-tibble-3-x-54.html#cb942-2"></a><span class="st">    `</span><span class="dt"> Price</span><span class="st">`</span> <span class="op">+</span><span class="st"> `</span><span class="dt"> Ambience</span><span class="st">`</span> <span class="op">+</span><span class="st"> `</span><span class="dt"> Customer Service</span><span class="st">`</span>, <span class="dt">data =</span> dinner)</span>
<span id="cb942-3"><a href="a-tibble-3-x-54.html#cb942-3"></a><span class="kw">summary</span>(mlr.dinner)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ` Willingness-to-pay (in EUR)` ~ ` Location` + ` Price` + 
##     ` Ambience` + ` Customer Service`, data = dinner)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -40.810 -18.205  -3.314  14.059  74.274 
## 
## Coefficients:
##                     Estimate Std. Error t value   Pr(&gt;|t|)    
## (Intercept)         55.31553   11.57393   4.779 0.00000538 ***
## ` Location`         -0.06739    0.25556  -0.264   0.792503    
## ` Price`            -0.28455    0.16117  -1.765   0.080205 .  
## ` Ambience`         -0.69755    0.19088  -3.654   0.000394 ***
## ` Customer Service`  0.10988    0.07931   1.386   0.168646    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 24.72 on 112 degrees of freedom
## Multiple R-squared:  0.1449, Adjusted R-squared:  0.1144 
## F-statistic: 4.745 on 4 and 112 DF,  p-value: 0.001421</code></pre>
<p>Out of all factors of importance when dinning out, the only one that suggests significance at 0.05 level of significance is ambience. From the summary we can conclude that increase in importance of ambience by 1 point, leads to decrease in willingness to pay by -0.697554.</p>
<div class="sourceCode" id="cb944"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb944-1"><a href="a-tibble-3-x-54.html#cb944-1"></a><span class="kw">confint</span>(mlr.dinner) <span class="op">%&gt;%</span><span class="st"> </span>kableExtra<span class="op">::</span><span class="kw">kbl</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb944-2"><a href="a-tibble-3-x-54.html#cb944-2"></a><span class="st">    </span><span class="kw">kable_paper</span>(<span class="st">&quot;hover&quot;</span>, <span class="dt">full_width =</span> F)</span></code></pre></div>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
2.5 %
</th>
<th style="text-align:center;">
97.5 %
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:center;">
32.3832720
</td>
<td style="text-align:center;">
78.2477971
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Location</code>
</td>
<td style="text-align:center;">
-0.5737479
</td>
<td style="text-align:center;">
0.4389706
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Price</code>
</td>
<td style="text-align:center;">
-0.6038940
</td>
<td style="text-align:center;">
0.0347931
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Ambience</code>
</td>
<td style="text-align:center;">
-1.0757599
</td>
<td style="text-align:center;">
-0.3193481
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Customer Service</code>
</td>
<td style="text-align:center;">
-0.0472542
</td>
<td style="text-align:center;">
0.2670130
</td>
</tr>
</tbody>
</table>
<p>From confidence intervals, We can conclude that when we do not consider any of given factors (location, price, ambience and customer service), willingness to pay will be somewhere between 32.383272EUR and 78.2477971EUR. Besides that, for each increase in importance of dinner ambiance by one point, there will be an average decrease of willingness to pay between -1.0757599 and -0.3193481.</p>
<div class="sourceCode" id="cb945"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb945-1"><a href="a-tibble-3-x-54.html#cb945-1"></a><span class="kw">library</span>(ggstatsplot)</span>
<span id="cb945-2"><a href="a-tibble-3-x-54.html#cb945-2"></a><span class="kw">ggcoefstats</span>(<span class="dt">x =</span> mlr.dinner, <span class="dt">title =</span> <span class="st">&quot;Willingness to pay predicted by importance of factors&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-636-1.png" width="672" /></p>
<p>There are couple of things we need to consider when we do multiple linear regression. One of them are potential outliers in our data. Here we identify and visualize them:</p>
<div class="sourceCode" id="cb946"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb946-1"><a href="a-tibble-3-x-54.html#cb946-1"></a><span class="co"># Outliers</span></span>
<span id="cb946-2"><a href="a-tibble-3-x-54.html#cb946-2"></a>outlier_values &lt;-<span class="st"> </span><span class="kw">boxplot.stats</span>(mlr.dinner<span class="op">$</span>residuals)<span class="op">$</span>out  <span class="co"># outlier values.</span></span>
<span id="cb946-3"><a href="a-tibble-3-x-54.html#cb946-3"></a>outlier_values</span></code></pre></div>
<pre><code>##       12       44       49 
## 70.56037 64.19796 74.27359</code></pre>
<p>We identified observations that belong to outlier values. We can even visualize them too:</p>
<div class="sourceCode" id="cb948"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb948-1"><a href="a-tibble-3-x-54.html#cb948-1"></a><span class="kw">boxplot</span>(mlr.dinner<span class="op">$</span>residuals, <span class="dt">main =</span> <span class="st">&quot;Willingnes to pay&quot;</span>, </span>
<span id="cb948-2"><a href="a-tibble-3-x-54.html#cb948-2"></a>    <span class="dt">boxwex =</span> <span class="fl">0.1</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-638-1.png" width="672" /></p>
<p>In addition, we need to observe whether there are any influential observations:</p>
<div class="sourceCode" id="cb949"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb949-1"><a href="a-tibble-3-x-54.html#cb949-1"></a><span class="kw">plot</span>(mlr.dinner, <span class="dv">4</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-639-1.png" width="672" /></p>
<p>A rule of thumb to determine whether an observation should be classified as influential or not is to look for observation with a Cook’s distance &gt; 1 .We see from the graph that there are no influential observations.</p>
<p>Another thing to consider is linearity, i.e. that the relationship between the dependent and the independent variable can be reasonably approximated in linear terms:</p>
<div class="sourceCode" id="cb950"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb950-1"><a href="a-tibble-3-x-54.html#cb950-1"></a><span class="co"># Linear specification</span></span>
<span id="cb950-2"><a href="a-tibble-3-x-54.html#cb950-2"></a><span class="kw">library</span>(car)</span>
<span id="cb950-3"><a href="a-tibble-3-x-54.html#cb950-3"></a><span class="kw">avPlots</span>(mlr.dinner)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-640-1.png" width="672" /></p>
<p>In our example it does not seem that linear relationships can be reasonably assumed for all variables.</p>
<p>As we already learned, another important assumption of the linear model is that the error terms have a constant variance (i.e., homoscedasticity):</p>
<div class="sourceCode" id="cb951"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb951-1"><a href="a-tibble-3-x-54.html#cb951-1"></a><span class="co"># Breusch-Pagan Test</span></span>
<span id="cb951-2"><a href="a-tibble-3-x-54.html#cb951-2"></a><span class="kw">library</span>(lmtest)</span>
<span id="cb951-3"><a href="a-tibble-3-x-54.html#cb951-3"></a><span class="kw">bptest</span>(mlr.dinner)</span></code></pre></div>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  mlr.dinner
## BP = 1.1478, df = 4, p-value = 0.8866</code></pre>
<p>The null hypothesis for this test is that the error variances are all equal, and our result is insignificant. Therefore, this assumption is met.</p>
<p>Another assumption to be met is that the error term is normally distributed. One way to check for normal distribution of the data is to employ statistical with the null hypothesis that the data is normally distributed. One of these is a Shapiro–Wilk test:</p>
<div class="sourceCode" id="cb953"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb953-1"><a href="a-tibble-3-x-54.html#cb953-1"></a><span class="kw">shapiro.test</span>(<span class="kw">resid</span>(mlr.dinner))</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resid(mlr.dinner)
## W = 0.94757, p-value = 0.0001763</code></pre>
<p>When the assumption of normally distributed errors is not met (as it is not met in our case), this might again be due to a misspecification of your model, in which case it might help to transform your data.</p>
<p>Finally, we need to check for multicollinearity, the case when there is a strong linear relationship between the independent variables:</p>
<div class="sourceCode" id="cb955"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb955-1"><a href="a-tibble-3-x-54.html#cb955-1"></a>correlation &lt;-<span class="st"> </span><span class="kw">cor</span>(dinner, <span class="dt">method =</span> <span class="kw">c</span>(<span class="st">&quot;pearson&quot;</span>))</span>
<span id="cb955-2"><a href="a-tibble-3-x-54.html#cb955-2"></a>correlation</span></code></pre></div>
<pre><code>##                                Location       Price    Ambience
##  Location                     1.0000000 -0.31732620 -0.36134355
##  Price                       -0.3173262  1.00000000 -0.21962027
##  Ambience                    -0.3613436 -0.21962027  1.00000000
##  Customer Service            -0.1668810  0.08894752 -0.02405881
##  Willingness-to-pay (in EUR)  0.1414540 -0.07438388 -0.32550607
##                               Customer Service  Willingness-to-pay (in EUR)
##  Location                          -0.16688104                   0.14145397
##  Price                              0.08894752                  -0.07438388
##  Ambience                          -0.02405881                  -0.32550607
##  Customer Service                   1.00000000                   0.12125571
##  Willingness-to-pay (in EUR)        0.12125571                   1.00000000</code></pre>
<p>By observing our correlation matrix, we can see that non of the coefficients suggest values close to 0.8 or 0.9. Consequently, we conclude that there are no concerns regarding the multicolinearity between independent variables.</p>
</div>
<div id="reporting" class="section level3">
<h3><span class="header-section-number">11.0.1</span> Reporting</h3>
<p>After you are done with statistical analysis, you are ready to create visually appealing and understandable graphs for your final report. In the following sections you can get certain ideas (and R code) for visualization of data obtained by frequently asked types of questions.</p>
<div class="infobox_orange hint">
<p>The format (e.g., data frame, matrix, list or similar) in which you have your data stored in R plays important role when you visualize that data. Therefore, reshaping data to the required form will be always a prerequisite for any visualization.</p>
</div>
<div class="infobox_red caution">
<p>The focus of the reporting section is on data visualisation, but do not forget to make correct interpretations and add them to your final report. How to communicate results of respective statistical test is a part of chapters before, so consult corresponding chapters if you are not sure how to report results of certain statistical test.</p>
</div>
<div id="multiple-choice-question-visualisation" class="section level5 unnumbered">
<h5>Multiple choice question visualisation</h5>
<p>In order to visualize a survey data obtained from multiple choice question with single answer, a data format needs to be in the appropriate format. Here we proceed with data format adaptation from the point where we stopped:</p>
<div class="sourceCode" id="cb957"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb957-1"><a href="a-tibble-3-x-54.html#cb957-1"></a><span class="co"># Converting long format to the</span></span>
<span id="cb957-2"><a href="a-tibble-3-x-54.html#cb957-2"></a><span class="co"># visualisation-friendly format</span></span>
<span id="cb957-3"><a href="a-tibble-3-x-54.html#cb957-3"></a>mlc_visualisation &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">table</span>(qualtrics<span class="op">$</span><span class="st">`</span><span class="dt">During a typical day, in what period of the day you prefer watching movies or TV series on Netflix?</span><span class="st">`</span>))</span>
<span id="cb957-4"><a href="a-tibble-3-x-54.html#cb957-4"></a><span class="co"># Naming columns</span></span>
<span id="cb957-5"><a href="a-tibble-3-x-54.html#cb957-5"></a><span class="kw">names</span>(mlc_visualisation) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Time&quot;</span>, <span class="st">&quot;Count&quot;</span>)</span>
<span id="cb957-6"><a href="a-tibble-3-x-54.html#cb957-6"></a><span class="co"># Observing</span></span>
<span id="cb957-7"><a href="a-tibble-3-x-54.html#cb957-7"></a><span class="kw">library</span>(kableExtra)</span>
<span id="cb957-8"><a href="a-tibble-3-x-54.html#cb957-8"></a>mlc_visualisation <span class="op">%&gt;%</span><span class="st"> </span>kableExtra<span class="op">::</span><span class="kw">kbl</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb957-9"><a href="a-tibble-3-x-54.html#cb957-9"></a><span class="st">    </span><span class="kw">kable_paper</span>(<span class="st">&quot;hover&quot;</span>, <span class="dt">full_width =</span> F)</span></code></pre></div>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:center;">
Time
</th>
<th style="text-align:center;">
Count
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Never
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
Early morning(00:00-06:00)
</td>
<td style="text-align:center;">
18
</td>
</tr>
<tr>
<td style="text-align:center;">
Morning(06:00-12:00)
</td>
<td style="text-align:center;">
22
</td>
</tr>
<tr>
<td style="text-align:center;">
Afternoon(12:00-18:00
</td>
<td style="text-align:center;">
35
</td>
</tr>
<tr>
<td style="text-align:center;">
Evening (18:00-22:00)
</td>
<td style="text-align:center;">
23
</td>
</tr>
</tbody>
</table>
<p>R package <code>ggplot2</code> allows you to create visually appealing graphs. Below you can see how to create simple versions of a bar chart and a pie chart.</p>
<div class="sourceCode" id="cb958"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb958-1"><a href="a-tibble-3-x-54.html#cb958-1"></a><span class="co"># Multiple choice question with single answer - a</span></span>
<span id="cb958-2"><a href="a-tibble-3-x-54.html#cb958-2"></a><span class="co"># bar chart</span></span>
<span id="cb958-3"><a href="a-tibble-3-x-54.html#cb958-3"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb958-4"><a href="a-tibble-3-x-54.html#cb958-4"></a>p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data =</span> mlc_visualisation, <span class="kw">aes</span>(<span class="dt">x =</span> Time, </span>
<span id="cb958-5"><a href="a-tibble-3-x-54.html#cb958-5"></a>    <span class="dt">y =</span> Count, <span class="dt">fill =</span> Time)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb958-6"><a href="a-tibble-3-x-54.html#cb958-6"></a><span class="st">    </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">label =</span> <span class="kw">paste0</span>(<span class="st">&quot;n=&quot;</span>, <span class="kw">round</span>(Count))), </span>
<span id="cb958-7"><a href="a-tibble-3-x-54.html#cb958-7"></a>        <span class="dt">position =</span> <span class="kw">position_stack</span>(<span class="dt">vjust =</span> <span class="fl">0.5</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">scale_fill_brewer</span>(<span class="dt">palette =</span> <span class="st">&quot;Blues&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb958-8"><a href="a-tibble-3-x-54.html#cb958-8"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="ot">NULL</span>, <span class="dt">y =</span> <span class="ot">NULL</span>, <span class="dt">fill =</span> <span class="ot">NULL</span>, <span class="dt">title =</span> <span class="st">&quot;The period of the day you prefer watching movies?&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb958-9"><a href="a-tibble-3-x-54.html#cb958-9"></a><span class="st">    </span><span class="kw">theme_classic</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">axis.line =</span> <span class="kw">element_blank</span>(), </span>
<span id="cb958-10"><a href="a-tibble-3-x-54.html#cb958-10"></a>    <span class="dt">axis.text =</span> <span class="kw">element_blank</span>(), <span class="dt">axis.ticks =</span> <span class="kw">element_blank</span>(), </span>
<span id="cb958-11"><a href="a-tibble-3-x-54.html#cb958-11"></a>    <span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>, <span class="dt">color =</span> <span class="st">&quot;#666666&quot;</span>))</span>
<span id="cb958-12"><a href="a-tibble-3-x-54.html#cb958-12"></a>p</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-645-1.png" width="672" /></p>
<div class="sourceCode" id="cb959"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb959-1"><a href="a-tibble-3-x-54.html#cb959-1"></a><span class="co"># Multiple choice question with single answer - a</span></span>
<span id="cb959-2"><a href="a-tibble-3-x-54.html#cb959-2"></a><span class="co"># pie chart</span></span>
<span id="cb959-3"><a href="a-tibble-3-x-54.html#cb959-3"></a>p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(mlc_visualisation, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="st">&quot;&quot;</span>, <span class="dt">y =</span> Count, </span>
<span id="cb959-4"><a href="a-tibble-3-x-54.html#cb959-4"></a>    <span class="dt">fill =</span> Time)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">width =</span> <span class="dv">1</span>, <span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb959-5"><a href="a-tibble-3-x-54.html#cb959-5"></a><span class="st">    </span><span class="kw">coord_polar</span>(<span class="st">&quot;y&quot;</span>, <span class="dt">start =</span> <span class="dv">0</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">label =</span> <span class="kw">paste0</span>(<span class="st">&quot;n=&quot;</span>, </span>
<span id="cb959-6"><a href="a-tibble-3-x-54.html#cb959-6"></a>    <span class="kw">round</span>(Count))), <span class="dt">position =</span> <span class="kw">position_stack</span>(<span class="dt">vjust =</span> <span class="fl">0.5</span>)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb959-7"><a href="a-tibble-3-x-54.html#cb959-7"></a><span class="st">    </span><span class="kw">scale_fill_brewer</span>(<span class="dt">palette =</span> <span class="st">&quot;Blues&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="ot">NULL</span>, </span>
<span id="cb959-8"><a href="a-tibble-3-x-54.html#cb959-8"></a>    <span class="dt">y =</span> <span class="ot">NULL</span>, <span class="dt">fill =</span> <span class="ot">NULL</span>, <span class="dt">title =</span> <span class="st">&quot;The period of the day you prefer watching movies?&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb959-9"><a href="a-tibble-3-x-54.html#cb959-9"></a><span class="st">    </span><span class="kw">theme_minimal</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">axis.line =</span> <span class="kw">element_blank</span>(), </span>
<span id="cb959-10"><a href="a-tibble-3-x-54.html#cb959-10"></a>    <span class="dt">axis.text =</span> <span class="kw">element_blank</span>(), <span class="dt">axis.ticks =</span> <span class="kw">element_blank</span>(), </span>
<span id="cb959-11"><a href="a-tibble-3-x-54.html#cb959-11"></a>    <span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>, <span class="dt">color =</span> <span class="st">&quot;#666666&quot;</span>))</span>
<span id="cb959-12"><a href="a-tibble-3-x-54.html#cb959-12"></a>p</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-646-1.png" width="672" /></p>
</div>
<div id="multiple-choice-question-with-multiple-answers" class="section level4">
<h4><span class="header-section-number">11.0.1.1</span> Multiple choice question with multiple answers</h4>
<p>If our multiple choice question has more possible answers, we would need first to calculate share of cases when each possible answer was selected.</p>
<div class="sourceCode" id="cb960"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb960-1"><a href="a-tibble-3-x-54.html#cb960-1"></a><span class="kw">setDT</span>(df.cochran, <span class="dt">keep.rownames =</span> <span class="ot">TRUE</span>)</span>
<span id="cb960-2"><a href="a-tibble-3-x-54.html#cb960-2"></a><span class="kw">colnames</span>(df.cochran)[<span class="dv">1</span>] &lt;-<span class="st"> &quot;Brand&quot;</span></span>
<span id="cb960-3"><a href="a-tibble-3-x-54.html#cb960-3"></a>df.cochran <span class="op">%&gt;%</span><span class="st"> </span>kableExtra<span class="op">::</span><span class="kw">kbl</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">kable_paper</span>(<span class="st">&quot;hover&quot;</span>, </span>
<span id="cb960-4"><a href="a-tibble-3-x-54.html#cb960-4"></a>    <span class="dt">full_width =</span> F)</span></code></pre></div>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:center;">
Brand
</th>
<th style="text-align:center;">
Frequnecy
</th>
<th style="text-align:center;">
Share_of_respondents
</th>
<th style="text-align:center;">
Share_of_cases
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
ja! Natürlich.
</td>
<td style="text-align:center;">
80
</td>
<td style="text-align:center;">
31.25000
</td>
<td style="text-align:center;">
68.37607
</td>
</tr>
<tr>
<td style="text-align:center;">
Clever
</td>
<td style="text-align:center;">
62
</td>
<td style="text-align:center;">
24.21875
</td>
<td style="text-align:center;">
52.99145
</td>
</tr>
<tr>
<td style="text-align:center;">
Spar Vital
</td>
<td style="text-align:center;">
71
</td>
<td style="text-align:center;">
27.73438
</td>
<td style="text-align:center;">
60.68376
</td>
</tr>
<tr>
<td style="text-align:center;">
…
</td>
<td style="text-align:center;">
43
</td>
<td style="text-align:center;">
16.79688
</td>
<td style="text-align:center;">
36.75214
</td>
</tr>
</tbody>
</table>
<p>After we make sure we have our data in the required form, we can create a nice bar chart:</p>
<div class="sourceCode" id="cb961"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb961-1"><a href="a-tibble-3-x-54.html#cb961-1"></a><span class="co"># Multiple choice question with multiple answers -</span></span>
<span id="cb961-2"><a href="a-tibble-3-x-54.html#cb961-2"></a><span class="co"># a bar chart</span></span>
<span id="cb961-3"><a href="a-tibble-3-x-54.html#cb961-3"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb961-4"><a href="a-tibble-3-x-54.html#cb961-4"></a>p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data =</span> df.cochran, <span class="kw">aes</span>(<span class="dt">x =</span> Brand, <span class="dt">y =</span> Share_of_cases, </span>
<span id="cb961-5"><a href="a-tibble-3-x-54.html#cb961-5"></a>    <span class="dt">fill =</span> Brand)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb961-6"><a href="a-tibble-3-x-54.html#cb961-6"></a><span class="st">    </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">label =</span> <span class="kw">paste0</span>(<span class="kw">round</span>(Share_of_cases), </span>
<span id="cb961-7"><a href="a-tibble-3-x-54.html#cb961-7"></a>        <span class="st">&quot;%&quot;</span>)), <span class="dt">position =</span> <span class="kw">position_stack</span>(<span class="dt">vjust =</span> <span class="fl">0.5</span>)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb961-8"><a href="a-tibble-3-x-54.html#cb961-8"></a><span class="st">    </span><span class="kw">scale_fill_brewer</span>(<span class="dt">palette =</span> <span class="st">&quot;Blues&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="ot">NULL</span>, </span>
<span id="cb961-9"><a href="a-tibble-3-x-54.html#cb961-9"></a>    <span class="dt">y =</span> <span class="ot">NULL</span>, <span class="dt">fill =</span> <span class="ot">NULL</span>, <span class="dt">title =</span> <span class="st">&quot;Brands repsondents are familiar with&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb961-10"><a href="a-tibble-3-x-54.html#cb961-10"></a><span class="st">    </span><span class="kw">theme_minimal</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">axis.line =</span> <span class="kw">element_blank</span>(), </span>
<span id="cb961-11"><a href="a-tibble-3-x-54.html#cb961-11"></a>    <span class="dt">axis.ticks =</span> <span class="kw">element_blank</span>(), <span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>, </span>
<span id="cb961-12"><a href="a-tibble-3-x-54.html#cb961-12"></a>        <span class="dt">color =</span> <span class="st">&quot;#666666&quot;</span>))</span>
<span id="cb961-13"><a href="a-tibble-3-x-54.html#cb961-13"></a>p</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-648-1.png" width="672" /></p>
<div id="rank-order-question-2" class="section level5">
<h5><span class="header-section-number">11.0.1.1.1</span> Rank order question</h5>
<p>In case of ranked data, one need to transform data from wide format to long format first.</p>
<div class="sourceCode" id="cb962"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb962-1"><a href="a-tibble-3-x-54.html#cb962-1"></a><span class="co"># Packages</span></span>
<span id="cb962-2"><a href="a-tibble-3-x-54.html#cb962-2"></a><span class="kw">library</span>(reshape2)</span>
<span id="cb962-3"><a href="a-tibble-3-x-54.html#cb962-3"></a><span class="kw">library</span>(ggpubr)</span>
<span id="cb962-4"><a href="a-tibble-3-x-54.html#cb962-4"></a><span class="kw">library</span>(rstatix)</span>
<span id="cb962-5"><a href="a-tibble-3-x-54.html#cb962-5"></a><span class="kw">library</span>(ggstatsplot)</span>
<span id="cb962-6"><a href="a-tibble-3-x-54.html#cb962-6"></a><span class="co"># Data in wide format</span></span>
<span id="cb962-7"><a href="a-tibble-3-x-54.html#cb962-7"></a><span class="kw">head</span>(rank.data) <span class="op">%&gt;%</span><span class="st"> </span>kableExtra<span class="op">::</span><span class="kw">kbl</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb962-8"><a href="a-tibble-3-x-54.html#cb962-8"></a><span class="st">    </span><span class="kw">kable_paper</span>(<span class="st">&quot;hover&quot;</span>, <span class="dt">full_width =</span> F)</span></code></pre></div>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:center;">
Measuring steps
</th>
<th style="text-align:center;">
Calories burned
</th>
<th style="text-align:center;">
Measuring heartbeat
</th>
<th style="text-align:center;">
Exercise tracking
</th>
<th style="text-align:center;">
Measuring distance
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
5
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
5
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb963"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb963-1"><a href="a-tibble-3-x-54.html#cb963-1"></a><span class="co"># Data in long format</span></span>
<span id="cb963-2"><a href="a-tibble-3-x-54.html#cb963-2"></a><span class="kw">head</span>(rank.data.long) <span class="op">%&gt;%</span><span class="st"> </span>kableExtra<span class="op">::</span><span class="kw">kbl</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb963-3"><a href="a-tibble-3-x-54.html#cb963-3"></a><span class="st">    </span><span class="kw">kable_paper</span>(<span class="st">&quot;hover&quot;</span>, <span class="dt">full_width =</span> F)</span></code></pre></div>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:center;">
Feature
</th>
<th style="text-align:center;">
Rank
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Measuring steps
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
Measuring steps
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
Measuring steps
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
Measuring steps
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
Measuring steps
</td>
<td style="text-align:center;">
5
</td>
</tr>
<tr>
<td style="text-align:center;">
Measuring steps
</td>
<td style="text-align:center;">
4
</td>
</tr>
</tbody>
</table>
<p>Simple way to depict ranks is a chart of box plots:</p>
<div class="sourceCode" id="cb964"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb964-1"><a href="a-tibble-3-x-54.html#cb964-1"></a><span class="co"># Rank order question - box plots</span></span>
<span id="cb964-2"><a href="a-tibble-3-x-54.html#cb964-2"></a>p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(rank.data.long, <span class="kw">aes</span>(<span class="dt">x =</span> Feature, <span class="dt">y =</span> Rank, </span>
<span id="cb964-3"><a href="a-tibble-3-x-54.html#cb964-3"></a>    <span class="dt">fill =</span> Feature)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme_minimal</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb964-4"><a href="a-tibble-3-x-54.html#cb964-4"></a><span class="st">    </span><span class="kw">ggtitle</span>(<span class="dt">label =</span> <span class="st">&quot;Perceived importance of features&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb964-5"><a href="a-tibble-3-x-54.html#cb964-5"></a><span class="st">    </span><span class="kw">theme</span>(<span class="dt">axis.text =</span> <span class="kw">element_blank</span>())</span>
<span id="cb964-6"><a href="a-tibble-3-x-54.html#cb964-6"></a>p</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-650-1.png" width="672" />
Package <code>ggstatsplot()</code> provides a great feature, which enables creation of a plot and conducting a statistical test at the same time.</p>
<div class="sourceCode" id="cb965"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb965-1"><a href="a-tibble-3-x-54.html#cb965-1"></a><span class="co"># Rank order question - ggstatsplot</span></span>
<span id="cb965-2"><a href="a-tibble-3-x-54.html#cb965-2"></a>ggstatsplot<span class="op">::</span><span class="kw">ggwithinstats</span>(</span>
<span id="cb965-3"><a href="a-tibble-3-x-54.html#cb965-3"></a>  <span class="dt">data =</span> rank.data.long,</span>
<span id="cb965-4"><a href="a-tibble-3-x-54.html#cb965-4"></a>  <span class="dt">x =</span> Feature,</span>
<span id="cb965-5"><a href="a-tibble-3-x-54.html#cb965-5"></a>  <span class="dt">y =</span> Rank,</span>
<span id="cb965-6"><a href="a-tibble-3-x-54.html#cb965-6"></a>  <span class="dt">type =</span> <span class="st">&quot;np&quot;</span>,</span>
<span id="cb965-7"><a href="a-tibble-3-x-54.html#cb965-7"></a>  <span class="dt">pairwise.comparisons =</span> <span class="ot">TRUE</span>, <span class="co"># show pairwise comparison test results</span></span>
<span id="cb965-8"><a href="a-tibble-3-x-54.html#cb965-8"></a>  <span class="dt">title =</span> <span class="st">&quot;What features are important to you when evualting fitness trackers?&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-651-1.png" width="672" /></p>
</div>
</div>
<div id="constant-sum-question-2" class="section level4">
<h4><span class="header-section-number">11.0.1.2</span> Constant Sum question</h4>
<p>Required data format for a data obtained from constant sum question is similar to ranked data.</p>
<div class="sourceCode" id="cb966"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb966-1"><a href="a-tibble-3-x-54.html#cb966-1"></a><span class="co"># Data in long format</span></span>
<span id="cb966-2"><a href="a-tibble-3-x-54.html#cb966-2"></a><span class="kw">head</span>(constant.sum.long) <span class="op">%&gt;%</span><span class="st"> </span>kableExtra<span class="op">::</span><span class="kw">kbl</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb966-3"><a href="a-tibble-3-x-54.html#cb966-3"></a><span class="st">    </span><span class="kw">kable_paper</span>(<span class="st">&quot;hover&quot;</span>, <span class="dt">full_width =</span> F)</span></code></pre></div>
<table class=" lightable-paper lightable-hover" style='font-family: "Arial Narrow", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:center;">
Factor
</th>
<th style="text-align:center;">
Points
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Location
</td>
<td style="text-align:center;">
32
</td>
</tr>
<tr>
<td style="text-align:center;">
Location
</td>
<td style="text-align:center;">
25
</td>
</tr>
<tr>
<td style="text-align:center;">
Location
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
Location
</td>
<td style="text-align:center;">
20
</td>
</tr>
<tr>
<td style="text-align:center;">
Location
</td>
<td style="text-align:center;">
30
</td>
</tr>
<tr>
<td style="text-align:center;">
Location
</td>
<td style="text-align:center;">
0
</td>
</tr>
</tbody>
</table>
<p>Here is one way to visualize data obtained from constant sum question.</p>
<div class="sourceCode" id="cb967"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb967-1"><a href="a-tibble-3-x-54.html#cb967-1"></a><span class="co"># Constant sum question</span></span>
<span id="cb967-2"><a href="a-tibble-3-x-54.html#cb967-2"></a>p &lt;-<span class="st"> </span>constant.sum.long <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Factor <span class="op">!=</span><span class="st"> &quot;id&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb967-3"><a href="a-tibble-3-x-54.html#cb967-3"></a><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Factor, <span class="dt">y =</span> Points, <span class="dt">fill =</span> Factor)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb967-4"><a href="a-tibble-3-x-54.html#cb967-4"></a><span class="st">    </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme_minimal</span>() <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;What factors do you consider when choosing a place to go for a dinner?&quot;</span>)</span>
<span id="cb967-5"><a href="a-tibble-3-x-54.html#cb967-5"></a>p</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-653-1.png" width="672" /></p>
<p>The following type of visualisation includes statistical test as well:</p>
<div class="sourceCode" id="cb968"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb968-1"><a href="a-tibble-3-x-54.html#cb968-1"></a>ggstatsplot<span class="op">::</span><span class="kw">ggwithinstats</span>(</span>
<span id="cb968-2"><a href="a-tibble-3-x-54.html#cb968-2"></a>  <span class="dt">data =</span> constant.sum.long <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Factor<span class="op">!=</span><span class="st">&quot;id&quot;</span>), <span class="co"># excluding &quot;id&quot; column from the data</span></span>
<span id="cb968-3"><a href="a-tibble-3-x-54.html#cb968-3"></a>  <span class="dt">x =</span> Factor,</span>
<span id="cb968-4"><a href="a-tibble-3-x-54.html#cb968-4"></a>  <span class="dt">y =</span> Points,</span>
<span id="cb968-5"><a href="a-tibble-3-x-54.html#cb968-5"></a>  <span class="dt">type =</span> <span class="st">&quot;p&quot;</span>,</span>
<span id="cb968-6"><a href="a-tibble-3-x-54.html#cb968-6"></a>  <span class="dt">bf.message =</span> F,</span>
<span id="cb968-7"><a href="a-tibble-3-x-54.html#cb968-7"></a>  <span class="dt">pairwise.comparisons =</span> <span class="ot">TRUE</span>, <span class="co"># show pairwise comparison test results</span></span>
<span id="cb968-8"><a href="a-tibble-3-x-54.html#cb968-8"></a>  <span class="dt">title =</span> <span class="st">&quot;What factors do you consider when choosing a place to go for a dinner?&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-654-1.png" width="672" /></p>
</div>
</div>
<div id="frequently-asked-questions" class="section level2">
<h2><span class="header-section-number">11.1</span> Frequently asked questions</h2>
<p>Here we will post the most frequent issues you might face with handling Qualtrics data in R.</p>
<div id="multiple-answers-stored-in-one-cell-in-csv" class="section level3">
<h3><span class="header-section-number">11.1.1</span> Multiple answers stored in one cell in CSV</h3>
<p><em>Issue:</em> When exported from Qualtrics to CSV, answers on multiple choice questions with multiple answers are stored in one cell. In the picture below you can see that this issue appears in the column “Q2”, where a respondent chose two answers (“1” and “2”), and these two answers are merged together in one cell.</p>
<p><img src="images/combined.png" width="40%" style="display: block; margin: auto;" /></p>
<p><em>Solution:</em></p>
<p>First, when you go to export your data from Qualtrics (“Data &amp; Analysis” &gt; “Export &amp; Import” &gt; “Export data”) choose CSV, and in the bottom-right corner you will find “More options”. After you click it, scroll down a bit, and there you should tick “Split multi-value fields into columns”. Please make sure that you are using the correct settings in Qualtrics export as depicted below:</p>
<p><img src="images/qualtrics_export.png" width="40%" style="display: block; margin: auto;" /></p>
<p>So, make sure you tick:</p>
<ul>
<li>Use numeric values</li>
<li>Remove line breaks</li>
<li>Split multi-value fields into columns</li>
</ul>
<p>This should result in your multi-value fields being divided into columns as depicted below.</p>
<p><img src="images/separate.png" width="40%" style="display: block; margin: auto;" /></p>
</div>
<div id="labels-for-numeric-values-in-csv-output" class="section level3">
<h3><span class="header-section-number">11.1.2</span> Labels for numeric values in CSV output</h3>
<p><strong>Issue</strong>: When exported from Qualtrics to CSV, answers are coded as numeric values, and I don’t know which value corresponds to which label(=answer)?</p>
<p><strong>Solution:</strong></p>
<p>You can check it or even change it in Qualtrics by doing the following steps:</p>
<ol style="list-style-type: decimal">
<li>Navigate to the Survey tab and select the question you want to check labels for.</li>
</ol>
<p><img src="images/recode1.png" width="40%" style="display: block; margin: auto;" /></p>
<ol start="2" style="list-style-type: decimal">
<li>Click the gray gear to the left to access the Question Options and choose Recode Values.</li>
</ol>
<p><img src="images/recode2.png" width="40%" style="display: block; margin: auto;" /></p>
<p>There you can see how Qualtrics coded your responses and you can potentially change it.</p>
<p><img src="images/recode3.png" width="425" style="display: block; margin: auto;" /></p>
</div>
<div id="bar-chart-for-multiple-choice-question-with-multiple-answers" class="section level3">
<h3><span class="header-section-number">11.1.3</span> Bar chart for multiple choice question with multiple answers</h3>
<p><strong>Issue:</strong> How to create a bar chart for multiple answers on multiple choice questions?</p>
<p><strong>Solution:</strong></p>
<p>Let’s load the packages <code>qualtRics</code> and <code>ggplot2</code> and Qualtrics survey data first:</p>
<div class="sourceCode" id="cb969"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb969-1"><a href="a-tibble-3-x-54.html#cb969-1"></a><span class="kw">library</span>(qualtRics)</span>
<span id="cb969-2"><a href="a-tibble-3-x-54.html#cb969-2"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb969-3"><a href="a-tibble-3-x-54.html#cb969-3"></a>qualtrics_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">read_survey</span>(<span class="st">&quot;data/mrda_2.csv&quot;</span>)</span></code></pre></div>
<p>We would like to visualize question 2 (multiple choice question with multiple answers) which has 4 categories:</p>
<div class="sourceCode" id="cb970"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb970-1"><a href="a-tibble-3-x-54.html#cb970-1"></a>qualtrics_<span class="dv">1</span>[, <span class="kw">c</span>(<span class="st">&quot;Q2_1&quot;</span>, <span class="st">&quot;Q2_2&quot;</span>, <span class="st">&quot;Q2_3&quot;</span>, <span class="st">&quot;Q2_4&quot;</span>)]</span></code></pre></div>
<pre><code>## # A tibble: 72 x 4
##     Q2_1  Q2_2 Q2_3   Q2_4
##    &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt; &lt;dbl&gt;
##  1    NA    NA NA        1
##  2     1    NA NA       NA
##  3     1    NA NA       NA
##  4    NA    NA NA        1
##  5     1    NA NA       NA
##  6     1    NA NA       NA
##  7     1     1 NA       NA
##  8     1    NA NA       NA
##  9     1    NA NA       NA
## 10     1    NA NA       NA
## # ... with 62 more rows</code></pre>
<p>We see that we have some NA values that needs to be handeled. Therefore, we replace NA values with 0 for each category:</p>
<div class="sourceCode" id="cb972"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb972-1"><a href="a-tibble-3-x-54.html#cb972-1"></a>qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">ifelse</span>(<span class="kw">is.na</span>(qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">1</span>), </span>
<span id="cb972-2"><a href="a-tibble-3-x-54.html#cb972-2"></a>    <span class="dv">0</span>, qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">1</span>)</span>
<span id="cb972-3"><a href="a-tibble-3-x-54.html#cb972-3"></a>qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">ifelse</span>(<span class="kw">is.na</span>(qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">2</span>), </span>
<span id="cb972-4"><a href="a-tibble-3-x-54.html#cb972-4"></a>    <span class="dv">0</span>, qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">2</span>)</span>
<span id="cb972-5"><a href="a-tibble-3-x-54.html#cb972-5"></a>qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">ifelse</span>(<span class="kw">is.na</span>(qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">3</span>), </span>
<span id="cb972-6"><a href="a-tibble-3-x-54.html#cb972-6"></a>    <span class="dv">0</span>, qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">3</span>)</span>
<span id="cb972-7"><a href="a-tibble-3-x-54.html#cb972-7"></a>qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">4</span> &lt;-<span class="st"> </span><span class="kw">ifelse</span>(<span class="kw">is.na</span>(qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">4</span>), </span>
<span id="cb972-8"><a href="a-tibble-3-x-54.html#cb972-8"></a>    <span class="dv">0</span>, qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">4</span>)</span></code></pre></div>
<p>Third, we compute share for each category:</p>
<div class="sourceCode" id="cb973"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb973-1"><a href="a-tibble-3-x-54.html#cb973-1"></a>share_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">sum</span>(qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">1</span>)<span class="op">/</span><span class="kw">nrow</span>(qualtrics_<span class="dv">1</span>)</span>
<span id="cb973-2"><a href="a-tibble-3-x-54.html#cb973-2"></a>share_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">sum</span>(qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">2</span>)<span class="op">/</span><span class="kw">nrow</span>(qualtrics_<span class="dv">1</span>)</span>
<span id="cb973-3"><a href="a-tibble-3-x-54.html#cb973-3"></a>share_<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">sum</span>(qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">3</span>)<span class="op">/</span><span class="kw">nrow</span>(qualtrics_<span class="dv">1</span>)</span>
<span id="cb973-4"><a href="a-tibble-3-x-54.html#cb973-4"></a>share_<span class="dv">4</span> &lt;-<span class="st"> </span><span class="kw">sum</span>(qualtrics_<span class="dv">1</span><span class="op">$</span>Q2_<span class="dv">4</span>)<span class="op">/</span><span class="kw">nrow</span>(qualtrics_<span class="dv">1</span>)</span></code></pre></div>
<p>Finally, we add category shares to the rest of the data:</p>
<div class="sourceCode" id="cb974"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb974-1"><a href="a-tibble-3-x-54.html#cb974-1"></a>shares &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">share =</span> <span class="kw">rbind</span>(share_<span class="dv">1</span>, share_<span class="dv">2</span>, </span>
<span id="cb974-2"><a href="a-tibble-3-x-54.html#cb974-2"></a>    share_<span class="dv">3</span>, share_<span class="dv">4</span>), <span class="dt">response =</span> <span class="kw">c</span>(<span class="st">&quot;yes, at uni&quot;</span>, </span>
<span id="cb974-3"><a href="a-tibble-3-x-54.html#cb974-3"></a>    <span class="st">&quot;yes, at job&quot;</span>, <span class="st">&quot;yes, other&quot;</span>, <span class="st">&quot;no&quot;</span>))</span>
<span id="cb974-4"><a href="a-tibble-3-x-54.html#cb974-4"></a><span class="kw">head</span>(shares)</span></code></pre></div>
<pre><code>##              share    response
## share_1 0.66666667 yes, at uni
## share_2 0.06944444 yes, at job
## share_3 0.00000000  yes, other
## share_4 0.27777778          no</code></pre>
<div class="infobox_red caution">
<p>If you are not sure which numeric value refers to which label, you can find how to do it under question <strong>“Labels for numeric values in CSV output”</strong>.</p>
</div>
<p>Now we are set to produce a bar chart. Please note two important points:</p>
<ul>
<li><p>We use <code>reorder()</code> function to wrap around the variable on x-axis in aesthetics part of ggplot function. In this way our bar chart will be shown in descending order.</p></li>
<li><p>We use <code>coord_flip()</code> function to turn our bar chart from being vertical to horizontal position.</p></li>
</ul>
<div class="sourceCode" id="cb976"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb976-1"><a href="a-tibble-3-x-54.html#cb976-1"></a><span class="kw">ggplot</span>(shares, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(response, share), <span class="dt">y =</span> share)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb976-2"><a href="a-tibble-3-x-54.html#cb976-2"></a><span class="st">    </span><span class="kw">geom_col</span>(<span class="kw">aes</span>(<span class="dt">fill =</span> response)) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;&quot;</span>, </span>
<span id="cb976-3"><a href="a-tibble-3-x-54.html#cb976-3"></a>    <span class="dt">title =</span> <span class="st">&quot;Share of responses&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">label =</span> <span class="kw">sprintf</span>(<span class="st">&quot;%.0f%%&quot;</span>, </span>
<span id="cb976-4"><a href="a-tibble-3-x-54.html#cb976-4"></a>    share<span class="op">/</span><span class="kw">sum</span>(share) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>)), <span class="dt">hjust =</span> <span class="fl">-0.2</span>, <span class="dt">size =</span> <span class="dv">6</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb976-5"><a href="a-tibble-3-x-54.html#cb976-5"></a><span class="st">    </span><span class="kw">theme_minimal</span>() <span class="op">+</span><span class="st"> </span><span class="kw">ylim</span>(<span class="dv">0</span>, <span class="fl">0.8</span>) <span class="op">+</span><span class="st"> </span><span class="kw">scale_fill_brewer</span>(<span class="dt">palette =</span> <span class="st">&quot;Blues&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb976-6"><a href="a-tibble-3-x-54.html#cb976-6"></a><span class="st">    </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">16</span>), <span class="dt">axis.text.y =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">16</span>), </span>
<span id="cb976-7"><a href="a-tibble-3-x-54.html#cb976-7"></a>        <span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>, <span class="dt">color =</span> <span class="st">&quot;#666666&quot;</span>), </span>
<span id="cb976-8"><a href="a-tibble-3-x-54.html#cb976-8"></a>        <span class="dt">legend.position =</span> <span class="st">&quot;none&quot;</span>, <span class="dt">title =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">20</span>)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb976-9"><a href="a-tibble-3-x-54.html#cb976-9"></a><span class="st">    </span><span class="kw">coord_flip</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-666-1.png" width="672" /></p>
<p>In the end, to save generated plot, we can use <code>ggsave()</code> function. The plot will be saved in your working directory.</p>
<div class="sourceCode" id="cb977"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb977-1"><a href="a-tibble-3-x-54.html#cb977-1"></a><span class="kw">ggsave</span>(<span class="st">&quot;bar_chart.jpg&quot;</span>, <span class="dt">height =</span> <span class="dv">5</span>, <span class="dt">width =</span> <span class="fl">8.5</span>)</span></code></pre></div>
</div>
<div id="how-to-create-a-radar-plot" class="section level3">
<h3><span class="header-section-number">11.1.4</span> How to create a radar plot?</h3>
<p><strong>Issue:</strong> How can I create a radar plot and compare numeric values across different categories or groups?</p>
<p><strong>Solution:</strong></p>
<p>To explain this issue, we will use a data frame with two categories and several numeric variables.</p>
<div class="sourceCode" id="cb978"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb978-1"><a href="a-tibble-3-x-54.html#cb978-1"></a><span class="kw">head</span>(Radar_chart)</span></code></pre></div>
<pre><code>##   R_Stability R_Education R_Healthcare R_Culture I_Stability I_Education
## 1    6.000000    7.000000     6.000000  6.666667           7           7
## 2    4.666667    6.666667     4.666667  6.333333           6           7
## 3    5.333333    5.000000     6.000000  6.333333           7           7
## 4    4.666667    6.000000     3.333333  7.000000           5           7
## 5    4.666667    4.000000     4.666667  6.333333           7           7
## 6    5.000000    5.666667     3.000000  6.333333           7           5
##   I_Healthcare I_Culture
## 1            7         7
## 2            7         7
## 3            7         6
## 4            7         6
## 5            7         5
## 6            7         5</code></pre>
<p>In this data frame we merged two information from a survey:</p>
<ul>
<li>Ranking(R) - how participants evaluated the city of Vienna on the dimensions of stability, education, health care, and culture (the scores for each dimension are derived from multi-item scales consisting of 7-point Likert-scales).</li>
<li>Importance(I) - how important participants judge each of the dimensions to be on a 7-point Likert-scale.</li>
</ul>
<p>We wish to create a radar plot to directly compare ranking and importance of each variable.</p>
<p>First, we create to separate data frames; one for “Ranking”</p>
<div class="sourceCode" id="cb980"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb980-1"><a href="a-tibble-3-x-54.html#cb980-1"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb980-2"><a href="a-tibble-3-x-54.html#cb980-2"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb980-3"><a href="a-tibble-3-x-54.html#cb980-3"></a><span class="kw">library</span>(ggiraph)</span>
<span id="cb980-4"><a href="a-tibble-3-x-54.html#cb980-4"></a><span class="kw">library</span>(ggiraphExtra)</span>
<span id="cb980-5"><a href="a-tibble-3-x-54.html#cb980-5"></a></span>
<span id="cb980-6"><a href="a-tibble-3-x-54.html#cb980-6"></a><span class="co"># Creation of Ranking table</span></span>
<span id="cb980-7"><a href="a-tibble-3-x-54.html#cb980-7"></a>Ranking &lt;-<span class="st"> </span>Radar_chart[, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>]</span>
<span id="cb980-8"><a href="a-tibble-3-x-54.html#cb980-8"></a><span class="co"># Assigning the corresponding row name</span></span>
<span id="cb980-9"><a href="a-tibble-3-x-54.html#cb980-9"></a>Ranking<span class="op">$</span>group &lt;-<span class="st"> &quot;Ranking&quot;</span></span>
<span id="cb980-10"><a href="a-tibble-3-x-54.html#cb980-10"></a></span>
<span id="cb980-11"><a href="a-tibble-3-x-54.html#cb980-11"></a><span class="kw">head</span>(Ranking)</span></code></pre></div>
<pre><code>##   R_Stability R_Education R_Healthcare R_Culture   group
## 1    6.000000    7.000000     6.000000  6.666667 Ranking
## 2    4.666667    6.666667     4.666667  6.333333 Ranking
## 3    5.333333    5.000000     6.000000  6.333333 Ranking
## 4    4.666667    6.000000     3.333333  7.000000 Ranking
## 5    4.666667    4.000000     4.666667  6.333333 Ranking
## 6    5.000000    5.666667     3.000000  6.333333 Ranking</code></pre>
<p>…and one for “Importance”</p>
<div class="sourceCode" id="cb982"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb982-1"><a href="a-tibble-3-x-54.html#cb982-1"></a><span class="co"># Creation of Importance table</span></span>
<span id="cb982-2"><a href="a-tibble-3-x-54.html#cb982-2"></a>Importance &lt;-<span class="st"> </span>Radar_chart[, <span class="dv">5</span><span class="op">:</span><span class="dv">8</span>]</span>
<span id="cb982-3"><a href="a-tibble-3-x-54.html#cb982-3"></a><span class="co"># Assigning the corresponding row name</span></span>
<span id="cb982-4"><a href="a-tibble-3-x-54.html#cb982-4"></a>Importance<span class="op">$</span>group &lt;-<span class="st"> &quot;Importance&quot;</span></span>
<span id="cb982-5"><a href="a-tibble-3-x-54.html#cb982-5"></a><span class="kw">head</span>(Importance)</span></code></pre></div>
<pre><code>##   I_Stability I_Education I_Healthcare I_Culture      group
## 1           7           7            7         7 Importance
## 2           6           7            7         7 Importance
## 3           7           7            7         6 Importance
## 4           5           7            7         6 Importance
## 5           7           7            7         5 Importance
## 6           7           5            7         5 Importance</code></pre>
<p>Now we want to bind these two data frames (Ranking and Importance), but beforehand we need to make sure that they have the same names of columns.</p>
<div class="sourceCode" id="cb984"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb984-1"><a href="a-tibble-3-x-54.html#cb984-1"></a><span class="kw">colnames</span>(Ranking) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Stability&quot;</span>, <span class="st">&quot;Education&quot;</span>, <span class="st">&quot;Healthcare&quot;</span>, </span>
<span id="cb984-2"><a href="a-tibble-3-x-54.html#cb984-2"></a>    <span class="st">&quot;Culture&quot;</span>, <span class="st">&quot;group&quot;</span>)</span>
<span id="cb984-3"><a href="a-tibble-3-x-54.html#cb984-3"></a><span class="kw">colnames</span>(Importance) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Stability&quot;</span>, <span class="st">&quot;Education&quot;</span>, </span>
<span id="cb984-4"><a href="a-tibble-3-x-54.html#cb984-4"></a>    <span class="st">&quot;Healthcare&quot;</span>, <span class="st">&quot;Culture&quot;</span>, <span class="st">&quot;group&quot;</span>)</span></code></pre></div>
<p>Our data frames are now prepared to be combined in one:</p>
<div class="sourceCode" id="cb985"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb985-1"><a href="a-tibble-3-x-54.html#cb985-1"></a><span class="co"># Connecting two data frames by rows</span></span>
<span id="cb985-2"><a href="a-tibble-3-x-54.html#cb985-2"></a>Radar_chart_new &lt;-<span class="st"> </span><span class="kw">rbind</span>(Ranking, Importance)</span></code></pre></div>
<p>Now we can run <code>ggRadar()</code> to create a radar plot:</p>
<div class="sourceCode" id="cb986"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb986-1"><a href="a-tibble-3-x-54.html#cb986-1"></a><span class="co"># Radar plot</span></span>
<span id="cb986-2"><a href="a-tibble-3-x-54.html#cb986-2"></a><span class="kw">ggRadar</span>(<span class="dt">data=</span>Radar_chart_new,</span>
<span id="cb986-3"><a href="a-tibble-3-x-54.html#cb986-3"></a>        <span class="kw">aes</span>(<span class="dt">color=</span>group), <span class="co"># Each category in the column &quot;Name&quot; will be assigned to different color</span></span>
<span id="cb986-4"><a href="a-tibble-3-x-54.html#cb986-4"></a>        <span class="dt">interactive =</span> <span class="ot">FALSE</span>, <span class="co"># When hover over the graph values appear</span></span>
<span id="cb986-5"><a href="a-tibble-3-x-54.html#cb986-5"></a>        <span class="dt">rescale =</span> <span class="ot">FALSE</span>, <span class="co"># If TRUE, all continuous variables in the data.frame are rescaled.</span></span>
<span id="cb986-6"><a href="a-tibble-3-x-54.html#cb986-6"></a>        <span class="dt">ylim =</span> <span class="dv">2</span>, <span class="co"># y coordinates ranges.</span></span>
<span id="cb986-7"><a href="a-tibble-3-x-54.html#cb986-7"></a>        <span class="dt">alpha =</span> <span class="fl">0.35</span>) <span class="co"># Transparency of colors in the graph</span></span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-674-1.png" width="50%" style="display: block; margin: auto;" /></p>
</div>
<div id="vertical-likert-line-chart" class="section level3">
<h3><span class="header-section-number">11.1.5</span> Vertical Likert line chart</h3>
<p>Additionally, we can calculate mean values and compare them with <code>ggPair()</code>:</p>
<div class="sourceCode" id="cb987"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb987-1"><a href="a-tibble-3-x-54.html#cb987-1"></a>Ranking_mean &lt;-<span class="st"> </span><span class="kw">apply</span>(Radar_chart_new[Radar_chart_new<span class="op">$</span>group <span class="op">==</span><span class="st"> </span></span>
<span id="cb987-2"><a href="a-tibble-3-x-54.html#cb987-2"></a><span class="st">    &quot;Ranking&quot;</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>], <span class="dv">2</span>, mean)</span>
<span id="cb987-3"><a href="a-tibble-3-x-54.html#cb987-3"></a>Ranking_mean &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">mean =</span> <span class="kw">t</span>(Ranking_mean), </span>
<span id="cb987-4"><a href="a-tibble-3-x-54.html#cb987-4"></a>    <span class="dt">group =</span> <span class="st">&quot;Ranking&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb988"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb988-1"><a href="a-tibble-3-x-54.html#cb988-1"></a>Importance_mean &lt;-<span class="st"> </span><span class="kw">apply</span>(Radar_chart_new[Radar_chart_new<span class="op">$</span>group <span class="op">==</span><span class="st"> </span></span>
<span id="cb988-2"><a href="a-tibble-3-x-54.html#cb988-2"></a><span class="st">    &quot;Importance&quot;</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>], <span class="dv">2</span>, mean)</span>
<span id="cb988-3"><a href="a-tibble-3-x-54.html#cb988-3"></a>Importance_mean &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">mean =</span> <span class="kw">t</span>(Importance_mean), </span>
<span id="cb988-4"><a href="a-tibble-3-x-54.html#cb988-4"></a>    <span class="dt">group =</span> <span class="st">&quot;Importance&quot;</span>)</span></code></pre></div>
<p>Before plotting we need to bind two data frames by rows:</p>
<div class="sourceCode" id="cb989"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb989-1"><a href="a-tibble-3-x-54.html#cb989-1"></a>Pair_chart &lt;-<span class="st"> </span><span class="kw">rbind</span>(Ranking_mean, Importance_mean)</span>
<span id="cb989-2"><a href="a-tibble-3-x-54.html#cb989-2"></a>Pair_chart<span class="op">$</span>group &lt;-<span class="st"> </span><span class="kw">as.factor</span>(Pair_chart<span class="op">$</span>group)</span></code></pre></div>
<p>Finally, we can create a pair plot:</p>
<div class="sourceCode" id="cb990"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb990-1"><a href="a-tibble-3-x-54.html#cb990-1"></a><span class="co"># Pair plot</span></span>
<span id="cb990-2"><a href="a-tibble-3-x-54.html#cb990-2"></a><span class="kw">ggPair</span>(Pair_chart, <span class="dt">horizontal =</span> <span class="ot">TRUE</span>, <span class="dt">interactive =</span> <span class="ot">FALSE</span>, </span>
<span id="cb990-3"><a href="a-tibble-3-x-54.html#cb990-3"></a>    <span class="kw">aes</span>(<span class="dt">color =</span> group))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-678-1.png" width="672" /></p>
</div>
<div id="diverging-stacked-barchart" class="section level3">
<h3><span class="header-section-number">11.1.6</span> Diverging stacked barchart</h3>
<p>Let’s use an example data frame again, where we observe the scores on 4 variables on a 7-point Likert-scale.</p>
<div class="sourceCode" id="cb991"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb991-1"><a href="a-tibble-3-x-54.html#cb991-1"></a><span class="kw">head</span>(likert_chart)</span></code></pre></div>
<pre><code>##   I_Stability I_Education I_Healthcare I_Culture
## 1           7           7            7         7
## 2           6           7            7         7
## 3           7           7            7         6
## 4           5           7            7         6
## 5           7           7            7         5
## 6           7           5            7         5</code></pre>
<p>Now we can use the <code>likert()</code> function from the <code>HH</code> package to create the Diverging stacked barchart as follows:</p>
<div class="sourceCode" id="cb993"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb993-1"><a href="a-tibble-3-x-54.html#cb993-1"></a><span class="kw">library</span>(HH)</span>
<span id="cb993-2"><a href="a-tibble-3-x-54.html#cb993-2"></a><span class="kw">likert</span>(<span class="kw">t</span>(likert_chart)[, <span class="dv">7</span><span class="op">:</span><span class="dv">1</span>], <span class="dt">horizontal =</span> <span class="ot">TRUE</span>, <span class="dt">main =</span> <span class="st">&quot;Diverging stacked barcharts&quot;</span>, </span>
<span id="cb993-3"><a href="a-tibble-3-x-54.html#cb993-3"></a>    <span class="dt">xlab =</span> <span class="st">&quot;Percent&quot;</span>, <span class="dt">auto.key =</span> <span class="kw">list</span>(<span class="dt">space =</span> <span class="st">&quot;right&quot;</span>, </span>
<span id="cb993-4"><a href="a-tibble-3-x-54.html#cb993-4"></a>        <span class="dt">columns =</span> <span class="dv">1</span>, <span class="dt">reverse =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-681-1.png" width="672" /></p>
</div>
<div id="collapserecode-categories" class="section level3">
<h3><span class="header-section-number">11.1.7</span> Collapse/recode categories</h3>
<p><strong>Issue:</strong> If you have certain number of categories (e.g. countries) and you would like to aggregate them by specific criteria (e.g. continents), how can you do it?</p>
<p><strong>Solution:</strong></p>
<p>There are several ways to do it, but we will show you the most intuitive.</p>
<p>For this purpose we will create a data frame:</p>
<div class="sourceCode" id="cb994"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb994-1"><a href="a-tibble-3-x-54.html#cb994-1"></a><span class="co"># generate random data</span></span>
<span id="cb994-2"><a href="a-tibble-3-x-54.html#cb994-2"></a>df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">country_id =</span> <span class="kw">round</span>(<span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">100</span>, </span>
<span id="cb994-3"><a href="a-tibble-3-x-54.html#cb994-3"></a>    <span class="dt">min =</span> <span class="dv">1</span>, <span class="dt">max =</span> <span class="dv">7</span>), <span class="dv">0</span>))</span>
<span id="cb994-4"><a href="a-tibble-3-x-54.html#cb994-4"></a><span class="co"># code factor variable for country</span></span>
<span id="cb994-5"><a href="a-tibble-3-x-54.html#cb994-5"></a>df<span class="op">$</span>country &lt;-<span class="st"> </span><span class="kw">factor</span>(df<span class="op">$</span>country_id, <span class="dt">levels =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">7</span>, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Bangladesh&quot;</span>, </span>
<span id="cb994-6"><a href="a-tibble-3-x-54.html#cb994-6"></a>    <span class="st">&quot;Japan&quot;</span>, <span class="st">&quot;Austria&quot;</span>, <span class="st">&quot;Germany&quot;</span>, <span class="st">&quot;Italy&quot;</span>, <span class="st">&quot;USA&quot;</span>, </span>
<span id="cb994-7"><a href="a-tibble-3-x-54.html#cb994-7"></a>    <span class="st">&quot;Taiwan&quot;</span>))</span>
<span id="cb994-8"><a href="a-tibble-3-x-54.html#cb994-8"></a><span class="kw">str</span>(df)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    100 obs. of  2 variables:
##  $ country_id: num  2 4 5 6 4 3 6 1 4 6 ...
##  $ country   : Factor w/ 7 levels &quot;Bangladesh&quot;,&quot;Japan&quot;,..: 2 4 5 6 4 3 6 1 4 6 ...</code></pre>
<p>In our data frame we have two columns, “country_id” and “country”.</p>
<p>Now we will create a third column, “region”, and assign each country to corresponding continent. For that purpose, we use <code>recode</code> function to assign region by country and create new variable for region:</p>
<div class="sourceCode" id="cb996"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb996-1"><a href="a-tibble-3-x-54.html#cb996-1"></a><span class="kw">library</span>(car)</span>
<span id="cb996-2"><a href="a-tibble-3-x-54.html#cb996-2"></a>df<span class="op">$</span>region =<span class="st"> </span><span class="kw">recode</span>(df<span class="op">$</span>country, <span class="st">&quot;&#39;Bangladesh&#39;=&#39;Asia&#39;; &#39;Japan&#39;=&#39;Asia&#39;; &#39;Austria&#39;=&#39;Europe&#39;; &#39;Germany&#39;=&#39;Europe&#39;; &#39;Italy&#39;=&#39;Europe&#39;; &#39;Taiwan&#39;=&#39;Asia&#39;; &#39;USA&#39;=&#39;other&#39;&quot;</span>)</span>
<span id="cb996-3"><a href="a-tibble-3-x-54.html#cb996-3"></a><span class="kw">head</span>(df)</span></code></pre></div>
<pre><code>##   country_id country region
## 1          2   Japan   Asia
## 2          4 Germany Europe
## 3          5   Italy Europe
## 4          6     USA  other
## 5          4 Germany Europe
## 6          3 Austria Europe</code></pre>
<p>This also works with numeric values:</p>
<div class="sourceCode" id="cb998"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb998-1"><a href="a-tibble-3-x-54.html#cb998-1"></a>df<span class="op">$</span>region_<span class="dv">1</span> =<span class="st"> </span><span class="kw">as.factor</span>(<span class="kw">recode</span>(df<span class="op">$</span>country_id, <span class="st">&quot;1=&#39;Asia&#39;; 2=&#39;Asia&#39;; 3=&#39;Europe&#39;; 3=&#39;Europe&#39;; 4=&#39;Europe&#39;; 5=&#39;Asia&#39;; 6=&#39;other&#39;; 7 = &#39;Asia&#39;&quot;</span>))</span>
<span id="cb998-2"><a href="a-tibble-3-x-54.html#cb998-2"></a><span class="kw">head</span>(df)</span></code></pre></div>
<pre><code>##   country_id country region region_1
## 1          2   Japan   Asia     Asia
## 2          4 Germany Europe   Europe
## 3          5   Italy Europe     Asia
## 4          6     USA  other    other
## 5          4 Germany Europe   Europe
## 6          3 Austria Europe   Europe</code></pre>
<p>Alternatively, you can use <code>gsub()</code> function to replace each category individually:</p>
<div class="sourceCode" id="cb1000"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1000-1"><a href="a-tibble-3-x-54.html#cb1000-1"></a>df<span class="op">$</span>region_<span class="dv">2</span> =<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;Bangladesh&quot;</span>, <span class="st">&quot;Asia&quot;</span>, df<span class="op">$</span>country)</span>
<span id="cb1000-2"><a href="a-tibble-3-x-54.html#cb1000-2"></a>df<span class="op">$</span>region_<span class="dv">2</span> =<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;Japan&quot;</span>, <span class="st">&quot;Asia&quot;</span>, df<span class="op">$</span>region_<span class="dv">2</span>)</span>
<span id="cb1000-3"><a href="a-tibble-3-x-54.html#cb1000-3"></a>df<span class="op">$</span>region_<span class="dv">2</span> =<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;Austria&quot;</span>, <span class="st">&quot;Europe&quot;</span>, df<span class="op">$</span>region_<span class="dv">2</span>)</span>
<span id="cb1000-4"><a href="a-tibble-3-x-54.html#cb1000-4"></a>df<span class="op">$</span>region_<span class="dv">2</span> =<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;Germany&quot;</span>, <span class="st">&quot;Europe&quot;</span>, df<span class="op">$</span>region_<span class="dv">2</span>)</span>
<span id="cb1000-5"><a href="a-tibble-3-x-54.html#cb1000-5"></a>df<span class="op">$</span>region_<span class="dv">2</span> =<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;Italy&quot;</span>, <span class="st">&quot;Europe&quot;</span>, df<span class="op">$</span>region_<span class="dv">2</span>)</span>
<span id="cb1000-6"><a href="a-tibble-3-x-54.html#cb1000-6"></a>df<span class="op">$</span>region_<span class="dv">2</span> =<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;Taiwan&quot;</span>, <span class="st">&quot;Asia&quot;</span>, df<span class="op">$</span>region_<span class="dv">2</span>)</span>
<span id="cb1000-7"><a href="a-tibble-3-x-54.html#cb1000-7"></a>df<span class="op">$</span>region_<span class="dv">2</span> =<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;USA&quot;</span>, <span class="st">&quot;other&quot;</span>, df<span class="op">$</span>region_<span class="dv">2</span>)</span>
<span id="cb1000-8"><a href="a-tibble-3-x-54.html#cb1000-8"></a>df<span class="op">$</span>region_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">as.factor</span>(df<span class="op">$</span>region_<span class="dv">2</span>)</span>
<span id="cb1000-9"><a href="a-tibble-3-x-54.html#cb1000-9"></a><span class="kw">head</span>(df)</span></code></pre></div>
<pre><code>##   country_id country region region_1 region_2
## 1          2   Japan   Asia     Asia     Asia
## 2          4 Germany Europe   Europe   Europe
## 3          5   Italy Europe     Asia   Europe
## 4          6     USA  other    other    other
## 5          4 Germany Europe   Europe   Europe
## 6          3 Austria Europe   Europe   Europe</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="survey-design-analysis.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
