<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Marketing Research Design &amp; Analysis 2017</title>
  <meta name="description" content="An Introduction to Statistics Using R">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Marketing Research Design &amp; Analysis 2017" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An Introduction to Statistics Using R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Marketing Research Design &amp; Analysis 2017" />
  
  <meta name="twitter:description" content="An Introduction to Statistics Using R" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="exploratory-factor-analysis.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<script src="libs/htmlwidgets-1.0/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.7.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotlyjs-1.29.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotlyjs-1.29.2/plotly-latest.min.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">MRDA 2017</a></strong></li>
<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a></li>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html"><i class="fa fa-check"></i>Course materials</a><ul>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html#main-reference"><i class="fa fa-check"></i>Main reference</a></li>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html#further-readings"><i class="fa fa-check"></i>Further readings</a></li>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html#datacamp"><i class="fa fa-check"></i>DataCamp</a></li>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html#other-web-resources"><i class="fa fa-check"></i>Other web-resources</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting started</a><ul>
<li class="chapter" data-level="1.1" data-path="getting-started.html"><a href="getting-started.html#why-r"><i class="fa fa-check"></i><b>1.1</b> Why R?</a></li>
<li class="chapter" data-level="1.2" data-path="getting-started.html"><a href="getting-started.html#how-to-download-and-install-r-and-rstudio"><i class="fa fa-check"></i><b>1.2</b> How to download and install R and RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="getting-started.html"><a href="getting-started.html#getting-help"><i class="fa fa-check"></i><b>1.3</b> Getting help</a></li>
<li class="chapter" data-level="1.4" data-path="getting-started.html"><a href="getting-started.html#functions"><i class="fa fa-check"></i><b>1.4</b> Functions</a></li>
<li class="chapter" data-level="1.5" data-path="getting-started.html"><a href="getting-started.html#packages"><i class="fa fa-check"></i><b>1.5</b> Packages</a></li>
<li class="chapter" data-level="1.6" data-path="getting-started.html"><a href="getting-started.html#a-typical-r-session"><i class="fa fa-check"></i><b>1.6</b> A typical R session</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basic-data-handling.html"><a href="basic-data-handling.html"><i class="fa fa-check"></i><b>2</b> Basic data handling</a><ul>
<li class="chapter" data-level="2.1" data-path="basic-data-handling.html"><a href="basic-data-handling.html#creating-objects"><i class="fa fa-check"></i><b>2.1</b> Creating objects</a></li>
<li class="chapter" data-level="2.2" data-path="basic-data-handling.html"><a href="basic-data-handling.html#data-types"><i class="fa fa-check"></i><b>2.2</b> Data types</a></li>
<li class="chapter" data-level="2.3" data-path="basic-data-handling.html"><a href="basic-data-handling.html#data-structures"><i class="fa fa-check"></i><b>2.3</b> Data structures</a><ul>
<li class="chapter" data-level="2.3.1" data-path="basic-data-handling.html"><a href="basic-data-handling.html#accessing-data-in-data-frames"><i class="fa fa-check"></i><b>2.3.1</b> Accessing data in data frames</a></li>
<li class="chapter" data-level="2.3.2" data-path="basic-data-handling.html"><a href="basic-data-handling.html#inspecting-the-content-of-a-data-frame"><i class="fa fa-check"></i><b>2.3.2</b> Inspecting the content of a data frame</a></li>
<li class="chapter" data-level="2.3.3" data-path="basic-data-handling.html"><a href="basic-data-handling.html#append-and-delete-variables-tofrom-data-frames"><i class="fa fa-check"></i><b>2.3.3</b> Append and delete variables to/from data frames</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-import-and-export.html"><a href="data-import-and-export.html"><i class="fa fa-check"></i><b>3</b> Data import and export</a><ul>
<li class="chapter" data-level="3.1" data-path="data-import-and-export.html"><a href="data-import-and-export.html#getting-data-for-this-course"><i class="fa fa-check"></i><b>3.1</b> Getting data for this course</a><ul>
<li class="chapter" data-level="3.1.1" data-path="data-import-and-export.html"><a href="data-import-and-export.html#directly-import-datasets-from-github-recommended"><i class="fa fa-check"></i><b>3.1.1</b> Directly import datasets from GitHub (recommended)</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-import-and-export.html"><a href="data-import-and-export.html#download-and-import-datasets-from-learnwu"><i class="fa fa-check"></i><b>3.1.2</b> Download and import datasets from “Learn@WU”</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-import-and-export.html"><a href="data-import-and-export.html#import-data-created-by-other-software-packages"><i class="fa fa-check"></i><b>3.2</b> Import data created by other software packages</a></li>
<li class="chapter" data-level="3.3" data-path="data-import-and-export.html"><a href="data-import-and-export.html#export-data"><i class="fa fa-check"></i><b>3.3</b> Export data</a></li>
<li class="chapter" data-level="3.4" data-path="data-import-and-export.html"><a href="data-import-and-export.html#import-data-from-the-web"><i class="fa fa-check"></i><b>3.4</b> Import data from the Web</a><ul>
<li class="chapter" data-level="3.4.1" data-path="data-import-and-export.html"><a href="data-import-and-export.html#scraping-data-from-websites"><i class="fa fa-check"></i><b>3.4.1</b> Scraping data from websites</a></li>
<li class="chapter" data-level="3.4.2" data-path="data-import-and-export.html"><a href="data-import-and-export.html#scraping-data-from-apis"><i class="fa fa-check"></i><b>3.4.2</b> Scraping data from APIs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="random-variables.html"><a href="random-variables.html"><i class="fa fa-check"></i><b>4</b> Random Variables</a><ul>
<li class="chapter" data-level="4.1" data-path="random-variables.html"><a href="random-variables.html#definitions"><i class="fa fa-check"></i><b>4.1</b> Definitions</a><ul>
<li class="chapter" data-level="4.1.1" data-path="random-variables.html"><a href="random-variables.html#why-random-variables"><i class="fa fa-check"></i><b>4.1.1</b> Why Random Variables?</a></li>
<li class="chapter" data-level="4.1.2" data-path="random-variables.html"><a href="random-variables.html#discrete-random-variables"><i class="fa fa-check"></i><b>4.1.2</b> Discrete Random Variables</a></li>
<li class="chapter" data-level="4.1.3" data-path="random-variables.html"><a href="random-variables.html#continuous-case"><i class="fa fa-check"></i><b>4.1.3</b> Continuous Case</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="summary-statistics.html"><a href="summary-statistics.html"><i class="fa fa-check"></i><b>5</b> Summary statistics</a><ul>
<li class="chapter" data-level="5.1" data-path="summary-statistics.html"><a href="summary-statistics.html#categorical-variables"><i class="fa fa-check"></i><b>5.1</b> Categorical variables</a></li>
<li class="chapter" data-level="5.2" data-path="summary-statistics.html"><a href="summary-statistics.html#continuous-variables"><i class="fa fa-check"></i><b>5.2</b> Continuous variables</a><ul>
<li class="chapter" data-level="5.2.1" data-path="summary-statistics.html"><a href="summary-statistics.html#descriptive-statistics"><i class="fa fa-check"></i><b>5.2.1</b> Descriptive statistics</a></li>
<li class="chapter" data-level="5.2.2" data-path="summary-statistics.html"><a href="summary-statistics.html#creating-subsets"><i class="fa fa-check"></i><b>5.2.2</b> Creating subsets</a></li>
<li class="chapter" data-level="5.2.3" data-path="summary-statistics.html"><a href="summary-statistics.html#confidence-intervals"><i class="fa fa-check"></i><b>5.2.3</b> Confidence intervals</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>6</b> Data visualization</a><ul>
<li class="chapter" data-level="6.1" data-path="data-visualization.html"><a href="data-visualization.html#categorical-variables-1"><i class="fa fa-check"></i><b>6.1</b> Categorical variables</a><ul>
<li class="chapter" data-level="6.1.1" data-path="data-visualization.html"><a href="data-visualization.html#bar-plot"><i class="fa fa-check"></i><b>6.1.1</b> Bar plot</a></li>
<li class="chapter" data-level="6.1.2" data-path="data-visualization.html"><a href="data-visualization.html#covariation-plots"><i class="fa fa-check"></i><b>6.1.2</b> Covariation plots</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="data-visualization.html"><a href="data-visualization.html#continuous-variables-1"><i class="fa fa-check"></i><b>6.2</b> Continuous variables</a><ul>
<li class="chapter" data-level="6.2.1" data-path="data-visualization.html"><a href="data-visualization.html#histogram"><i class="fa fa-check"></i><b>6.2.1</b> Histogram</a></li>
<li class="chapter" data-level="6.2.2" data-path="data-visualization.html"><a href="data-visualization.html#boxplot"><i class="fa fa-check"></i><b>6.2.2</b> Boxplot</a></li>
<li class="chapter" data-level="6.2.3" data-path="data-visualization.html"><a href="data-visualization.html#plot-of-means"><i class="fa fa-check"></i><b>6.2.3</b> Plot of means</a></li>
<li class="chapter" data-level="6.2.4" data-path="data-visualization.html"><a href="data-visualization.html#scatter-plot"><i class="fa fa-check"></i><b>6.2.4</b> Scatter plot</a></li>
<li class="chapter" data-level="6.2.5" data-path="data-visualization.html"><a href="data-visualization.html#line-plot"><i class="fa fa-check"></i><b>6.2.5</b> Line plot</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="data-visualization.html"><a href="data-visualization.html#saving-plots"><i class="fa fa-check"></i><b>6.3</b> Saving plots</a></li>
<li class="chapter" data-level="6.4" data-path="data-visualization.html"><a href="data-visualization.html#additional-options"><i class="fa fa-check"></i><b>6.4</b> Additional options</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>7</b> Hypothesis testing</a><ul>
<li class="chapter" data-level="7.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction"><i class="fa fa-check"></i><b>7.1</b> Introduction</a><ul>
<li class="chapter" data-level="7.1.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#why-do-we-test-hypotheses"><i class="fa fa-check"></i><b>7.1.1</b> Why do we test hypotheses?</a></li>
<li class="chapter" data-level="7.1.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#the-process-of-hypothesis-testing"><i class="fa fa-check"></i><b>7.1.2</b> The process of hypothesis testing</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#parametric-tests"><i class="fa fa-check"></i><b>7.2</b> Parametric tests</a><ul>
<li class="chapter" data-level="7.2.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#independent-means-t-test"><i class="fa fa-check"></i><b>7.2.1</b> Independent-means t-test</a></li>
<li class="chapter" data-level="7.2.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#dependent-means-t-test"><i class="fa fa-check"></i><b>7.2.2</b> Dependent-means t-test</a></li>
<li class="chapter" data-level="7.2.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-sample-t-test"><i class="fa fa-check"></i><b>7.2.3</b> One-sample t-test</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#non-parametric-tests"><i class="fa fa-check"></i><b>7.3</b> Non-parametric tests</a><ul>
<li class="chapter" data-level="7.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#mann-whitney-u-test-a.k.a.-wilcoxon-rank-sum-test"><i class="fa fa-check"></i><b>7.3.1</b> Mann-Whitney U Test (a.k.a. Wilcoxon rank-sum test)</a></li>
<li class="chapter" data-level="7.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>7.3.2</b> Wilcoxon signed-rank test</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#categorical-data"><i class="fa fa-check"></i><b>7.4</b> Categorical data</a><ul>
<li class="chapter" data-level="7.4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#comparing-proportions"><i class="fa fa-check"></i><b>7.4.1</b> Comparing proportions</a></li>
<li class="chapter" data-level="7.4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#chi-square-test"><i class="fa fa-check"></i><b>7.4.2</b> Chi-square test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html"><i class="fa fa-check"></i><b>8</b> Analysis of variance</a><ul>
<li class="chapter" data-level="8.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#introduction-1"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#decomposing-variance"><i class="fa fa-check"></i><b>8.2</b> Decomposing variance</a><ul>
<li class="chapter" data-level="8.2.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#total-sum-of-squares"><i class="fa fa-check"></i><b>8.2.1</b> Total sum of squares</a></li>
<li class="chapter" data-level="8.2.2" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#model-sum-of-squares"><i class="fa fa-check"></i><b>8.2.2</b> Model sum of squares</a></li>
<li class="chapter" data-level="8.2.3" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#residual-sum-of-squares"><i class="fa fa-check"></i><b>8.2.3</b> Residual sum of squares</a></li>
<li class="chapter" data-level="8.2.4" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#effect-strength"><i class="fa fa-check"></i><b>8.2.4</b> Effect strength</a></li>
<li class="chapter" data-level="8.2.5" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#test-of-significance"><i class="fa fa-check"></i><b>8.2.5</b> Test of significance</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#one-way-anova"><i class="fa fa-check"></i><b>8.3</b> One-way ANOVA</a><ul>
<li class="chapter" data-level="8.3.1" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#basic-anova"><i class="fa fa-check"></i><b>8.3.1</b> Basic ANOVA</a></li>
<li class="chapter" data-level="8.3.2" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#post-hoc-tests"><i class="fa fa-check"></i><b>8.3.2</b> Post-hoc tests</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#n-way-anova"><i class="fa fa-check"></i><b>8.4</b> N-way ANOVA</a></li>
<li class="chapter" data-level="8.5" data-path="analysis-of-variance.html"><a href="analysis-of-variance.html#non-parametric-tests-1"><i class="fa fa-check"></i><b>8.5</b> Non-parametric tests</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>9</b> Regression</a><ul>
<li class="chapter" data-level="9.1" data-path="regression.html"><a href="regression.html#correlation"><i class="fa fa-check"></i><b>9.1</b> Correlation</a><ul>
<li class="chapter" data-level="9.1.1" data-path="regression.html"><a href="regression.html#correlation-coefficient"><i class="fa fa-check"></i><b>9.1.1</b> Correlation coefficient</a></li>
<li class="chapter" data-level="9.1.2" data-path="regression.html"><a href="regression.html#significance-testing"><i class="fa fa-check"></i><b>9.1.2</b> Significance testing</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="regression.html"><a href="regression.html#regression-1"><i class="fa fa-check"></i><b>9.2</b> Regression</a><ul>
<li class="chapter" data-level="9.2.1" data-path="regression.html"><a href="regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>9.2.1</b> Simple linear regression</a></li>
<li class="chapter" data-level="9.2.2" data-path="regression.html"><a href="regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>9.2.2</b> Multiple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="regression.html"><a href="regression.html#potential-problems"><i class="fa fa-check"></i><b>9.3</b> Potential problems</a><ul>
<li class="chapter" data-level="9.3.1" data-path="regression.html"><a href="regression.html#outliers"><i class="fa fa-check"></i><b>9.3.1</b> Outliers</a></li>
<li class="chapter" data-level="9.3.2" data-path="regression.html"><a href="regression.html#influential-observations"><i class="fa fa-check"></i><b>9.3.2</b> Influential observations</a></li>
<li class="chapter" data-level="9.3.3" data-path="regression.html"><a href="regression.html#non-linearity"><i class="fa fa-check"></i><b>9.3.3</b> Non-linearity</a></li>
<li class="chapter" data-level="9.3.4" data-path="regression.html"><a href="regression.html#non-constant-error-variance"><i class="fa fa-check"></i><b>9.3.4</b> Non-constant error variance</a></li>
<li class="chapter" data-level="9.3.5" data-path="regression.html"><a href="regression.html#non-normally-distributed-errors"><i class="fa fa-check"></i><b>9.3.5</b> Non-normally distributed errors</a></li>
<li class="chapter" data-level="9.3.6" data-path="regression.html"><a href="regression.html#correlation-of-errors"><i class="fa fa-check"></i><b>9.3.6</b> Correlation of errors</a></li>
<li class="chapter" data-level="9.3.7" data-path="regression.html"><a href="regression.html#collinearity"><i class="fa fa-check"></i><b>9.3.7</b> Collinearity</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="regression.html"><a href="regression.html#categorical-predictors"><i class="fa fa-check"></i><b>9.4</b> Categorical predictors</a><ul>
<li class="chapter" data-level="9.4.1" data-path="regression.html"><a href="regression.html#two-categories"><i class="fa fa-check"></i><b>9.4.1</b> Two categories</a></li>
<li class="chapter" data-level="9.4.2" data-path="regression.html"><a href="regression.html#more-than-two-categories"><i class="fa fa-check"></i><b>9.4.2</b> More than two categories</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="regression.html"><a href="regression.html#extensions-of-the-linear-model"><i class="fa fa-check"></i><b>9.5</b> Extensions of the linear model</a><ul>
<li class="chapter" data-level="9.5.1" data-path="regression.html"><a href="regression.html#interaction-effects"><i class="fa fa-check"></i><b>9.5.1</b> Interaction effects</a></li>
<li class="chapter" data-level="9.5.2" data-path="regression.html"><a href="regression.html#non-linear-relationships"><i class="fa fa-check"></i><b>9.5.2</b> Non-linear relationships</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html"><i class="fa fa-check"></i><b>10</b> Exploratory factor analysis</a><ul>
<li class="chapter" data-level="10.1" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#introduction-2"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#steps-in-factor-analysis"><i class="fa fa-check"></i><b>10.2</b> Steps in factor analysis</a><ul>
<li class="chapter" data-level="10.2.1" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#are-the-assumptions-satisfied"><i class="fa fa-check"></i><b>10.2.1</b> Are the assumptions satisfied?</a></li>
<li class="chapter" data-level="10.2.2" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#deriving-factors"><i class="fa fa-check"></i><b>10.2.2</b> Deriving factors</a></li>
<li class="chapter" data-level="10.2.3" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#factor-interpretation"><i class="fa fa-check"></i><b>10.2.3</b> Factor interpretation</a></li>
<li class="chapter" data-level="10.2.4" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#creating-new-variables"><i class="fa fa-check"></i><b>10.2.4</b> Creating new variables</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#reliability-analysis"><i class="fa fa-check"></i><b>10.3</b> Reliability analysis</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="assignments.html"><a href="assignments.html"><i class="fa fa-check"></i><b>11</b> Assignments</a><ul>
<li class="chapter" data-level="11.1" data-path="assignments.html"><a href="assignments.html#assignment-2-hypothesis-testing"><i class="fa fa-check"></i><b>11.1</b> Assignment 2 (Hypothesis Testing)</a><ul>
<li class="chapter" data-level="11.1.1" data-path="assignments.html"><a href="assignments.html#load-data"><i class="fa fa-check"></i><b>11.1.1</b> Load data</a></li>
<li class="chapter" data-level="11.1.2" data-path="assignments.html"><a href="assignments.html#question-1"><i class="fa fa-check"></i><b>11.1.2</b> Question 1</a></li>
<li class="chapter" data-level="11.1.3" data-path="assignments.html"><a href="assignments.html#question-2"><i class="fa fa-check"></i><b>11.1.3</b> Question 2</a></li>
<li class="chapter" data-level="11.1.4" data-path="assignments.html"><a href="assignments.html#question-3"><i class="fa fa-check"></i><b>11.1.4</b> Question 3</a></li>
<li class="chapter" data-level="11.1.5" data-path="assignments.html"><a href="assignments.html#question-4"><i class="fa fa-check"></i><b>11.1.5</b> Question 4</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="assignments.html"><a href="assignments.html#assignment-3-anova"><i class="fa fa-check"></i><b>11.2</b> Assignment 3 (Anova)</a><ul>
<li class="chapter" data-level="11.2.1" data-path="assignments.html"><a href="assignments.html#load-data-1"><i class="fa fa-check"></i><b>11.2.1</b> Load data</a></li>
<li class="chapter" data-level="11.2.2" data-path="assignments.html"><a href="assignments.html#question-1-1"><i class="fa fa-check"></i><b>11.2.2</b> Question 1</a></li>
<li class="chapter" data-level="11.2.3" data-path="assignments.html"><a href="assignments.html#question-2-1"><i class="fa fa-check"></i><b>11.2.3</b> Question 2</a></li>
<li class="chapter" data-level="11.2.4" data-path="assignments.html"><a href="assignments.html#question-3-1"><i class="fa fa-check"></i><b>11.2.4</b> Question 3</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="assignments.html"><a href="assignments.html#assignment-4-regression"><i class="fa fa-check"></i><b>11.3</b> Assignment 4 (Regression)</a><ul>
<li class="chapter" data-level="11.3.1" data-path="assignments.html"><a href="assignments.html#load-data-2"><i class="fa fa-check"></i><b>11.3.1</b> Load data</a></li>
<li class="chapter" data-level="11.3.2" data-path="assignments.html"><a href="assignments.html#question-1-2"><i class="fa fa-check"></i><b>11.3.2</b> Question 1</a></li>
<li class="chapter" data-level="11.3.3" data-path="assignments.html"><a href="assignments.html#question-2-2"><i class="fa fa-check"></i><b>11.3.3</b> Question 2</a></li>
<li class="chapter" data-level="11.3.4" data-path="assignments.html"><a href="assignments.html#question-3-2"><i class="fa fa-check"></i><b>11.3.4</b> Question 3</a></li>
<li class="chapter" data-level="11.3.5" data-path="assignments.html"><a href="assignments.html#question-4-1"><i class="fa fa-check"></i><b>11.3.5</b> Question 4</a></li>
<li class="chapter" data-level="11.3.6" data-path="assignments.html"><a href="assignments.html#question-5"><i class="fa fa-check"></i><b>11.3.6</b> Question 5</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Marketing Research Design &amp; Analysis 2017</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="assignments" class="section level1">
<h1><span class="header-section-number">11</span> Assignments</h1>
<p><strong>Note that depending on which data set you received, your results might differ slightly from the results presented here!</strong></p>
<div id="assignment-2-hypothesis-testing" class="section level2">
<h2><span class="header-section-number">11.1</span> Assignment 2 (Hypothesis Testing)</h2>
<p>As a marketing manager at a video streaming service, you are interested in the effect of online advertising on the number of streams that a movie receives. To test the effect of online advertising on streams, you select a representative sample of 200 movies and randomly assign 100 movies to be included in an online advertising campaign. The other half of the sample serves as the control group. You run the experiment for one week and collect data regarding the number of streams from this period. In addition, you collect other variables about the movies that you wish to analyze. Overall, the data set includes the following variables:</p>
<ul>
<li>movieID: unique movie ID</li>
<li>streams_sd: number of streams in SD-quality</li>
<li>streams_hd: number of streams in HD-quality</li>
<li>online_advertising: indicator whether a movie was included in the online advertising campaign (0 = no, 1 = yes)</li>
<li>customer_rating: satisfaction measured on a 5-point Likert scale after the moviews were watched: (1) “very dissatisfied” – (5) “very satisfied”&quot;</li>
<li>academy_award: 0= non-nominated film, 1=nominated film</li>
<li>genre: 1 = drama, 2 = romance, 3 = comedy, 4 = thriller, 5 = action</li>
</ul>
<p>Apply appropriate statistical methods to answer the following questions:</p>
<ol style="list-style-type: decimal">
<li>Is there a significant difference in streams between movies that were included in the online advertising campaign and those that were not included? (Please conduct the test for SD and HD movies)</li>
<li>Is there a significant difference in streams between movies in HD and SD quality?</li>
<li>Is there a significant association between the genre of a movie and the academy award nomination?</li>
<li>Is there a significant difference in customer ratings between nominated and non-nominated movies?</li>
</ol>
<p>When answering the questions, please remember to address the following points:</p>
<ul>
<li>Formulate the corresponding hypotheses and choose an appropriate statistical test</li>
<li>Provide the reason for your choice and discuss if the assumptions of the test are met</li>
<li>Convert the variables to the appropriate type (e.g., factor variables)</li>
<li>Create appropriate graphs to explore the data (e.g., boxplot, bar chart, histogram)</li>
<li>Provide appropriate descriptive statistics for the variables</li>
<li>Report and interpret the test results accurately (including confidence intervals where appropriate)<br />
</li>
<li>Finally, don’t forget to report your research conclusion in an appropriate way</li>
</ul>
<p>When you are done with your analysis, click on “Knit to HTML” button above the code editor. This will create a HTML document of your results in the folder where the “assignment.Rmd” file is stored. Open this file in your Internet browser to see if the output is correct. If the output is correct, submit the HTML file via Learn@WU. The file name should be “assignment2_studendID_name.html”.</p>
<div id="load-data" class="section level3">
<h3><span class="header-section-number">11.1.1</span> Load data</h3>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["streams_sd"],"name":[1],"type":["int"],"align":["right"]},{"label":["online_advertising"],"name":[2],"type":["int"],"align":["right"]},{"label":["customer_rating"],"name":[3],"type":["int"],"align":["right"]},{"label":["streams_hd"],"name":[4],"type":["int"],"align":["right"]},{"label":["movieID"],"name":[5],"type":["int"],"align":["right"]},{"label":["genre"],"name":[6],"type":["int"],"align":["right"]},{"label":["academy_award"],"name":[7],"type":["int"],"align":["right"]}],"data":[{"1":"3511","2":"0","3":"5","4":"1468","5":"1","6":"1","7":"1"},{"1":"3068","2":"0","3":"5","4":"2164","5":"2","6":"1","7":"1"},{"1":"2445","2":"1","3":"3","4":"2164","5":"3","6":"1","7":"1"},{"1":"3839","2":"1","3":"3","4":"1762","5":"4","6":"1","7":"0"},{"1":"3180","2":"0","3":"4","4":"1524","5":"5","6":"1","7":"1"},{"1":"4369","2":"1","3":"5","4":"1697","5":"6","6":"1","7":"1"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre><code>## &#39;data.frame&#39;:    200 obs. of  7 variables:
##  $ streams_sd        : int  3511 3068 2445 3839 3180 4369 1187 2829 2222 1139 ...
##  $ online_advertising: int  0 0 1 1 0 1 0 1 1 0 ...
##  $ customer_rating   : int  5 5 3 3 4 5 3 5 1 2 ...
##  $ streams_hd        : int  1468 2164 2164 1762 1524 1697 1883 1730 1870 760 ...
##  $ movieID           : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ genre             : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ academy_award     : int  1 1 1 0 1 1 1 1 1 1 ...</code></pre>
<p>The first step is to load the required packages for visualization and descriptive statistcs.</p>
<p>Note that these packages should be installed prior to creating the HTML output from the .Rmd file.</p>
</div>
<div id="question-1" class="section level3">
<h3><span class="header-section-number">11.1.2</span> Question 1</h3>
<p>First we will analyse whether the advertising campaign had an effect on SD streams. We need to formulate a hypothesis which we can test. In this case the null hypothesis is that the campaign had no effect on the mean number of streams, i.e. that there is no difference in the mean number of streams. The alternative hypothesis states that the campaign <em>did</em> have an effect, meaning that there is a difference in the mean number of streams. In more formal notation this is:</p>
<p><span class="math display">\[H_0: \mu_0 = \mu_1 \\ H_1: \mu_0 \neq \mu_1\]</span></p>
<p>We need to transform the variable online_advertising into a factor variable for some of our applications.</p>
<p>A good way to get a feeling for the data is to create descriptive statistics and appropriate plots (e.g., plot of means, boxplot).</p>
<pre><code>## 
##  Descriptive statistics by group 
## group: no
##    vars   n mean  sd median trimmed  mad min  max range skew kurtosis se
## X1    1 100 2053 840   2048    2023 1115 641 4067  3426 0.22       -1 84
## -------------------------------------------------------- 
## group: yes
##    vars   n mean  sd median trimmed mad  min  max range  skew kurtosis se
## X1    1 100 3305 942   3338    3308 987 1099 5571  4472 -0.02    -0.26 94</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-309-1.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-309-2.png" width="672" /></p>
<p>As we can see in both the descriptive statistics and the plots, the mean of the number of streams is higher where online_advertising = 1, i.e. for the videos that were included in the marketing campaign. To test whether or not this difference is significant, we need to use a <strong>two sample t-test</strong>. The requirements are clearly met:</p>
<ul>
<li>Our dependent value is on a ratio scale.</li>
<li>Since we have more than 30 observations per group we do not really have to concern ourselves with whether the data is normally distributed or not.</li>
<li>If a video was inluded in the campaign or not was assigned randomly.</li>
<li>Since we have equal group sizes, the homogeneity of variance assumption is not too relevant. Furthermore, R automatically performs Welch’s t-test, which corrects for unequal variance anyway.</li>
</ul>
<p>Thus we can perform the test in R</p>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  streams_sd by online_advertising
## t = -10, df = 200, p-value &lt;0.0000000000000002
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1501 -1003
## sample estimates:
##  mean in group no mean in group yes 
##              2053              3305</code></pre>
<p>The test is significant for any sensible level of confidence, leading us to reject the null hypothesis that there is no difference in the mean number of streams. In effect, this means that the advertising campaign had an effect on the average number of times a video was streamed. Another thing we can extract from this test result is the confidence interval around the difference in means. We are 95% certain that the true difference of means lies somewhere between -1003.213 and -1500.967.</p>
<p>The same can be done analogously for HD streams:</p>
<pre><code>## 
##  Descriptive statistics by group 
## group: no
##    vars   n mean  sd median trimmed mad min  max range skew kurtosis se
## X1    1 100 1493 435   1458    1490 457 553 2605  2052 0.13    -0.49 43
## -------------------------------------------------------- 
## group: yes
##    vars   n mean  sd median trimmed mad min  max range  skew kurtosis se
## X1    1 100 2163 629   2138    2167 629 534 3874  3340 -0.02    -0.03 63</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-311-1.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-311-2.png" width="672" /></p>
<p>Again, the summary statistics and boxplots seem to indicate that there is a difference in means. Using the same reasoning as before, we can deduce that we need a two sample t-test to determine whether this difference is signficant.</p>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  streams_hd by online_advertising
## t = -9, df = 200, p-value = 0.000000000000002
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -821 -519
## sample estimates:
##  mean in group no mean in group yes 
##              1493              2163</code></pre>
<p>Again, the p-value is so low that any sensible signifcance level would lead us to reject the null hypothesis, leading us to the conclusion that there is a difference in mean number of streams between videos included in the campaign and those that aren’t. Looking again at the 95 percent confidence intervals, however, it would appear that the effect was stronger for SD streams than for HD streams, since here we are 95 percent certain that the true difference in means lies between -821.2123 and -519.3277.</p>
</div>
<div id="question-2" class="section level3">
<h3><span class="header-section-number">11.1.3</span> Question 2</h3>
<p>Next we want to examine whether HD and SD streams have similar numbers o on average. The null hypothesis here is that there is no difference in the mean number of HD streams and the mean number of SD streams, with the alternative hypothesis is that such a difference exists. In mathematical notation this implies</p>
<p><span class="math display">\[H_0: \mu_0 = \mu_1 \\ H_1: \mu_0 \neq \mu_1\]</span></p>
<p>Again, we start with descriptive statistics to get a feel for the data.</p>
<pre><code>##    vars   n mean   sd median trimmed  mad min  max range skew kurtosis se
## X1    1 200 2679 1089   2666    2652 1070 641 5571  4930 0.18    -0.59 77</code></pre>
<pre><code>##    vars   n mean  sd median trimmed mad min  max range skew kurtosis se
## X1    1 200 1828 636   1760    1798 599 534 3874  3340 0.41    -0.08 45</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-313-1.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-313-2.png" width="672" /></p>
<p>As in question one, it appears that there is a difference in the means. To test whether it is significant we again need a t-test, with one important distinction: Our observations were in both experimental conditions, meaning we have data on HD and SD streams for each observation. This means that we need a <strong>dependent means t-test</strong>. The other assumptions are virtually identical to the regular t-test. The test can be executed in R by adding <code>paired = TRUE</code> to the code.</p>
<pre><code>## 
##  Paired t-test
## 
## data:  movie_data$streams_hd and movie_data$streams_sd
## t = -10, df = 200, p-value &lt;0.0000000000000002
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -991 -713
## sample estimates:
## mean of the differences 
##                    -852</code></pre>
<p>The p-value is again lower than any sensible signifance level, which means that we reject the null hypothesis that there is no difference in the mean number of streams. Interesting to note again is the 95 percent confidence interval, which states that we are 95 percent certain that the true difference of means lies between -990.5032 and -712.5568.</p>
</div>
<div id="question-3" class="section level3">
<h3><span class="header-section-number">11.1.4</span> Question 3</h3>
<p>Next we want to know whether there is a significant association between the genre of a movie and the academy award nomination. This is essentially a question of <strong>dependence</strong>, which means that our null hypothesis is that the two variables are independent and the alternative hypothesis is that they are dependent.</p>
<p>First we need to reshape the first variable into a factor and, while we’re at it, give the factor levels more descriptive names.</p>
<p>The next step is to produce a relative frequency table and an appropriate visualization - in this case a stacked bar plot.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-316-1.png" width="672" /></p>
<p>If the two variables truly are independent, knowing the genre would tell us nothing about the probability of an academy award. The relative frequency table and the above plot hint at the fact that this may not be the case. To actually test this we use the <strong>Chi-squared test</strong> .</p>
<pre><code>##           academy_award
## genre       0  1
##   Drama    10 26
##   Romance  24 22
##   Comedy   13 13
##   Thriller 40 17
##   Action   21 14</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  cont_table
## X-squared = 20, df = 4, p-value = 0.002</code></pre>
<p>Applying the widely used confidence level of 0.05 leads us to reject the null hypothesis in this case, with the alternative hypothesis being that the variables <code>genre</code> and <code>academy_award</code> are actually dependent.</p>
</div>
<div id="question-4" class="section level3">
<h3><span class="header-section-number">11.1.5</span> Question 4</h3>
<p>Finally we want to examine whether there is a difference in customer ratings between movies that wer nominated for an academy award and those that were not. In this case our null hypothesis is that both have a similar distribution in regard to their customer rating. The alternative hypothesis is that they are not drawn from the same distribution.</p>
<p>First we create a table with the conditional relative frequencies, which enables us to plot the data.</p>
<p>The next step is to create a barplot of the conditional relative frequencies, to give us an overview of the distribution of the data.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-319-1.png" width="672" /></p>
<p>Based solely on this plot it seems that movies with academy awards are more likely to gain higher customer ratings. To be able to test this, we need the Mann-Whitney U Test (a.k.a. Wilcoxon rank-sum test). Obviously, we need to check whether the assumptions for the test are fulfilled.</p>
<ul>
<li>Our dependent variable is ordinally scaled (i.e. there is a “natural” order to customer satisfaction ratings).</li>
<li>The independent variable is a factor with two levels.</li>
<li>The data comes from two independent samples.</li>
</ul>
<p>The reason why the dependent t-test is not appropriate is because the dependent variable is not measured on a continuous scale (i.e., inveral or ratio).</p>
<p>To perform the Mann-Whitney U Test we use the function <code>wilcox.test()</code>.</p>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  customer_rating by academy_award
## W = 4000, p-value = 0.09
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>Using a confidence level of 0.05, we cannot reject the null hypothesis in this case, meaning we would retain the assumption that customer ratings for movies with and without academy award nomination are drawn from the same distribution.</p>
<p>Note that a using a different confidence level (e.g., 0.1) we could speak of a marginally significant result.</p>
</div>
</div>
<div id="assignment-3-anova" class="section level2">
<h2><span class="header-section-number">11.2</span> Assignment 3 (Anova)</h2>
<p>The data file contains customer information from an online fashion shop. In an experiment, the customers were exposed to different types of online advertising over the past year (randomly assigned) and now you wish to analyze the results.</p>
<p>The following variables are included in the data set:</p>
<ul>
<li>customerID: unique customer ID</li>
<li>revenue: revenue per cusomer for the past year (in EUR)</li>
<li>gender: 0=male, 1=female</li>
<li>retargeting: type of online advertising that the customer was exposed to (3 levels: 1 = no advertising, 2 = generic retargeting, 3 = dynamic retargeting)</li>
<li>customerRank: ranking of customers according to their expenditure level (low rank = valuable customer, high rank = less valuable customer)</li>
</ul>
<p>Use R and appropriate analytical techniques to answer the following questions:</p>
<ol style="list-style-type: decimal">
<li>Has the types of online advertising an effect on revenue? Are there significant differences between the individual groups?</li>
<li>Does the effect of online advertising on revenue depend on gender? (conduct a 2 x 3 analysis of variance with “revenue” as the dependent variable and “gender” and “retargeting” as the independent variables or factors.)</li>
<li>Is the customer ranking significantly influenced by the type of online advertising? Are there significant differences between the individual groups?</li>
</ol>
<p>When answering the questions, please remember to address the following points:</p>
<ul>
<li>Formulate the corresponding hypotheses and choose an appropriate statistical test</li>
<li>Provide the reason for your choice and discuss if the assumptions of the test are met</li>
<li>Convert the variables to the appropriate type (e.g., factor variables)</li>
<li>Create appropriate graphs to explore the data (e.g., boxplot, bar chart)</li>
<li>Provide appropriate descriptive statistics for the variables</li>
<li>Report and interpret the test results accurately</li>
<li>Finally, don’t forget to report your research conclusion in an appropriate way</li>
</ul>
<p>When you are done with your analysis, click on “Knit to HTML” button above the code editor. This will create a HTML document of your results in the folder where the “assignment3.Rmd” file is stored. Open this file in your Internet browser to see if the output is correct. If the output is correct, submit the HTML file via Learn@WU. The file name should be “assignment3_studendID_name.html”.</p>
<div id="load-data-1" class="section level3">
<h3><span class="header-section-number">11.2.1</span> Load data</h3>
<p>As always, the first step is to load required packages (packages that have not been used as often in the course will be loaded as required to show which packages contain certain functions) and to load and inspect the data.</p>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["revenue"],"name":[1],"type":["int"],"align":["right"]},{"label":["gender"],"name":[2],"type":["int"],"align":["right"]},{"label":["retargeting"],"name":[3],"type":["int"],"align":["right"]},{"label":["customerID"],"name":[4],"type":["int"],"align":["right"]},{"label":["rank"],"name":[5],"type":["int"],"align":["right"]}],"data":[{"1":"754","2":"0","3":"2","4":"1","5":"254"},{"1":"2141","2":"0","3":"2","4":"2","5":"97"},{"1":"1762","2":"1","3":"3","4":"3","5":"140"},{"1":"2103","2":"0","3":"3","4":"4","5":"99"},{"1":"1859","2":"0","3":"2","4":"5","5":"125"},{"1":"1118","2":"0","3":"1","4":"6","5":"223"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre><code>## &#39;data.frame&#39;:    291 obs. of  5 variables:
##  $ revenue    : int  754 2141 1762 2103 1859 1118 2606 1269 2464 733 ...
##  $ gender     : int  0 0 1 0 0 0 1 1 1 0 ...
##  $ retargeting: int  2 2 3 3 2 1 2 1 2 1 ...
##  $ customerID : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ rank       : int  254 97 140 99 125 223 50 196 61 256 ...</code></pre>
<p>Next we are going to recode some of the variables into factors and give them more descriptive level names.</p>
</div>
<div id="question-1-1" class="section level3">
<h3><span class="header-section-number">11.2.2</span> Question 1</h3>
<p>To answer whether the type of advertising has an effect on revenue we need to formulate a testable null hypothesis. In our case the null hypothesis is stating that the average level of sales is equal for all advertising types. In mathematical notation this implies:</p>
<p><span class="math display">\[H_0: \mu_1 = \mu_2 = \mu_3 \]</span></p>
<p>The alternate hypothesis is simply that the means are not all equal, i.e.,</p>
<p><span class="math display">\[H_1: \textrm{Means are not all equal}\]</span></p>
<p>If you wanted to put this in mathematical notation, you could also write:</p>
<p><span class="math display">\[H_1: \exists {i,j}: {\mu_i \ne \mu_j} \]</span></p>
<p>However, this was not required.</p>
<p>The appropriate test for such a hypothesis is one-way ANOVA since we have a metric scales dependent variable and a categorical independent variable with more than two levels.</p>
<p>Next we will calculate summary statistics for the data and produce an approppriate plot.</p>
<pre><code>## dld.full$retargeting: no retargeting
##      nbr.val     nbr.null       nbr.na          min          max 
##       103.00         0.00         0.00        24.00      3406.00 
##        range          sum       median         mean      SE.mean 
##      3382.00    139425.00      1299.00      1353.64        70.13 
## CI.mean.0.95          var      std.dev     coef.var 
##       139.09    506518.45       711.70         0.53 
## -------------------------------------------------------- 
## dld.full$retargeting: generic retargeting
##      nbr.val     nbr.null       nbr.na          min          max 
##        89.00         0.00         0.00       137.00      4371.00 
##        range          sum       median         mean      SE.mean 
##      4234.00    152181.00      1705.00      1709.90        87.46 
## CI.mean.0.95          var      std.dev     coef.var 
##       173.81    680801.46       825.11         0.48 
## -------------------------------------------------------- 
## dld.full$retargeting: dynamic retargeting
##      nbr.val     nbr.null       nbr.na          min          max 
##         99.0          0.0          0.0        212.0       4297.0 
##        range          sum       median         mean      SE.mean 
##       4085.0     217953.0       2237.0       2201.5         88.1 
## CI.mean.0.95          var      std.dev     coef.var 
##        174.9     768762.8        876.8          0.4</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-323-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Both the summary statistics and the plot hint at the fact that the means may not be equal. Before we move to the test, we need to see if a series of assumptions are met, namely:</p>
<ul>
<li>Distributional assumptions</li>
<li>Homogeneity of variances</li>
<li>Indepnedence of observations</li>
</ul>
<p>The last assumption is satisfied due to the fact that the observations were randomly assigned to the advertisement groups. To see if we need to worry about distributional assumptions we first take a look at the number of observations in each advertising group.</p>
<pre><code>## 
##      no retargeting generic retargeting dynamic retargeting 
##                 103                  89                  99</code></pre>
<p>Due to the fact that there always more than 30 observations in each group we can rely on the central limit theorem to satisfy the distributional assumptions.</p>
<p>Homogeneity of variances can be checked with Levene’s test (implemented as <code>leveneTest()</code> from the <code>car</code> package). The null hypothesis of this test is that the variances are equal, with the alternative hypothesis being that the variances not all equal.</p>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = mean)
##        Df F value Pr(&gt;F)
## group   2    1.96   0.14
##       288</code></pre>
<p>The test is not significant (for a signifcance level of 5 %), meaning that we do not reject the null hypothesis of equal variances and can operate under the assumption that the variances are equal.</p>
<p>Since all assumptions are fulfilled we can move on to conducting the actual ANOVA using the <code>aov()</code> function.</p>
<pre><code>##              Df    Sum Sq  Mean Sq F value          Pr(&gt;F)    
## retargeting   2  36509595 18254797    28.1 0.0000000000069 ***
## Residuals   288 186914162   649008                            
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The p-value is below any sensible level of signficance, which means that we reject the null hypothesis of the means being equal in the three advertising groups.</p>
<p>Next we will briefly inspect the residuals of the ANOVA to see if the assumptions of the test really are justified.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-327-1.png" width="672" /></p>
<p>The first plot gives us a feel for the distribution of the residuals of the three groups. The residuals seem to be roughly equally distributed, which speaks for the fact that the homogeneity of variances assumptions is fulfilled.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-328-1.png" width="672" /></p>
<p>The second plot is a QQ-plot of the residuals, meant as a quick visual check to see if the normality assumption is fulfilled. Leading up to the test we only checked if there were more than 30 observations per group to satisfy the normality assumption but despite this being fulfilled it is still important to check the normality of the residuals, as any strange behaviour here may indicate problems with the model specification.</p>
<p>To further confirm that the residuals are roughly normally distributed we employ the Shapiro-Wilk test. The null hypothesis is that the distribution of the data is normal, with the alternative hypothesis positing that the data is not normally distributed.</p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resid(aov)
## W = 1, p-value = 0.8</code></pre>
<p>The p value is far above any widely used significance level and thus we can not reject the null hypothesis of normal distribution, which further implies that the normality assumption is fulfilled.</p>
<p>The ANOVA result only tells us that the means of the three groups are not equal, but it does not tell us anything about <em>which</em> pairs of means are unequal. To find this out we need to conduct post hoc tests. Here we will conduct both the Bonferroni correction as well as Tukey’s HSD test, however either would be sufficient for your homework.</p>
<p>Bonferroni’s correction conducts multiple pairwise t-tests, with the null hypothesis being that of equal means in each case and the alternative hypothesis stating that the means are unequal.</p>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  dld.full$revenue and dld.full$retargeting 
## 
##                     no retargeting generic retargeting
## generic retargeting 0.007          -                  
## dynamic retargeting 0.000000000003 0.000117127044     
## 
## P value adjustment method: bonferroni</code></pre>
<p>All of the p-values in our output are well below 0.05, meaning that we reject the null hypothesis in all three cases.</p>
<p>Tukey’s HSD similarly compares pairwise means, corrected for family-wise errors.</p>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Multiple Comparisons of Means: Tukey Contrasts
## 
## 
## Fit: aov(formula = revenue ~ retargeting, data = dld.full)
## 
## Linear Hypotheses:
##                                                Estimate Std. Error t value
## generic retargeting - no retargeting == 0           356        117    3.06
## dynamic retargeting - no retargeting == 0           848        113    7.48
## dynamic retargeting - generic retargeting == 0      492        118    4.18
##                                                Pr(&gt;|t|)    
## generic retargeting - no retargeting == 0       0.00691 ** 
## dynamic retargeting - no retargeting == 0      &lt; 0.0001 ***
## dynamic retargeting - generic retargeting == 0  0.00012 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Adjusted p values reported -- single-step method)</code></pre>
<p>As in the case of Bonferroni’s correction, all three p-values are well below 0.05 and thus we reject the null hypothesis of equal means. Tukey’s HSD further lets us estimate the difference in means with corresponding confidence intervals.</p>
<pre><code>## 
##   Simultaneous Confidence Intervals
## 
## Multiple Comparisons of Means: Tukey Contrasts
## 
## 
## Fit: aov(formula = revenue ~ retargeting, data = dld.full)
## 
## Quantile = 2.4
## 95% family-wise confidence level
##  
## 
## Linear Hypotheses:
##                                                Estimate lwr      upr     
## generic retargeting - no retargeting == 0       356.258   81.555  630.961
## dynamic retargeting - no retargeting == 0       847.905  580.748 1115.061
## dynamic retargeting - generic retargeting == 0  491.647  214.383  768.910</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-332-1.png" width="672" /></p>
<p>It is clearly visible that none of the CIs cross the 0 bound, which further indicates that the differences in means are statistically significantly different from 0.</p>
<p>From a reporting standpoint we can say that revenue is higher when using generic retargeting vs. no retargeting, dynamic retargeting vs. no retargeting and also when using dynamic retargeting vs. generic retargeting.</p>
</div>
<div id="question-2-1" class="section level3">
<h3><span class="header-section-number">11.2.3</span> Question 2</h3>
<p>Next we want to analyse whether gender interacts with retargeting when it comes to revenue. The correct tool for this analysis is n-way ANOVA (a.k.a factorial ANOVA). As usual, we start off with some descriptive statistics and plots to get a feel for the data.</p>
<pre><code>## dld.full$Group: dynamic retargeting_female
##      nbr.val     nbr.null       nbr.na          min          max 
##         50.0          0.0          0.0        432.0       4297.0 
##        range          sum       median         mean      SE.mean 
##       3865.0     129647.0       2600.5       2592.9        110.7 
## CI.mean.0.95          var      std.dev     coef.var 
##        222.5     613064.5        783.0          0.3 
## -------------------------------------------------------- 
## dld.full$Group: dynamic retargeting_male
##      nbr.val     nbr.null       nbr.na          min          max 
##        49.00         0.00         0.00       212.00      3391.00 
##        range          sum       median         mean      SE.mean 
##      3179.00     88306.00      1849.00      1802.16       112.61 
## CI.mean.0.95          var      std.dev     coef.var 
##       226.41    621318.93       788.24         0.44 
## -------------------------------------------------------- 
## dld.full$Group: generic retargeting_female
##      nbr.val     nbr.null       nbr.na          min          max 
##        45.00         0.00         0.00       336.00      3387.00 
##        range          sum       median         mean      SE.mean 
##      3051.00     75377.00      1705.00      1675.04       120.18 
## CI.mean.0.95          var      std.dev     coef.var 
##       242.20    649920.04       806.18         0.48 
## -------------------------------------------------------- 
## dld.full$Group: generic retargeting_male
##      nbr.val     nbr.null       nbr.na          min          max 
##        44.00         0.00         0.00       137.00      4371.00 
##        range          sum       median         mean      SE.mean 
##      4234.00     76804.00      1692.00      1745.55       128.42 
## CI.mean.0.95          var      std.dev     coef.var 
##       258.99    725662.07       851.86         0.49 
## -------------------------------------------------------- 
## dld.full$Group: no retargeting_female
##      nbr.val     nbr.null       nbr.na          min          max 
##        51.00         0.00         0.00        38.00      3406.00 
##        range          sum       median         mean      SE.mean 
##      3368.00     73336.00      1414.00      1437.96        94.26 
## CI.mean.0.95          var      std.dev     coef.var 
##       189.32    453109.96       673.13         0.47 
## -------------------------------------------------------- 
## dld.full$Group: no retargeting_male
##      nbr.val     nbr.null       nbr.na          min          max 
##        52.00         0.00         0.00        24.00      3261.00 
##        range          sum       median         mean      SE.mean 
##      3237.00     66089.00      1141.00      1270.94       103.29 
## CI.mean.0.95          var      std.dev     coef.var 
##       207.35    554728.45       744.80         0.59</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-333-1.png" width="672" style="display: block; margin: auto;" /><img src="_main_files/figure-html/unnamed-chunk-333-2.png" width="672" style="display: block; margin: auto;" /></p>
<p>Both the summary statistics and the plots seem to indicate a difference between men and women. Before we can jump straight into the analysis, we need to test whether the assumptions of the model are justified.</p>
<p>We begin with the distributional assumptions. To this end we check how many observations are in each group.</p>
<pre><code>## 
## dynamic retargeting_female   dynamic retargeting_male 
##                         50                         49 
## generic retargeting_female   generic retargeting_male 
##                         45                         44 
##      no retargeting_female        no retargeting_male 
##                         51                         52</code></pre>
<p>Since there are more than 30 observations in each group, we can again rely on the central limit theorem to satisfy the normality assumption. Next is the homogeneity of variances assumption, which we again test using Levene’s test.</p>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = mean)
##        Df F value Pr(&gt;F)
## group   5     0.9   0.48
##       285</code></pre>
<p>Again the p-value is far above any widely used significance level and we can not reject the null hypothesis of equal variances. As the necessary assumptions are fulfilled, we can move on to the factorial ANOVA.</p>
<pre><code>##                     Df    Sum Sq  Mean Sq F value         Pr(&gt;F)    
## retargeting          2  36509595 18254797   30.49 0.000000000001 ***
## gender               1   6837311  6837311   11.42        0.00083 ***
## retargeting:gender   2   9466785  4733392    7.91        0.00045 ***
## Residuals          285 170610067   598632                           
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Since the interaction effect is significant, we can no longer interpret the main effects and can only resort to saying that the effect of one factor depends on the other, i.e. that gender has an effect on the level of revenue in each advertising group. This means that gender has an effect on the revenue generated in each advertising group.</p>
<p>As a final step we again check the residuals to see whether or not the assumptions are justified.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-337-1.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-337-2.png" width="672" /></p>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resid(aov)
## W = 1, p-value = 0.6</code></pre>
<p>Both assumptions (homogeneity of variances and the normality assumption) seem to be justifiable through the residuals.</p>
</div>
<div id="question-3-1" class="section level3">
<h3><span class="header-section-number">11.2.4</span> Question 3</h3>
<p>For the last question we want to examine whether customer ranks are signifcantly different for different types of advertising. Because we are dealing with data on an ordinal scale, we can not use ANOVA for this type of question. The non-parametric counterpart is the Kruskal-Wallis test, which tests for differences in medians between groups. Hence, the null hypothesis is that the medians are equal in each group and the alternative hypothesis is that the medians are unequal.</p>
<p><span class="math display">\[H_0: \tilde{x}_1 =  \tilde{x}_2 = \tilde{x}_3 \]</span> <span class="math display">\[H_1: \textrm{The meadians are not all equal} \]</span> A good way to visualize ordinal data is through a boxplot.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-338-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The boxplot seems to indicate that the medians are unequal.</p>
<p>The only assumption that we require for this test is that the dependent variable is at least ordinal, which is fulfilled for customer ranks. Hence we can move on to performing the test in R.</p>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  rank by retargeting
## Kruskal-Wallis chi-squared = 50, df = 2, p-value = 0.00000000002</code></pre>
<p>The p-value is again below any sensible signifcance level and thus we reject the null hypothesis of equal medians. This means that the median rank of customers is different for different types of retargeting, implying that the type of retargeting has an effect on the customer rank.</p>
<p>To further see which of the medians are unequeal we perform the Nemenyi post hoc test, which can be found in the <code>PCMCR</code> package in R. The null hyptohesis is that the pairwise medians are equal, while the alternative hypothesis is that the pairwise medians are unequal.</p>
<pre><code>## 
##  Pairwise comparisons using Tukey and Kramer (Nemenyi) test  
##                    with Tukey-Dist approximation for independent samples 
## 
## data:  dld.full$rank and dld.full$retargeting 
## 
##                     no retargeting generic retargeting
## generic retargeting 0.00998        -                  
## dynamic retargeting 0.000000000007 0.00032            
## 
## P value adjustment method: none</code></pre>
<p>All of the p-values are well below 0.05, meaning that the pairwise differences between the medians are always signifianct. This in turn implies that every type of advertising leads to different customer ranks.</p>
</div>
</div>
<div id="assignment-4-regression" class="section level2">
<h2><span class="header-section-number">11.3</span> Assignment 4 (Regression)</h2>
<p>As a marketing manager of a consumer electronics company, you are assigned the task to analyze the relative influence of different marketing activities. Specifically, you are supposed to analyse the effects of (1) TV advertising, (2) online advertising, and (3) radio advertising on the sales of fitness trackers (wristbands). Your data set consists of sales of the product in different markets (each line represents one market) from the past year, along with the advertising budgets for the product in each of those markets for three different media: TV, online, and radio.</p>
<p>The following variables are available to you:</p>
<ul>
<li>Sales (in thousands of units)</li>
<li>TV advertising budget (in thousands of Euros)</li>
<li>Online advertising budget (in thousands of Euros)</li>
<li>Radio advertising budget (in thousands of Euros)</li>
</ul>
<p>Please conduct the following analyses:</p>
<ol style="list-style-type: decimal">
<li>Formally state the regression equation, which you will use to determine the relative influence of the marketing activities on sales.</li>
<li>Describe the model variables using appropriate statstics and plots</li>
<li>Estimate a multiple linear regression model to determine the relative influence of each of the variables. Before you interpret the results, test if the model assumptions are fulfilled and use appropriate tests and plots to test the assumptions.</li>
<li>Interpret the model results:</li>
</ol>
<ul>
<li>Which variables have a significant influence on sales and what is the interpretation of the coefficients?</li>
<li>What is the relative importance of the predictor variables?</li>
<li>Interpret the F-test</li>
<li>How do you judge the fit of the model? Please also visualize the model fit using an appropriate graph.</li>
</ul>
<ol start="5" style="list-style-type: decimal">
<li>What sales quantity would you predict based on your model for a product when the marketing activities are planned as follows: TV: 150 thsd. €, Online: 26 thsd. €, Radio: 15 thsd. €? Please provide the equation you used to make the prediction.</li>
</ol>
<p>When you are done with your analysis, click on “Knit to HTML” button above the code editor. This will create a HTML document of your results in the folder where the “assignment4.Rmd” file is stored. Open this file in your Internet browser to see if the output is correct. If the output is correct, submit the HTML file via Learn@WU. The file name should be “assignment4_studendID_name.html”.</p>
<div id="load-data-2" class="section level3">
<h3><span class="header-section-number">11.3.1</span> Load data</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sales_data &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;https://raw.githubusercontent.com/IMSMWU/Teaching/master/MRDA2017/assignment4.2.dat&quot;</span>, 
                         <span class="dt">sep =</span> <span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>, 
                         <span class="dt">header =</span> <span class="ot">TRUE</span>) <span class="co">#read in data</span>
sales_data<span class="op">$</span>market_id &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(sales_data)
<span class="kw">head</span>(sales_data)</code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["tv_adspend"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["online_adspend"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["radio_adspend"],"name":[3],"type":["int"],"align":["right"]},{"label":["sales"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["market_id"],"name":[5],"type":["int"],"align":["right"]}],"data":[{"1":"146","2":"31.5","3":"39","4":"14","5":"1"},{"1":"241","2":"12.4","3":"9","4":"16","5":"2"},{"1":"286","2":"9.9","3":"5","4":"16","5":"3"},{"1":"138","2":"7.2","3":"27","4":"11","5":"4"},{"1":"149","2":"21.0","3":"34","4":"11","5":"5"},{"1":"190","2":"36.7","3":"68","4":"19","5":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(sales_data)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    240 obs. of  5 variables:
##  $ tv_adspend    : num  146 241 286 138 149 ...
##  $ online_adspend: num  31.5 12.4 9.9 7.2 21 36.7 1.3 18.4 11.9 16.5 ...
##  $ radio_adspend : int  39 9 5 27 34 68 28 39 26 22 ...
##  $ sales         : num  14.5 15.6 16 11.4 11 18.7 7.4 10.3 9 17.8 ...
##  $ market_id     : int  1 2 3 4 5 6 7 8 9 10 ...</code></pre>
</div>
<div id="question-1-2" class="section level3">
<h3><span class="header-section-number">11.3.2</span> Question 1</h3>
<p>In a first step, we specifiy the regression equation. In this case, sales is the dependend variable which is regressed on the different types of advertising expenditures that represent the independent variables. Thus, the regression equation is:</p>
<p><span class="math display">\[Sales=\beta_0 + \beta_1 * tvadspend + \beta_2 * onlineadspend + \beta_3 * radioadspend + \epsilon\]</span></p>
</div>
<div id="question-2-2" class="section level3">
<h3><span class="header-section-number">11.3.3</span> Question 2</h3>
<p>The descriptive statistics can be checked using the <code>describe()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(psych)
psych<span class="op">::</span><span class="kw">describe</span>(sales_data)</code></pre></div>
<pre><code>##                vars   n mean   sd median trimmed  mad min max range  skew
## tv_adspend        1 240  158 81.6    161     160 97.3 0.1 300   300 -0.14
## online_adspend    2 240   26 14.0     26      25 15.2 0.5  68    68  0.48
## radio_adspend     3 240   26 13.3     25      25 14.8 1.0  68    67  0.25
## sales             4 240   15  5.1     15      15  5.3 1.0  28    27 -0.13
## market_id         5 240  120 69.4    120     120 89.0 1.0 240   239  0.00
##                kurtosis   se
## tv_adspend        -1.04 5.27
## online_adspend    -0.07 0.90
## radio_adspend     -0.44 0.86
## sales             -0.23 0.33
## market_id         -1.22 4.48</code></pre>
<p>Since we have continuous variables, we use scatterplots to investigate the relationship between sales and each of the predictor variables.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">ggplot</span>(sales_data, <span class="kw">aes</span>(<span class="dt">x =</span> tv_adspend, <span class="dt">y =</span> sales)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="kw">theme_bw</span>()</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-343-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(sales_data, <span class="kw">aes</span>(<span class="dt">x =</span> online_adspend, <span class="dt">y =</span> sales)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="kw">theme_bw</span>()</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-343-2.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(sales_data, <span class="kw">aes</span>(<span class="dt">x =</span> radio_adspend, <span class="dt">y =</span> sales)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="kw">theme_bw</span>()</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-343-3.png" width="672" /></p>
<p>The plots already suggest that there might be a positive linear relationship between sales and TV- and online-advertising. However, there does not appear to be a strong relationship between sales and radio advertising.</p>
</div>
<div id="question-3-2" class="section level3">
<h3><span class="header-section-number">11.3.4</span> Question 3</h3>
<p>The estimate the model, we will use the <code>lm()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">linear_model &lt;-<span class="st"> </span><span class="kw">lm</span>(sales <span class="op">~</span><span class="st"> </span>tv_adspend <span class="op">+</span><span class="st"> </span>online_adspend <span class="op">+</span><span class="st"> </span>radio_adspend, <span class="dt">data =</span> sales_data)</code></pre></div>
<p>Before we can inspect the results, we need to test if there might be potential problems with our model specification.</p>
<div id="outliers-1" class="section level4">
<h4><span class="header-section-number">11.3.4.1</span> Outliers</h4>
<p>The check for outliers, we extract the studentized residuals from our model and test if there are any absolute values larger than 3.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sales_data<span class="op">$</span>stud_resid &lt;-<span class="st"> </span><span class="kw">rstudent</span>(linear_model)
<span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(sales_data),sales_data<span class="op">$</span>stud_resid, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="fl">3.3</span>,<span class="fl">3.3</span>)) <span class="co">#create scatterplot </span>
<span class="kw">abline</span>(<span class="dt">h=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>,<span class="dv">3</span>),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lty=</span><span class="dv">2</span>) <span class="co">#add reference lines</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-345-1.png" width="672" /></p>
<p>Since there are no residuals with absolut values larger than 3, we conclude that there are no severe outliers.</p>
</div>
<div id="influencial-observations" class="section level4">
<h4><span class="header-section-number">11.3.4.2</span> Influencial observations</h4>
<p>To test for influential observations, we use Cook’s Distance. You may use the following two plots to verify if any Cook’s Dinstance values are larger than the cutoff of 1.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(linear_model,<span class="dv">4</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-346-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(linear_model,<span class="dv">5</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-346-2.png" width="672" /></p>
<p>Since all values are well below the cutoff, we conclude that influencial observations are not a problem in our model.</p>
</div>
<div id="non-linear-relationships-1" class="section level4">
<h4><span class="header-section-number">11.3.4.3</span> Non-linear relationships</h4>
<p>Next, we test if a linear specification appears feasible. You could test this using the added variable plots:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(car)
<span class="kw">avPlots</span>(linear_model)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-347-1.png" width="672" /></p>
<p>The plots suggest that the linear specification is appropriate. In addition, you could also use the residuals plot to see if the linear specification is appropriate. The red line is a smoothed curve through the residuals plot and if it deviates from the dashed grey horizontal line a lot, this would suggest that a linear specification is not appropriate.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(linear_model, <span class="dv">1</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-348-1.png" width="672" /></p>
<p>In this example, the red line is close to the dashed grey line, so the linear specification appears reasonable.</p>
</div>
<div id="heteroscedasticity" class="section level4">
<h4><span class="header-section-number">11.3.4.4</span> Heteroscedasticity</h4>
<p>Next, we test if the residual variance is approximately the same at all levels of the predicted outcome variables (i.e., homoscedasticity). To do this, we use the residuals plot again.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(linear_model, <span class="dv">1</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-349-1.png" width="672" /></p>
<p>The spread of residuals at different levels of the predicted outcome does not appear to be very different. Thus, we can conclude that heteroscedasticity is unlikely to be a problem.</p>
</div>
<div id="non-normally-distributed-errors-1" class="section level4">
<h4><span class="header-section-number">11.3.4.5</span> Non-normally distributed errors</h4>
<p>Next, we test if the residuals are approximately normally distributed using the Q-Q plot from the output:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(linear_model,<span class="dv">2</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-350-1.png" width="672" /></p>
<p>The Q-Q plot does not suggest a severe deviation from a normal distribution. This could also be validated using the Shapiro test:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">shapiro.test</span>(<span class="kw">resid</span>(linear_model))</code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resid(linear_model)
## W = 1, p-value = 0.6</code></pre>
</div>
<div id="correlation-of-errors-1" class="section level4">
<h4><span class="header-section-number">11.3.4.6</span> Correlation of errors</h4>
<p>Next, we test if the residuals are uncorrelated. Any clustered pattern in the residuals plot would indicate dependence of errors.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(linear_model,<span class="dv">1</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-352-1.png" width="672" /></p>
<p>In our example, the residuals do not appear to be correlated since there is no clustered pattern.</p>
</div>
<div id="multicollinearity" class="section level4">
<h4><span class="header-section-number">11.3.4.7</span> Multicollinearity</h4>
<p>To test for linear dependence of the regressors, we first test the bivariate correlations for any extremely high correlations (i.e., &gt;0.8).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;Hmisc&quot;</span>)
<span class="kw">rcorr</span>(<span class="kw">as.matrix</span>(sales_data[,<span class="kw">c</span>(<span class="st">&quot;tv_adspend&quot;</span>,<span class="st">&quot;online_adspend&quot;</span>,<span class="st">&quot;radio_adspend&quot;</span>)]))</code></pre></div>
<pre><code>##                tv_adspend online_adspend radio_adspend
## tv_adspend           1.00           0.04         -0.07
## online_adspend       0.04           1.00          0.02
## radio_adspend       -0.07           0.02          1.00
## 
## n= 240 
## 
## 
## P
##                tv_adspend online_adspend radio_adspend
## tv_adspend                0.49           0.30         
## online_adspend 0.49                      0.77         
## radio_adspend  0.30       0.77</code></pre>
<p>The results show that the bivariate correlations are rather low. This can also be shown in a plot:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(sales_data[,<span class="kw">c</span>(<span class="st">&quot;tv_adspend&quot;</span>,<span class="st">&quot;online_adspend&quot;</span>,<span class="st">&quot;radio_adspend&quot;</span>)])</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-354-1.png" width="672" /></p>
<p>In a next step, we compute the variance inflation factor for each predictor variable. The values should be close to 1 and values larger than 4 indicate potential problems with the linear dependence of regressors.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(car)
<span class="kw">vif</span>(linear_model)</code></pre></div>
<pre><code>##     tv_adspend online_adspend  radio_adspend 
##              1              1              1</code></pre>
<p>Here, all vif values are well below the cutoff, indicating that there are no problems with multicollinearity.</p>
</div>
</div>
<div id="question-4-1" class="section level3">
<h3><span class="header-section-number">11.3.5</span> Question 4</h3>
<p>In a next step, we will investigate the results from the model using the <code>summary()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(linear_model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sales ~ tv_adspend + online_adspend + radio_adspend, 
##     data = sales_data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -5.629 -1.338 -0.199  1.551  5.591 
## 
## Coefficients:
##                Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)     2.81171    0.48565    5.79          0.000000022 ***
## tv_adspend      0.04482    0.00172   26.04 &lt; 0.0000000000000002 ***
## online_adspend  0.19162    0.01004   19.09 &lt; 0.0000000000000002 ***
## radio_adspend   0.00713    0.01050    0.68                  0.5    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.2 on 236 degrees of freedom
## Multiple R-squared:  0.822,  Adjusted R-squared:  0.82 
## F-statistic:  364 on 3 and 236 DF,  p-value: &lt;0.0000000000000002</code></pre>
<p>For each of the individual predictors, we test the following hypothesis:</p>
<p><span class="math display">\[H_0: \beta_k=0\]</span> <span class="math display">\[H_1: \beta_k\ne0\]</span></p>
<p>where k denotes the number of the regression coefficient. In the present example, we reject the null hypothesis for the first two predictors, where we observe a significant effect (i.e., p &lt; 0.05 for “tv_adspend” and “online_adspend”). However, we fail to reject the null for the “radio_adspend” variable (i.e., the effect is insignificant).</p>
<p>The interpretation of the coefficients is as follows:</p>
<ul>
<li>tv_adspend (β<sub>1</sub>): when tv advertising expenditures increase by 1 Euro, sales will increase by 0.04 units</li>
<li>online_adspend (β<sub>2</sub>): when online advertising expenditures increase by 1 Euro, sales will increase by 0.19 units</li>
<li>radio_adspend (β<sub>3</sub>): when radio advertising expenditures increase by 1 Euro, sales will increase by 0.01 units</li>
</ul>
<p>You should always provide a measure of uncertainty that is associated with the estimates. You could compute the confidence intervals around the coefficients using the <code>confint()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(linear_model)</code></pre></div>
<pre><code>##                 2.5 % 97.5 %
## (Intercept)     1.855  3.768
## tv_adspend      0.041  0.048
## online_adspend  0.172  0.211
## radio_adspend  -0.014  0.028</code></pre>
<p>The results show that, for example, with a 95% probability the effect of online advertising will be between 0.172 and 0.211.</p>
<p>Although the variables are measured on the same scale, you should still test the relative influence by inspecting the standardized coefficients that express the effects in terms of standard deviations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(lm.beta)
<span class="kw">lm.beta</span>(linear_model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sales ~ tv_adspend + online_adspend + radio_adspend, 
##     data = sales_data)
## 
## Standardized Coefficients::
##    (Intercept)     tv_adspend online_adspend  radio_adspend 
##          0.000          0.717          0.525          0.019</code></pre>
<p>Here, we conclude that tv advertising has the largest ROI followed by online advertising and radio advertising.</p>
<p>Another significance test is the F-test. It tests the null hypothesis:</p>
<p><span class="math display">\[H_0: R^2=0\]</span></p>
<p>This is equivalent to the following null hypothesis:</p>
<p><span class="math display">\[H_0: \beta_1=\beta_2=\beta_3=\beta_k=0\]</span></p>
<p>The result of the test is provided in the output above (“F-statistic: 363.7 on 3 and 236 DF, p-value: &lt; 2.2e-16”). Since the p-value is smaller than 0.05, we reject the null hypothesis that all coefficients are zero.</p>
<p>If you would like to make it more explicit, you could use the <code>anova()</code> function to get the specific anova results.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(linear_model)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: sales
##                 Df Sum Sq Mean Sq F value              Pr(&gt;F)    
## tv_adspend       1   3396    3396  725.54 &lt;0.0000000000000002 ***
## online_adspend   1   1709    1709  365.07 &lt;0.0000000000000002 ***
## radio_adspend    1      2       2    0.46                 0.5    
## Residuals      236   1105       5                                
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Regarding the model fit, the R<sup>2</sup> statistic tells us that approximately 82% of the variance can be explained by the model. This can be visualized as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sales_data<span class="op">$</span>yhat &lt;-<span class="st"> </span><span class="kw">predict</span>(linear_model)
<span class="kw">ggplot</span>(sales_data,<span class="kw">aes</span>(yhat,sales)) <span class="op">+</span><span class="st">  </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size=</span><span class="dv">2</span>,<span class="dt">shape=</span><span class="dv">1</span>) <span class="op">+</span><span class="st">  </span><span class="co">#Use hollow circles</span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">name=</span><span class="st">&quot;predicted values&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">name=</span><span class="st">&quot;observed values&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">intercept =</span> <span class="dv">0</span>, <span class="dt">slope =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>()</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-360-1.png" width="672" /></p>
</div>
<div id="question-5" class="section level3">
<h3><span class="header-section-number">11.3.6</span> Question 5</h3>
<p>Finally, we can predict the outcome for the given marketing mix using the following equation:</p>
<p><span class="math display">\[\hat{sales}= 0.045*150 + 0.192*26 + 0.007*15 = 14.623\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(linear_model)<span class="op">$</span>coefficients[<span class="dv">1</span>,<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summary</span>(linear_model)<span class="op">$</span>coefficients[<span class="dv">2</span>,<span class="dv">1</span>]<span class="op">*</span><span class="dv">150</span> <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summary</span>(linear_model)<span class="op">$</span>coefficients[<span class="dv">3</span>,<span class="dv">1</span>]<span class="op">*</span><span class="dv">26</span> <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summary</span>(linear_model)<span class="op">$</span>coefficients[<span class="dv">4</span>,<span class="dv">1</span>]<span class="op">*</span><span class="dv">15</span></code></pre></div>
<pre><code>## [1] 15</code></pre>
<p>This means that given the planned marketing mix, we would expect to seel around 14,623 units.</p>

<div id="refs" class="references">
<div>
<p>Casella, George, and Roger L Berger. 2002. <em>Statistical Inference</em>. 2nd ed. Duxbury Pacific Grove, CA.</p>
</div>
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="exploratory-factor-analysis.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
