<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Exploratory factor analysis | Marketing Research Design &amp; Analysis 2019</title>
  <meta name="description" content="An Introduction to Statistics Using R" />
  <meta name="generator" content="bookdown 0.16 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Exploratory factor analysis | Marketing Research Design &amp; Analysis 2019" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An Introduction to Statistics Using R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Exploratory factor analysis | Marketing Research Design &amp; Analysis 2019" />
  
  <meta name="twitter:description" content="An Introduction to Statistics Using R" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="prev" href="regression.html"/>
<link rel="next" href="appendix.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.49.4/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.49.4/plotly-latest.min.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">MRDA 2019</a></strong></li>
<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a></li>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html"><i class="fa fa-check"></i>Course materials</a><ul>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html#main-reference"><i class="fa fa-check"></i>Main reference</a></li>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html#further-readings"><i class="fa fa-check"></i>Further readings</a></li>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html#datacamp"><i class="fa fa-check"></i>DataCamp</a></li>
<li class="chapter" data-level="" data-path="course-materials.html"><a href="course-materials.html#other-web-resources"><i class="fa fa-check"></i>Other web-resources</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting started</a><ul>
<li class="chapter" data-level="1.1" data-path="getting-started.html"><a href="getting-started.html#how-to-download-and-install-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> How to download and install R and RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="getting-started.html"><a href="getting-started.html#getting-help"><i class="fa fa-check"></i><b>1.2</b> Getting help</a></li>
<li class="chapter" data-level="1.3" data-path="getting-started.html"><a href="getting-started.html#functions"><i class="fa fa-check"></i><b>1.3</b> Functions</a></li>
<li class="chapter" data-level="1.4" data-path="getting-started.html"><a href="getting-started.html#packages"><i class="fa fa-check"></i><b>1.4</b> Packages</a></li>
<li class="chapter" data-level="1.5" data-path="getting-started.html"><a href="getting-started.html#a-typical-r-session"><i class="fa fa-check"></i><b>1.5</b> A typical R session</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-handling.html"><a href="data-handling.html"><i class="fa fa-check"></i><b>2</b> Data handling</a><ul>
<li class="chapter" data-level="2.1" data-path="data-handling.html"><a href="data-handling.html#basic-data-handling"><i class="fa fa-check"></i><b>2.1</b> Basic data handling</a><ul>
<li class="chapter" data-level="2.1.1" data-path="data-handling.html"><a href="data-handling.html#creating-objects"><i class="fa fa-check"></i><b>2.1.1</b> Creating objects</a></li>
<li class="chapter" data-level="2.1.2" data-path="data-handling.html"><a href="data-handling.html#data-types"><i class="fa fa-check"></i><b>2.1.2</b> Data types</a></li>
<li class="chapter" data-level="2.1.3" data-path="data-handling.html"><a href="data-handling.html#data-structures"><i class="fa fa-check"></i><b>2.1.3</b> Data structures</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="data-handling.html"><a href="data-handling.html#advanced-data-handling"><i class="fa fa-check"></i><b>2.2</b> Advanced data handling</a><ul>
<li class="chapter" data-level="2.2.1" data-path="data-handling.html"><a href="data-handling.html#the-dplyr-package"><i class="fa fa-check"></i><b>2.2.1</b> The dplyr package</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-handling.html"><a href="data-handling.html#dealing-with-strings"><i class="fa fa-check"></i><b>2.2.2</b> Dealing with strings</a></li>
<li class="chapter" data-level="2.2.3" data-path="data-handling.html"><a href="data-handling.html#case-study"><i class="fa fa-check"></i><b>2.2.3</b> Case study</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-handling.html"><a href="data-handling.html#data-import-and-export"><i class="fa fa-check"></i><b>2.3</b> Data import and export</a><ul>
<li class="chapter" data-level="2.3.1" data-path="data-handling.html"><a href="data-handling.html#getting-data-for-this-course"><i class="fa fa-check"></i><b>2.3.1</b> Getting data for this course</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-handling.html"><a href="data-handling.html#import-data-created-by-other-software-packages"><i class="fa fa-check"></i><b>2.3.2</b> Import data created by other software packages</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-handling.html"><a href="data-handling.html#export-data"><i class="fa fa-check"></i><b>2.3.3</b> Export data</a></li>
<li class="chapter" data-level="2.3.4" data-path="data-handling.html"><a href="data-handling.html#import-data-from-the-web"><i class="fa fa-check"></i><b>2.3.4</b> Import data from the Web</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="summarizing-data.html"><a href="summarizing-data.html"><i class="fa fa-check"></i><b>3</b> Summarizing data</a><ul>
<li class="chapter" data-level="3.1" data-path="summarizing-data.html"><a href="summarizing-data.html#summary-statistics"><i class="fa fa-check"></i><b>3.1</b> Summary statistics</a><ul>
<li class="chapter" data-level="3.1.1" data-path="summarizing-data.html"><a href="summarizing-data.html#categorical-variables"><i class="fa fa-check"></i><b>3.1.1</b> Categorical variables</a></li>
<li class="chapter" data-level="3.1.2" data-path="summarizing-data.html"><a href="summarizing-data.html#continuous-variables"><i class="fa fa-check"></i><b>3.1.2</b> Continuous variables</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="summarizing-data.html"><a href="summarizing-data.html#data-visualization"><i class="fa fa-check"></i><b>3.2</b> Data visualization</a><ul>
<li class="chapter" data-level="3.2.1" data-path="summarizing-data.html"><a href="summarizing-data.html#categorical-variables-1"><i class="fa fa-check"></i><b>3.2.1</b> Categorical variables</a></li>
<li class="chapter" data-level="3.2.2" data-path="summarizing-data.html"><a href="summarizing-data.html#continuous-variables-1"><i class="fa fa-check"></i><b>3.2.2</b> Continuous variables</a></li>
<li class="chapter" data-level="3.2.3" data-path="summarizing-data.html"><a href="summarizing-data.html#saving-plots"><i class="fa fa-check"></i><b>3.2.3</b> Saving plots</a></li>
<li class="chapter" data-level="3.2.4" data-path="summarizing-data.html"><a href="summarizing-data.html#additional-options"><i class="fa fa-check"></i><b>3.2.4</b> Additional options</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="summarizing-data.html"><a href="summarizing-data.html#writing-reports-using-r-markdown"><i class="fa fa-check"></i><b>3.3</b> Writing reports using R-Markdown</a><ul>
<li class="chapter" data-level="3.3.1" data-path="summarizing-data.html"><a href="summarizing-data.html#creating-a-new-r-markdown-document"><i class="fa fa-check"></i><b>3.3.1</b> Creating a new R-Markdown document</a></li>
<li class="chapter" data-level="3.3.2" data-path="summarizing-data.html"><a href="summarizing-data.html#text-and-equations"><i class="fa fa-check"></i><b>3.3.2</b> Text and Equations</a></li>
<li class="chapter" data-level="3.3.3" data-path="summarizing-data.html"><a href="summarizing-data.html#r-code"><i class="fa fa-check"></i><b>3.3.3</b> R-Code</a></li>
<li class="chapter" data-level="3.3.4" data-path="summarizing-data.html"><a href="summarizing-data.html#latex-math"><i class="fa fa-check"></i><b>3.3.4</b> LaTeX Math</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html"><i class="fa fa-check"></i><b>4</b> Introduction to Statistical Inference</a><ul>
<li class="chapter" data-level="4.1" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#if-we-knew-it-all"><i class="fa fa-check"></i><b>4.1</b> If we knew it all</a><ul>
<li class="chapter" data-level="4.1.1" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#sampling-from-a-known-population"><i class="fa fa-check"></i><b>4.1.1</b> Sampling from a known population</a></li>
<li class="chapter" data-level="4.1.2" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>4.1.2</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>4.2</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="4.3" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#using-what-we-actually-know"><i class="fa fa-check"></i><b>4.3</b> Using what we actually know</a><ul>
<li class="chapter" data-level="4.3.1" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#confidence-intervals-for-the-sample-mean"><i class="fa fa-check"></i><b>4.3.1</b> Confidence Intervals for the Sample Mean</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#summary"><i class="fa fa-check"></i><b>4.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>5</b> Hypothesis testing</a><ul>
<li class="chapter" data-level="5.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction"><i class="fa fa-check"></i><b>5.1</b> Introduction</a><ul>
<li class="chapter" data-level="5.1.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#the-null-hypothesis"><i class="fa fa-check"></i><b>5.1.1</b> The null hypothesis</a></li>
<li class="chapter" data-level="5.1.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#statistical-inference-on-a-sample"><i class="fa fa-check"></i><b>5.1.2</b> Statistical inference on a sample</a></li>
<li class="chapter" data-level="5.1.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#choosing-the-right-test"><i class="fa fa-check"></i><b>5.1.3</b> Choosing the right test</a></li>
<li class="chapter" data-level="5.1.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#summary-1"><i class="fa fa-check"></i><b>5.1.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-sample-t-test"><i class="fa fa-check"></i><b>5.2</b> One sample t-test</a></li>
<li class="chapter" data-level="5.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#comparing-two-means"><i class="fa fa-check"></i><b>5.3</b> Comparing two means</a><ul>
<li class="chapter" data-level="5.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#independent-means-t-test"><i class="fa fa-check"></i><b>5.3.1</b> Independent-means t-test</a></li>
<li class="chapter" data-level="5.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#dependent-means-t-test"><i class="fa fa-check"></i><b>5.3.2</b> Dependent-means t-test</a></li>
<li class="chapter" data-level="5.3.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#further-considerations"><i class="fa fa-check"></i><b>5.3.3</b> Further considerations</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#comparing-several-means"><i class="fa fa-check"></i><b>5.4</b> Comparing several means</a><ul>
<li class="chapter" data-level="5.4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction-1"><i class="fa fa-check"></i><b>5.4.1</b> Introduction</a></li>
<li class="chapter" data-level="5.4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#decomposing-variance"><i class="fa fa-check"></i><b>5.4.2</b> Decomposing variance</a></li>
<li class="chapter" data-level="5.4.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-way-anova"><i class="fa fa-check"></i><b>5.4.3</b> One-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#non-parametric-tests"><i class="fa fa-check"></i><b>5.5</b> Non-parametric tests</a><ul>
<li class="chapter" data-level="5.5.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#mann-whitney-u-test-a.k.a.-wilcoxon-rank-sum-test"><i class="fa fa-check"></i><b>5.5.1</b> Mann-Whitney U Test (a.k.a. Wilcoxon rank-sum test)</a></li>
<li class="chapter" data-level="5.5.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>5.5.2</b> Wilcoxon signed-rank test</a></li>
<li class="chapter" data-level="5.5.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#kruskal-wallis-test"><i class="fa fa-check"></i><b>5.5.3</b> Kruskal-Wallis test</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#categorical-data"><i class="fa fa-check"></i><b>5.6</b> Categorical data</a><ul>
<li class="chapter" data-level="5.6.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#confidence-intervals-for-proportions"><i class="fa fa-check"></i><b>5.6.1</b> Confidence intervals for proportions</a></li>
<li class="chapter" data-level="5.6.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#chi-square-test"><i class="fa fa-check"></i><b>5.6.2</b> Chi-square test</a></li>
<li class="chapter" data-level="5.6.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#sample-size-1"><i class="fa fa-check"></i><b>5.6.3</b> Sample size</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>6</b> Regression</a><ul>
<li class="chapter" data-level="6.1" data-path="regression.html"><a href="regression.html#correlation"><i class="fa fa-check"></i><b>6.1</b> Correlation</a><ul>
<li class="chapter" data-level="6.1.1" data-path="regression.html"><a href="regression.html#correlation-coefficient"><i class="fa fa-check"></i><b>6.1.1</b> Correlation coefficient</a></li>
<li class="chapter" data-level="6.1.2" data-path="regression.html"><a href="regression.html#significance-testing"><i class="fa fa-check"></i><b>6.1.2</b> Significance testing</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="regression.html"><a href="regression.html#regression-1"><i class="fa fa-check"></i><b>6.2</b> Regression</a><ul>
<li class="chapter" data-level="6.2.1" data-path="regression.html"><a href="regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>6.2.1</b> Simple linear regression</a></li>
<li class="chapter" data-level="6.2.2" data-path="regression.html"><a href="regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>6.2.2</b> Multiple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="regression.html"><a href="regression.html#potential-problems"><i class="fa fa-check"></i><b>6.3</b> Potential problems</a><ul>
<li class="chapter" data-level="6.3.1" data-path="regression.html"><a href="regression.html#outliers"><i class="fa fa-check"></i><b>6.3.1</b> Outliers</a></li>
<li class="chapter" data-level="6.3.2" data-path="regression.html"><a href="regression.html#influential-observations"><i class="fa fa-check"></i><b>6.3.2</b> Influential observations</a></li>
<li class="chapter" data-level="6.3.3" data-path="regression.html"><a href="regression.html#non-linearity"><i class="fa fa-check"></i><b>6.3.3</b> Non-linearity</a></li>
<li class="chapter" data-level="6.3.4" data-path="regression.html"><a href="regression.html#non-constant-error-variance"><i class="fa fa-check"></i><b>6.3.4</b> Non-constant error variance</a></li>
<li class="chapter" data-level="6.3.5" data-path="regression.html"><a href="regression.html#non-normally-distributed-errors"><i class="fa fa-check"></i><b>6.3.5</b> Non-normally distributed errors</a></li>
<li class="chapter" data-level="6.3.6" data-path="regression.html"><a href="regression.html#correlation-of-errors"><i class="fa fa-check"></i><b>6.3.6</b> Correlation of errors</a></li>
<li class="chapter" data-level="6.3.7" data-path="regression.html"><a href="regression.html#collinearity"><i class="fa fa-check"></i><b>6.3.7</b> Collinearity</a></li>
<li class="chapter" data-level="6.3.8" data-path="regression.html"><a href="regression.html#omitted-variables"><i class="fa fa-check"></i><b>6.3.8</b> Omitted Variables</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="regression.html"><a href="regression.html#categorical-predictors"><i class="fa fa-check"></i><b>6.4</b> Categorical predictors</a><ul>
<li class="chapter" data-level="6.4.1" data-path="regression.html"><a href="regression.html#two-categories"><i class="fa fa-check"></i><b>6.4.1</b> Two categories</a></li>
<li class="chapter" data-level="6.4.2" data-path="regression.html"><a href="regression.html#more-than-two-categories"><i class="fa fa-check"></i><b>6.4.2</b> More than two categories</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="regression.html"><a href="regression.html#extensions-of-the-linear-model"><i class="fa fa-check"></i><b>6.5</b> Extensions of the linear model</a><ul>
<li class="chapter" data-level="6.5.1" data-path="regression.html"><a href="regression.html#interaction-effects"><i class="fa fa-check"></i><b>6.5.1</b> Interaction effects</a></li>
<li class="chapter" data-level="6.5.2" data-path="regression.html"><a href="regression.html#non-linear-relationships"><i class="fa fa-check"></i><b>6.5.2</b> Non-linear relationships</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="regression.html"><a href="regression.html#logistic-regression"><i class="fa fa-check"></i><b>6.6</b> Logistic regression</a><ul>
<li class="chapter" data-level="6.6.1" data-path="regression.html"><a href="regression.html#motivation-and-intuition"><i class="fa fa-check"></i><b>6.6.1</b> Motivation and intuition</a></li>
<li class="chapter" data-level="6.6.2" data-path="regression.html"><a href="regression.html#technical-details-of-the-model"><i class="fa fa-check"></i><b>6.6.2</b> Technical details of the model</a></li>
<li class="chapter" data-level="6.6.3" data-path="regression.html"><a href="regression.html#estimation-in-r"><i class="fa fa-check"></i><b>6.6.3</b> Estimation in R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html"><i class="fa fa-check"></i><b>7</b> Exploratory factor analysis</a><ul>
<li class="chapter" data-level="7.1" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#introduction-2"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#steps-in-factor-analysis"><i class="fa fa-check"></i><b>7.2</b> Steps in factor analysis</a><ul>
<li class="chapter" data-level="7.2.1" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#are-the-assumptions-satisfied"><i class="fa fa-check"></i><b>7.2.1</b> Are the assumptions satisfied?</a></li>
<li class="chapter" data-level="7.2.2" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#deriving-factors"><i class="fa fa-check"></i><b>7.2.2</b> Deriving factors</a></li>
<li class="chapter" data-level="7.2.3" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#factor-interpretation"><i class="fa fa-check"></i><b>7.2.3</b> Factor interpretation</a></li>
<li class="chapter" data-level="7.2.4" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#creating-new-variables"><i class="fa fa-check"></i><b>7.2.4</b> Creating new variables</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#reliability-analysis"><i class="fa fa-check"></i><b>7.3</b> Reliability analysis</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i><b>8</b> Appendix</a><ul>
<li class="chapter" data-level="8.1" data-path="appendix.html"><a href="appendix.html#random-variables-probability-distributions"><i class="fa fa-check"></i><b>8.1</b> Random Variables &amp; Probability Distributions</a><ul>
<li class="chapter" data-level="8.1.1" data-path="appendix.html"><a href="appendix.html#random-variables"><i class="fa fa-check"></i><b>8.1.1</b> Random variables</a></li>
<li class="chapter" data-level="8.1.2" data-path="appendix.html"><a href="appendix.html#probability-distributions"><i class="fa fa-check"></i><b>8.1.2</b> Probability Distributions</a></li>
<li class="chapter" data-level="8.1.3" data-path="appendix.html"><a href="appendix.html#appendix-1"><i class="fa fa-check"></i><b>8.1.3</b> Appendix</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="appendix.html"><a href="appendix.html#regression-2"><i class="fa fa-check"></i><b>8.2</b> Regression</a><ul>
<li class="chapter" data-level="8.2.1" data-path="appendix.html"><a href="appendix.html#linear-regression"><i class="fa fa-check"></i><b>8.2.1</b> Linear regression</a></li>
<li class="chapter" data-level="8.2.2" data-path="appendix.html"><a href="appendix.html#logistic-regression-1"><i class="fa fa-check"></i><b>8.2.2</b> Logistic regression</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="assignments.html"><a href="assignments.html"><i class="fa fa-check"></i><b>9</b> Assignments</a><ul>
<li class="chapter" data-level="9.1" data-path="assignments.html"><a href="assignments.html#assignment-2-hypothesis-testing"><i class="fa fa-check"></i><b>9.1</b> Assignment 2 (Hypothesis Testing)</a></li>
<li class="chapter" data-level="9.2" data-path="assignments.html"><a href="assignments.html#assignment-3-hypothesis-testing-2"><i class="fa fa-check"></i><b>9.2</b> Assignment 3 (Hypothesis Testing 2)</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Marketing Research Design &amp; Analysis 2019</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="exploratory-factor-analysis" class="section level1">
<h1><span class="header-section-number">7</span> Exploratory factor analysis</h1>
<p>This chapter is primarily based on</p>
<ul>
<li>Field, A., Miles J., &amp; Field, Z. (2012): Discovering Statistics Using R. Sage Publications, <strong>chapter 17</strong></li>
<li>Malhotra, N. K.(2010). Marketing Research: An Applied Orientation (6th. ed.). Prentice Hall. <strong>chapter 19</strong></li>
</ul>
<p><a href="./Code/12-pca.R">You can download the corresponding R-Code here</a></p>
<div id="introduction-2" class="section level2">
<h2><span class="header-section-number">7.1</span> Introduction</h2>
<p>In this chapter, we will focus on exploratory factor analysis.</p>
<p>Generally, factor analysis is a class of procedures used for data reduction or summarization. It is an <strong>interdependence technique</strong>, meaning that there is
no distinction between dependent and independent variables and all variables are considered simultaneously. In <strong>exploratory factor analysis</strong>, specific hypotheses about how many factors will emerge, and what items these factors will comprise are not requires (as opposed to confirmatory factor analysis). Principal Components Analysis (PCA) is one of the most frequently used techniques. The goals are …</p>
<ul>
<li>To identify underlying dimensions, or factors, that explain the correlations among a set of variables</li>
<li>To identify a new, smaller set of uncorrelated variables to replace the original set of correlated variables in subsequent multivariate analysis (e.g., regression analysis, t-test, etc.)</li>
</ul>
<p>To see what this means, let’s use a simple example. Say, you wanted to explain the motives underlying the purchasing of toothpaste. You come up with six items that represent different motives of purchasing toothpaste:</p>
<ul>
<li><strong>Item 1</strong>: It is important to buy toothpaste that prevents cavities.</li>
<li><strong>Item 2</strong>: I like a toothpaste that gives shiny teeth.</li>
<li><strong>Item 3</strong>: A toothpaste should strengthen your gums.</li>
<li><strong>Item 4</strong>: I prefer a toothpaste that freshens breath.</li>
<li><strong>Item 5</strong>: Prevention of tooth decay should not be an important benefit offered by a toothpaste.</li>
<li><strong>Item 6</strong>: The most important consideration in buying a toothpaste is attractive teeth.</li>
</ul>
<p>Let’s assume you collect data from 30 respondents and you use 7-point itemized rating scales to measure the extent of agreement to each of these statements. This is the data that you have collected:</p>
<div class="sourceCode" id="cb653"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb653-1" title="1">factor_analysis &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;https://raw.githubusercontent.com/IMSMWU/Teaching/master/MRDA2017/toothpaste.dat&quot;</span>, </a>
<a class="sourceLine" id="cb653-2" title="2">    <span class="dt">sep =</span> <span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>, <span class="dt">header =</span> <span class="ot">TRUE</span>)  <span class="co">#read in data</span></a>
<a class="sourceLine" id="cb653-3" title="3"><span class="kw">str</span>(factor_analysis)  <span class="co">#inspect data</span></a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    30 obs. of  6 variables:
##  $ prevent_cavities: int  7 1 6 4 1 6 5 6 3 2 ...
##  $ shiny_teeth     : int  3 3 2 5 2 3 3 4 4 6 ...
##  $ strengthen_gum  : int  6 2 7 4 2 6 6 7 2 2 ...
##  $ fresh_breath    : int  4 4 4 6 3 4 3 4 3 6 ...
##  $ prevent_decay   : int  6 3 7 6 2 6 4 7 2 1 ...
##  $ attract_teeth   : int  4 4 3 5 2 4 3 4 3 6 ...</code></pre>
<div class="sourceCode" id="cb655"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb655-1" title="1"><span class="kw">head</span>(factor_analysis)  <span class="co">#inspect data</span></a></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["prevent_cavities"],"name":[1],"type":["int"],"align":["right"]},{"label":["shiny_teeth"],"name":[2],"type":["int"],"align":["right"]},{"label":["strengthen_gum"],"name":[3],"type":["int"],"align":["right"]},{"label":["fresh_breath"],"name":[4],"type":["int"],"align":["right"]},{"label":["prevent_decay"],"name":[5],"type":["int"],"align":["right"]},{"label":["attract_teeth"],"name":[6],"type":["int"],"align":["right"]}],"data":[{"1":"7","2":"3","3":"6","4":"4","5":"6","6":"4"},{"1":"1","2":"3","3":"2","4":"4","5":"3","6":"4"},{"1":"6","2":"2","3":"7","4":"4","5":"7","6":"3"},{"1":"4","2":"5","3":"4","4":"6","5":"6","6":"5"},{"1":"1","2":"2","3":"2","4":"3","5":"2","6":"2"},{"1":"6","2":"3","3":"6","4":"4","5":"6","6":"4"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p><br></p>
<p>A <strong>construct</strong> is a specific type of concept that exists at a higher level of abstraction than everyday concepts. In this example, the <em>perceived benefits</em> of toothpaste represent the construct that we would like to measure. The construct is unobservable (‘latent’) but it can be inferred from other measurable variables (items) that together comprise a scale (latent construct). A <strong>multi-item scale</strong> consists of multiple items, where an item is a single question or statement to be evaluated. In the above example, we use six items to measure the perceived benefits of toothpaste. If several items correlate highly, they might measure aspects of a common underlying dimension (a.k.a. factors). That is, specific patterns in the correlation matrix signal the existence of one or more factors underlying the data. Let’s inspect the correlation matrix using the <code>rcorr()</code> function from the <code>Hmisc</code> package.</p>
<p><br></p>
<div class="sourceCode" id="cb656"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb656-1" title="1"><span class="kw">library</span>(<span class="st">&quot;Hmisc&quot;</span>)</a>
<a class="sourceLine" id="cb656-2" title="2"><span class="kw">rcorr</span>(<span class="kw">as.matrix</span>(factor_analysis))</a></code></pre></div>
<pre><code>##                  prevent_cavities shiny_teeth strengthen_gum fresh_breath
## prevent_cavities             1.00       -0.05           0.87        -0.09
## shiny_teeth                 -0.05        1.00          -0.16         0.57
## strengthen_gum               0.87       -0.16           1.00        -0.25
## fresh_breath                -0.09        0.57          -0.25         1.00
## prevent_decay                0.86       -0.02           0.78         0.01
## attract_teeth                0.00        0.64          -0.02         0.64
##                  prevent_decay attract_teeth
## prevent_cavities          0.86          0.00
## shiny_teeth              -0.02          0.64
## strengthen_gum            0.78         -0.02
## fresh_breath              0.01          0.64
## prevent_decay             1.00          0.14
## attract_teeth             0.14          1.00
## 
## n= 30 
## 
## 
## P
##                  prevent_cavities shiny_teeth strengthen_gum fresh_breath
## prevent_cavities                  0.7800      0.0000         0.6508      
## shiny_teeth      0.7800                       0.4134         0.0010      
## strengthen_gum   0.0000           0.4134                     0.1868      
## fresh_breath     0.6508           0.0010      0.1868                     
## prevent_decay    0.0000           0.9175      0.0000         0.9725      
## attract_teeth    0.9826           0.0001      0.9245         0.0001      
##                  prevent_decay attract_teeth
## prevent_cavities 0.0000        0.9826       
## shiny_teeth      0.9175        0.0001       
## strengthen_gum   0.0000        0.9245       
## fresh_breath     0.9725        0.0001       
## prevent_decay                  0.4723       
## attract_teeth    0.4723</code></pre>
<p><br></p>
<p>You can see that some of the items correlate highly, while others don’t. Specifically, there appear to be two groups of items that correlate highly and that might represent underlying dimensions of the construct:</p>
<ul>
<li>Factor 1: Items 1, 3, 5</li>
<li>Factor 2: Items 2, 4, 6</li>
</ul>
<p>Going back to the specific wording of the items you can see that the first group of items (i.e., items 1,3,5) refer to the <strong>health benefits</strong>, while the second item group (i.e., items 2,4,6) refer to the <strong>social benefits</strong>. Imagine now, for example, you would like to include the above variables as explanatory variables in a regression model. Due to the high degree of correlation among the items, you are likely to run into problems of multicollinearity. Instead of omitting some of the items, you might try to combine highly correlated items into one variable. Another application could be when you are developing a new measurement scale for a construct and you wish to explore the underlying dimensions of this construct. In these applications, you need to make sure that the questions that you are asking actually relate to the construct that you intend to measure.</p>
<p>The goal of factor analysis is to explain the maximum amount of total variance in a correlation matrix by transforming the original variables into linear components. This means that the correlation matrix is broken down into a smaller set of dimensions. The generalized formal representation of the linear relationship between a latent factor <em>Y</em> and the set of variables can be written as:</p>
<p><span class="math display" id="eq:factor1">\[\begin{equation} 
Y_i=b_1X_{1i} + b_2X_{2i} + b_nX_{ni}+\epsilon_i
\tag{7.1}
\end{equation}\]</span></p>
<p>where X<sub>n</sub> represents the data that we have collected for the different variables. To make it more explicit, the equation could also be written as</p>
<p><span class="math display" id="eq:factor2">\[\begin{equation} 
Factor_i=b_1Variable_{1i} + b_2Variable_{2i} + b_nVariable_{ni}+\epsilon_i
\tag{7.2}
\end{equation}\]</span></p>
<p>where the dependent variable “Factor” refers to the factor score of person <em>i</em> on the underlying dimensions. In our case, the initial inspection suggested two underlying factors (i.e., health benefits and social benefits), so that we can construct two equations that describe both factors in terms of the variables that we have measured:</p>
<p><span class="math display" id="eq:factor3">\[\begin{equation} 
Health_i=b_1X_{1i} + b_2X_{2i} + b_3X_{3i}+ b_4X_{4i}+ b_5X_{5i}+ b_6X_{6i}+\epsilon_i
\tag{7.3}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:factor4">\[\begin{equation} 
Social_i=b_1X_{1i} + b_2X_{2i} + b_3X_{3i}+ b_4X_{4i}+ b_5X_{5i}+ b_6X_{6i}+\epsilon_i
\tag{7.4}
\end{equation}\]</span></p>
<p>where the b’s in each equation represent the <strong>factor loadings</strong>. You can see that both equations include the same set of predictors. However, their values in each equation will be different, depending on the importance of each variable to the respective factor. Once the factor loadings have been computed (we will see how this is done below), we can summarize them in a component matrix, which is usually denoted as <code>A</code>:</p>
<p><span class="math display">\[\mathbf{A} = \left[\begin{array}
{rrr}
0.93 &amp; 0.25 \\
-0.30 &amp; 0.80 \\
0.94 &amp; 0.13 \\
-0.34 &amp; 0.79 \\
0.87 &amp; 0.35 \\
-0.18 &amp; 0.87
\end{array}\right]\]</span></p>
<p>The linear relation between the factors and the factor loadings can also be shown in a graph, where each axis represents a factor and the variables are placed on the coordinates according to the strength of the relationship between the variable and each factor. The greater the loading of variables on a factor, the more that factor explains relationships between those variables. You can also think of the factor loadings as the correlations between a factor and a variable.</p>
<p><br></p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-382"></span>
<img src="_main_files/figure-html/unnamed-chunk-382-1.png" alt="Factor loadings" width="672" />
<p class="caption">
Figure 7.1: Factor loadings
</p>
</div>
<p><br></p>
<p>The factor loadings may then be used to compute the two new variables (i.e., factor scores) representing the two underlying dimensions. Using a rather simplistic approach, the factor scores for person <em>i</em> could be computed by</p>
<p><span class="math display" id="eq:factor5">\[\begin{equation} 
\begin{split}
Health_i=&amp; 0.93*preventCavities_{i} -0.3*shinyTeeth_{i} + 0.94*strengthenGum_{i}\\
          &amp;-0.34*freshBreath_{i} + 0.87*preventDecay_{i} - 0.18*attractTeeth_{i}
\end{split}
\tag{7.5}
\end{equation}\]</span></p>
<p><span class="math display" id="eq:factor6">\[\begin{equation} 
\begin{split}
Social_i=&amp; 0.25*preventCavities_{i} + 0.80*shinyTeeth_{i} + 0.13*strengthenGum_{i}\\
         &amp;+ 0.79*freshBreath_{i}+ 0.35*preventDecay_{i}+ 0.87*attractTeeth_{i}
\end{split}
\tag{7.6}
\end{equation}\]</span></p>
<p>where the variable names are replaced by the values that were observed for respondent <em>i</em> to compute the factor scores for respondent <em>i</em>. This means that we have reduced the number of variables from six to two. Note that this is a rather simple approach that is intended to explain the underlying logic. However, that the resulting factor scores will depend on the measurement scales of the variables. If different measurement scales would be used, the resulting factor scores for different factors could not be compared. Thus, R will compute the factor scores using more sophisticated methods as we will see below.</p>
</div>
<div id="steps-in-factor-analysis" class="section level2">
<h2><span class="header-section-number">7.2</span> Steps in factor analysis</h2>
<div class="sourceCode" id="cb658"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb658-1" title="1"><span class="kw">readRDS</span>(<span class="st">&quot;music_data.rds&quot;</span>)</a></code></pre></div>
<p>Now that we have a broad understanding of how factor analysis works, let’s use another example to go through the process of deriving factors step by step. In this section, we will use Spotify data.</p>
<div class="figure">
<img src="/home/felix/Documents/e-Assistant%20IMSM/course_daniel/Spotify_logo_with_text.svg.png" alt="Spotify Data © spotify.com" />
<p class="caption">Spotify Data © spotify.com</p>
</div>
<p>We have collected data for 0 songs and stored the results in the data set “music_data”.</p>
<div class="sourceCode" id="cb659"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb659-1" title="1"><span class="co"># spotify_data &lt;-</span></a>
<a class="sourceLine" id="cb659-2" title="2"><span class="co"># read.csv(&#39;/home/felix/Documents/e-Assistant</span></a>
<a class="sourceLine" id="cb659-3" title="3"><span class="co"># IMSM/course_daniel/music_data.csv&#39;, sep = &#39;,&#39;,</span></a>
<a class="sourceLine" id="cb659-4" title="4"><span class="co"># header = TRUE) #read in data spotify_data &lt;-</span></a>
<a class="sourceLine" id="cb659-5" title="5"><span class="co"># na.omit(spotify_data[,c(16:26)])</span></a></code></pre></div>
<div id="are-the-assumptions-satisfied" class="section level3">
<h3><span class="header-section-number">7.2.1</span> Are the assumptions satisfied?</h3>
<p>Since PCA is based on the correlation between variables, the first step is to inspect the correlation matrix, which can be created using the <code>cor()</code> function.</p>
<div class="sourceCode" id="cb660"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb660-1" title="1">spotify_matrix &lt;-<span class="st"> </span><span class="kw">cor</span>(music_data)</a>
<a class="sourceLine" id="cb660-2" title="2"><span class="kw">round</span>(spotify_matrix, <span class="dv">3</span>)</a></code></pre></div>
<pre><code>##                  danceability energy    key loudness   mode speechiness
## danceability            1.000  0.198  0.010    0.187 -0.123       0.227
## energy                  0.198  1.000  0.022    0.737 -0.110       0.093
## key                     0.010  0.022  1.000    0.004 -0.161       0.023
## loudness                0.187  0.737  0.004    1.000 -0.065      -0.012
## mode                   -0.123 -0.110 -0.161   -0.065  1.000      -0.106
## speechiness             0.227  0.093  0.023   -0.012 -0.106       1.000
## acousticness           -0.247 -0.602 -0.006   -0.460  0.086      -0.077
## instrumentalness       -0.089 -0.064 -0.007   -0.198  0.006      -0.077
## liveness               -0.085  0.166 -0.010    0.088  0.019       0.034
## valence                 0.369  0.402  0.031    0.271 -0.061       0.050
## tempo                  -0.084  0.094 -0.004    0.077  0.011       0.061
##                  acousticness instrumentalness liveness valence  tempo
## danceability           -0.247           -0.089   -0.085   0.369 -0.084
## energy                 -0.602           -0.064    0.166   0.402  0.094
## key                    -0.006           -0.007   -0.010   0.031 -0.004
## loudness               -0.460           -0.198    0.088   0.271  0.077
## mode                    0.086            0.006    0.019  -0.061  0.011
## speechiness            -0.077           -0.077    0.034   0.050  0.061
## acousticness            1.000            0.037   -0.070  -0.168 -0.083
## instrumentalness        0.037            1.000   -0.008  -0.087 -0.016
## liveness               -0.070           -0.008    1.000   0.060  0.018
## valence                -0.168           -0.087    0.060   1.000  0.037
## tempo                  -0.083           -0.016    0.018   0.037  1.000</code></pre>
<p>If the variables measure the same construct, we would expect to see a certain degree of correlation between the variables. Even if the variables turn out to measure different dimensions of the same underlying construct, we would still expect to see some degree of correlation. So the first problem that could occur is that the <strong>correlations are not high enough</strong>. A first approach would be to scan the correlation matrix for correlations lower than about 0.3 and identify variables that have many correlations below this threshold. If your data set contains many variables, this task can be quite tedious. To make the task a little easier, you could proceed as follows.</p>
<p>Create a dataframe from the correlation matrix and set the diagonal elements to missing since these are always 1:</p>
<div class="sourceCode" id="cb662"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb662-1" title="1">correlations &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(spotify_matrix)</a>
<a class="sourceLine" id="cb662-2" title="2"><span class="kw">diag</span>(correlations) &lt;-<span class="st"> </span><span class="ot">NA</span></a></code></pre></div>
<p>Now we can use the <code>apply()</code> function to count the number of correlations for each variable that are below a certain threshold (say, 0.3). The <code>apply()</code> function is very useful as it lets you apply function by the rows or columns in your dataframe. In the following example <code>abs(correlations) &lt; 0.3</code> returns a logical value for the correlation matrix that returns <code>TRUE</code> if the statement is true. The second argument <code>1</code> means that the function should be applied to the rows (<code>2</code> would apply it to the columns). The third argument states the function that should be applied. In our case, we would like to count the number of absolute correlations below 0.3 so we apply the <code>sum</code> function, which sums the number of <code>TRUE</code> occurrences by row. The final argument <code>na.rm = TRUE</code> simply tells R to neglect the missing values that we have created for the diagonals of the matrix.</p>
<div class="sourceCode" id="cb663"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb663-1" title="1"><span class="kw">apply</span>(<span class="kw">abs</span>(correlations) <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.3</span>, <span class="dv">1</span>, sum, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>##     danceability           energy              key         loudness 
##                9                7               10                8 
##             mode      speechiness     acousticness instrumentalness 
##               10               10                8               10 
##         liveness          valence            tempo 
##               10                8               10</code></pre>
<p>The output shows you the number of correlations below the threshold for each variable. In a similar way, it would also be possible to compute the mean correlation for each variable.</p>
<div class="sourceCode" id="cb665"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb665-1" title="1"><span class="kw">apply</span>(<span class="kw">abs</span>(correlations), <span class="dv">1</span>, mean, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>##     danceability           energy              key         loudness 
##       0.16183862       0.24875103       0.02788204       0.21006057 
##             mode      speechiness     acousticness instrumentalness 
##       0.07479551       0.07587377       0.18365552       0.05876931 
##         liveness          valence            tempo 
##       0.05602206       0.15360042       0.04864903</code></pre>
<p>Another way to make the correlations more salient is to plot the correlation matrix using different colors that indicate the strength of the correlations. This can be done using the <code>corPlot()</code> function from the <code>psych</code> package.</p>
<div class="sourceCode" id="cb667"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb667-1" title="1"><span class="kw">corPlot</span>(correlations, <span class="dt">numbers =</span> <span class="ot">TRUE</span>, <span class="dt">upper =</span> <span class="ot">FALSE</span>, </a>
<a class="sourceLine" id="cb667-2" title="2">    <span class="dt">diag =</span> <span class="ot">FALSE</span>, <span class="dt">xlas =</span> <span class="dv">2</span>, <span class="dt">main =</span> <span class="st">&quot;Correlations between variables&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-391"></span>
<img src="_main_files/figure-html/unnamed-chunk-391-1.png" alt="Correlation matrix" width="960" />
<p class="caption">
Figure 7.2: Correlation matrix
</p>
</div>
<p>You will, however, notice that this is a rather subjective approach. The <strong>Bartlett’s test</strong> is a statistical test that can be used to test whether all the off-diagonal elements in the population correlation matrix are zero (i.e., whether the population correlation matrix resembles an identify matrix). Thus, it tests whether the correlations are overall too small. If the matrix is an identify matrix, it means that all variables are independent. Thus, a significant test statistic (i.e., p &lt; 0.05) indicates that there is some relationship between variables. The test can be implemented using the <code>cortest.bartlett()</code> function from the <code>psych</code> package:</p>
<div class="sourceCode" id="cb668"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb668-1" title="1"><span class="kw">library</span>(psych)</a>
<a class="sourceLine" id="cb668-2" title="2"><span class="kw">cortest.bartlett</span>(spotify_matrix, <span class="dt">n =</span> <span class="kw">nrow</span>(music_data))</a></code></pre></div>
<pre><code>## $chisq
## [1] 93590.9
## 
## $p.value
## [1] 0
## 
## $df
## [1] 55</code></pre>
<p>In our example, the p-value is less than 0.05, which is good news since it confirms that overall the correlation between variables is different from zero.</p>
<p>The other problem that might occur is that <strong>the correlations are too high</strong>. Actually, a certain degree of multicollinearity is not a problem in PCA. However, it is important to avoid extreme multicollinearity (i.e., variables are highly correlated) and singularity (i.e., variables are perfectly correlated). Multicollinearity causes problems, because it becomes difficult to determine the unique contribution of a variable (as was the case in linear regression analysis). Again, inspecting the entire correlation matrix when there are many variables will be a tedious task. .</p>
<div class="sourceCode" id="cb670"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb670-1" title="1"><span class="kw">apply</span>(<span class="kw">abs</span>(correlations) <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.8</span>, <span class="dv">1</span>, sum, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>##     danceability           energy              key         loudness 
##                0                0                0                0 
##             mode      speechiness     acousticness instrumentalness 
##                0                0                0                0 
##         liveness          valence            tempo 
##                0                0                0</code></pre>
<p>The results do not suggest any extreme or perfect correlations. Again, there is a more objective measure that could be applied. The <strong>determinant</strong> tells us whether the correlation matrix is singular (determinant = 0), or if all variables are completely unrelated (determinant = 1), or somewhere in between. As a rule of thumb, the determinant should be greater than 0.00001. The <code>det()</code> function can be used to compute the determinant:</p>
<div class="sourceCode" id="cb672"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb672-1" title="1"><span class="kw">det</span>(spotify_matrix)</a></code></pre></div>
<pre><code>## [1] 0.1475783</code></pre>
<div class="sourceCode" id="cb674"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb674-1" title="1"><span class="kw">det</span>(spotify_matrix) <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.00001</span></a></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>As you can see, the determinant is larger than the threshold, indicating that the overall correlation between variables is not too strong.</p>
<p>Finally, you should test if the correlation pattern in the matrix is appropriate for factor analysis using the Kaiser-Meyer-Olkin (KMO) measure of sampling adequacy. This statistic is a measure of the proportion of variance among variables that might be common variance.</p>
<p><span class="math display" id="eq:MSA">\[\begin{equation} 
MSA_j=\frac{\sum_{k\ne j}^{}{r^2_{jk}}}{\sum_{k\ne j}^{}{r^2_{jk}}+\sum_{k\ne j}^{}{p^2_{jk}}}
\tag{7.7}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(r_{jk}\)</span> is the correlation between two variables of interest and <span class="math inline">\(p_{jk}\)</span> is their partial correlation. The partial correlation measures the degree of association between the two variables, when the effect of the remaining variables is controlled for. It can take values between 0 (bad) and 1 (good), where a value of 0 indicates that the sum of partial correlations is large relative to the sum of correlations. If the remaining correlation between two variables remains high if you control for all the other variables, this provides an indication that the correlation is fairly concentrated and on a subset of the variables and factor analysis is likely to be inappropriate. In contrast, a value close to 1 means that the sum of the partial correlations is fairly low, indicating a more compact pattern of correlations between a larger set of variables. Values should at least exceed 0.50, with the thresholds:</p>
<ul>
<li>&lt;.50 = unacceptable</li>
<li>&gt;.50 = miserable</li>
<li>&gt;.60 = mediocre</li>
<li>&gt;.70 = middling</li>
<li>&gt;.80 = meritorious</li>
<li>&gt;.90 = marvelous</li>
</ul>
<p>The KMO measure of sampling adequacy can be computed using the <code>KMO()</code> function from the <code>psych</code> package:</p>
<div class="sourceCode" id="cb676"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb676-1" title="1"><span class="kw">KMO</span>(music_data)</a></code></pre></div>
<pre><code>## Kaiser-Meyer-Olkin factor adequacy
## Call: KMO(r = music_data)
## Overall MSA =  0.61
## MSA for each item = 
##     danceability           energy              key         loudness 
##             0.55             0.59             0.51             0.64 
##             mode      speechiness     acousticness instrumentalness 
##             0.66             0.42             0.72             0.44 
##         liveness          valence            tempo 
##             0.59             0.59             0.51</code></pre>
<p>You can see that the statistic is calculated for the entire matrix and for each variable individually. In our example, the values for all variables as well as the overall matrix is above 0.5, suggesting that factor analysis is appropriate.</p>
</div>
<div id="deriving-factors" class="section level3">
<h3><span class="header-section-number">7.2.2</span> Deriving factors</h3>
<p>After testing that the data can be used for PCA, we can move on to conducting PCA. Conducting PCA is fairly simple in R using the <code>principal()</code> function from the <code>psych</code> package. However, before we apply the function to our data, it is useful to reflect on the goals of PCA again. The goal is to explain the maximum amount of total variance in a correlation matrix by transforming the original variables into a smaller set of linear components (factors). So the first decision we have to make is how many factors we should extract. There are different methods that can be used to decide on the appropriate number of factors, including:</p>
<ul>
<li><strong>A priori determination</strong>: Requires prior knowledge</li>
<li><strong>Determination based on percentage of variance</strong>: When cumulative percentage of variance extracted by the factors reaches a satisfactory level (e.g., factors extracted should account for at least 60% of the variance)</li>
<li><strong>Eigenvalues</strong>: Eigenvalues refer to the total variance that is explained by each factor. Factors with eigenvalues greater than 1.0 are retained (factors with a variance less than 1.0 are no better than a single variable)</li>
<li><strong>Scree plot</strong>: Is a plot of the eigenvalues against the number of factors in order of extraction. Assumption: the point at which the scree begins denotes the true number of factors.</li>
</ul>
<p>Often, the decision is made based on a combination of different criteria.</p>
<p>By extracting as many factors as there are variables we can inspect their eigenvalues and make decisions about which factors to extract. Since we have 11 variables, we set the argument <code>nfactors</code> to 11, which is equivalent to the number of columns <code>ncol</code> in our dataset.</p>
<div class="sourceCode" id="cb678"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb678-1" title="1">pc1 &lt;-<span class="st"> </span><span class="kw">principal</span>(music_data, <span class="dt">nfactors =</span> <span class="kw">ncol</span>(music_data), </a>
<a class="sourceLine" id="cb678-2" title="2">    <span class="dt">rotate =</span> <span class="st">&quot;none&quot;</span>)</a>
<a class="sourceLine" id="cb678-3" title="3">pc1</a></code></pre></div>
<pre><code>## Principal Components Analysis
## Call: principal(r = music_data, nfactors = ncol(music_data), rotate = &quot;none&quot;)
## Standardized loadings (pattern matrix) based upon correlation matrix
##                    PC1   PC2   PC3   PC4   PC5   PC6   PC7   PC8   PC9  PC10
## danceability      0.47  0.58 -0.35 -0.07  0.16 -0.03  0.12  0.03 -0.43  0.28
## energy            0.88 -0.23  0.09 -0.08  0.05 -0.02 -0.06  0.05  0.20  0.02
## key               0.05  0.32  0.67 -0.16 -0.30  0.09  0.31  0.47 -0.04  0.02
## loudness          0.80 -0.27  0.01 -0.10 -0.20 -0.05 -0.13  0.02  0.19  0.37
## mode             -0.20 -0.47 -0.54  0.08 -0.01  0.00  0.27  0.61 -0.01  0.02
## speechiness       0.19  0.49 -0.02  0.63  0.29  0.11 -0.24  0.28  0.30 -0.03
## acousticness     -0.72  0.16 -0.08  0.07 -0.13  0.16  0.29 -0.20  0.34  0.39
## instrumentalness -0.22 -0.10  0.26 -0.33  0.81 -0.23  0.12  0.09  0.10  0.11
## liveness          0.16 -0.36  0.21  0.25  0.25  0.78  0.14 -0.11 -0.21  0.06
## valence           0.56  0.21 -0.23 -0.10  0.06  0.08  0.62 -0.21  0.24 -0.27
## tempo             0.12 -0.26  0.25  0.64 -0.01 -0.52  0.35 -0.15 -0.16  0.07
##                   PC11 h2                   u2 com
## danceability      0.06  1 -0.00000000000000067 4.5
## energy            0.33  1  0.00000000000000178 1.6
## key               0.00  1 -0.00000000000000044 3.6
## loudness         -0.23  1  0.00000000000000078 2.3
## mode              0.01  1 -0.00000000000000022 3.6
## speechiness      -0.04  1  0.00000000000000044 4.1
## acousticness      0.11  1  0.00000000000000178 3.2
## instrumentalness -0.04  1  0.00000000000000000 2.2
## liveness         -0.02  1 -0.00000000000000044 2.6
## valence          -0.09  1  0.00000000000000122 3.8
## tempo             0.01  1  0.00000000000000089 3.8
## 
##                        PC1  PC2  PC3  PC4  PC5  PC6  PC7  PC8  PC9 PC10 PC11
## SS loadings           2.63 1.30 1.11 1.05 0.99 0.98 0.89 0.80 0.60 0.47 0.19
## Proportion Var        0.24 0.12 0.10 0.10 0.09 0.09 0.08 0.07 0.05 0.04 0.02
## Cumulative Var        0.24 0.36 0.46 0.55 0.64 0.73 0.81 0.89 0.94 0.98 1.00
## Proportion Explained  0.24 0.12 0.10 0.10 0.09 0.09 0.08 0.07 0.05 0.04 0.02
## Cumulative Proportion 0.24 0.36 0.46 0.55 0.64 0.73 0.81 0.89 0.94 0.98 1.00
## 
## Mean item complexity =  3.2
## Test of the hypothesis that 11 components are sufficient.
## 
## The root mean square of the residuals (RMSR) is  0 
##  with the empirical chi square  0  with prob &lt;  NA 
## 
## Fit based upon off diagonal values = 1</code></pre>
The output is quite complex, but we will focus only on the <code>SS loadings</code> for now, which are the Eigenvalues (a.k.a. sum of squared loadings). One common rule is to retain factors with eigenvalues greater than 1.0. So based on this rule, we would extract 4 factors (i.e., the SS loadings for the
<p>
5<sup>th</sup> factor is &lt; 1).
</p>
<p>You can also plot the eigenvalues against the number of factors in order of extraction using a so-called <strong>Scree plot</strong>:</p>
<div class="sourceCode" id="cb680"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb680-1" title="1"><span class="kw">plot</span>(pc1<span class="op">$</span>values, <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>)</a>
<a class="sourceLine" id="cb680-2" title="2"><span class="kw">axis</span>(<span class="dt">side =</span> <span class="dv">1</span>, <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">ncol</span>(music_data)))</a>
<a class="sourceLine" id="cb680-3" title="3"><span class="kw">abline</span>(<span class="dt">h =</span> <span class="dv">1</span>, <span class="dt">lty =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb680-4" title="4"><span class="kw">abline</span>(<span class="dt">v =</span> nfac, <span class="dt">lty =</span> <span class="dv">2</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-398"></span>
<img src="_main_files/figure-html/unnamed-chunk-398-1.png" alt="Scree plot" width="672" />
<p class="caption">
Figure 7.3: Scree plot
</p>
</div>
<p>The dashed line is simply a visualization of the rule that we will retain factors with Eigenvalues &gt; 1 (suggesting 4 factors). Another criterion based on this plot would be to find the point where the curve flattens (point of inflection). If the largest few eigenvalues in the covariance matrix dominate in magnitude, then the scree plot will exhibit an “elbow”. From that point onwards, the incremental gain in explained variance is rather low. Also according to this criterion, we would extract 4 factors. Taken together, the results suggest that we should extract 4 factors.</p>
<p>Now that we know how many components we want to extract, we can rerun the analysis, specifying that number:</p>
<div class="sourceCode" id="cb681"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb681-1" title="1">pc2 &lt;-<span class="st"> </span><span class="kw">principal</span>(music_data, <span class="dt">nfactors =</span> nfac, <span class="dt">rotate =</span> <span class="st">&quot;none&quot;</span>)</a>
<a class="sourceLine" id="cb681-2" title="2">pc2</a></code></pre></div>
<pre><code>## Principal Components Analysis
## Call: principal(r = music_data, nfactors = nfac, rotate = &quot;none&quot;)
## Standardized loadings (pattern matrix) based upon correlation matrix
##                    PC1   PC2   PC3   PC4   h2   u2 com
## danceability      0.47  0.58 -0.35 -0.07 0.69 0.31 2.7
## energy            0.88 -0.23  0.09 -0.08 0.84 0.16 1.2
## key               0.05  0.32  0.67 -0.16 0.58 0.42 1.6
## loudness          0.80 -0.27  0.01 -0.10 0.72 0.28 1.3
## mode             -0.20 -0.47 -0.54  0.08 0.55 0.45 2.3
## speechiness       0.19  0.49 -0.02  0.63 0.68 0.32 2.1
## acousticness     -0.72  0.16 -0.08  0.07 0.55 0.45 1.1
## instrumentalness -0.22 -0.10  0.26 -0.33 0.24 0.76 2.9
## liveness          0.16 -0.36  0.21  0.25 0.26 0.74 2.9
## valence           0.56  0.21 -0.23 -0.10 0.43 0.57 1.7
## tempo             0.12 -0.26  0.25  0.64 0.56 0.44 1.7
## 
##                        PC1  PC2  PC3  PC4
## SS loadings           2.63 1.30 1.11 1.05
## Proportion Var        0.24 0.12 0.10 0.10
## Cumulative Var        0.24 0.36 0.46 0.55
## Proportion Explained  0.43 0.21 0.18 0.17
## Cumulative Proportion 0.43 0.65 0.83 1.00
## 
## Mean item complexity =  2
## Test of the hypothesis that 4 components are sufficient.
## 
## The root mean square of the residuals (RMSR) is  0.11 
##  with the empirical chi square  70129.69  with prob &lt;  0 
## 
## Fit based upon off diagonal values = 0.63</code></pre>
<p>Now that the output is less complex, we can inspect the remaining statistics. The first part of the output is the <strong>factor matrix</strong>, which contains the factor loadings of all the variables on the 4 extracted factors (i.e., PC1, PC2, PC3, PC4). As we have said before, the <strong>factor loadings</strong> are the correlations between the variables and the factors. The factor matrix also contains the columns “h2” and “u2”. “h2” refers to the <strong>communality</strong>, which is the proportion of variance a variable shares with all the other variables being considered. This is also the proportion of variance explained by the common factors. In contrast, “u2” refers to the unique variance, which is the proportion of the variance that is unique to a particular variable. In PCA, we are primarily interested in the common variance. When the communality is very low (say &lt;.30), a variable is “quite unique” and should be removed, as it is definitely measuring “something else”. In our example, all communalities (i.e., h2) are above 0.3 so that we retain all variables.</p>
<div class="sourceCode" id="cb683"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb683-1" title="1"><span class="co"># pc2$communality &lt; 0.3</span></a>
<a class="sourceLine" id="cb683-2" title="2"><span class="kw">sum</span>(pc2<span class="op">$</span>communality <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.3</span>)</a></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>Note that there is a difference between PCA and common factor analysis. PCA focuses on the variance and aims to reproduce the total variable variance. This means that the components reflect both common and unique variance of the variables. Factor analysis, in contrast, focuses on the correlation and aims to reproduce the correlations among variables. Here, the factors only represent the common variance that variable share and do not include the unique variance. In other words, while factor analysis focuses on explaining the off-diagonal terms in the correlation matrix (i.e., shared co-variance), PCA focuses on explaining the diagonal terms (i.e., the variances). However, although PCA aims to reproduce the on-diagonal terms in the correlation matrix, it also tends to fit the off-diagonal correlations quite well. Hence, the results are often comparable. See also <a href="https://en.wikipedia.org/wiki/Principal_component_analysis#Relation_between_PCA_and_factor_analysis" target="_blank">here</a>.</p>
<p>You should also take a closer look at the residuals in order to check whether you have extracted the correct number of factors. The difference between the reproduced and the actual correlation matrices are the residuals. We can extract the residuals from our model using the <code>factor.residuals()</code> function from the <code>psych</code> package. It takes the original correlation matrix and the factor loadings as arguments:</p>
<div class="sourceCode" id="cb685"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb685-1" title="1">residuals &lt;-<span class="st"> </span><span class="kw">factor.residuals</span>(spotify_matrix, pc2<span class="op">$</span>loadings)</a>
<a class="sourceLine" id="cb685-2" title="2"><span class="kw">round</span>(residuals, <span class="dv">3</span>)</a></code></pre></div>
<pre><code>##                  danceability energy    key loudness   mode speechiness
## danceability            0.310 -0.058  0.025   -0.035  0.060      -0.115
## energy                 -0.058  0.161 -0.023   -0.033  0.014       0.086
## key                     0.025 -0.023  0.419    0.026  0.373      -0.033
## loudness               -0.035 -0.033  0.026    0.283 -0.018       0.032
## mode                    0.060  0.014  0.373   -0.018  0.446       0.104
## speechiness            -0.115  0.086 -0.033    0.032  0.104       0.323
## acousticness           -0.024  0.077  0.048    0.161 -0.035      -0.061
## instrumentalness        0.144  0.052 -0.190   -0.092  0.080       0.232
## liveness                0.137 -0.061 -0.004   -0.117 -0.024       0.029
## valence                -0.107 -0.033  0.074   -0.130  0.034      -0.100
## tempo                   0.139 -0.047  0.003   -0.027  0.000      -0.235
##                  acousticness instrumentalness liveness valence  tempo
## danceability           -0.024            0.144    0.137  -0.107  0.139
## energy                  0.077            0.052   -0.061  -0.033 -0.047
## key                     0.048           -0.190   -0.004   0.074  0.003
## loudness                0.161           -0.092   -0.117  -0.130 -0.027
## mode                   -0.035            0.080   -0.024   0.034  0.000
## speechiness            -0.061            0.232    0.029  -0.100 -0.235
## acousticness            0.449           -0.056    0.104   0.192  0.022
## instrumentalness       -0.056            0.763    0.017   0.081  0.132
## liveness                0.104            0.017    0.739   0.117 -0.305
## valence                 0.192            0.081    0.117   0.573  0.147
## tempo                   0.022            0.132   -0.305   0.147  0.443</code></pre>
<p>Note that the diagonal elements in the residual matrix correspond to the unique variance in each variable that cannot be explained by the factors (i.e., “u2” in the output above). For example, the proportion of unique variance for <code>danceability</code> is 0.31, which is reflected in the first cell in the residual matrix. The off-diagonal elements represent the difference between the actual correlations and the correlation based on the reproduced correlation matrix for all variable pairs. To see this, the reproduced correlation matrix could be generated by using the <code>factor.model()</code> function:</p>
<div class="sourceCode" id="cb687"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb687-1" title="1">reproduced_matrix &lt;-<span class="st"> </span><span class="kw">factor.model</span>(pc2<span class="op">$</span>loadings)</a>
<a class="sourceLine" id="cb687-2" title="2"><span class="kw">round</span>(reproduced_matrix, <span class="dv">3</span>)</a></code></pre></div>
<pre><code>##                  danceability energy    key loudness   mode speechiness
## danceability            0.690  0.255 -0.015    0.222 -0.183       0.342
## energy                  0.255  0.839  0.045    0.770 -0.124       0.007
## key                    -0.015  0.045  0.581   -0.022 -0.534       0.056
## loudness                0.222  0.770 -0.022    0.717 -0.048      -0.044
## mode                   -0.183 -0.124 -0.534   -0.048  0.554      -0.209
## speechiness             0.342  0.007  0.056   -0.044 -0.209       0.677
## acousticness           -0.223 -0.679 -0.055   -0.621  0.122      -0.015
## instrumentalness       -0.232 -0.116  0.183   -0.106 -0.074      -0.308
## liveness               -0.222  0.227 -0.006    0.205  0.043       0.005
## valence                 0.476  0.435 -0.043    0.401 -0.095       0.149
## tempo                  -0.223  0.142 -0.008    0.105  0.010       0.296
##                  acousticness instrumentalness liveness valence  tempo
## danceability           -0.223           -0.232   -0.222   0.476 -0.223
## energy                 -0.679           -0.116    0.227   0.435  0.142
## key                    -0.055            0.183   -0.006  -0.043 -0.008
## loudness               -0.621           -0.106    0.205   0.401  0.105
## mode                    0.122           -0.074    0.043  -0.095  0.010
## speechiness            -0.015           -0.308    0.005   0.149  0.296
## acousticness            0.551            0.092   -0.175  -0.360 -0.106
## instrumentalness        0.092            0.237   -0.025  -0.168 -0.148
## liveness               -0.175           -0.025    0.261  -0.056  0.323
## valence                -0.360           -0.168   -0.056   0.427 -0.110
## tempo                  -0.106           -0.148    0.323  -0.110  0.557</code></pre>
<p>You can see that the reproduced correlation between the first and second variable is 0.255. From the correlation table from the beginning we know, however, that the observed correlation was 0.198. Hence, the difference between the observed and reproduced correlation is: 0.198 - 0.255 = -0.058, which corresponds to the residual of this variable pair in the residual matrix. Note that the diagonal elements in the reproduced matrix correspond to the communalities in the model summary above (i.e., “h2”).</p>
<p>A measure of fit can now be computed based on the size of the residuals. In the worst case, the residuals would be as large as the correlations in the original matrix, which would be the case if we extracted no factors at all. A measure of fit could therefore be the sum of the squared residuals divided by the sum of the squared correlations. We square the residuals to account for positive and negative deviations. <strong>Values &gt;0.90 are considered indicators of good fit.</strong> From the output above, you can see that: “Fit based upon off diagonal values = 0.63”. Thus, we conclude that the model has a mediocre fit.</p>
<p>You could also manually compute this statistic by summing over the squared residuals and correlations, take their ratio and subtract it from one (note that we use the <code>upper.tri()</code> function to use the upper triangle of the matrix only; this has the effect of discarding the diagonal elements and the elements below the diagonal).</p>
<div class="sourceCode" id="cb689"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb689-1" title="1">ssr &lt;-<span class="st"> </span>(<span class="kw">sum</span>(residuals[<span class="kw">upper.tri</span>((residuals))]<span class="op">^</span><span class="dv">2</span>))  <span class="co">#sum of squared residuals </span></a>
<a class="sourceLine" id="cb689-2" title="2">ssc &lt;-<span class="st"> </span>(<span class="kw">sum</span>(spotify_matrix[<span class="kw">upper.tri</span>((spotify_matrix))]<span class="op">^</span><span class="dv">2</span>))  <span class="co">#sum of squared correlations</span></a>
<a class="sourceLine" id="cb689-3" title="3"><span class="dv">1</span> <span class="op">-</span><span class="st"> </span>(ssr<span class="op">/</span>ssc)  <span class="co">#model fit</span></a></code></pre></div>
<pre><code>## [1] 0.6336011</code></pre>
<p>In a next step, we check the size of the residuals. <strong>If fewer residuals than 50% have absolute values greater than 0.05 the model is a good fit.</strong> This can be tested using the following code. We first convert the residuals to a matrix and select the upper triangular again to avoid duplicates. Finally, we count all occurrences where the absolute value is larger than 0.05 and divide it by the number of total observations to get the proportion.</p>
<div class="sourceCode" id="cb691"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb691-1" title="1">residuals &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(residuals[<span class="kw">upper.tri</span>((residuals))])</a>
<a class="sourceLine" id="cb691-2" title="2">large_res &lt;-<span class="st"> </span><span class="kw">abs</span>(residuals) <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.05</span></a>
<a class="sourceLine" id="cb691-3" title="3"><span class="kw">sum</span>(large_res)</a></code></pre></div>
<pre><code>## [1] 32</code></pre>
<div class="sourceCode" id="cb693"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb693-1" title="1"><span class="kw">sum</span>(large_res)<span class="op">/</span><span class="kw">nrow</span>(residuals)</a></code></pre></div>
<pre><code>## [1] 0.5818182</code></pre>
<p>In our example, we cannot confirm that the proportion of residuals &gt; 0.05 is less than 50%.</p>
<p>Another way to evaluate the residuals is by looking at their mean value (rather, we square the residuals first to account for positive and negative values, compute the mean and then take the square root).</p>
<div class="sourceCode" id="cb695"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb695-1" title="1"><span class="kw">sqrt</span>(<span class="kw">mean</span>(residuals<span class="op">^</span><span class="dv">2</span>))</a></code></pre></div>
<pre><code>## [1] 0.1141605</code></pre>
<p>This means that our mean residual is 0.1142 and this value should be as low as possible.</p>
<p>Finally, we need to validate if the residuals are approximately normally distributed, which we do by using a histogram, a Q-Q plot and the Shapiro test.</p>
<div class="sourceCode" id="cb697"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb697-1" title="1"><span class="kw">hist</span>(residuals)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-408"></span>
<img src="_main_files/figure-html/unnamed-chunk-408-1.png" alt="Histogram of residuals" width="672" />
<p class="caption">
Figure 7.4: Histogram of residuals
</p>
</div>
<div class="sourceCode" id="cb698"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb698-1" title="1"><span class="kw">qqnorm</span>(residuals)</a>
<a class="sourceLine" id="cb698-2" title="2"><span class="kw">qqline</span>(residuals)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-409"></span>
<img src="_main_files/figure-html/unnamed-chunk-409-1.png" alt="Q-Q plot" width="672" />
<p class="caption">
Figure 7.5: Q-Q plot
</p>
</div>
<div class="sourceCode" id="cb699"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb699-1" title="1"><span class="kw">shapiro.test</span>(residuals)</a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals
## W = 0.97658, p-value = 0.3559</code></pre>
<p>All of the tests suggest that the distribution of the residuals is approximately normal.</p>
</div>
<div id="factor-interpretation" class="section level3">
<h3><span class="header-section-number">7.2.3</span> Factor interpretation</h3>
<p>To aid interpretation, it is possible to maximize the loading of a variable on one factor while minimizing its loading on all other factors. This is known as factor rotation. There are two types of factor rotation:</p>
<ul>
<li>orthogonal (assumes that factors are uncorrelated)</li>
<li>oblique (assumes that factors are intercorrelated)</li>
</ul>
<p>To carry out a orthogonal rotation, we change the rotate option in the <code>principal()</code> function from “none” to “varimax” (we could also exclude it altogether because varimax is the default if the option is not specified):</p>
<div class="sourceCode" id="cb701"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb701-1" title="1">pc3 &lt;-<span class="st"> </span><span class="kw">principal</span>(music_data, <span class="dt">nfactors =</span> nfac, <span class="dt">rotate =</span> <span class="st">&quot;varimax&quot;</span>)</a>
<a class="sourceLine" id="cb701-2" title="2">pc3</a></code></pre></div>
<pre><code>## Principal Components Analysis
## Call: principal(r = music_data, nfactors = nfac, rotate = &quot;varimax&quot;)
## Standardized loadings (pattern matrix) based upon correlation matrix
##                    RC1   RC4   RC3   RC2   h2   u2 com
## danceability      0.33  0.52  0.08 -0.55 0.69 0.31 2.7
## energy            0.90  0.05  0.06  0.14 0.84 0.16 1.1
## key               0.00 -0.11  0.75  0.03 0.58 0.42 1.0
## loudness          0.84  0.00 -0.03  0.10 0.72 0.28 1.0
## mode             -0.09 -0.11 -0.73  0.07 0.55 0.45 1.1
## speechiness      -0.06  0.79  0.19  0.11 0.68 0.32 1.2
## acousticness     -0.73 -0.05 -0.08 -0.09 0.55 0.45 1.1
## instrumentalness -0.11 -0.44  0.18 -0.03 0.24 0.76 1.5
## liveness          0.18 -0.04 -0.03  0.47 0.26 0.74 1.3
## valence           0.51  0.27 -0.01 -0.30 0.43 0.57 2.2
## tempo             0.04  0.28  0.01  0.69 0.56 0.44 1.3
## 
##                        RC1  RC4  RC3  RC2
## SS loadings           2.49 1.27 1.18 1.15
## Proportion Var        0.23 0.12 0.11 0.10
## Cumulative Var        0.23 0.34 0.45 0.55
## Proportion Explained  0.41 0.21 0.19 0.19
## Cumulative Proportion 0.41 0.62 0.81 1.00
## 
## Mean item complexity =  1.4
## Test of the hypothesis that 4 components are sufficient.
## 
## The root mean square of the residuals (RMSR) is  0.11 
##  with the empirical chi square  70129.69  with prob &lt;  0 
## 
## Fit based upon off diagonal values = 0.63</code></pre>
<p>Interpreting the factor loading matrix is a little complex, so we can make it easier by using the <code>print.psych()</code> function, which we can use to exclude loading below a cutoff from the display and order the variables by their loading within each factor. In the following, we will only display loadings that exceed the value 0.3.</p>
<div class="sourceCode" id="cb703"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb703-1" title="1"><span class="kw">print.psych</span>(pc3, <span class="dt">cut =</span> <span class="fl">0.3</span>, <span class="dt">sort =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## Principal Components Analysis
## Call: principal(r = music_data, nfactors = nfac, rotate = &quot;varimax&quot;)
## Standardized loadings (pattern matrix) based upon correlation matrix
##                  item   RC1   RC4   RC3   RC2   h2   u2 com
## energy              2  0.90                   0.84 0.16 1.1
## loudness            4  0.84                   0.72 0.28 1.0
## acousticness        7 -0.73                   0.55 0.45 1.1
## valence            10  0.51                   0.43 0.57 2.2
## speechiness         6        0.79             0.68 0.32 1.2
## instrumentalness    8       -0.44             0.24 0.76 1.5
## key                 3              0.75       0.58 0.42 1.0
## mode                5             -0.73       0.55 0.45 1.1
## tempo              11                    0.69 0.56 0.44 1.3
## danceability        1  0.33  0.52       -0.55 0.69 0.31 2.7
## liveness            9                    0.47 0.26 0.74 1.3
## 
##                        RC1  RC4  RC3  RC2
## SS loadings           2.49 1.27 1.18 1.15
## Proportion Var        0.23 0.12 0.11 0.10
## Cumulative Var        0.23 0.34 0.45 0.55
## Proportion Explained  0.41 0.21 0.19 0.19
## Cumulative Proportion 0.41 0.62 0.81 1.00
## 
## Mean item complexity =  1.4
## Test of the hypothesis that 4 components are sufficient.
## 
## The root mean square of the residuals (RMSR) is  0.11 
##  with the empirical chi square  70129.69  with prob &lt;  0 
## 
## Fit based upon off diagonal values = 0.63</code></pre>
<p>After obtaining the rotated matrix, variables with high loading are used for interpreting (=naming) the factor. Note that factor loading can be positive or negative (depends on scaling of the variable), thus take care when interpreting! Look for simple structure: each variable (hopefully) loads high on 1 factor and low on other factors.</p>
<p>As an example, we could name our factors as follows:</p>
<ul>
<li><strong>Factor 1:</strong> energetic</li>
<li><strong>Factor 2:</strong> fast</li>
<li><strong>Factor 3:</strong> pitch</li>
<li><strong>Factor 4:</strong> dancefloor</li>
</ul>
<p>The previous type of rotation (i.e., “varimax”) assumed that the factors are independent. Oblique rotation is another type of rotation that can handle correlation between the factors. The command for an oblique rotation is very similar to that for an orthogonal rotation – we just change the rotate option from “varimax” to “oblimin”.</p>
<div class="sourceCode" id="cb705"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb705-1" title="1">pc4 &lt;-<span class="st"> </span><span class="kw">principal</span>(music_data, <span class="dt">nfactors =</span> nfac, <span class="dt">rotate =</span> <span class="st">&quot;oblimin&quot;</span>, </a>
<a class="sourceLine" id="cb705-2" title="2">    <span class="dt">scores =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb705-3" title="3"><span class="kw">print.psych</span>(pc4, <span class="dt">cut =</span> <span class="fl">0.3</span>, <span class="dt">sort =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## Principal Components Analysis
## Call: principal(r = music_data, nfactors = nfac, rotate = &quot;oblimin&quot;, 
##     scores = TRUE)
## Standardized loadings (pattern matrix) based upon correlation matrix
##                  item   TC1   TC2   TC4   TC3   h2   u2 com
## energy              2  0.92                   0.84 0.16 1.0
## loudness            4  0.85                   0.72 0.28 1.0
## acousticness        7 -0.74                   0.55 0.45 1.0
## valence            10  0.42 -0.42             0.43 0.57 2.2
## danceability        1       -0.70  0.30       0.69 0.31 1.5
## tempo              11        0.60  0.47       0.56 0.44 2.0
## liveness            9        0.45             0.26 0.74 1.8
## speechiness         6              0.82       0.68 0.32 1.1
## instrumentalness    8             -0.41       0.24 0.76 1.8
## key                 3                    0.77 0.58 0.42 1.0
## mode                5                   -0.71 0.55 0.45 1.1
## 
##                        TC1  TC2  TC4  TC3
## SS loadings           2.47 1.26 1.19 1.16
## Proportion Var        0.22 0.11 0.11 0.11
## Cumulative Var        0.22 0.34 0.45 0.55
## Proportion Explained  0.41 0.21 0.20 0.19
## Cumulative Proportion 0.41 0.61 0.81 1.00
## 
##  With component correlations of 
##       TC1   TC2   TC4   TC3
## TC1  1.00 -0.11  0.16  0.04
## TC2 -0.11  1.00 -0.09 -0.06
## TC4  0.16 -0.09  1.00  0.08
## TC3  0.04 -0.06  0.08  1.00
## 
## Mean item complexity =  1.4
## Test of the hypothesis that 4 components are sufficient.
## 
## The root mean square of the residuals (RMSR) is  0.11 
##  with the empirical chi square  70129.69  with prob &lt;  0 
## 
## Fit based upon off diagonal values = 0.63</code></pre>
<p>The component correlations indicate that the factors are not correlated, therefore orthogonal rotation is appropriate.</p>
</div>
<div id="creating-new-variables" class="section level3">
<h3><span class="header-section-number">7.2.4</span> Creating new variables</h3>
<p>Once we have decided on the final model, we can calculate the new variables as the weighted sum of the variables that form a factor. This means, we estimate a person’s score on a factor based on their scores on the items that constitute the measurement scales. These scores are also referred to as the <strong>factor scores</strong>. Because we have used the <code>scores = TRUE</code> argument in the previous command, the factor scores have already been created for us. By default, R uses the regression method to compute the factor scores, which controls for differences in the units of measurement. You can access the residuals as follows:</p>
<div class="sourceCode" id="cb707"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb707-1" title="1"><span class="kw">head</span>(pc4<span class="op">$</span>scores)</a></code></pre></div>
<pre><code>##              TC1        TC2        TC4         TC3
## [1,]  0.05562364  0.8984766  1.9432405 -0.17399267
## [2,] -0.19181568 -1.1350614 -0.7694889 -0.18914454
## [3,]  0.42472334  2.5388163  0.2524246 -0.06814408
## [4,]  0.63759981 -0.9029330 -0.4110607  1.22065459
## [5,]  0.46279072 -0.1900550 -0.4111348 -1.34062432
## [6,] -0.39042128 -1.0295503  2.7229197  1.56781951</code></pre>
<p>We can also use the <code>cbind()</code> function to add the computed factor scores to the existing data set:</p>
<div class="sourceCode" id="cb709"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb709-1" title="1">music_data &lt;-<span class="st"> </span><span class="kw">cbind</span>(music_data, pc4<span class="op">$</span>scores)</a></code></pre></div>
<p>This way, it is easier to use the new variables in subsequent analysis (e.g., t-tests, regression, ANOVA, cluster analysis).</p>
</div>
</div>
<div id="reliability-analysis" class="section level2">
<h2><span class="header-section-number">7.3</span> Reliability analysis</h2>
<p>When you are using multi-item scales to measure a latent construct (e.g., the output from the PCA above), it is useful to check the reliability of your scale. Reliability means that our items should consistently reflect the construct that they are intended to measure. In other words, individual items should produce results consistent with the overall scale. This means that for a scale to be reliable, the score of a person on one half of the items should be similar to the score derived based on the other half of the items (split-half reliability). The problem is that there are several ways in which data can be split. A measure that reflects this underlying intuition is <strong>Cronbach’s alpha</strong>, which is approximately equal to the average of all possible split-half reliabilities. It is computed as follows:</p>
<p><span class="math display" id="eq:calpha">\[\begin{equation} 
\alpha=\frac{N^2\overline{Cov}}{\sum{s^2_{item}}+\sum{Cov_{item}}}
\tag{7.8}
\end{equation}\]</span></p>
<p>The share of the items common variance (inter-correlation) in the total variance is supposed to be as high as possible across all items. The thresholds are as follows:</p>
<ul>
<li>&gt;0.7 reasonable for practical application/explorative research</li>
<li>&gt;0.8 necessary for fundamental research</li>
<li>&gt;0.9 desirable for applied research</li>
</ul>
<p>To see if the subscales that were derived from the previous PCA exhibit a sufficient degree of reliability, we first create subsets of our data set that contain the respective items for each of the factors (we use the results from the oblimin rotation here):</p>
<div class="sourceCode" id="cb710"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb710-1" title="1">energetic &lt;-<span class="st"> </span>music_data[, <span class="kw">c</span>(rc1)]</a>
<a class="sourceLine" id="cb710-2" title="2">fast &lt;-<span class="st"> </span>music_data[, <span class="kw">c</span>(rc2)]</a>
<a class="sourceLine" id="cb710-3" title="3">pitch &lt;-<span class="st"> </span>music_data[, <span class="kw">c</span>(rc3)]</a>
<a class="sourceLine" id="cb710-4" title="4">dancefloor &lt;-<span class="st"> </span>music_data[, <span class="kw">c</span>(rc4)]</a></code></pre></div>
<p>Now we can use the <code>alpha()</code> function from the <code>psych</code> package to test the reliability. Note that the <code>keys</code> argument may be used to indicate reverse coded items.</p>
<div class="sourceCode" id="cb711"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb711-1" title="1">psych<span class="op">::</span><span class="kw">alpha</span>(energetic)</a></code></pre></div>
<pre><code>## Some items ( acousticness ) were negatively correlated with the total scale and 
## probably should be reversed.  
## To do this, run the function again with the &#39;check.keys=TRUE&#39; option</code></pre>
<pre><code>## 
## Reliability analysis   
## Call: psych::alpha(x = energetic)
## 
##   raw_alpha std.alpha G6(smc) average_r  S/N    ase  mean   sd median_r
##       0.08      0.27    0.54     0.069 0.37 0.0013 -0.96 0.59     0.19
## 
##  lower alpha upper     95% confidence boundaries
## 0.08 0.08 0.08 
## 
##  Reliability if an item is dropped:
##              raw_alpha std.alpha G6(smc) average_r    S/N alpha se var.r
## danceability     0.060     0.110    0.49    0.0301  0.124   0.0013 0.275
## energy          -0.033    -0.032    0.19   -0.0078 -0.031   0.0016 0.109
## loudness        -0.257    -0.032    0.31   -0.0079 -0.031   0.0094 0.158
## acousticness     0.190     0.693    0.70    0.3608  2.258   0.0012 0.042
## valence          0.028    -0.137    0.34   -0.0311 -0.121   0.0010 0.249
##                med.r
## danceability  0.0517
## energy        0.0098
## loudness      0.0149
## acousticness  0.3202
## valence      -0.0296
## 
##  Item statistics 
##                  n raw.r std.r r.cor r.drop  mean   sd
## danceability 48919  0.25  0.60  0.37   0.20  0.65 0.15
## energy       48919  0.75  0.69  0.76   0.73  0.64 0.18
## loudness     48919  0.99  0.69  0.69   0.27 -6.85 2.82
## acousticness 48919 -0.41 -0.19 -0.58  -0.48  0.27 0.26
## valence      48919  0.37  0.74  0.62   0.30  0.50 0.23</code></pre>
<div class="sourceCode" id="cb714"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb714-1" title="1">psych<span class="op">::</span><span class="kw">alpha</span>(fast)</a></code></pre></div>
<pre><code>## Some items ( danceability ) were negatively correlated with the total scale and 
## probably should be reversed.  
## To do this, run the function again with the &#39;check.keys=TRUE&#39; option</code></pre>
<pre><code>## 
## Reliability analysis   
## Call: psych::alpha(x = fast)
## 
##   raw_alpha std.alpha G6(smc) average_r   S/N      ase mean  sd median_r
##    -0.0011     -0.17    -0.1     -0.05 -0.14 0.000095   41 9.4   -0.084
## 
##  lower alpha upper     95% confidence boundaries
## 0 0 0 
## 
##  Reliability if an item is dropped:
##              raw_alpha std.alpha G6(smc) average_r    S/N alpha se var.r  med.r
## danceability   0.00037     0.036   0.018     0.018  0.037 0.000091    NA  0.018
## liveness      -0.00177    -0.184  -0.084    -0.084 -0.155 0.000095    NA -0.084
## tempo         -0.18486    -0.185  -0.085    -0.085 -0.156 0.010704    NA -0.085
## 
##  Item statistics 
##                  n  raw.r std.r r.cor r.drop   mean    sd
## danceability 48919 -0.079  0.51   NaN -0.084   0.65  0.15
## liveness     48919  0.023  0.57   NaN  0.018   0.18  0.14
## tempo        48919  1.000  0.57   NaN -0.050 121.31 28.21</code></pre>
<div class="sourceCode" id="cb717"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb717-1" title="1"><span class="co"># psych::alpha(statistics_fear,</span></a>
<a class="sourceLine" id="cb717-2" title="2"><span class="co"># keys=c(1,1,1,1,1,1,1,1))</span></a>
<a class="sourceLine" id="cb717-3" title="3">psych<span class="op">::</span><span class="kw">alpha</span>(pitch)</a></code></pre></div>
<pre><code>## Some items ( key ) were negatively correlated with the total scale and 
## probably should be reversed.  
## To do this, run the function again with the &#39;check.keys=TRUE&#39; option</code></pre>
<pre><code>## 
## Reliability analysis   
## Call: psych::alpha(x = pitch)
## 
##   raw_alpha std.alpha G6(smc) average_r   S/N    ase mean  sd median_r
##      -0.09     -0.38   -0.16     -0.16 -0.28 0.0026    3 1.8    -0.16
## 
##  lower alpha upper     95% confidence boundaries
## -0.09 -0.09 -0.08 
## 
##  Reliability if an item is dropped:
##      raw_alpha std.alpha G6(smc) average_r S/N alpha se  var.r med.r
## key     -0.161     -0.16   0.026     -0.16  NA       NA -0.161 -0.16
## mode     0.026     -0.16      NA        NA  NA       NA  0.026 -0.16
## 
##  Item statistics 
##          n  raw.r std.r r.cor r.drop mean   sd
## key  48919  0.991  0.65   NaN  -0.16 5.34 3.62
## mode 48919 -0.025  0.65   NaN  -0.16 0.58 0.49</code></pre>
<div class="sourceCode" id="cb720"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb720-1" title="1">psych<span class="op">::</span><span class="kw">alpha</span>(dancefloor)</a></code></pre></div>
<pre><code>## Some items ( instrumentalness ) were negatively correlated with the total scale and 
## probably should be reversed.  
## To do this, run the function again with the &#39;check.keys=TRUE&#39; option</code></pre>
<pre><code>## 
## Reliability analysis   
## Call: psych::alpha(x = dancefloor)
## 
##   raw_alpha std.alpha G6(smc) average_r   S/N    ase mean    sd median_r
##        0.1     0.059   0.079     0.021 0.063 0.0066 0.26 0.073   -0.077
## 
##  lower alpha upper     95% confidence boundaries
## 0.09 0.1 0.12 
## 
##  Reliability if an item is dropped:
##                  raw_alpha std.alpha G6(smc) average_r   S/N alpha se var.r
## danceability         -0.16     -0.17  -0.077    -0.077 -0.14   0.0104    NA
## speechiness          -0.18     -0.19  -0.089    -0.089 -0.16   0.0098    NA
## instrumentalness      0.36      0.37   0.227     0.227  0.59   0.0056    NA
##                   med.r
## danceability     -0.077
## speechiness      -0.089
## instrumentalness  0.227
## 
##  Item statistics 
##                      n raw.r std.r r.cor r.drop  mean    sd
## danceability     48919  0.75  0.64  0.39   0.12 0.651 0.148
## speechiness      48919  0.64  0.65  0.41   0.15 0.116 0.115
## instrumentalness 48919  0.35  0.47 -0.31  -0.11 0.017 0.099</code></pre>
<p>The above output would lead us to conclude that the fear of computers, fear of statistics and fear of maths subscales of the RAQ all had sufficiently high reliabilities (i.e., Cronbach’s alpha &gt; 0.70). However, the fear of negative peer evaluation subscale had relatively low reliability (Cronbach’s alpha = 0.57). As the output under “Reliability if an item is dropped” suggests, the alpha score would also not increase if an item was dropped from the scale.</p>
<p>As another example, consider the multi-item scale from the statistical ability questionnaire.</p>
<div class="sourceCode" id="cb723"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb723-1" title="1">test_data &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;https://raw.githubusercontent.com/IMSMWU/Teaching/master/MRDA2017/survey2017.dat&quot;</span>, </a>
<a class="sourceLine" id="cb723-2" title="2">    <span class="dt">sep =</span> <span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>, <span class="dt">header =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb723-3" title="3"><span class="kw">head</span>(test_data)</a></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["startdate"],"name":[1],"type":["fctr"],"align":["left"]},{"label":["enddate"],"name":[2],"type":["fctr"],"align":["left"]},{"label":["ipaddress"],"name":[3],"type":["fctr"],"align":["left"]},{"label":["duration"],"name":[4],"type":["int"],"align":["right"]},{"label":["experience"],"name":[5],"type":["int"],"align":["right"]},{"label":["theory_ht"],"name":[6],"type":["int"],"align":["right"]},{"label":["theory_anova"],"name":[7],"type":["int"],"align":["right"]},{"label":["theory_reg"],"name":[8],"type":["int"],"align":["right"]},{"label":["theory_fa"],"name":[9],"type":["int"],"align":["right"]},{"label":["pract_ht"],"name":[10],"type":["int"],"align":["right"]},{"label":["pract_anova"],"name":[11],"type":["int"],"align":["right"]},{"label":["pract_reg"],"name":[12],"type":["int"],"align":["right"]},{"label":["pract_fa"],"name":[13],"type":["int"],"align":["right"]},{"label":["overall_knowledge"],"name":[14],"type":["int"],"align":["right"]},{"label":["multi_1"],"name":[15],"type":["int"],"align":["right"]},{"label":["multi_2"],"name":[16],"type":["int"],"align":["right"]},{"label":["multi_3"],"name":[17],"type":["int"],"align":["right"]},{"label":["multi_4"],"name":[18],"type":["int"],"align":["right"]},{"label":["overall_100"],"name":[19],"type":["int"],"align":["right"]},{"label":["prior_SPSS"],"name":[20],"type":["int"],"align":["right"]},{"label":["prior_R"],"name":[21],"type":["int"],"align":["right"]},{"label":["prior_Stata"],"name":[22],"type":["int"],"align":["right"]},{"label":["prior_Excel"],"name":[23],"type":["int"],"align":["right"]},{"label":["prior_SAS"],"name":[24],"type":["int"],"align":["right"]},{"label":["software_preference"],"name":[25],"type":["int"],"align":["right"]},{"label":["future_importance"],"name":[26],"type":["int"],"align":["right"]},{"label":["gender"],"name":[27],"type":["int"],"align":["right"]},{"label":["country"],"name":[28],"type":["int"],"align":["right"]},{"label":["group"],"name":[29],"type":["int"],"align":["right"]},{"label":["lat"],"name":[30],"type":["dbl"],"align":["right"]},{"label":["long"],"name":[31],"type":["dbl"],"align":["right"]}],"data":[{"1":"04.09.2017 21:03","2":"04.09.2017 21:05","3":"188.23.190.194","4":"136","5":"3","6":"2","7":"2","8":"2","9":"2","10":"3","11":"3","12":"3","13":"3","14":"2","15":"2","16":"2","17":"4","18":"3","19":"25","20":"1","21":"1","22":"1","23":"5","24":"1","25":"5","26":"4","27":"1","28":"1","29":"1","30":"48.30000","31":"16.350006"},{"1":"04.09.2017 21:07","2":"04.09.2017 21:12","3":"93.10.250.2","4":"297","5":"3","6":"1","7":"3","8":"3","9":"3","10":"1","11":"1","12":"1","13":"1","14":"2","15":"2","16":"2","17":"2","18":"4","19":"15","20":"1","21":"1","22":"1","23":"4","24":"1","25":"5","26":"4","27":"2","28":"2","29":"1","30":"43.71671","31":"7.366699"},{"1":"04.09.2017 21:09","2":"04.09.2017 21:13","3":"91.0.18.86","4":"237","5":"3","6":"2","7":"3","8":"3","9":"1","10":"1","11":"1","12":"1","13":"1","14":"2","15":"3","16":"3","17":"3","18":"3","19":"30","20":"1","21":"1","22":"1","23":"2","24":"1","25":"5","26":"4","27":"2","28":"2","29":"2","30":"50.91330","31":"6.815201"},{"1":"04.09.2017 21:14","2":"04.09.2017 21:23","3":"37.116.255.55","4":"579","5":"1","6":"3","7":"3","8":"3","9":"2","10":"3","11":"3","12":"2","13":"2","14":"3","15":"4","16":"3","17":"3","18":"2","19":"65","20":"1","21":"1","22":"1","23":"3","24":"1","25":"3","26":"4","27":"2","28":"2","29":"1","30":"45.50000","31":"11.399994"},{"1":"04.09.2017 21:25","2":"04.09.2017 21:30","3":"178.165.131.208","4":"290","5":"1","6":"3","7":"3","8":"2","9":"2","10":"5","11":"5","12":"4","13":"3","14":"3","15":"4","16":"3","17":"4","18":"2","19":"70","20":"3","21":"1","22":"1","23":"3","24":"1","25":"1","26":"4","27":"2","28":"1","29":"1","30":"48.20869","31":"16.240707"},{"1":"04.09.2017 21:42","2":"04.09.2017 21:46","3":"212.28.68.81","4":"205","5":"3","6":"2","7":"3","8":"3","9":"1","10":"1","11":"1","12":"1","13":"1","14":"1","15":"3","16":"3","17":"2","18":"4","19":"0","20":"1","21":"1","22":"1","23":"1","24":"1","25":"5","26":"4","27":"2","28":"2","29":"1","30":"47.00560","31":"28.857498"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>The four variables “multi_1” - “multi_4” represent the multi-item scales. We can test the reliability of the scale using the <code>alpha()</code> function (item 4 was reverse coded, hence the “-1” in the <code>keys</code> vector):</p>
<div class="sourceCode" id="cb724"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb724-1" title="1">psych<span class="op">::</span><span class="kw">alpha</span>(test_data[, <span class="kw">c</span>(<span class="st">&quot;multi_1&quot;</span>, <span class="st">&quot;multi_2&quot;</span>, <span class="st">&quot;multi_3&quot;</span>, </a>
<a class="sourceLine" id="cb724-2" title="2">    <span class="st">&quot;multi_4&quot;</span>)], <span class="dt">keys =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">-1</span>))</a></code></pre></div>
<pre><code>## 
## Reliability analysis   
## Call: psych::alpha(x = test_data[, c(&quot;multi_1&quot;, &quot;multi_2&quot;, &quot;multi_3&quot;, 
##     &quot;multi_4&quot;)], keys = c(1, 1, 1, -1))
## 
##   raw_alpha std.alpha G6(smc) average_r  S/N  ase mean   sd median_r
##       0.22      0.27    0.71     0.084 0.37 0.14  2.8 0.58     0.05
## 
##  lower alpha upper     95% confidence boundaries
## -0.06 0.22 0.51 
## 
##  Reliability if an item is dropped:
##         raw_alpha std.alpha G6(smc) average_r   S/N alpha se  var.r med.r
## multi_1     -0.69     -0.61    0.39     -0.14 -0.38    0.377 0.6413 -0.61
## multi_2     -0.85     -0.77    0.23     -0.17 -0.43    0.412 0.5494 -0.59
## multi_3     -0.57     -0.47    0.49     -0.12 -0.32    0.358 0.6858 -0.59
## multi_4      0.91      0.91    0.88      0.77  9.95    0.022 0.0058  0.78
## 
##  Item statistics 
##          n raw.r std.r r.cor r.drop mean  sd
## multi_1 55  0.86  0.87  0.87   0.62  2.7 1.0
## multi_2 55  0.89  0.90  0.95   0.70  2.6 1.0
## multi_3 55  0.83  0.83  0.79   0.54  2.5 1.1
## multi_4 55 -0.34 -0.36 -0.73  -0.65  3.2 1.1
## 
## Non missing response frequency for each item
##            1    2    3    4    5 miss
## multi_1 0.11 0.36 0.25 0.25 0.02    0
## multi_2 0.11 0.42 0.25 0.18 0.04    0
## multi_3 0.18 0.38 0.22 0.20 0.02    0
## multi_4 0.04 0.31 0.16 0.40 0.09    0</code></pre>
<p>Since the scale exhibits a sufficient degree of reliability, we can compute the new variable as the average score on these items. However, before doing this, we need to recode the reverse coded variable in the appropriate way. It is easy to recode the reverse coded item to be in line with the remaining items on the dimension using the <code>recode()</code> function from the <code>car</code> package.</p>
<div class="sourceCode" id="cb726"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb726-1" title="1"><span class="kw">library</span>(car)</a>
<a class="sourceLine" id="cb726-2" title="2">test_data<span class="op">$</span>multi_<span class="dv">4</span>_rec =<span class="st"> </span><span class="kw">recode</span>(test_data<span class="op">$</span>multi_<span class="dv">4</span>, <span class="st">&quot;1=5; 2=4; 3=3; 4=2; 5=1&quot;</span>)</a></code></pre></div>
<p>Now we can compute the new variable as the average score of the four items:</p>
<div class="sourceCode" id="cb727"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb727-1" title="1"><span class="kw">library</span>(car)</a>
<a class="sourceLine" id="cb727-2" title="2">test_data<span class="op">$</span>new_variable =<span class="st"> </span>(test_data<span class="op">$</span>multi_<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>test_data<span class="op">$</span>multi_<span class="dv">2</span> <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb727-3" title="3"><span class="st">    </span>test_data<span class="op">$</span>multi_<span class="dv">3</span> <span class="op">+</span><span class="st"> </span>test_data<span class="op">$</span>multi_<span class="dv">4</span>_rec)<span class="op">/</span><span class="dv">4</span></a></code></pre></div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="appendix.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
