<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Hypothesis testing | Marketing Research Design &amp; Analysis 2020</title>
  <meta name="description" content="An Introduction to Statistics Using R" />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Hypothesis testing | Marketing Research Design &amp; Analysis 2020" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An Introduction to Statistics Using R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Hypothesis testing | Marketing Research Design &amp; Analysis 2020" />
  
  <meta name="twitter:description" content="An Introduction to Statistics Using R" />
  

<meta name="author" content="Mirza Mujanovic - 01553283" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="prev" href="introduction-to-statistical-inference.html"/>
<link rel="next" href="regression.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">MRDA 2019</a></strong></li>
<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#main-reference"><i class="fa fa-check"></i>Main reference</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#further-readings"><i class="fa fa-check"></i>Further readings</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#finding-your-way-to-r"><i class="fa fa-check"></i>Finding Your Way To R</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#datacamp"><i class="fa fa-check"></i>DataCamp</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#other-web-resources"><i class="fa fa-check"></i>Other web-resources</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting started</a><ul>
<li class="chapter" data-level="1.1" data-path="getting-started.html"><a href="getting-started.html#how-to-download-and-install-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> How to download and install R and RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="getting-started.html"><a href="getting-started.html#getting-help"><i class="fa fa-check"></i><b>1.2</b> Getting help</a></li>
<li class="chapter" data-level="1.3" data-path="getting-started.html"><a href="getting-started.html#functions"><i class="fa fa-check"></i><b>1.3</b> Functions</a></li>
<li class="chapter" data-level="1.4" data-path="getting-started.html"><a href="getting-started.html#packages"><i class="fa fa-check"></i><b>1.4</b> Packages</a></li>
<li class="chapter" data-level="1.5" data-path="getting-started.html"><a href="getting-started.html#a-typical-r-session"><i class="fa fa-check"></i><b>1.5</b> A typical R session</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-handling.html"><a href="data-handling.html"><i class="fa fa-check"></i><b>2</b> Data handling</a><ul>
<li class="chapter" data-level="2.1" data-path="data-handling.html"><a href="data-handling.html#basic-data-handling"><i class="fa fa-check"></i><b>2.1</b> Basic data handling</a><ul>
<li class="chapter" data-level="2.1.1" data-path="data-handling.html"><a href="data-handling.html#creating-objects"><i class="fa fa-check"></i><b>2.1.1</b> Creating objects</a></li>
<li class="chapter" data-level="2.1.2" data-path="data-handling.html"><a href="data-handling.html#data-types"><i class="fa fa-check"></i><b>2.1.2</b> Data types</a></li>
<li class="chapter" data-level="2.1.3" data-path="data-handling.html"><a href="data-handling.html#data-structures"><i class="fa fa-check"></i><b>2.1.3</b> Data structures</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html"><a href="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html"><i class="fa fa-check"></i><b>3</b> Selects all columns from top10_track_explicit to top_10_track_release_date</a><ul>
<li class="chapter" data-level="3.1" data-path="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html"><a href="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html#advanced-data-handling"><i class="fa fa-check"></i><b>3.1</b> Advanced data handling</a><ul>
<li class="chapter" data-level="3.1.1" data-path="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html"><a href="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html#the-dplyr-package"><i class="fa fa-check"></i><b>3.1.1</b> The dplyr package</a></li>
<li class="chapter" data-level="3.1.2" data-path="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html"><a href="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html#dealing-with-strings"><i class="fa fa-check"></i><b>3.1.2</b> Dealing with strings</a></li>
<li class="chapter" data-level="3.1.3" data-path="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html"><a href="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html#case-study"><i class="fa fa-check"></i><b>3.1.3</b> Case study</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html"><a href="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html#data-import-and-export"><i class="fa fa-check"></i><b>3.2</b> Data import and export</a><ul>
<li class="chapter" data-level="3.2.1" data-path="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html"><a href="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html#getting-data-for-this-course"><i class="fa fa-check"></i><b>3.2.1</b> Getting data for this course</a></li>
<li class="chapter" data-level="3.2.2" data-path="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html"><a href="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html#import-data-created-by-other-software-packages"><i class="fa fa-check"></i><b>3.2.2</b> Import data created by other software packages</a></li>
<li class="chapter" data-level="3.2.3" data-path="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html"><a href="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html#export-data"><i class="fa fa-check"></i><b>3.2.3</b> Export data</a></li>
<li class="chapter" data-level="3.2.4" data-path="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html"><a href="selects-all-columns-from-top10-track-explicit-to-top-10-track-release-date.html#import-data-from-the-web"><i class="fa fa-check"></i><b>3.2.4</b> Import data from the Web</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="summarizing-data.html"><a href="summarizing-data.html"><i class="fa fa-check"></i><b>4</b> Summarizing data</a><ul>
<li class="chapter" data-level="4.1" data-path="summarizing-data.html"><a href="summarizing-data.html#summary-statistics"><i class="fa fa-check"></i><b>4.1</b> Summary statistics</a><ul>
<li class="chapter" data-level="4.1.1" data-path="summarizing-data.html"><a href="summarizing-data.html#categorical-variables"><i class="fa fa-check"></i><b>4.1.1</b> Categorical variables</a></li>
<li class="chapter" data-level="4.1.2" data-path="summarizing-data.html"><a href="summarizing-data.html#continuous-variables"><i class="fa fa-check"></i><b>4.1.2</b> Continuous variables</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="summarizing-data.html"><a href="summarizing-data.html#data-visualization"><i class="fa fa-check"></i><b>4.2</b> Data visualization</a><ul>
<li class="chapter" data-level="4.2.1" data-path="summarizing-data.html"><a href="summarizing-data.html#categorical-variables-1"><i class="fa fa-check"></i><b>4.2.1</b> Categorical variables</a></li>
<li class="chapter" data-level="4.2.2" data-path="summarizing-data.html"><a href="summarizing-data.html#continuous-variables-1"><i class="fa fa-check"></i><b>4.2.2</b> Continuous variables</a></li>
<li class="chapter" data-level="4.2.3" data-path="summarizing-data.html"><a href="summarizing-data.html#saving-plots"><i class="fa fa-check"></i><b>4.2.3</b> Saving plots</a></li>
<li class="chapter" data-level="4.2.4" data-path="summarizing-data.html"><a href="summarizing-data.html#additional-options"><i class="fa fa-check"></i><b>4.2.4</b> Additional options</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="summarizing-data.html"><a href="summarizing-data.html#writing-reports-using-r-markdown"><i class="fa fa-check"></i><b>4.3</b> Writing reports using R-Markdown</a><ul>
<li class="chapter" data-level="4.3.1" data-path="summarizing-data.html"><a href="summarizing-data.html#creating-a-new-r-markdown-document"><i class="fa fa-check"></i><b>4.3.1</b> Creating a new R-Markdown document</a></li>
<li class="chapter" data-level="4.3.2" data-path="summarizing-data.html"><a href="summarizing-data.html#text-and-equations"><i class="fa fa-check"></i><b>4.3.2</b> Text and Equations</a></li>
<li class="chapter" data-level="4.3.3" data-path="summarizing-data.html"><a href="summarizing-data.html#r-code"><i class="fa fa-check"></i><b>4.3.3</b> R-Code</a></li>
<li class="chapter" data-level="4.3.4" data-path="summarizing-data.html"><a href="summarizing-data.html#latex-math"><i class="fa fa-check"></i><b>4.3.4</b> LaTeX Math</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html"><i class="fa fa-check"></i><b>5</b> Introduction to Statistical Inference</a><ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#if-we-knew-it-all"><i class="fa fa-check"></i><b>5.1</b> If we knew it all</a><ul>
<li class="chapter" data-level="5.1.1" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#sampling-from-a-known-population"><i class="fa fa-check"></i><b>5.1.1</b> Sampling from a known population</a></li>
<li class="chapter" data-level="5.1.2" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>5.1.2</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>5.2</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="5.3" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#using-what-we-actually-know"><i class="fa fa-check"></i><b>5.3</b> Using what we actually know</a><ul>
<li class="chapter" data-level="5.3.1" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#confidence-intervals-for-the-sample-mean"><i class="fa fa-check"></i><b>5.3.1</b> Confidence Intervals for the Sample Mean</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="introduction-to-statistical-inference.html"><a href="introduction-to-statistical-inference.html#summary"><i class="fa fa-check"></i><b>5.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>6</b> Hypothesis testing</a><ul>
<li class="chapter" data-level="6.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction"><i class="fa fa-check"></i><b>6.1</b> Introduction</a><ul>
<li class="chapter" data-level="6.1.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#the-null-hypothesis"><i class="fa fa-check"></i><b>6.1.1</b> The null hypothesis</a></li>
<li class="chapter" data-level="6.1.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#statistical-inference-on-a-sample"><i class="fa fa-check"></i><b>6.1.2</b> Statistical inference on a sample</a></li>
<li class="chapter" data-level="6.1.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#choosing-the-right-test"><i class="fa fa-check"></i><b>6.1.3</b> Choosing the right test</a></li>
<li class="chapter" data-level="6.1.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#summary-1"><i class="fa fa-check"></i><b>6.1.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-sample-t-test"><i class="fa fa-check"></i><b>6.2</b> One sample t-test</a></li>
<li class="chapter" data-level="6.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#comparing-two-means"><i class="fa fa-check"></i><b>6.3</b> Comparing two means</a><ul>
<li class="chapter" data-level="6.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#independent-means-t-test"><i class="fa fa-check"></i><b>6.3.1</b> Independent-means t-test</a></li>
<li class="chapter" data-level="6.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#dependent-means-t-test"><i class="fa fa-check"></i><b>6.3.2</b> Dependent-means t-test</a></li>
<li class="chapter" data-level="6.3.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#further-considerations"><i class="fa fa-check"></i><b>6.3.3</b> Further considerations</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#comparing-several-means"><i class="fa fa-check"></i><b>6.4</b> Comparing several means</a><ul>
<li class="chapter" data-level="6.4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction-1"><i class="fa fa-check"></i><b>6.4.1</b> Introduction</a></li>
<li class="chapter" data-level="6.4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#decomposing-variance"><i class="fa fa-check"></i><b>6.4.2</b> Decomposing variance</a></li>
<li class="chapter" data-level="6.4.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-way-anova"><i class="fa fa-check"></i><b>6.4.3</b> One-way ANOVA</a></li>
<li class="chapter" data-level="6.4.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#summary-3"><i class="fa fa-check"></i><b>6.4.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#non-parametric-tests"><i class="fa fa-check"></i><b>6.5</b> Non-parametric tests</a><ul>
<li class="chapter" data-level="6.5.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#mann-whitney-u-test-a.k.a.-wilcoxon-rank-sum-test"><i class="fa fa-check"></i><b>6.5.1</b> Mann-Whitney U Test (a.k.a. Wilcoxon rank-sum test)</a></li>
<li class="chapter" data-level="6.5.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>6.5.2</b> Wilcoxon signed-rank test</a></li>
<li class="chapter" data-level="6.5.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#kruskal-wallis-test"><i class="fa fa-check"></i><b>6.5.3</b> Kruskal-Wallis test</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#categorical-data"><i class="fa fa-check"></i><b>6.6</b> Categorical data</a><ul>
<li class="chapter" data-level="6.6.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#confidence-intervals-for-proportions"><i class="fa fa-check"></i><b>6.6.1</b> Confidence intervals for proportions</a></li>
<li class="chapter" data-level="6.6.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#chi-square-test"><i class="fa fa-check"></i><b>6.6.2</b> Chi-square test</a></li>
<li class="chapter" data-level="6.6.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#sample-size-1"><i class="fa fa-check"></i><b>6.6.3</b> Sample size</a></li>
<li class="chapter" data-level="6.6.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#summary-4"><i class="fa fa-check"></i><b>6.6.4</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>7</b> Regression</a><ul>
<li class="chapter" data-level="7.1" data-path="regression.html"><a href="regression.html#correlation"><i class="fa fa-check"></i><b>7.1</b> Correlation</a><ul>
<li class="chapter" data-level="7.1.1" data-path="regression.html"><a href="regression.html#correlation-coefficient"><i class="fa fa-check"></i><b>7.1.1</b> Correlation coefficient</a></li>
<li class="chapter" data-level="7.1.2" data-path="regression.html"><a href="regression.html#significance-testing"><i class="fa fa-check"></i><b>7.1.2</b> Significance testing</a></li>
<li class="chapter" data-level="7.1.3" data-path="regression.html"><a href="regression.html#summary-5"><i class="fa fa-check"></i><b>7.1.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="regression.html"><a href="regression.html#regression-1"><i class="fa fa-check"></i><b>7.2</b> Regression</a><ul>
<li class="chapter" data-level="7.2.1" data-path="regression.html"><a href="regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>7.2.1</b> Simple linear regression</a></li>
<li class="chapter" data-level="7.2.2" data-path="regression.html"><a href="regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>7.2.2</b> Multiple linear regression</a></li>
<li class="chapter" data-level="7.2.3" data-path="regression.html"><a href="regression.html#estimation-of-the-regression-plane"><i class="fa fa-check"></i><b>7.2.3</b> Estimation of the regression plane</a></li>
<li class="chapter" data-level="7.2.4" data-path="regression.html"><a href="regression.html#calculate-z-on-a-grid-of-x-y-values"><i class="fa fa-check"></i><b>7.2.4</b> Calculate z on a grid of x-y values</a></li>
<li class="chapter" data-level="7.2.5" data-path="regression.html"><a href="regression.html#summary-6"><i class="fa fa-check"></i><b>7.2.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="regression.html"><a href="regression.html#potential-problems"><i class="fa fa-check"></i><b>7.3</b> Potential problems</a><ul>
<li class="chapter" data-level="7.3.1" data-path="regression.html"><a href="regression.html#outliers"><i class="fa fa-check"></i><b>7.3.1</b> Outliers</a></li>
<li class="chapter" data-level="7.3.2" data-path="regression.html"><a href="regression.html#influential-observations"><i class="fa fa-check"></i><b>7.3.2</b> Influential observations</a></li>
<li class="chapter" data-level="7.3.3" data-path="regression.html"><a href="regression.html#non-linearity"><i class="fa fa-check"></i><b>7.3.3</b> Non-linearity</a></li>
<li class="chapter" data-level="7.3.4" data-path="regression.html"><a href="regression.html#non-constant-error-variance"><i class="fa fa-check"></i><b>7.3.4</b> Non-constant error variance</a></li>
<li class="chapter" data-level="7.3.5" data-path="regression.html"><a href="regression.html#non-normally-distributed-errors"><i class="fa fa-check"></i><b>7.3.5</b> Non-normally distributed errors</a></li>
<li class="chapter" data-level="7.3.6" data-path="regression.html"><a href="regression.html#correlation-of-errors"><i class="fa fa-check"></i><b>7.3.6</b> Correlation of errors</a></li>
<li class="chapter" data-level="7.3.7" data-path="regression.html"><a href="regression.html#collinearity"><i class="fa fa-check"></i><b>7.3.7</b> Collinearity</a></li>
<li class="chapter" data-level="7.3.8" data-path="regression.html"><a href="regression.html#omitted-variables"><i class="fa fa-check"></i><b>7.3.8</b> Omitted Variables</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="regression.html"><a href="regression.html#categorical-predictors"><i class="fa fa-check"></i><b>7.4</b> Categorical predictors</a><ul>
<li class="chapter" data-level="7.4.1" data-path="regression.html"><a href="regression.html#two-categories"><i class="fa fa-check"></i><b>7.4.1</b> Two categories</a></li>
<li class="chapter" data-level="7.4.2" data-path="regression.html"><a href="regression.html#more-than-two-categories"><i class="fa fa-check"></i><b>7.4.2</b> More than two categories</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="regression.html"><a href="regression.html#extensions-of-the-linear-model"><i class="fa fa-check"></i><b>7.5</b> Extensions of the linear model</a><ul>
<li class="chapter" data-level="7.5.1" data-path="regression.html"><a href="regression.html#interaction-effects"><i class="fa fa-check"></i><b>7.5.1</b> Interaction effects</a></li>
<li class="chapter" data-level="7.5.2" data-path="regression.html"><a href="regression.html#non-linear-relationships"><i class="fa fa-check"></i><b>7.5.2</b> Non-linear relationships</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="inspect-data.html"><a href="inspect-data.html"><i class="fa fa-check"></i><b>8</b> Inspect data</a><ul>
<li class="chapter" data-level="8.1" data-path="inspect-data.html"><a href="inspect-data.html#logistic-regression"><i class="fa fa-check"></i><b>8.1</b> Logistic regression</a><ul>
<li class="chapter" data-level="8.1.1" data-path="inspect-data.html"><a href="inspect-data.html#motivation-and-intuition"><i class="fa fa-check"></i><b>8.1.1</b> Motivation and intuition</a></li>
<li class="chapter" data-level="8.1.2" data-path="inspect-data.html"><a href="inspect-data.html#technical-details-of-the-model"><i class="fa fa-check"></i><b>8.1.2</b> Technical details of the model</a></li>
<li class="chapter" data-level="8.1.3" data-path="inspect-data.html"><a href="inspect-data.html#estimation-in-r"><i class="fa fa-check"></i><b>8.1.3</b> Estimation in R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html"><i class="fa fa-check"></i><b>9</b> Exploratory factor analysis</a><ul>
<li class="chapter" data-level="9.1" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#introduction-2"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#steps-in-factor-analysis"><i class="fa fa-check"></i><b>9.2</b> Steps in factor analysis</a><ul>
<li class="chapter" data-level="9.2.1" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#are-the-assumptions-satisfied"><i class="fa fa-check"></i><b>9.2.1</b> Are the assumptions satisfied?</a></li>
<li class="chapter" data-level="9.2.2" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#deriving-factors"><i class="fa fa-check"></i><b>9.2.2</b> Deriving factors</a></li>
<li class="chapter" data-level="9.2.3" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#factor-interpretation"><i class="fa fa-check"></i><b>9.2.3</b> Factor interpretation</a></li>
<li class="chapter" data-level="9.2.4" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#creating-new-variables"><i class="fa fa-check"></i><b>9.2.4</b> Creating new variables</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#reliability-analysis"><i class="fa fa-check"></i><b>9.3</b> Reliability analysis</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i><b>10</b> Appendix</a><ul>
<li class="chapter" data-level="10.1" data-path="appendix.html"><a href="appendix.html#random-variables-probability-distributions"><i class="fa fa-check"></i><b>10.1</b> Random Variables &amp; Probability Distributions</a><ul>
<li class="chapter" data-level="10.1.1" data-path="appendix.html"><a href="appendix.html#random-variables"><i class="fa fa-check"></i><b>10.1.1</b> Random variables</a></li>
<li class="chapter" data-level="10.1.2" data-path="appendix.html"><a href="appendix.html#probability-distributions"><i class="fa fa-check"></i><b>10.1.2</b> Probability Distributions</a></li>
<li class="chapter" data-level="10.1.3" data-path="appendix.html"><a href="appendix.html#appendix-1"><i class="fa fa-check"></i><b>10.1.3</b> Appendix</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="this-is-the-same-as-avplot.html"><a href="this-is-the-same-as-avplot.html"><i class="fa fa-check"></i><b>11</b> This is the same as avPlot</a><ul>
<li class="chapter" data-level="11.1" data-path="this-is-the-same-as-avplot.html"><a href="this-is-the-same-as-avplot.html#regression-2"><i class="fa fa-check"></i><b>11.1</b> Regression</a><ul>
<li class="chapter" data-level="11.1.1" data-path="this-is-the-same-as-avplot.html"><a href="this-is-the-same-as-avplot.html#linear-regression"><i class="fa fa-check"></i><b>11.1.1</b> Linear regression</a></li>
<li class="chapter" data-level="11.1.2" data-path="this-is-the-same-as-avplot.html"><a href="this-is-the-same-as-avplot.html#logistic-regression-1"><i class="fa fa-check"></i><b>11.1.2</b> Logistic regression</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="assignments.html"><a href="assignments.html"><i class="fa fa-check"></i><b>12</b> Assignments</a><ul>
<li class="chapter" data-level="12.1" data-path="assignments.html"><a href="assignments.html#assignment-2-hypothesis-testing"><i class="fa fa-check"></i><b>12.1</b> Assignment 2 (Hypothesis Testing)</a></li>
<li class="chapter" data-level="12.2" data-path="assignments.html"><a href="assignments.html#assignment-3-hypothesis-testing-2"><i class="fa fa-check"></i><b>12.2</b> Assignment 3 (Hypothesis Testing 2)</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="questionnaire-design.html"><a href="questionnaire-design.html"><i class="fa fa-check"></i><b>13</b> Questionnaire design</a><ul>
<li class="chapter" data-level="13.1" data-path="questionnaire-design.html"><a href="questionnaire-design.html#questionnaire-design-process"><i class="fa fa-check"></i><b>13.1</b> Questionnaire design process</a><ul>
<li class="chapter" data-level="13.1.1" data-path="questionnaire-design.html"><a href="questionnaire-design.html#specification-of-the-information-needed"><i class="fa fa-check"></i><b>13.1.1</b> Specification of the information needed</a></li>
<li class="chapter" data-level="13.1.2" data-path="questionnaire-design.html"><a href="questionnaire-design.html#specify-the-interviewing-method"><i class="fa fa-check"></i><b>13.1.2</b> Specify the interviewing method</a></li>
<li class="chapter" data-level="13.1.3" data-path="questionnaire-design.html"><a href="questionnaire-design.html#determine-the-content-of-questions"><i class="fa fa-check"></i><b>13.1.3</b> Determine the content of questions</a></li>
<li class="chapter" data-level="13.1.4" data-path="questionnaire-design.html"><a href="questionnaire-design.html#inability-and-unwillingness-to-answer"><i class="fa fa-check"></i><b>13.1.4</b> Inability and unwillingness to answer</a></li>
<li class="chapter" data-level="13.1.5" data-path="questionnaire-design.html"><a href="questionnaire-design.html#decide-on-measurement-scales-and-scaling-techniques"><i class="fa fa-check"></i><b>13.1.5</b> Decide on measurement scales and scaling techniques</a></li>
<li class="chapter" data-level="13.1.6" data-path="questionnaire-design.html"><a href="questionnaire-design.html#questionnaire-structure"><i class="fa fa-check"></i><b>13.1.6</b> Questionnaire structure</a></li>
<li class="chapter" data-level="13.1.7" data-path="questionnaire-design.html"><a href="questionnaire-design.html#question-wording"><i class="fa fa-check"></i><b>13.1.7</b> Question wording</a></li>
<li class="chapter" data-level="13.1.8" data-path="questionnaire-design.html"><a href="questionnaire-design.html#choose-adequate-order"><i class="fa fa-check"></i><b>13.1.8</b> Choose adequate order</a></li>
<li class="chapter" data-level="13.1.9" data-path="questionnaire-design.html"><a href="questionnaire-design.html#test-your-questionnaire"><i class="fa fa-check"></i><b>13.1.9</b> Test your questionnaire</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="questionnaire-design.html"><a href="questionnaire-design.html#questionnaire-in-qualtrics"><i class="fa fa-check"></i><b>13.2</b> Questionnaire in Qualtrics</a></li>
<li class="chapter" data-level="13.3" data-path="questionnaire-design.html"><a href="questionnaire-design.html#question-types-and-data-analysis"><i class="fa fa-check"></i><b>13.3</b> Question-Types-and-Data-Analysis</a><ul>
<li class="chapter" data-level="13.3.1" data-path="questionnaire-design.html"><a href="questionnaire-design.html#multiple-choice-with-a-single-answer"><i class="fa fa-check"></i><b>13.3.1</b> Multiple choice with a single answer</a></li>
<li class="chapter" data-level="13.3.2" data-path="questionnaire-design.html"><a href="questionnaire-design.html#multiple-choice-with-multiple-answers"><i class="fa fa-check"></i><b>13.3.2</b> Multiple choice with multiple answers</a></li>
<li class="chapter" data-level="13.3.3" data-path="questionnaire-design.html"><a href="questionnaire-design.html#rank-order-question"><i class="fa fa-check"></i><b>13.3.3</b> Rank order question</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="questionnaire-design.html"><a href="questionnaire-design.html#question-types-and-data-analysis-1"><i class="fa fa-check"></i><b>13.4</b> Question-Types-and-Data-Analysis</a><ul>
<li class="chapter" data-level="13.4.1" data-path="questionnaire-design.html"><a href="questionnaire-design.html#multiple-choice-with-a-single-answer-1"><i class="fa fa-check"></i><b>13.4.1</b> Multiple choice with a single answer</a></li>
<li class="chapter" data-level="13.4.2" data-path="questionnaire-design.html"><a href="questionnaire-design.html#multiple-choice-with-multiple-answers-1"><i class="fa fa-check"></i><b>13.4.2</b> Multiple choice with multiple answers</a></li>
<li class="chapter" data-level="13.4.3" data-path="questionnaire-design.html"><a href="questionnaire-design.html#rank-order-question-1"><i class="fa fa-check"></i><b>13.4.3</b> Rank order question</a></li>
<li class="chapter" data-level="13.4.4" data-path="questionnaire-design.html"><a href="questionnaire-design.html#constant-sum-question"><i class="fa fa-check"></i><b>13.4.4</b> Constant Sum question</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="questionnaire-design.html"><a href="questionnaire-design.html#learning"><i class="fa fa-check"></i><b>13.5</b> Learning</a><ul>
<li class="chapter" data-level="13.5.1" data-path="questionnaire-design.html"><a href="questionnaire-design.html#dataset-presentation"><i class="fa fa-check"></i><b>13.5.1</b> Dataset presentation</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Marketing Research Design &amp; Analysis 2020</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="hypothesis-testing" class="section level1">
<h1><span class="header-section-number">6</span> Hypothesis testing</h1>
<p>This chapter is primarily based on Field, A., Miles J., &amp; Field, Z. (2012): Discovering Statistics Using R. Sage Publications, <strong>chapters 5, 9, 15, 18</strong>.</p>
<p><a href="./Code/07-hypothesis_testing%20(2).R">You can download the corresponding R-Code here</a></p>
<div id="introduction" class="section level2">
<h2><span class="header-section-number">6.1</span> Introduction</h2>
<p>We test hypotheses because we are confined to taking samples – we rarely work with the entire population. In the previous chapter, we introduced the standard error (i.e., the standard deviation of a large number of hypothetical samples) as an estimate of how well a particular sample represents the population. We also saw how we can construct confidence intervals around the sample mean <span class="math inline">\(\bar x\)</span> by computing <span class="math inline">\(SE_{\bar x}\)</span> as an estimate of <span class="math inline">\(\sigma_{\bar x}\)</span> using <span class="math inline">\(s\)</span> as an estimate of <span class="math inline">\(\sigma\)</span> and calculating the 95% CI as <span class="math inline">\(\bar x \pm 1.96 * SE_{\bar x}\)</span>. Although we do not know the true population mean (<span class="math inline">\(\mu\)</span>), we might have an hypothesis about it and this would tell us how the corresponding sampling distribution looks like. Based on the sampling distribution of the hypothesized population mean, we could then determine the probability of a given sample <strong>assuming that the hypothesis is true</strong>.</p>
<p>Let us again begin by assuming we know the entire population using the example of music listening times among students from the previous example. As a reminder, the following plot shows the distribution of music listening times in the population of WU students.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb1-2" title="2"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb1-3" title="3"><span class="kw">library</span>(latex2exp)</a>
<a class="sourceLine" id="cb1-4" title="4"><span class="kw">set.seed</span>(<span class="dv">321</span>)</a>
<a class="sourceLine" id="cb1-5" title="5">hours &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="dv">2</span>, <span class="dt">scale =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb1-6" title="6"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(hours)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> hours), </a>
<a class="sourceLine" id="cb1-7" title="7">    <span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="kw">mean</span>(hours), </a>
<a class="sourceLine" id="cb1-8" title="8">    <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Histogram of listening times&quot;</span>, </a>
<a class="sourceLine" id="cb1-9" title="9">    <span class="dt">subtitle =</span> <span class="kw">TeX</span>(<span class="kw">sprintf</span>(<span class="st">&quot;Population mean ($</span><span class="ch">\\</span><span class="st">mu$) = %.2f; population standard deviation ($</span><span class="ch">\\</span><span class="st">sigma$) = %.2f&quot;</span>, </a>
<a class="sourceLine" id="cb1-10" title="10">        <span class="kw">round</span>(<span class="kw">mean</span>(hours), <span class="dv">2</span>), <span class="kw">round</span>(<span class="kw">sd</span>(hours), <span class="dv">2</span>))), </a>
<a class="sourceLine" id="cb1-11" title="11">    <span class="dt">y =</span> <span class="st">&quot;Number of students&quot;</span>, <span class="dt">x =</span> <span class="st">&quot;Hours&quot;</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>In this example, the population mean (<span class="math inline">\(\mu\)</span>) is equal to 19.98, and the population standard deviation <span class="math inline">\(\sigma\)</span> is equal to 14.15.</p>
<div id="the-null-hypothesis" class="section level3">
<h3><span class="header-section-number">6.1.1</span> The null hypothesis</h3>
<p>Let us assume that we were planning to take a random sample of 50 students from this population and our hypothesis was that the mean listening time is equal to some specific value <span class="math inline">\(\mu_0\)</span>, say <span class="math inline">\(10\)</span>. This would be our <strong>null hypothesis</strong>. The null hypothesis refers to the statement that is being tested and is usually a statement of the status quo, one of no difference or no effect. In our example, the null hypothesis would state that there is no difference between the true population mean <span class="math inline">\(\mu\)</span> and the hypothesized value <span class="math inline">\(\mu_0\)</span> (in our example <span class="math inline">\(10\)</span>), which can be expressed as follows:</p>
<p><span class="math display">\[
H_0: \mu = \mu_0
\]</span>
When conducting research, we are usually interested in providing evidence against the null hypothesis. If we then observe sufficient evidence against it and our estimate is said to be significant. If the null hypothesis is rejected, this is taken as support for the <strong>alternative hypothesis</strong>. The alternative hypothesis assumes that some difference exists, which can be expressed as follows:</p>
<p><span class="math display">\[
H_1: \mu \neq \mu_0
\]</span>
Accepting the alternative hypothesis in turn will often lead to changes in opinions or actions. Note that while the null hypothesis may be rejected, it can never be accepted based on a single test. If we fail to reject the null hypothesis, it means that we simply haven’t collected enough evidence against the null hypothesis to disprove it. In classical hypothesis testing, there is no way to determine whether the null hypothesis is true. <strong>Hypothesis testing</strong> provides a means to quantify to what extent the data from our sample is in line with the null hypothesis.</p>
<p>In order to quantify the concept of “sufficient evidence” we look at the theoretical distribution of the sample means given our null hypothesis and the sample standard error. Using the available information we can infer the sampling distribution for our null hypothesis. Recall that the standard deviation of the sampling distribution (i.e., the standard error of the mean) is given by <span class="math inline">\(\sigma_{\bar x}={\sigma \over \sqrt{n}}\)</span>, and thus can be computed as follows:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1">mean_pop &lt;-<span class="st"> </span><span class="kw">mean</span>(hours)</a>
<a class="sourceLine" id="cb2-2" title="2">sigma &lt;-<span class="st"> </span><span class="kw">sd</span>(hours)  <span class="co">#population standard deviation</span></a>
<a class="sourceLine" id="cb2-3" title="3">n &lt;-<span class="st"> </span><span class="dv">50</span>  <span class="co">#sample size</span></a>
<a class="sourceLine" id="cb2-4" title="4">standard_error &lt;-<span class="st"> </span>sigma<span class="op">/</span><span class="kw">sqrt</span>(n)  <span class="co">#standard error</span></a>
<a class="sourceLine" id="cb2-5" title="5">standard_error</a></code></pre></div>
<pre><code>## [1] 2.001639</code></pre>
<p>Since we know from the central limit theorem that the sampling distribution is normal for large enough samples, we can now visualize the expected sampling distribution <strong>if our null hypothesis was in fact true</strong> (i.e., if the was no difference between the true population mean and the hypothesized mean of 10).</p>
<p><img src="_main_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>We also know that 95% of the probability is within 1.96 standard deviations from the mean. Values higher than that are rather unlikely, if our hypothesis about the population mean was indeed true. This is shown by the shaded area, also known as the “rejection region”. To test our hypothesis that the population mean is equal to <span class="math inline">\(10\)</span>, let us take a random sample from the population.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1"><span class="kw">set.seed</span>(<span class="dv">12567</span>)</a>
<a class="sourceLine" id="cb4-2" title="2">H_<span class="dv">0</span> &lt;-<span class="st"> </span><span class="dv">10</span></a>
<a class="sourceLine" id="cb4-3" title="3">student_sample &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">25000</span>, <span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb4-4" title="4">student_sample &lt;-<span class="st"> </span>hours[student_sample]</a>
<a class="sourceLine" id="cb4-5" title="5">mean_sample &lt;-<span class="st"> </span><span class="kw">mean</span>(student_sample)</a>
<a class="sourceLine" id="cb4-6" title="6"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(student_sample)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> student_sample), </a>
<a class="sourceLine" id="cb4-7" title="7">    <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">bins =</span> <span class="dv">20</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb4-8" title="8"><span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="kw">mean</span>(student_sample), <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, </a>
<a class="sourceLine" id="cb4-9" title="9">        <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="kw">TeX</span>(<span class="kw">sprintf</span>(<span class="st">&quot;Distribution of values in the sample ($n =$ %.0f, $</span><span class="ch">\\</span><span class="st">bar{x] = $ %.2f, s = %.2f)&quot;</span>, </a>
<a class="sourceLine" id="cb4-10" title="10">    n, <span class="kw">mean</span>(student_sample), <span class="kw">sd</span>(student_sample))), </a>
<a class="sourceLine" id="cb4-11" title="11">    <span class="dt">x =</span> <span class="st">&quot;Hours&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Frequency&quot;</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The mean listening time in the sample (black line) <span class="math inline">\(\bar x\)</span> is 18.59. We can already see from the graphic above that such a value is rather unlikely under the hypothesis that the population mean is <span class="math inline">\(10\)</span>. Intuitively, such a result would therefore provide evidence against our null hypothesis. But how could we quantify specifically how unlikely it is to obtain such a value and decide whether or not to reject the null hypothesis? Significance tests can be used to provide answers to these questions.</p>
</div>
<div id="statistical-inference-on-a-sample" class="section level3">
<h3><span class="header-section-number">6.1.2</span> Statistical inference on a sample</h3>
<div id="test-statistic" class="section level4">
<h4><span class="header-section-number">6.1.2.1</span> Test statistic</h4>
<div id="z-scores" class="section level5">
<h5><span class="header-section-number">6.1.2.1.1</span> z-scores</h5>
<p>Let’s go back to the sampling distribution above. We know that 95% of all values will fall within 1.96 standard deviations from the mean. So if we could express the distance between our sample mean and the null hypothesis in terms of standard deviations, we could make statements about the probability of getting a sample mean of the observed magnitude (or more extreme values). Essentially, we would like to know how many standard deviations (<span class="math inline">\(\sigma_{\bar x}\)</span>) our sample mean (<span class="math inline">\(\bar x\)</span>) is away from the population mean if the null hypothesis was true (<span class="math inline">\(\mu_0\)</span>). This can be formally expressed as follows:</p>
<p><span class="math display">\[
\bar x-  \mu_0 = z \sigma_{\bar x}
\]</span></p>
<p>In this equation, <code>z</code> will tell us how many standard deviations the sample mean <span class="math inline">\(\bar x\)</span> is away from the null hypothesis <span class="math inline">\(\mu_0\)</span>. Solving for <code>z</code> gives us:</p>
<p><span class="math display">\[
z = {\bar x-  \mu_0 \over \sigma_{\bar x}}={\bar x-  \mu_0 \over \sigma / \sqrt{n}}
\]</span></p>
<p>This standardized value (or “z-score”) is also referred to as a <strong>test statistic</strong>. Let’s compute the test statistic for our example above:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1">z_score &lt;-<span class="st"> </span>(mean_sample <span class="op">-</span><span class="st"> </span>H_<span class="dv">0</span>)<span class="op">/</span>(sigma<span class="op">/</span><span class="kw">sqrt</span>(n))</a>
<a class="sourceLine" id="cb5-2" title="2">z_score</a></code></pre></div>
<pre><code>## [1] 4.292454</code></pre>
<p>To make a decision on whether the difference can be deemed statistically significant, we now need to compare this calculated test statistic to a meaningful threshold. In order to do so, we need to decide on a significance level <span class="math inline">\(\alpha\)</span>, which expresses the probability of finding an effect that does not actually exist (i.e., Type I Error). You can find a detailed discussion of this point at the end of this chapter. For now, we will adopt the widely accepted significance level of 5% and set <span class="math inline">\(\alpha\)</span> to 0.05. The critical value for the normal distribution and <span class="math inline">\(\alpha\)</span> = 0.05 can be computed using the <code>qnorm()</code> function as follows:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1">z_crit &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>)</a>
<a class="sourceLine" id="cb7-2" title="2">z_crit</a></code></pre></div>
<pre><code>## [1] 1.959964</code></pre>
<p>We use <code>0.975</code> and not <code>0.95</code> since we are running a two-sided test and need to account for the rejection region at the other end of the distribution. Recall that for the normal distribution, 95% of the total probability falls within 1.96 standard deviations of the mean, so that higher (absolute) values provide evidence against the null hypothesis. Generally, we speak of a statistically significant effect if the (absolute) calculated test statistic is larger than the (absolute) critical value. We can easily check if this is the case in our example:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1"><span class="kw">abs</span>(z_score) <span class="op">&gt;</span><span class="st"> </span><span class="kw">abs</span>(z_crit)</a></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Since the absolute value of the calculated test statistic is larger than the critical value, we would reject <span class="math inline">\(H_0\)</span> and conclude that the true population mean <span class="math inline">\(\mu\)</span> is significantly different from the hypothesized value <span class="math inline">\(\mu_0 = 10\)</span>.</p>
</div>
<div id="t-statistic" class="section level5">
<h5><span class="header-section-number">6.1.2.1.2</span> t-statistic</h5>
<p>You may have noticed that the formula for the z-score above assumes that we know the true population standard deviation (<span class="math inline">\(\sigma\)</span>) when computing the standard deviation of the sampling distribution (<span class="math inline">\(\sigma_{\bar x}\)</span>) in the denominator. However, the population standard deviation is usually not known in the real world and therefore represents another unknown population parameter which we have to estimate from the sample. We saw in the previous chapter that we usually use <span class="math inline">\(s\)</span> as an estimate of <span class="math inline">\(\sigma\)</span> and <span class="math inline">\(SE_{\bar x}\)</span> as and estimate of <span class="math inline">\(\sigma_{\bar x}\)</span>. Intuitively, we should be more conservative regarding the critical value that we used above to assess whether we have a significant effect to reflect this uncertainty about the true population standard deviation. That is, the threshold for a “significant” effect should be higher to safeguard against falsely claiming a significant effect when there is none. If we replace <span class="math inline">\(\sigma_{\bar x}\)</span> by it’s estimate <span class="math inline">\(SE_{\bar x}\)</span> in the formula for the z-score, we get a new test statistic (i.e, the <strong>t-statistic</strong>) with its own distribution (the <strong>t-distribution</strong>):</p>
<p><span class="math display">\[
t = {\bar x-  \mu_0 \over SE_{\bar x}}={\bar x-  \mu_0 \over s / \sqrt{n}}
\]</span></p>
<p>Here, <span class="math inline">\(\bar X\)</span> denotes the sample mean and <span class="math inline">\(s\)</span> the sample standard deviation. The t-distribution has more probability in its “tails”, i.e. farther away from the mean. This reflects the higher uncertainty introduced by replacing the population standard deviation by its sample estimate. Intuitively, this is particularly relevant for small samples, since the uncertainty about the true population parameters decreases with increasing sample size. This is reflected by the fact that the exact shape of the t-distribution depends on the <strong>degrees of freedom</strong>, which is the sample size minus one (i.e., <span class="math inline">\(n-1\)</span>). To see this, the following graph shows the t-distribution with different degrees of freedom for a two-tailed test and <span class="math inline">\(\alpha = 0.05\)</span>. The grey curve shows the normal distribution.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-9-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>Notice that as <span class="math inline">\(n\)</span> gets larger, the t-distribution gets closer and closer to the normal distribution, reflecting the fact that the uncertainty introduced by <span class="math inline">\(s\)</span> is reduced. To summarize, we now have an estimate for the standard deviation of the distribution of the sample mean (i.e., <span class="math inline">\(SE_{\bar x}\)</span>) and an appropriate distribution that takes into account the necessary uncertainty (i.e., the t-distribution). Let us now compute the t-statistic according to the formula above:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1">SE &lt;-<span class="st"> </span>(<span class="kw">sd</span>(student_sample)<span class="op">/</span><span class="kw">sqrt</span>(n))</a>
<a class="sourceLine" id="cb11-2" title="2">t_score &lt;-<span class="st"> </span>(mean_sample <span class="op">-</span><span class="st"> </span>H_<span class="dv">0</span>)<span class="op">/</span>SE</a>
<a class="sourceLine" id="cb11-3" title="3">t_score</a></code></pre></div>
<pre><code>## [1] 4.84204</code></pre>
<p>Notice that the value of the t-statistic is higher compared to the z-score (4.29). This can be attributed to the fact that by using the <span class="math inline">\(s\)</span> as and estimate of <span class="math inline">\(\sigma\)</span>, we underestimate the true population standard deviation. Hence, the critical value would need to be larger to adjust for this. This is what the t-distribution does. Let us compute the critical value from the t-distribution with <code>n - 1</code>degrees of freedom.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1">df =<span class="st"> </span>n <span class="op">-</span><span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb13-2" title="2">t_crit &lt;-<span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dt">df =</span> df)</a>
<a class="sourceLine" id="cb13-3" title="3">t_crit</a></code></pre></div>
<pre><code>## [1] 2.009575</code></pre>
<p>Again, we use <code>0.975</code> and not <code>0.95</code> since we are running a two-sided test and need to account for the rejection region at the other end of the distribution. Notice that the new critical value based on the t-distributionis larger, to reflect the uncertainty when estimating <span class="math inline">\(\sigma\)</span> from <span class="math inline">\(s\)</span>. Now we can see that the calculated test statistic is still larger than the critical value.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1"><span class="kw">abs</span>(t_score) <span class="op">&gt;</span><span class="st"> </span><span class="kw">abs</span>(t_crit)</a></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>The following graphics shows that the calculated test statistic (red line) falls into the rejection region so that in our example, we would reject the null hypothesis that the true population mean is equal to <span class="math inline">\(10\)</span>.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-13-1.png" width="768" style="display: block; margin: auto;" /></p>
<p><strong>Decision:</strong> Reject <span class="math inline">\(H_0\)</span>, given that the calculated test statistic is larger than critical value.</p>
<p>Something to keep in mind here is the fact the test statistic is a function of the sample size. This, as <span class="math inline">\(n\)</span> gets large, the test statistic gets larger as well and we are more likely to find a significant effect. This reflects the decrease in uncertainty about the true population mean as our sample size increases.</p>
</div>
</div>
<div id="p-values" class="section level4">
<h4><span class="header-section-number">6.1.2.2</span> P-values</h4>
<p>In the previous section, we computed the test statistic, which tells us how close our sample is to the null hypothesis. The p-value corresponds to the probability that the test statistic would take a value as extreme or more extreme than the one that we actually observed, <strong>assuming that the null hypothesis is true</strong>. It is important to note that this is a <strong>conditional probability</strong>: we compute the probability of observing a sample mean (or a more extreme value) conditional on the assumption that the null hypothesis is true. The <code>pnorm()</code>function can be used to compute this probability. It is the cumulative probability distribution function of the `normal distribution. Cumulative probability means that the function returns the probability that the test statistic will take a value <strong>less than or equal to</strong> the calculated test statistic given the degrees of freedom. However, we are interested in obtaining the probability of observing a test statistic <strong>larger than or equal to</strong> the calculated test statistic under the null hypothesis (i.e., the p-value). Thus, we need to subtract the cumulative probability from 1. In addition, since we are running a two-sided test, we need to multiply the probability by 2 to account for the rejection region at the other side of the distribution.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1">p_value &lt;-<span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pt</span>(<span class="kw">abs</span>(t_score), <span class="dt">df =</span> df))</a>
<a class="sourceLine" id="cb17-2" title="2">p_value</a></code></pre></div>
<pre><code>## [1] 0.00001326885</code></pre>
<p>This value corresponds to the probability of observing a mean equal to or larger than the one we obtained from our sample, if the null hypothesis was true. As you can see, this probability is very low. A small p-value signals that it is unlikely to observe the calculated test statistic under the null hypothesis. To decide whether or not to reject the null hypothesis, we would now compare this value to the level of significance (<span class="math inline">\(\alpha\)</span>) that we chose for our test. For this example, we adopt the widely accepted significance level of 5%, so any test results with a p-value &lt; 0.05 would be deemed statistically significant. Note that the p-value is directly related to the value of the test statistic. The relationship is such that the higher (lower) the value of the test statistic, the lower (higher) the p-value.</p>
<p><strong>Decision:</strong> Reject <span class="math inline">\(H_0\)</span>, given that the p-value is smaller than 0.05.</p>
</div>
<div id="confidence-interval" class="section level4">
<h4><span class="header-section-number">6.1.2.3</span> Confidence interval</h4>
<p>For a given statistic calculated for a sample of observations (e.g., listening times), a 95% confidence interval can be constructed such that in 95% of samples, the true value of the true population mean will fall within its limits. If the parameter value specified in the null hypothesis (here <span class="math inline">\(10\)</span>) does not lie within the bounds, we reject <span class="math inline">\(H_0\)</span>. Building on what we learned about confidence intervals in the previous chapter, the 95% confidence interval based on the t-distribution can be computed as follows:</p>
<p><span class="math display">\[
CI_{lower} = {\bar x} - t_{1-{\alpha \over 2}} * SE_{\bar x} \\
CI_{upper} = {\bar x} + t_{1-{\alpha \over 2}} * SE_{\bar x}
\]</span></p>
<p>It is easy to compute this interval manually:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" title="1">ci_lower &lt;-<span class="st"> </span>(mean_sample) <span class="op">-</span><span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dt">df =</span> df) <span class="op">*</span><span class="st"> </span>SE</a>
<a class="sourceLine" id="cb19-2" title="2">ci_upper &lt;-<span class="st"> </span>(mean_sample) <span class="op">+</span><span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dt">df =</span> df) <span class="op">*</span><span class="st"> </span>SE</a>
<a class="sourceLine" id="cb19-3" title="3">ci_lower</a></code></pre></div>
<pre><code>## [1] 15.02606</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1">ci_upper</a></code></pre></div>
<pre><code>## [1] 22.15783</code></pre>
<p>The interpretation of this interval is as follows: if we would (hypothetically) take 100 samples and calculated the mean and confidence interval for each of them, then the true population mean would be included in 95% of these intervals. The CI is informative when reporting the result of your test, since it provides an estimate of the uncertainty associated with the test result. From the test statistic or the p-value alone, it is not easy to judge in which range the true population parameter is located. The CI provides an estimate of this range.</p>
<p><strong>Decision:</strong> Reject <span class="math inline">\(H_0\)</span>, given that the parameter value from the null hypothesis (<span class="math inline">\(10\)</span>) is not included in the interval.</p>
<p>To summarize, you can see that we arrive at the same conclusion (i.e., reject <span class="math inline">\(H_0\)</span>), irrespective if we use the test statistic, the p-value, or the confidence interval. However, keep in mind that rejecting the null hypothesis does not prove the alternative hypothesis (we can merely provide support for it). Rather, think of the p-value as the chance of obtaining the data we’ve collected assuming that the null hypothesis is true. You should report the confidence interval to provide an estimate of the uncertainty associated with your test results.</p>
</div>
</div>
<div id="choosing-the-right-test" class="section level3">
<h3><span class="header-section-number">6.1.3</span> Choosing the right test</h3>
<p>The test statistic, as we have seen, measures how close the sample is to the null hypothesis and often follows a well-known distribution (e.g., normal, t, or chi-square). To select the correct test, various factors need to be taken into consideration. Some examples are:</p>
<ul>
<li>On what scale are your variables measured (categorical vs. continuous)?</li>
<li>Do you want to test for relationships or differences?</li>
<li>If you test for differences, how many groups would you like to test?</li>
<li>For parametric tests, are the assumptions fulfilled?</li>
</ul>
<p>The previous discussion used a <strong>one sample t-test</strong> as an example, which requires that variable is measured on an interval or ratio scale. If you are confronted with other settings, the following flow chart provides a rough guideline on selecting the correct test:</p>
<div class="figure">
<img src="https://github.com/IMSMWU/Teaching/raw/master/MRDA2017/testselection.JPG" alt="Flowchart for selecting an appropriate test (source: McElreath, R. (2016): Statistical Rethinking, p. 2)" />
<p class="caption">Flowchart for selecting an appropriate test (source: McElreath, R. (2016): Statistical Rethinking, p. 2)</p>
</div>
<p>For a detailed overview over the different type of tests, please also refer to <a href="https://stats.idre.ucla.edu/other/mult-pkg/whatstat/" target="_blank">this overview</a> by the UCLA.</p>
<div id="parametric-vs.-non-parametric-tests" class="section level4">
<h4><span class="header-section-number">6.1.3.1</span> Parametric vs. non-parametric tests</h4>
<p>A basic distinction can be made between parametric and non-parametric tests. <strong>Parametric tests</strong> require that variables are measured on an interval or ratio scale and that the sampling distribution follows a known distribution. <strong>Non-Parametric tests</strong> on the other hand do not require the sampling distribution to be normally distributed (a.k.a. “assumption free tests”). These tests may be used when the variable of interest is measured on an ordinal scale or when the parametric assumptions do not hold. They often rely on ranking the data instead of analyzing the actual scores. By ranking the data, information on the magnitude of differences is lost. Thus, parametric tests are more powerful if the sampling distribution is normally distributed. In this chapter, we will first focus on parametric tests and cover non-parametric tests later.</p>
</div>
<div id="one-tailed-vs.-two-tailed-test" class="section level4">
<h4><span class="header-section-number">6.1.3.2</span> One-tailed vs. two-tailed test</h4>
<p>For some tests you may choose between a <strong>one-tailed test</strong> versus a <strong>two-tailed test</strong>. The choice depends on the hypothesis you specified, i.e., whether you specified a directional or a non-directional hypotheses. In the example above, we used a <strong>non-directional hypothesis</strong>. That is, we stated that the mean is different from the comparison value <span class="math inline">\(\mu_0\)</span>, but we did not state the direction of the effect. A <strong>directional hypothesis</strong> states the direction of the effect. For example, we might test whether the population mean is smaller than a comparison value:</p>
<p><span class="math display">\[
H_0: \mu \ge \mu_0 \\
H_1: \mu &lt; \mu_0
\]</span></p>
<p>Similarly, we could test whether the population mean is larger than a comparison value:</p>
<p><span class="math display">\[
H_0: \mu \le \mu_0 \\
H_1: \mu &gt; \mu_0
\]</span></p>
<p>Connected to the decision of how to phrase the hypotheses (directional vs. non-directional) is the choice of a <strong>one-tailed test</strong> versus a <strong>two-tailed test</strong>. Let’s first think about the meaning of a one-tailed test. Using a significance level of 0.05, a one-tailed test means that 5% of the total area under the probability distribution of our test statistic is located in one tail. Thus, under a one-tailed test, we test for the possibility of the relationship in one direction only, disregarding the possibility of a relationship in the other direction. In our example, a one-tailed test could test either if the mean listening time is significantly larger or smaller compared to the control condition, but not both. Depending on the direction, the mean listening time is significantly larger (smaller) if the test statistic is located in the top (bottom) 5% of its probability distribution.</p>
<p>The following graph shows the critical values that our test statistic would need to surpass so that the difference between the population mean and the comparison value would be deemed statistically significant.</p>
<p><img src="_main_files/figure-html/fig2-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>It can be seen that under a one-sided test, the rejection region is at one end of the distribution or the other. In a two-sided test, the rejection region is split between the two tails. As a consequence, the critical value of the test statistic is smaller using a one-tailed test, meaning that it has more power to detect an effect. Having said that, in most applications, we would like to be able catch effects in both directions, simply because we can often not rule out that an effect might exist that is not in the hypothesized direction. For example, if we would conduct a one-tailed test for a mean larger than some specified value but the mean turns out to be substantially smaller, then testing a one-directional hypothesis ($H_0: _0 $) would not allow us to conclude that there is a significant effect because there is not rejection at this end of the distribution.</p>
</div>
</div>
<div id="summary-1" class="section level3">
<h3><span class="header-section-number">6.1.4</span> Summary</h3>
<p>As we have seen, the process of hypothesis testing consists of various steps:</p>
<ol style="list-style-type: decimal">
<li>Formulate null and alternative hypotheses</li>
<li>Select an appropriate test</li>
<li>Choose the level of significance (<span class="math inline">\(\alpha\)</span>)</li>
<li>Descriptive statistics and data visualization</li>
<li>Conduct significance test</li>
<li>Report results and draw a marketing conclusion</li>
</ol>
<p>In the following, we will go through the individual steps using examples for different tests.</p>
</div>
</div>
<div id="one-sample-t-test" class="section level2">
<h2><span class="header-section-number">6.2</span> One sample t-test</h2>
<p>The example we used in the introduction was an example of the <strong>one sample t-test</strong> and we computed all statistics by hand to explain the underlying intuition. When you conduct hypothesis tests using R, you do not need to calculate these statistics by hand, since there are build-in routines to conduct the steps for you. Let us use the same example again to see how you would conduct hypothesis tests in R.</p>
<p><strong>1. Formulate null and alternative hypotheses</strong></p>
<p>The null hypothesis states that there is no difference between the true population mean <span class="math inline">\(\mu\)</span> and the hypothesized value (i.e., <span class="math inline">\(10\)</span>), while the alternative hypothesis states the opposite:</p>
<p><span class="math display">\[
H_0: \mu = 10 \\
H_1: \mu \neq 10
\]</span></p>
<p><strong>2. Select an appropriate test</strong></p>
<p>Because we would like to test if the mean of a variable is different from a specified threshold, the one-sample t-test is appropriate. The assumptions of the test are 1) that the variable is measured using an interval or ratio scale, and 2) that the sampling distribution is normal. Both assumptions are met since 1) listening time is a ratio scale, and 2) we deem the sample size (n = 50) large enough to assume a normal sampling distribution according to the central limit theorem.</p>
<p><strong>3. Choose the level of significance</strong></p>
<p>We choose the conventional 5% significance level.</p>
<p><strong>4. Descriptive statistics and data visualization</strong></p>
<p>Provide descriptive statistics using the <code>stat.desc()</code> function:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1"><span class="kw">library</span>(pastecs)</a>
<a class="sourceLine" id="cb23-2" title="2"><span class="kw">stat.desc</span>(student_sample)</a></code></pre></div>
<pre><code>##      nbr.val     nbr.null       nbr.na          min          max        range 
##   50.0000000    0.0000000    0.0000000    1.9365049   64.9843737   63.0478688 
##          sum       median         mean      SE.mean CI.mean.0.95          var 
##  929.5971917   16.2246844   18.5919438    1.7744470    3.5658848  157.4331152 
##      std.dev     coef.var 
##   12.5472354    0.6748749</code></pre>
<p>From this, we can already see that the mean is different from the hypothesized value. The question however remains, whether this difference is significantly different, given the sample size and the variability in the data. Since we only have one continuous variable, we can visualize the distribution in a histogram.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(student_sample)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> student_sample), </a>
<a class="sourceLine" id="cb25-2" title="2">    <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">bins =</span> <span class="dv">20</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb25-3" title="3"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of values in the sample&quot;</span>, </a>
<a class="sourceLine" id="cb25-4" title="4">        <span class="dt">x =</span> <span class="st">&quot;Hours&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Frequency&quot;</span>)</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p><strong>5. Conduct significance test</strong></p>
<p>In the beginning of the chapter, we saw, how you could conduct significance test by hand. However, R has built-in routines that you can use to conduct the analyses. The <code>t.test()</code> function can be used to conduct the test. To test if the listening time among WU students was 10, you can use the following code:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" title="1">H_<span class="dv">0</span> &lt;-<span class="st"> </span><span class="dv">10</span></a>
<a class="sourceLine" id="cb26-2" title="2"><span class="kw">t.test</span>(student_sample, <span class="dt">mu =</span> H_<span class="dv">0</span>, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  student_sample
## t = 4.842, df = 49, p-value = 0.00001327
## alternative hypothesis: true mean is not equal to 10
## 95 percent confidence interval:
##  15.02606 22.15783
## sample estimates:
## mean of x 
##  18.59194</code></pre>
<p>Note that if you would have stated a directional hypothesis (i.e., the mean is either greater or smaller than 10 hours), you could easily amend the code to conduct a one sided test by changing the argument <code>alternative</code>from <code>'two.sided'</code> to either <code>'less'</code> or <code>'greater'</code>.</p>
<p><strong>6. Report results and draw a marketing conclusion</strong></p>
<p>Note that the results are the same as above, when we computed the test by hand. You could summarize the results as follows:</p>
<p>On average, the listening times in our sample were different form 10 hours per month (Mean = 18.99 hours, SE = 1.78). This difference was significant t(49) = 5.058, p &lt; .05 (95% CI = [15.42; 22.56]). Based on this evidence, we can conclude that the mean in our sample is significantly lower compared to the hypothesized population mean of <span class="math inline">\(10\)</span> hours, providing evidence against the null hypothesis.</p>
<p>Note that in the reporting above, the number <code>49</code> in parenthesis refers to the degrees of freedom that are available from the output.</p>
</div>
<div id="comparing-two-means" class="section level2">
<h2><span class="header-section-number">6.3</span> Comparing two means</h2>
<p>In the one-sample test above, we tested the hypothesis that the population mean has some specific value <span class="math inline">\(\mu_0\)</span> using data from only one sample. In marketing (as in many other disciplines), you will often be confronted with a situation where you wish to compare the means of two groups. For example, you may conduct an experiment and randomly split your sample into two groups, one of which receives a treatment (experimental group) while the other doesn’t (control group). In this case, the units (e.g., participants, products) in each group are different (‘between-subjects design’) and the samples are said to be independent. Hence, we would use a <strong>independent-means t-test</strong>. If you run an experiment with two experimental conditions and the same units (e.g., participants, products) were observed in both experimental conditions, the sample is said to be dependent in the sense that you have the same units in each group (‘within-subjects design’). In this case, we would need to conduct an <strong>dependent-means t-test</strong>. Both tests are described in the following sections, beginning with the independent-means t-test.</p>
<div id="independent-means-t-test" class="section level3">
<h3><span class="header-section-number">6.3.1</span> Independent-means t-test</h3>
<p>Using an independent-means t-test, we can compare the means of two possibly different populations. It is, for example, quite common for online companies to test new service features by running an experiment and randomly splitting their website visitors into two groups: one is exposed to the website with the new feature (experimental group) and the other group is not exposed to the new feature (control group). This is a typical A/B-Test scenario.</p>
<p>As an example, imagine that a music streaming service would like to introduce a new playlist feature that let’s their users access playlists created by other users. The goal is to analyse how the new service feature impacts the listening time of users. The service randomly splits a representative subset of their users into two groups and collects data about their listening times over one month. Let’s create a data set to simulate such a scenario.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" title="1"><span class="kw">set.seed</span>(<span class="dv">321</span>)</a>
<a class="sourceLine" id="cb28-2" title="2">hours_population_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="dv">2</span>, <span class="dt">scale =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb28-3" title="3"><span class="kw">set.seed</span>(<span class="dv">12567</span>)</a>
<a class="sourceLine" id="cb28-4" title="4">sample_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">25000</span>, <span class="dt">size =</span> <span class="dv">98</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb28-5" title="5">sample_<span class="dv">1</span>_hours &lt;-<span class="st"> </span>hours_population_<span class="dv">1</span>[sample_<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb28-6" title="6">sample_<span class="dv">1</span>_df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">hours =</span> <span class="kw">round</span>(sample_<span class="dv">1</span>_hours, </a>
<a class="sourceLine" id="cb28-7" title="7">    <span class="dv">0</span>), <span class="dt">group =</span> <span class="st">&quot;A&quot;</span>)</a>
<a class="sourceLine" id="cb28-8" title="8"><span class="kw">set.seed</span>(<span class="dv">321</span>)</a>
<a class="sourceLine" id="cb28-9" title="9">hours_population_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="fl">2.5</span>, <span class="dt">scale =</span> <span class="dv">11</span>)</a>
<a class="sourceLine" id="cb28-10" title="10"><span class="kw">set.seed</span>(<span class="dv">12567</span>)</a>
<a class="sourceLine" id="cb28-11" title="11">sample_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">25000</span>, <span class="dt">size =</span> <span class="dv">112</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb28-12" title="12">sample_<span class="dv">2</span>_hours &lt;-<span class="st"> </span>hours_population_<span class="dv">2</span>[sample_<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb28-13" title="13">sample_<span class="dv">2</span>_df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">hours =</span> <span class="kw">round</span>(sample_<span class="dv">2</span>_hours, </a>
<a class="sourceLine" id="cb28-14" title="14">    <span class="dv">0</span>), <span class="dt">group =</span> <span class="st">&quot;B&quot;</span>)</a>
<a class="sourceLine" id="cb28-15" title="15">hours_a_b &lt;-<span class="st"> </span><span class="kw">rbind</span>(sample_<span class="dv">1</span>_df, sample_<span class="dv">2</span>_df)</a>
<a class="sourceLine" id="cb28-16" title="16"><span class="kw">head</span>(hours_a_b)</a></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["hours"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["group"],"name":[2],"type":["chr"],"align":["left"]}],"data":[{"1":"2","2":"A"},{"1":"27","2":"A"},{"1":"25","2":"A"},{"1":"2","2":"A"},{"1":"46","2":"A"},{"1":"13","2":"A"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>This data set contains two variables: the variable <code>hours</code> indicates the music listening times (in hours) and the variable <code>group</code> indicates from which group the observation comes, where ‘A’ refers to the control group (with the standard service) and ‘B’ refers to the experimental group (with the new playlist feature). Let’s first look at the descriptive statistics by group using the <code>describeBy</code> function:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" title="1"><span class="kw">library</span>(psych)</a></code></pre></div>
<pre><code>## 
## Attaching package: &#39;psych&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:ggplot2&#39;:
## 
##     %+%, alpha</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1"><span class="kw">describeBy</span>(hours_a_b<span class="op">$</span>hours, hours_a_b<span class="op">$</span>group)</a></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: A
##    vars  n  mean   sd median trimmed   mad min max range skew kurtosis   se
## X1    1 98 18.11 12.1     15   16.88 10.38   2  65    63 1.08     1.21 1.22
## ------------------------------------------------------------ 
## group: B
##    vars   n mean    sd median trimmed   mad min max range skew kurtosis  se
## X1    1 112 28.5 17.97   24.5   26.56 15.57   1  83    82 0.96     0.82 1.7</code></pre>
<p>From this, we can already see that there is a difference in means between groups A and B. We can also see that the number of observations is different, as is the standard deviation. The question that we would like to answer is whether there is a significant difference in mean listening times between the groups. Remember that different users are contained in each group (‘between-subjects design’) and that the observations in one group are independent of the observations in the other group. Before we will see how you can easily conduct an independent-means t-test, let’s go over some theory first.</p>
<div id="theory" class="section level4">
<h4><span class="header-section-number">6.3.1.1</span> Theory</h4>
<p>As a starting point, let us label the unknown population mean of group A (control group) in our experiment <span class="math inline">\(\mu_1\)</span>, and that of group B (experimental group) <span class="math inline">\(\mu_2\)</span>. In this setting, the null hypothesis would state that the mean in group A is equal to the mean in group B:</p>
<p><span class="math display">\[
H_0: \mu_1=\mu_2
\]</span></p>
<p>This is equivalent to stating that the difference between the two groups (<span class="math inline">\(\delta\)</span>) is zero:</p>
<p><span class="math display">\[
H_0: \mu_1 - \mu_2=0=\delta
\]</span></p>
<p>That is, <span class="math inline">\(\delta\)</span> is the new unknown population parameter, so that the null and alternative hypothesis become:</p>
<p><span class="math display">\[
H_0: \delta = 0 \\
H_1: \delta \ne 0
\]</span></p>
<p>Remember that we usually don’t have access to the entire population so that we can not observe <span class="math inline">\(\delta\)</span> and have to estimate is from a sample statistic, which we define as <span class="math inline">\(d = \bar x_1-\bar x_2\)</span>, i.e., the difference between the sample means from group a (<span class="math inline">\(\bar x_1\)</span>) and group b (<span class="math inline">\(\bar x_2\)</span>). But can we really estimate <span class="math inline">\(d\)</span> from <span class="math inline">\(\delta\)</span>? Remember from the previous chapter, that we could estimate <span class="math inline">\(\mu\)</span> from <span class="math inline">\(\bar x\)</span>, because if we (hypothetically) take a larger number of samples, the distribution of the means of these samples (the sampling distribution) will be normally distributed and its mean will be (in the limit) equal to the population mean. It turns out that we can use the same underlying logic here. The above samples were drawn from two different populations with <span class="math inline">\(\mu_1\)</span> and <span class="math inline">\(\mu_2\)</span>. Let us compute the difference in means between these two populations:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" title="1">delta_pop &lt;-<span class="st"> </span><span class="kw">mean</span>(hours_population_<span class="dv">1</span>) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(hours_population_<span class="dv">2</span>)</a>
<a class="sourceLine" id="cb34-2" title="2">delta_pop</a></code></pre></div>
<pre><code>## [1] -7.422855</code></pre>
<p>This means that the true difference between the mean listening times of groups a and b is -7.42. Let us now repeat the exercise from the previous chapter: let us repeatedly draw a large number of <span class="math inline">\(20,000\)</span> random samples of 100 users from each of these populations, compute the difference (i.e., <span class="math inline">\(d\)</span>, our estimate of <span class="math inline">\(\delta\)</span>), store the difference for each draw and create a histogram of <span class="math inline">\(d\)</span>.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" title="1"><span class="kw">set.seed</span>(<span class="dv">321</span>)</a>
<a class="sourceLine" id="cb36-2" title="2">hours_population_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="dv">2</span>, <span class="dt">scale =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb36-3" title="3">hours_population_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="fl">2.5</span>, <span class="dt">scale =</span> <span class="dv">11</span>)</a>
<a class="sourceLine" id="cb36-4" title="4"></a>
<a class="sourceLine" id="cb36-5" title="5">samples &lt;-<span class="st"> </span><span class="dv">20000</span></a>
<a class="sourceLine" id="cb36-6" title="6">mean_delta &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="ot">NA</span>, <span class="dt">nrow =</span> samples)</a>
<a class="sourceLine" id="cb36-7" title="7"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>samples) {</a>
<a class="sourceLine" id="cb36-8" title="8">    student_sample &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">25000</span>, <span class="dt">size =</span> <span class="dv">100</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb36-9" title="9">    mean_delta[i, ] &lt;-<span class="st"> </span><span class="kw">mean</span>(hours_population_<span class="dv">1</span>[student_sample]) <span class="op">-</span><span class="st"> </span></a>
<a class="sourceLine" id="cb36-10" title="10"><span class="st">        </span><span class="kw">mean</span>(hours_population_<span class="dv">2</span>[student_sample])</a>
<a class="sourceLine" id="cb36-11" title="11">}</a>
<a class="sourceLine" id="cb36-12" title="12"></a>
<a class="sourceLine" id="cb36-13" title="13"><span class="kw">ggplot</span>(<span class="kw">data.frame</span>(mean_delta)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mean_delta), </a>
<a class="sourceLine" id="cb36-14" title="14">    <span class="dt">bins =</span> <span class="dv">30</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb36-15" title="15"><span class="st">    </span><span class="kw">theme</span>(<span class="dt">legend.title =</span> <span class="kw">element_blank</span>()) <span class="op">+</span><span class="st"> </span><span class="kw">geom_vline</span>(<span class="kw">aes</span>(<span class="dt">xintercept =</span> <span class="kw">mean</span>(mean_delta)), </a>
<a class="sourceLine" id="cb36-16" title="16">    <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;d&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="kw">TeX</span>(<span class="kw">sprintf</span>(<span class="st">&quot;%d samples; $d_{</span><span class="ch">\\</span><span class="st">bar{x}}$ = %.2f&quot;</span>, </a>
<a class="sourceLine" id="cb36-17" title="17">    samples, <span class="kw">round</span>(<span class="kw">mean</span>(mean_delta), <span class="dv">2</span>))))</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>This gives us the sampling distribution of the mean differences between the samples. You will notice that this distribution follows a normal distribution and is centered around the true difference between the populations. This means that, on average, the difference between two sample means <span class="math inline">\(d\)</span> is a good estimate of <span class="math inline">\(\delta\)</span>. In our example, the difference between <span class="math inline">\(\bar x_1\)</span> and <span class="math inline">\(\bar x_2\)</span> is:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" title="1">mean_x1 &lt;-<span class="st"> </span><span class="kw">mean</span>(hours_a_b[hours_a_b<span class="op">$</span>group <span class="op">==</span><span class="st"> &quot;A&quot;</span>, <span class="st">&quot;hours&quot;</span>])</a>
<a class="sourceLine" id="cb37-2" title="2">mean_x1</a></code></pre></div>
<pre><code>## [1] 18.11224</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" title="1">mean_x2 &lt;-<span class="st"> </span><span class="kw">mean</span>(hours_a_b[hours_a_b<span class="op">$</span>group <span class="op">==</span><span class="st"> &quot;B&quot;</span>, <span class="st">&quot;hours&quot;</span>])</a>
<a class="sourceLine" id="cb39-2" title="2">mean_x2</a></code></pre></div>
<pre><code>## [1] 28.5</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" title="1">d &lt;-<span class="st"> </span>mean_x1 <span class="op">-</span><span class="st"> </span>mean_x2</a>
<a class="sourceLine" id="cb41-2" title="2">d</a></code></pre></div>
<pre><code>## [1] -10.38776</code></pre>
<p>Now that we have <span class="math inline">\(d\)</span> as an estimate of <span class="math inline">\(\delta\)</span>, how can we find out if the observed difference is significantly different from the null hypothesis (i.e., <span class="math inline">\(\delta = 0\)</span>)?</p>
<p>Recall from the previous section, that the standard deviation of the sampling distribution <span class="math inline">\(\sigma_{\bar x}\)</span> (i.e., the standard error) gives us indication about the precision of our estimate. Further recall that the standard error can be calculated as <span class="math inline">\(\sigma_{\bar x}={\sigma \over \sqrt{n}}\)</span>. So how can we calculate the standard error of the difference between two population means? According to the <strong>variance sum law</strong>, to find the variance of the sampling distribution of differences, we merely need to add together the variances of the sampling distributions of the two populations that we are comparing. To find the standard error, we only need to take the square root of the variance (because the standard error is the standard deviation of the sampling distribution and the standard deviation is the square root of the variance), so that we get:</p>
<p><span class="math display">\[
\sigma_{\bar x_1-\bar x_2} = \sqrt{{\sigma_1^2 \over n_1}+{\sigma_2^2 \over n_2}}
\]</span></p>
<p>But recall that we don’t actually know the true population standard deviation, so we use <span class="math inline">\(SE_{\bar x_1-\bar x_2}\)</span> as an estimate of <span class="math inline">\(\sigma_{\bar x_1-\bar x_2}\)</span>:</p>
<p><span class="math display">\[
SE_{\bar x_1-\bar x_2} = \sqrt{{s_1^2 \over n_1}+{s_2^2 \over n_2}}
\]</span></p>
<p>Hence, for our example, we can calculate the standard error as follows:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1">n1 &lt;-<span class="st"> </span><span class="dv">98</span></a>
<a class="sourceLine" id="cb43-2" title="2">n2 &lt;-<span class="st"> </span><span class="dv">112</span></a>
<a class="sourceLine" id="cb43-3" title="3">s1 &lt;-<span class="st"> </span><span class="kw">var</span>(hours_a_b[hours_a_b<span class="op">$</span>group <span class="op">==</span><span class="st"> &quot;A&quot;</span>, <span class="st">&quot;hours&quot;</span>])</a>
<a class="sourceLine" id="cb43-4" title="4">s1</a></code></pre></div>
<pre><code>## [1] 146.4924</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1">s2 &lt;-<span class="st"> </span><span class="kw">var</span>(hours_a_b[hours_a_b<span class="op">$</span>group <span class="op">==</span><span class="st"> &quot;B&quot;</span>, <span class="st">&quot;hours&quot;</span>])</a>
<a class="sourceLine" id="cb45-2" title="2">s2</a></code></pre></div>
<pre><code>## [1] 322.9189</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1">SE_x1_x2 &lt;-<span class="st"> </span><span class="kw">sqrt</span>(s1<span class="op">/</span>n1 <span class="op">+</span><span class="st"> </span>s2<span class="op">/</span>n2)</a>
<a class="sourceLine" id="cb47-2" title="2">SE_x1_x2</a></code></pre></div>
<pre><code>## [1] 2.092373</code></pre>
<p>Recall from above that we can calculate the t-statistic as:</p>
<p><span class="math display">\[
t= {\bar x - \mu_0 \over {s \over \sqrt{n}}} 
\]</span></p>
<p>Exchanging <span class="math inline">\(\bar x\)</span> for <span class="math inline">\(d\)</span>, we get</p>
<p><span class="math display">\[
t= {(\bar{x}_1 - \bar{x}_2) - (\mu_1 - \mu_2) \over {\sqrt{{s_1^2 \over n_1}+{s_2^2 \over n_2}}}} 
\]</span></p>
<p>Note that according to our hypothesis <span class="math inline">\(\mu_1-\mu_2=0\)</span>, so that we can calculate the t-statistic as:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1">t_score &lt;-<span class="st"> </span>d<span class="op">/</span>SE_x1_x2</a>
<a class="sourceLine" id="cb49-2" title="2">t_score</a></code></pre></div>
<pre><code>## [1] -4.964581</code></pre>
<p>Following the example of our one sample t-test above, we would now need to compare this calculated test statistic to a critical value in order to assess if <span class="math inline">\(d\)</span> is sufficiently far away from the null hypothesis to be statistically significant. To do this, we would need to know the exact t-distribution, which depends on the degrees of freedom. The problem is that deriving the degrees of freedom in this case is not that obvious. If we were willing to assume that <span class="math inline">\(\sigma_1=\sigma_2\)</span>, the correct t-distribution has <span class="math inline">\(n_1 -1 + n_2-1\)</span> degrees of freedom (i.e., the sum of the degrees of freedom of the two samples). However, because in real life we don not know if <span class="math inline">\(\sigma_1=\sigma_2\)</span>, we need to account for this additional uncertainty. We will not go into detail here, but R automatically uses a sophisticated approach to correct the degrees of freedom called the Welch’s correction, as we will see in the subsequent application.</p>
</div>
<div id="application" class="section level4">
<h4><span class="header-section-number">6.3.1.2</span> Application</h4>
<p>The section above explained the theory behind the independent-means t-test and showed how to compute the statistics manually. Obviously you don’t have to compute these statistics by hand in this section shows you how to conduct an independent-means t-test in R using the example from above.</p>
<p><strong>1. Formulate null and alternative hypotheses</strong></p>
<p>We wish to analyze whether there is a significant difference in music listening times between groups A and B. So our null hypothesis is that the means from the two populations are the same (i.e., there is no difference), while the alternative hypothesis states the opposite:</p>
<p><span class="math display">\[
H_0: \mu_1=\mu_2\\
H_1: \mu_1 \ne \mu_2
\]</span></p>
<p><strong>2. Select an appropriate test</strong></p>
<p>Since we have a ratio scaled variable (i.e., listening times) and two independent groups, where the mean of one sample is independent of the group of the second sample (i.e., the groups contain different units), the independent-means t-test is appropriate.</p>
<p><strong>3. Choose the level of significance</strong></p>
<p>We choose the conventional 5% significance level.</p>
<p><strong>4. Descriptive statistics and data visualization</strong></p>
<p>We can compute the descriptive statistics for each group separately, using the <code>describeBy()</code> function:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1"><span class="kw">library</span>(psych)</a>
<a class="sourceLine" id="cb51-2" title="2"><span class="kw">describeBy</span>(hours_a_b<span class="op">$</span>hours, hours_a_b<span class="op">$</span>group)</a></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: A
##    vars  n  mean   sd median trimmed   mad min max range skew kurtosis   se
## X1    1 98 18.11 12.1     15   16.88 10.38   2  65    63 1.08     1.21 1.22
## ------------------------------------------------------------ 
## group: B
##    vars   n mean    sd median trimmed   mad min max range skew kurtosis  se
## X1    1 112 28.5 17.97   24.5   26.56 15.57   1  83    82 0.96     0.82 1.7</code></pre>
<p>This already shows us that the mean between groups A and B are different. We can visualize the data using a plot of means, boxplot, and a histogram.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1"><span class="kw">ggplot</span>(hours_a_b, <span class="kw">aes</span>(group, hours)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;summary&quot;</span>, </a>
<a class="sourceLine" id="cb53-2" title="2">    <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">width =</span> <span class="fl">0.7</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb53-3" title="3"><span class="st">    </span><span class="kw">geom_pointrange</span>(<span class="dt">stat =</span> <span class="st">&quot;summary&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Group&quot;</span>, </a>
<a class="sourceLine" id="cb53-4" title="4">    <span class="dt">y =</span> <span class="st">&quot;Listening time (hours)&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;Means and standard errors of listening times&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb53-5" title="5"><span class="st">    </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" title="1"><span class="kw">ggplot</span>(hours_a_b, <span class="kw">aes</span>(<span class="dt">x =</span> group, <span class="dt">y =</span> hours)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb54-2" title="2"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Group&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Listening time (hours)&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb54-3" title="3"><span class="st">    </span><span class="kw">ggtitle</span>(<span class="st">&quot;Boxplot of listening times&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-27-2.png" width="672" /></p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1"><span class="kw">ggplot</span>(hours_a_b, <span class="kw">aes</span>(hours)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">col =</span> <span class="st">&quot;black&quot;</span>, </a>
<a class="sourceLine" id="cb55-2" title="2">    <span class="dt">fill =</span> <span class="st">&quot;darkblue&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Listening time (hours)&quot;</span>, </a>
<a class="sourceLine" id="cb55-3" title="3">    <span class="dt">y =</span> <span class="st">&quot;Frequency&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;Histogram of listening times&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb55-4" title="4"><span class="st">    </span><span class="kw">facet_wrap</span>(<span class="op">~</span>group) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-27-3.png" width="672" /></p>
<p><strong>5. Conduct significance test</strong></p>
<p>To conduct the independent means t-test, we can use the <code>t.test()</code> function:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" title="1"><span class="kw">t.test</span>(hours <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> hours_a_b, <span class="dt">mu =</span> <span class="dv">0</span>, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, </a>
<a class="sourceLine" id="cb56-2" title="2">    <span class="dt">conf.level =</span> <span class="fl">0.95</span>, <span class="dt">var.equal =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  hours by group
## t = -4.9646, df = 195.73, p-value = 0.000001494
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -14.514246  -6.261264
## sample estimates:
## mean in group A mean in group B 
##        18.11224        28.50000</code></pre>
<p><strong>6. Report results and draw a marketing conclusion</strong></p>
<p>The results showed that listening times were higher in the experimental group (Mean = 26.43, SE = 1.54) compared to the control group (Mean = 20.91, SE = 1.37). This means that the listening times were 10.39 hours higher on average in the experimental group, compared to the control group. An independent-means t-test showed that this difference is significant t(207) = 2.684, p &lt; .05 (95% CI = [1.46,9.58]).</p>
</div>
</div>
<div id="dependent-means-t-test" class="section level3">
<h3><span class="header-section-number">6.3.2</span> Dependent-means t-test</h3>
<p>While the independent-means t-test is used when different units (e.g., participants, products) were assigned to the different condition, the <strong>dependent-means t-test</strong> is used when there are two experimental conditions and the same units (e.g., participants, products) were observed in both experimental conditions.</p>
<p>Imagine, for example, a slightly different experimental setup for the above experiment. Imagine that we do not assign different users to the groups, but that a sample of 100 users gets to use the music streaming service with the new feature for one month and we compare the music listening times of these users during the month of the experiment with the listening time in the previous month. Let us generate data for this example:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1"><span class="kw">set.seed</span>(<span class="dv">321</span>)</a>
<a class="sourceLine" id="cb58-2" title="2">hours_population_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="dv">2</span>, <span class="dt">scale =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb58-3" title="3"><span class="kw">set.seed</span>(<span class="dv">12567</span>)</a>
<a class="sourceLine" id="cb58-4" title="4">sample_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">25000</span>, <span class="dt">size =</span> <span class="dv">100</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb58-5" title="5">sample_<span class="dv">1</span>_hours &lt;-<span class="st"> </span>hours_population_<span class="dv">1</span>[sample_<span class="dv">1</span>]</a>
<a class="sourceLine" id="cb58-6" title="6"><span class="kw">set.seed</span>(<span class="dv">321</span>)</a>
<a class="sourceLine" id="cb58-7" title="7">hours_population_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">rgamma</span>(<span class="dv">25000</span>, <span class="dt">shape =</span> <span class="fl">2.5</span>, <span class="dt">scale =</span> <span class="dv">11</span>)</a>
<a class="sourceLine" id="cb58-8" title="8"><span class="kw">set.seed</span>(<span class="dv">12567</span>)</a>
<a class="sourceLine" id="cb58-9" title="9">sample_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">25000</span>, <span class="dt">size =</span> <span class="dv">100</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb58-10" title="10">sample_<span class="dv">2</span>_hours &lt;-<span class="st"> </span>hours_population_<span class="dv">2</span>[sample_<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb58-11" title="11">hours_a_b_paired &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">hours_a =</span> <span class="kw">round</span>(sample_<span class="dv">1</span>_hours, </a>
<a class="sourceLine" id="cb58-12" title="12">    <span class="dv">0</span>), <span class="dt">hours_b =</span> <span class="kw">round</span>(sample_<span class="dv">2</span>_hours, <span class="dv">0</span>))</a>
<a class="sourceLine" id="cb58-13" title="13"><span class="kw">head</span>(hours_a_b_paired)</a></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["hours_a"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["hours_b"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"24"},{"1":"27","2":"21"},{"1":"25","2":"51"},{"1":"2","2":"12"},{"1":"46","2":"54"},{"1":"13","2":"18"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Note that the data set has almost the same structure as before only that we know have two variables representing the listening times of each user in the month before the experiment and during the month of the experiment when the new feature was tested.</p>
<div id="theory-1" class="section level4">
<h4><span class="header-section-number">6.3.2.1</span> Theory</h4>
<p>In this case, we want to test the hypothesis that there is no difference in mean the mean listening times between the two months. This can be expressed as follows:</p>
<p><span class="math display">\[
H_0: \mu_D = 0 \\
\]</span>
Note that the hypothesis only refers to one population, since both observations come from the same units (i.e., users). To use consistent notation, we replace <span class="math inline">\(\mu_D\)</span> with <span class="math inline">\(\delta\)</span> and get:</p>
<p><span class="math display">\[
H_0: \delta = 0 \\
H_1: \delta \neq 0
\]</span></p>
<p>where <span class="math inline">\(\delta\)</span> denotes the difference between the observed listening times from the two consecutive months <strong>of the same users</strong>. As is the previous example, since we do not observe the entire population, we estimate <span class="math inline">\(\delta\)</span> based on the sample using <span class="math inline">\(d\)</span>, which is the difference in mean listening time between the two months for our sample. Note that we assume that everything else (e.g., number of new releases) remained constant over the two month to keep it simple. We can show as above that the sampling distribution follows a normal distribution with a mean that is (in the limit) the same as the population mean. This means, again, that the difference in sample means is a good estimate for the difference in population means. Let’s compute a new variable <span class="math inline">\(d\)</span>, which is the difference between two month.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1">hours_a_b_paired<span class="op">$</span>d &lt;-<span class="st"> </span>hours_a_b_paired<span class="op">$</span>hours_a <span class="op">-</span><span class="st"> </span>hours_a_b_paired<span class="op">$</span>hours_b</a>
<a class="sourceLine" id="cb59-2" title="2"><span class="kw">head</span>(hours_a_b_paired)</a></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["hours_a"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["hours_b"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["d"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"24","3":"-22"},{"1":"27","2":"21","3":"6"},{"1":"25","2":"51","3":"-26"},{"1":"2","2":"12","3":"-10"},{"1":"46","2":"54","3":"-8"},{"1":"13","2":"18","3":"-5"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Note that we now have a new variable, which is the difference in listening times (in hours) between the two months. The mean of this difference is:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1">mean_d &lt;-<span class="st"> </span><span class="kw">mean</span>(hours_a_b_paired<span class="op">$</span>d)</a>
<a class="sourceLine" id="cb60-2" title="2">mean_d</a></code></pre></div>
<pre><code>## [1] -11.65</code></pre>
<p>Again, we use <span class="math inline">\(SE_{\bar x}\)</span> as an estimate of <span class="math inline">\(\sigma_{\bar x}\)</span>:</p>
<p><span class="math display">\[
SE_{\bar d}={s \over \sqrt{n}}
\]</span>
Hence, we can compute the standard error as:</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1">n &lt;-<span class="st"> </span><span class="kw">nrow</span>(hours_a_b_paired)</a>
<a class="sourceLine" id="cb62-2" title="2">SE_d &lt;-<span class="st"> </span><span class="kw">sd</span>(hours_a_b_paired<span class="op">$</span>d)<span class="op">/</span><span class="kw">sqrt</span>(n)</a>
<a class="sourceLine" id="cb62-3" title="3">SE_d</a></code></pre></div>
<pre><code>## [1] 2.151503</code></pre>
<p>The test statistic is therefore:</p>
<p><span class="math display">\[
t = {\bar d-  \mu_0 \over SE_{\bar d}}
\]</span>
on 99 (i.e., n-1) degrees of freedom. Now we can compute the t-statistic as follows:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1">t_score &lt;-<span class="st"> </span>mean_d<span class="op">/</span>SE_d</a>
<a class="sourceLine" id="cb64-2" title="2">t_score</a></code></pre></div>
<pre><code>## [1] -5.41482</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" title="1"><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dt">df =</span> <span class="dv">99</span>)</a></code></pre></div>
<pre><code>## [1] 1.984217</code></pre>
<p>Note that in the case of the dependent-means t-test, we only base our hypothesis on one population and hence there is only one population variance. This is because in the dependent sample test, the observations come from the same observational units (i.e., users). Hence, there is no unsystematic variation due to potential differences between users that were assigned to the experimental groups. This means that the influence of unobserved factors (unsystematic variation) relative to the variation due to the experimental manipulation (systematic variation) is not as strong in the dependent-means test compared to the independent-means test and we don’t need to correct for differences in the population variances.</p>
</div>
<div id="application-1" class="section level4">
<h4><span class="header-section-number">6.3.2.2</span> Application</h4>
<p>Again, we don’t have to compute all this by hand since the <code>t.test(...)</code> function can be used to do it for us. Now we have to use the argument <code>paired=TRUE</code> to let R know that we are working with dependent observations.</p>
<p><strong>1. Formulate null and alternative hypotheses</strong></p>
<p>We would like to the test if there is a difference in music listening times between the two consecutive months, so our null hypothesis is that there is no difference, while the alternative hypothesis states the opposite:</p>
<p><span class="math display">\[
H_0: \mu_D = 0 \\
H_0: \mu_D \ne 0
\]</span></p>
<p><strong>2. Select an appropriate test</strong></p>
<p>Since we have a ratio scaled variable (i.e., listening times) and two observations of the same group of users (i.e., the groups contain the same units), the dependent-means t-test is appropriate.</p>
<p><strong>3. Choose the level of significance</strong></p>
<p>We choose the conventional 5% significance level.</p>
<p><strong>4. Descriptive statistics and data visualization</strong></p>
<p>We can compute the descriptive statistics for each month separately, using the <code>describe()</code> function:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" title="1"><span class="kw">library</span>(psych)</a>
<a class="sourceLine" id="cb68-2" title="2"><span class="kw">describe</span>(hours_a_b_paired)</a></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["vars"],"name":[1],"type":["int"],"align":["right"]},{"label":["n"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["mean"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["sd"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["median"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["trimmed"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["mad"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["min"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["max"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["range"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["skew"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["kurtosis"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["se"],"name":[13],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"100","3":"17.93","4":"12.06988","5":"15","6":"16.5875","7":"10.3782","8":"2","9":"65","10":"63","11":"1.0913320","12":"1.2549609","13":"1.206988"},{"1":"2","2":"100","3":"29.58","4":"18.41562","5":"25","6":"27.6250","7":"17.0499","8":"3","9":"83","10":"80","11":"0.8966967","12":"0.5662360","13":"1.841562"},{"1":"3","2":"100","3":"-11.65","4":"21.51503","5":"-9","6":"-10.6000","7":"19.2738","8":"-76","9":"51","10":"127","11":"-0.3750444","12":"0.7209769","13":"2.151503"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>This already shows us that the mean between the two months are different. We can visiualize the data using a plot of means, boxplot, and a histogram.</p>
<p>To plot the data, we need to do some restructuring first, since the variables are now stored in two different columns (“hours_a” and “hours_b”). This is also known as the “wide” format. To plot the data we need all observations to be stored in one variable. This is also known as the “long” format. We can use the <code>melt(...)</code> function from the <code>reshape2</code>package to “melt” the two variable into one column to plot the data.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" title="1"><span class="kw">library</span>(reshape2)</a>
<a class="sourceLine" id="cb69-2" title="2">hours_a_b_paired_long &lt;-<span class="st"> </span><span class="kw">melt</span>(hours_a_b_paired[, <span class="kw">c</span>(<span class="st">&quot;hours_a&quot;</span>, </a>
<a class="sourceLine" id="cb69-3" title="3">    <span class="st">&quot;hours_b&quot;</span>)])</a>
<a class="sourceLine" id="cb69-4" title="4"><span class="kw">names</span>(hours_a_b_paired_long) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;group&quot;</span>, <span class="st">&quot;hours&quot;</span>)</a>
<a class="sourceLine" id="cb69-5" title="5"><span class="kw">head</span>(hours_a_b_paired_long)</a></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["group"],"name":[1],"type":["fctr"],"align":["left"]},{"label":["hours"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"hours_a","2":"2"},{"1":"hours_a","2":"27"},{"1":"hours_a","2":"25"},{"1":"hours_a","2":"2"},{"1":"hours_a","2":"46"},{"1":"hours_a","2":"13"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>Now we are ready to plot the data:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" title="1"><span class="kw">ggplot</span>(hours_a_b_paired_long, <span class="kw">aes</span>(group, hours)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb70-2" title="2"><span class="st">    </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;summary&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>, </a>
<a class="sourceLine" id="cb70-3" title="3">        <span class="dt">width =</span> <span class="fl">0.7</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_pointrange</span>(<span class="dt">stat =</span> <span class="st">&quot;summary&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb70-4" title="4"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Group&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Listening time (hours)&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb70-5" title="5"><span class="st">    </span><span class="kw">ggtitle</span>(<span class="st">&quot;Means and standard errors of listining times&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb70-6" title="6"><span class="st">    </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" title="1"><span class="kw">ggplot</span>(hours_a_b_paired_long, <span class="kw">aes</span>(<span class="dt">x =</span> group, <span class="dt">y =</span> hours)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb71-2" title="2"><span class="st">    </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Group&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Listening time (hours)&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb71-3" title="3"><span class="st">    </span><span class="kw">ggtitle</span>(<span class="st">&quot;Boxplot of listening times&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-36-2.png" width="672" /></p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" title="1"><span class="kw">ggplot</span>(hours_a_b_paired_long, <span class="kw">aes</span>(hours)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">col =</span> <span class="st">&quot;black&quot;</span>, </a>
<a class="sourceLine" id="cb72-2" title="2">    <span class="dt">fill =</span> <span class="st">&quot;darkblue&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Listening time (hours)&quot;</span>, </a>
<a class="sourceLine" id="cb72-3" title="3">    <span class="dt">y =</span> <span class="st">&quot;Frequency&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&quot;Histogram of listening times&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb72-4" title="4"><span class="st">    </span><span class="kw">facet_wrap</span>(<span class="op">~</span>group) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</a></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-36-3.png" width="672" /></p>
<p><strong>5. Conduct significance test</strong></p>
<p>To conduct the independent means t-test, we can use the <code>t.test()</code> function with the argument <code>paired = TRUE</code>:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" title="1"><span class="kw">t.test</span>(hours_a_b_paired<span class="op">$</span>hours_a, hours_a_b_paired<span class="op">$</span>hours_b, </a>
<a class="sourceLine" id="cb73-2" title="2">    <span class="dt">mu =</span> <span class="dv">0</span>, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, <span class="dt">conf.level =</span> <span class="fl">0.95</span>, </a>
<a class="sourceLine" id="cb73-3" title="3">    <span class="dt">paired =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  hours_a_b_paired$hours_a and hours_a_b_paired$hours_b
## t = -5.4148, df = 99, p-value = 0.00000043
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -15.919048  -7.380952
## sample estimates:
## mean of the differences 
##                  -11.65</code></pre>
<p><strong>6. Report results and draw a marketing conclusion</strong></p>
<p>On average, the same users used the service more when it included the new feature (M = 25.96, SE = 1.68) compared to the service without the feature (M = 20.99, SE = 1.34). This difference was significant t(99) = 2.3781, p &lt; .05 (95% CI = [0.82, 9.12]).</p>
</div>
<div id="summary-2" class="section level4">
<h4><span class="header-section-number">6.3.2.3</span> Summary</h4>
<ul>
<li><p>Between-subject experimental design: When you run experiment and randomly split sample into two groups whose units/participants are independent of each other, one of which receives a treatment (experimental group) while the other doesn’t (control group). In this case we have two independent samples and use independent t-test.</p></li>
<li><p>Within-subject experimental design: If you run an experiment with two experimental conditions and the same participants/units were observed in both experimental conditions, the sample is said to be dependent in the sense that you have the same participants/units in each group. In this case we have two dependent samples and use dependent t-test (Paired test).</p></li>
<li><p>Hypotheses:</p>
<ul>
<li>H0: The difference between the two (independent or dependent) groups is equal zero.</li>
<li>H1: The difference between the two (independent or dependent) groups is not equal 0.</li>
</ul></li>
<li><p>Both the independent t-test and the dependent t-test are parametric tests based on the normal distribution.</p></li>
<li><p>Assumptions for both type of tests:</p>
<ul>
<li><p>The sampling distribution is normally distributed. In the dependent t-test this means that the sampling distribution of the differences between scores should be normal, not the scores themselves.</p></li>
<li><p>Data are measured at least at the interval level.</p></li>
</ul></li>
<li><p>The independent t-test, because it is used to test independent groups of people, also assumes:</p>
<ul>
<li><p>Scores in different treatment conditions (control group and test group) are independent (because they come from different participants/units/products).</p></li>
<li><p>Homogeneity of variance – it assumes equal variances.</p></li>
</ul></li>
<li><p>Application in marketing: T-test can help marketing department of retailers to answer questions about customers spendings. Since they have collected extensive data about their customers through loyalty program, they may want to use to conduct a research. They might be interested in comparing average amount of Euros spent per purchase between customers who live closer (within range of 500 m) and customers who live further (more than 500m) from their new outlet. Therefore, they could form the following hypotheses:</p>
<ul>
<li>H0: There is no difference in a spending per purchase between customers who live closer to the outlet and customers who live further.<br />
</li>
<li>H1: There is a difference in a spending per purchase between customers who live closer to the outlet and customers who live further.</li>
</ul></li>
</ul>
</div>
</div>
<div id="further-considerations" class="section level3">
<h3><span class="header-section-number">6.3.3</span> Further considerations</h3>
<div id="type-i-and-type-ii-errors" class="section level4">
<h4><span class="header-section-number">6.3.3.1</span> Type I and Type II Errors</h4>
<p>When choosing the level of significance (<span class="math inline">\(\alpha\)</span>). It is important to note that the choice of the significance level affects the type 1 and type 2 error:</p>
<ul>
<li>Type I error: When we believe there is a genuine effect in our population, when in fact there isn’t. Probability of type I error (<span class="math inline">\(\alpha\)</span>) = level of significance.</li>
<li>Type II error: When we believe that there is no effect in the population, when in fact there is.</li>
</ul>
<p>This following table shows the possible outcomes of a test (retain vs. reject <span class="math inline">\(H_0\)</span>), depending on whether <span class="math inline">\(H_0\)</span> is true or false in reality.</p>
<table>
<colgroup>
<col width="16%" />
<col width="41%" />
<col width="41%" />
</colgroup>
<thead>
<tr class="header">
<th> </th>
<th>Retain <b>H<sub>0</sub></b></th>
<th>Reject <b>H<sub>0</sub></b></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><b>H<sub>0</sub> is true</b></td>
<td>Correct decision:<br>1-α (probability of correct retention);</td>
<td>Type 1 error:<br> α (level of significance)</td>
</tr>
<tr class="even">
<td><b>H<sub>0</sub> is false</b></td>
<td>Type 2 error:<br>β (type 2 error rate)</td>
<td>Correct decision:<br>1-β (power of the test)</td>
</tr>
</tbody>
</table>
</div>
<div id="significance-level-sample-size-power-and-effect-size" class="section level4">
<h4><span class="header-section-number">6.3.3.2</span> Significance level, sample size, power, and effect size</h4>
<p>When you plan to conduct an experiment, there are some factors that are under direct control of the researcher:</p>
<ul>
<li><strong>Significance level (<span class="math inline">\(\alpha\)</span>)</strong>: The probability of finding an effect that does not genuinely exist.</li>
<li><strong>Sample size (n)</strong>: The number of observations in each group of the experimental design.</li>
</ul>
<p>Unlike α and n, which are specified by the researcher, the magnitude of β depends on the actual value of the population parameter. In addition, β is influenced by the effect size (e.g., Cohen’s d), which can be used to determine a standardized measure of the magnitude of an observed effect. The following parameters are affected more indirectly:</p>
<ul>
<li><strong>Power (1-β)</strong>: The probability of finding an effect that does genuinely exists.</li>
<li><strong>Effect size (d)</strong>: Standardized measure of the effect size under the alternate hypothesis.</li>
</ul>
<p>Although β is unknown, it is related to α. For example, if we would like to be absolutely sure that we do not falsely identify an effect which does not exist (i.e., make a type I error), this means that the probability of identifying an effect that does exist (i.e., 1-β) decreases and vice versa. Thus, an extremely low value of α (e.g., α = 0.0001) will result in intolerably high β errors. A common approach is to set α=0.05 and β=0.80.</p>
<p>Unlike the t-value of our test, the effect size (d) is unaffected by the sample size and can be categorized as follows (see Cohen, J. 1988):</p>
<ul>
<li>0.2 (small effect)</li>
<li>0.5 (medium effect)</li>
<li>0.8 (large effect)</li>
</ul>
<p>In order to test more subtle effects (smaller effect sizes), you need a larger sample size compared to the test of more obvious effects. In <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2205186" target="_blank">this paper</a>, you can find a list of examples for different effect sizes and the number of observations you need to reliably find an effect of that magnitude. Although the exact effect size is unknown before the experiment, you might be able to make a guess about the effect size (e.g., based on previous studies).</p>
<p>If you wish to obtain a standardized measure of the effect, you may compute the effect size (Cohen’s d) using the <code>cohensD()</code> function from the <code>lsr</code> package. Using the examples from the independent-means t-test above, we would use:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1"><span class="kw">library</span>(lsr)</a>
<a class="sourceLine" id="cb75-2" title="2"><span class="kw">cohensD</span>(hours <span class="op">~</span><span class="st"> </span>group, <span class="dt">data =</span> hours_a_b)</a></code></pre></div>
<pre><code>## [1] 0.6696301</code></pre>
<p>According to the thresholds defined above, this effect would be judged to be a small-medium effect.</p>
<p>For the dependent-means t-test, we would use:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" title="1"><span class="kw">cohensD</span>(hours_a_b_paired<span class="op">$</span>hours_a, hours_a_b_paired<span class="op">$</span>hours_b, </a>
<a class="sourceLine" id="cb77-2" title="2">    <span class="dt">method =</span> <span class="st">&quot;paired&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 0.541482</code></pre>
<p>According to the thresholds defined above, this effect would also be judged to be a small-medium effect.</p>
<p>When constructing an experimental design, your goal should be to maximize the power of the test while maintaining an acceptable significance level and keeping the sample as small as possible. To achieve this goal, you may use the <code>pwr</code> package, which let’s you compute <code>n</code>, <code>d</code>, <code>alpha</code>, and <code>power</code>. You only need to specify three of the four input variables to get the fourth.</p>
<p>For example, what sample size do we need (per group) to identify an effect with d = 0.6, α = 0.05, and power = 0.8:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" title="1"><span class="kw">library</span>(pwr)</a>
<a class="sourceLine" id="cb79-2" title="2"><span class="kw">pwr.t.test</span>(<span class="dt">d =</span> <span class="fl">0.6</span>, <span class="dt">sig.level =</span> <span class="fl">0.05</span>, <span class="dt">power =</span> <span class="fl">0.8</span>, </a>
<a class="sourceLine" id="cb79-3" title="3">    <span class="dt">type =</span> <span class="kw">c</span>(<span class="st">&quot;two.sample&quot;</span>), <span class="dt">alternative =</span> <span class="kw">c</span>(<span class="st">&quot;two.sided&quot;</span>))</a></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 44.58577
##               d = 0.6
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<p>Or we could ask, what is the power of our test with 51 observations in each group, d = 0.6, and α = 0.05:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" title="1"><span class="kw">pwr.t.test</span>(<span class="dt">n =</span> <span class="dv">51</span>, <span class="dt">d =</span> <span class="fl">0.6</span>, <span class="dt">sig.level =</span> <span class="fl">0.05</span>, <span class="dt">type =</span> <span class="kw">c</span>(<span class="st">&quot;two.sample&quot;</span>), </a>
<a class="sourceLine" id="cb81-2" title="2">    <span class="dt">alternative =</span> <span class="kw">c</span>(<span class="st">&quot;two.sided&quot;</span>))</a></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 51
##               d = 0.6
##       sig.level = 0.05
##           power = 0.850985
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
</div>
<div id="p-values-stopping-rules-and-p-hacking" class="section level4">
<h4><span class="header-section-number">6.3.3.3</span> P-values, stopping rules and p-hacking</h4>
<p>From my experience, students tend to place a lot of weight on p-values when interpreting their research findings. It is therefore important to note some points that hopefully help to put the meaning of a “significant” vs. “insignificant” test result into perspective.</p>
<p><strong>Significant result</strong></p>
<ul>
<li>Even if the probability of the effect being a chance result is small (e.g., less than .05) it doesn’t necessarily mean that the effect is important.</li>
<li>Very small and unimportant effects can turn out to be statistically significant if the sample size is large enough.</li>
</ul>
<p><strong>Insignificant result</strong></p>
<ul>
<li>If the probability of the effect occurring by chance is large (greater than .05), the alternative hypothesis is rejected. However, this does not mean that the null hypothesis is true.</li>
<li>Although an effect might not be large enough to be anything other than a chance finding, it doesn’t mean that the effect is zero.</li>
<li>In fact, two random samples will always have slightly different means that would deemed to be statistically significant if the samples were large enough.</li>
</ul>
<p>Thus, you should not base your research conclusion on p-values alone!</p>
<p>It is also crucial to <strong>determine the sample size before you run the experiment</strong> or before you start your analysis. Why? Consider the following example:</p>
<ul>
<li>You run an experiment</li>
<li>After each respondent you analyze the data and look at the mean difference between the two groups with a t-test</li>
<li>You stop when you have a significant effect</li>
</ul>
<p>This is called p-hacking and should be avoided at all costs. Assuming that both groups come from the same population (i.e., there is <strong>no difference</strong> in the means): What is the likelihood that the result will be significant at some point? In other words, what is the likelihood that you will draw the wrong conclusion from your data that there is an effect, while there is none? This is shown in the following graph using simulated data - the color red indicates significant test results that arise although there is no effect (i.e., false positives).</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-42"></span>
<img src="_main_files/figure-html/unnamed-chunk-42-1.png" alt="p-hacking (red indicates false positives)" width="672" />
<p class="caption">
Figure 6.1: p-hacking (red indicates false positives)
</p>
</div>

</div>
</div>
</div>
<div id="comparing-several-means" class="section level2">
<h2><span class="header-section-number">6.4</span> Comparing several means</h2>
<div id="introduction-1" class="section level3">
<h3><span class="header-section-number">6.4.1</span> Introduction</h3>
</div>
<div id="decomposing-variance" class="section level3">
<h3><span class="header-section-number">6.4.2</span> Decomposing variance</h3>
<div id="total-sum-of-squares" class="section level4">
<h4><span class="header-section-number">6.4.2.1</span> Total sum of squares</h4>
</div>
<div id="model-sum-of-squares" class="section level4">
<h4><span class="header-section-number">6.4.2.2</span> Model sum of squares</h4>
</div>
<div id="residual-sum-of-squares" class="section level4">
<h4><span class="header-section-number">6.4.2.3</span> Residual sum of squares</h4>
</div>
<div id="effect-strength" class="section level4">
<h4><span class="header-section-number">6.4.2.4</span> Effect strength</h4>
</div>
<div id="test-of-significance" class="section level4">
<h4><span class="header-section-number">6.4.2.5</span> Test of significance</h4>
</div>
</div>
<div id="one-way-anova" class="section level3">
<h3><span class="header-section-number">6.4.3</span> One-way ANOVA</h3>
<div id="basic-anova" class="section level4">
<h4><span class="header-section-number">6.4.3.1</span> Basic ANOVA</h4>
<div id="independence-of-observations" class="section level5 unnumbered">
<h5>Independence of observations</h5>
</div>
<div id="distributional-assumptions" class="section level5 unnumbered">
<h5>Distributional assumptions</h5>
</div>
<div id="homogeneity-of-variance" class="section level5 unnumbered">
<h5>Homogeneity of variance</h5>
</div>
</div>
<div id="post-hoc-tests" class="section level4">
<h4><span class="header-section-number">6.4.3.2</span> Post-hoc tests</h4>
<div id="bonferroni" class="section level5">
<h5><span class="header-section-number">6.4.3.2.1</span> Bonferroni</h5>
</div>
<div id="tukeys-hsd" class="section level5">
<h5><span class="header-section-number">6.4.3.2.2</span> Tukey’s HSD</h5>
</div>
</div>
</div>
<div id="summary-3" class="section level3">
<h3><span class="header-section-number">6.4.4</span> Summary</h3>

</div>
</div>
<div id="non-parametric-tests" class="section level2">
<h2><span class="header-section-number">6.5</span> Non-parametric tests</h2>
<div id="mann-whitney-u-test-a.k.a.-wilcoxon-rank-sum-test" class="section level3">
<h3><span class="header-section-number">6.5.1</span> Mann-Whitney U Test (a.k.a. Wilcoxon rank-sum test)</h3>
</div>
<div id="wilcoxon-signed-rank-test" class="section level3">
<h3><span class="header-section-number">6.5.2</span> Wilcoxon signed-rank test</h3>
</div>
<div id="kruskal-wallis-test" class="section level3">
<h3><span class="header-section-number">6.5.3</span> Kruskal-Wallis test</h3>
</div>
</div>
<div id="categorical-data" class="section level2">
<h2><span class="header-section-number">6.6</span> Categorical data</h2>
<div id="confidence-intervals-for-proportions" class="section level3">
<h3><span class="header-section-number">6.6.1</span> Confidence intervals for proportions</h3>
</div>
<div id="chi-square-test" class="section level3">
<h3><span class="header-section-number">6.6.2</span> Chi-square test</h3>
</div>
<div id="sample-size-1" class="section level3">
<h3><span class="header-section-number">6.6.3</span> Sample size</h3>
</div>
<div id="summary-4" class="section level3">
<h3><span class="header-section-number">6.6.4</span> Summary</h3>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-to-statistical-inference.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
