<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>9 R Markdown &amp; assignments | Marketing Research Design &amp; Analysis 2020</title>
  <meta name="description" content="An Introduction to Data Analytics Using R" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="9 R Markdown &amp; assignments | Marketing Research Design &amp; Analysis 2020" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An Introduction to Data Analytics Using R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="9 R Markdown &amp; assignments | Marketing Research Design &amp; Analysis 2020" />
  
  <meta name="twitter:description" content="An Introduction to Data Analytics Using R" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="prev" href="exploratory-factor-analysis.html"/>
<link rel="next" href="survey-design-analysis.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">MRDA 2020</a></strong></li>

<li class="divider"></li>
<li class="part"><span><b>I Course outline</b></span></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#course-motivation"><i class="fa fa-check"></i>Course motivation</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#course-structure"><i class="fa fa-check"></i>Course structure</a><ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#schedule"><i class="fa fa-check"></i>Schedule</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#grading"><i class="fa fa-check"></i>Grading</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#course-materials"><i class="fa fa-check"></i>Course materials</a><ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#main-reference"><i class="fa fa-check"></i>Main reference</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#further-readings"><i class="fa fa-check"></i>Further readings</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#discussion-forum"><i class="fa fa-check"></i>Discussion forum</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#datacamp"><i class="fa fa-check"></i>DataCamp</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#other-web-resources"><i class="fa fa-check"></i>Other web-resources</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#contact"><i class="fa fa-check"></i>Contact</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Lecture notes</b></span></li>
<li class="chapter" data-level="1" data-path="preliminaries.html"><a href="preliminaries.html"><i class="fa fa-check"></i><b>1</b> Preliminaries</a><ul>
<li class="chapter" data-level="1.1" data-path="preliminaries.html"><a href="preliminaries.html#marketing-foundations-recap"><i class="fa fa-check"></i><b>1.1</b> Marketing foundations (recap)</a></li>
<li class="chapter" data-level="1.2" data-path="preliminaries.html"><a href="preliminaries.html#the-research-process"><i class="fa fa-check"></i><b>1.2</b> The research process</a><ul>
<li class="chapter" data-level="1.2.1" data-path="preliminaries.html"><a href="preliminaries.html#research-question-and-hypothesis"><i class="fa fa-check"></i><b>1.2.1</b> Research question and hypothesis</a></li>
<li class="chapter" data-level="1.2.2" data-path="preliminaries.html"><a href="preliminaries.html#choosing-a-research-design"><i class="fa fa-check"></i><b>1.2.2</b> Choosing a research design</a></li>
<li class="chapter" data-level="1.2.3" data-path="preliminaries.html"><a href="preliminaries.html#collecting-data"><i class="fa fa-check"></i><b>1.2.3</b> Collecting data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="preliminaries.html"><a href="preliminaries.html#learning-check"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="preliminaries.html"><a href="preliminaries.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html"><i class="fa fa-check"></i><b>2</b> Getting started with R</a><ul>
<li class="chapter" data-level="2.1" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#how-to-download-and-install-r-and-rstudio"><i class="fa fa-check"></i><b>2.1</b> How to download and install R and RStudio</a></li>
<li class="chapter" data-level="2.2" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#the-r-studio-interface"><i class="fa fa-check"></i><b>2.2</b> The R Studio interface</a></li>
<li class="chapter" data-level="2.3" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#functions"><i class="fa fa-check"></i><b>2.3</b> Functions</a></li>
<li class="chapter" data-level="2.4" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#packages"><i class="fa fa-check"></i><b>2.4</b> Packages</a></li>
<li class="chapter" data-level="2.5" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#a-typical-r-session"><i class="fa fa-check"></i><b>2.5</b> A typical R session</a></li>
<li class="chapter" data-level="2.6" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html#getting-help"><i class="fa fa-check"></i><b>2.6</b> Getting help</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-handling.html"><a href="data-handling.html"><i class="fa fa-check"></i><b>3</b> Data handling</a><ul>
<li class="chapter" data-level="3.1" data-path="data-handling.html"><a href="data-handling.html#basic-data-handling"><i class="fa fa-check"></i><b>3.1</b> Basic data handling</a><ul>
<li class="chapter" data-level="3.1.1" data-path="data-handling.html"><a href="data-handling.html#creating-objects"><i class="fa fa-check"></i><b>3.1.1</b> Creating objects</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-handling.html"><a href="data-handling.html#data-types"><i class="fa fa-check"></i><b>3.1.2</b> Data types</a></li>
<li class="chapter" data-level="3.1.3" data-path="data-handling.html"><a href="data-handling.html#data-structures"><i class="fa fa-check"></i><b>3.1.3</b> Data structures</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-handling.html"><a href="data-handling.html#data-import-and-export"><i class="fa fa-check"></i><b>3.2</b> Data import and export</a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-handling.html"><a href="data-handling.html#getting-data-for-this-course"><i class="fa fa-check"></i><b>3.2.1</b> Getting data for this course</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-handling.html"><a href="data-handling.html#import-data-created-by-other-software-packages"><i class="fa fa-check"></i><b>3.2.2</b> Import data created by other software packages</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-handling.html"><a href="data-handling.html#import-data-from-qualtrics"><i class="fa fa-check"></i><b>3.2.3</b> Import data from Qualtrics</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-handling.html"><a href="data-handling.html#export-data"><i class="fa fa-check"></i><b>3.2.4</b> Export data</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-handling.html"><a href="data-handling.html#import-data-from-the-web"><i class="fa fa-check"></i><b>3.2.5</b> Import data from the Web</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-handling.html"><a href="data-handling.html#learning-check-1"><i class="fa fa-check"></i>Learning check</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="summarizing-data.html"><a href="summarizing-data.html"><i class="fa fa-check"></i><b>4</b> Summarizing data</a><ul>
<li class="chapter" data-level="4.1" data-path="summarizing-data.html"><a href="summarizing-data.html#summary-statistics"><i class="fa fa-check"></i><b>4.1</b> Summary statistics</a><ul>
<li class="chapter" data-level="4.1.1" data-path="summarizing-data.html"><a href="summarizing-data.html#categorical-variables"><i class="fa fa-check"></i><b>4.1.1</b> Categorical variables</a></li>
<li class="chapter" data-level="4.1.2" data-path="summarizing-data.html"><a href="summarizing-data.html#continuous-variables"><i class="fa fa-check"></i><b>4.1.2</b> Continuous variables</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="summarizing-data.html"><a href="summarizing-data.html#data-visualization"><i class="fa fa-check"></i><b>4.2</b> Data visualization</a><ul>
<li class="chapter" data-level="4.2.1" data-path="summarizing-data.html"><a href="summarizing-data.html#categorical-variables-1"><i class="fa fa-check"></i><b>4.2.1</b> Categorical variables</a></li>
<li class="chapter" data-level="4.2.2" data-path="summarizing-data.html"><a href="summarizing-data.html#continuous-variables-1"><i class="fa fa-check"></i><b>4.2.2</b> Continuous variables</a></li>
<li class="chapter" data-level="4.2.3" data-path="summarizing-data.html"><a href="summarizing-data.html#saving-plots"><i class="fa fa-check"></i><b>4.2.3</b> Saving plots</a></li>
<li class="chapter" data-level="4.2.4" data-path="summarizing-data.html"><a href="summarizing-data.html#ggplot-extensions"><i class="fa fa-check"></i><b>4.2.4</b> ggplot extensions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="summarizing-data.html"><a href="summarizing-data.html#learning-check-2"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="summarizing-data.html"><a href="summarizing-data.html#references-1"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i><b>5</b> Statistical inference</a><ul>
<li class="chapter" data-level="5.1" data-path="statistical-inference.html"><a href="statistical-inference.html#if-we-knew-it-all"><i class="fa fa-check"></i><b>5.1</b> If we knew it all</a><ul>
<li class="chapter" data-level="5.1.1" data-path="statistical-inference.html"><a href="statistical-inference.html#sampling-from-a-known-population"><i class="fa fa-check"></i><b>5.1.1</b> Sampling from a known population</a></li>
<li class="chapter" data-level="5.1.2" data-path="statistical-inference.html"><a href="statistical-inference.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>5.1.2</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="statistical-inference.html"><a href="statistical-inference.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>5.2</b> The Central Limit Theorem</a></li>
<li class="chapter" data-level="5.3" data-path="statistical-inference.html"><a href="statistical-inference.html#using-what-we-actually-know"><i class="fa fa-check"></i><b>5.3</b> Using what we actually know</a></li>
<li class="chapter" data-level="5.4" data-path="statistical-inference.html"><a href="statistical-inference.html#confidence-intervals-for-the-sample-mean"><i class="fa fa-check"></i><b>5.4</b> Confidence Intervals for the Sample Mean</a></li>
<li class="chapter" data-level="" data-path="statistical-inference.html"><a href="statistical-inference.html#learning-check-3"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="statistical-inference.html"><a href="statistical-inference.html#references-2"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>6</b> Hypothesis testing</a><ul>
<li class="chapter" data-level="6.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction-1"><i class="fa fa-check"></i><b>6.1</b> Introduction</a><ul>
<li class="chapter" data-level="6.1.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#the-null-hypothesis"><i class="fa fa-check"></i><b>6.1.1</b> The null hypothesis</a></li>
<li class="chapter" data-level="6.1.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#statistical-inference-on-a-sample"><i class="fa fa-check"></i><b>6.1.2</b> Statistical inference on a sample</a></li>
<li class="chapter" data-level="6.1.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#choosing-the-right-test"><i class="fa fa-check"></i><b>6.1.3</b> Choosing the right test</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-sample-t-test"><i class="fa fa-check"></i><b>6.2</b> One sample t-test</a></li>
<li class="chapter" data-level="6.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#comparing-two-means"><i class="fa fa-check"></i><b>6.3</b> Comparing two means</a><ul>
<li class="chapter" data-level="6.3.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#independent-means-t-test"><i class="fa fa-check"></i><b>6.3.1</b> Independent-means t-test</a></li>
<li class="chapter" data-level="6.3.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#dependent-means-t-test"><i class="fa fa-check"></i><b>6.3.2</b> Dependent-means t-test</a></li>
<li class="chapter" data-level="6.3.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#further-considerations"><i class="fa fa-check"></i><b>6.3.3</b> Further considerations</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#comparing-several-means"><i class="fa fa-check"></i><b>6.4</b> Comparing several means</a><ul>
<li class="chapter" data-level="6.4.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#introduction-2"><i class="fa fa-check"></i><b>6.4.1</b> Introduction</a></li>
<li class="chapter" data-level="6.4.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#decomposing-variance"><i class="fa fa-check"></i><b>6.4.2</b> Decomposing variance</a></li>
<li class="chapter" data-level="6.4.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#one-way-anova"><i class="fa fa-check"></i><b>6.4.3</b> One-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#non-parametric-tests"><i class="fa fa-check"></i><b>6.5</b> Non-parametric tests</a><ul>
<li class="chapter" data-level="6.5.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#mann-whitney-u-test-a.k.a.-wilcoxon-rank-sum-test"><i class="fa fa-check"></i><b>6.5.1</b> Mann-Whitney U Test (a.k.a. Wilcoxon rank-sum test)</a></li>
<li class="chapter" data-level="6.5.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>6.5.2</b> Wilcoxon signed-rank test</a></li>
<li class="chapter" data-level="6.5.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#kruskal-wallis-test"><i class="fa fa-check"></i><b>6.5.3</b> Kruskal-Wallis test</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#categorical-data"><i class="fa fa-check"></i><b>6.6</b> Categorical data</a><ul>
<li class="chapter" data-level="6.6.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#confidence-intervals-for-proportions"><i class="fa fa-check"></i><b>6.6.1</b> Confidence intervals for proportions</a></li>
<li class="chapter" data-level="6.6.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#chi-square-test"><i class="fa fa-check"></i><b>6.6.2</b> Chi-square test</a></li>
<li class="chapter" data-level="6.6.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#sample-size-1"><i class="fa fa-check"></i><b>6.6.3</b> Sample size</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#learning-check-4"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#references-3"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>7</b> Regression</a><ul>
<li class="chapter" data-level="7.1" data-path="regression.html"><a href="regression.html#correlation"><i class="fa fa-check"></i><b>7.1</b> Correlation</a><ul>
<li class="chapter" data-level="7.1.1" data-path="regression.html"><a href="regression.html#correlation-coefficient"><i class="fa fa-check"></i><b>7.1.1</b> Correlation coefficient</a></li>
<li class="chapter" data-level="7.1.2" data-path="regression.html"><a href="regression.html#significance-testing"><i class="fa fa-check"></i><b>7.1.2</b> Significance testing</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="regression.html"><a href="regression.html#regression-1"><i class="fa fa-check"></i><b>7.2</b> Regression</a><ul>
<li class="chapter" data-level="7.2.1" data-path="regression.html"><a href="regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>7.2.1</b> Simple linear regression</a></li>
<li class="chapter" data-level="7.2.2" data-path="regression.html"><a href="regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>7.2.2</b> Multiple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="regression.html"><a href="regression.html#potential-problems"><i class="fa fa-check"></i><b>7.3</b> Potential problems</a><ul>
<li class="chapter" data-level="7.3.1" data-path="regression.html"><a href="regression.html#outliers"><i class="fa fa-check"></i><b>7.3.1</b> Outliers</a></li>
<li class="chapter" data-level="7.3.2" data-path="regression.html"><a href="regression.html#influential-observations"><i class="fa fa-check"></i><b>7.3.2</b> Influential observations</a></li>
<li class="chapter" data-level="7.3.3" data-path="regression.html"><a href="regression.html#non-linearity"><i class="fa fa-check"></i><b>7.3.3</b> Non-linearity</a></li>
<li class="chapter" data-level="7.3.4" data-path="regression.html"><a href="regression.html#non-constant-error-variance"><i class="fa fa-check"></i><b>7.3.4</b> Non-constant error variance</a></li>
<li class="chapter" data-level="7.3.5" data-path="regression.html"><a href="regression.html#non-normally-distributed-errors"><i class="fa fa-check"></i><b>7.3.5</b> Non-normally distributed errors</a></li>
<li class="chapter" data-level="7.3.6" data-path="regression.html"><a href="regression.html#correlation-of-errors"><i class="fa fa-check"></i><b>7.3.6</b> Correlation of errors</a></li>
<li class="chapter" data-level="7.3.7" data-path="regression.html"><a href="regression.html#collinearity"><i class="fa fa-check"></i><b>7.3.7</b> Collinearity</a></li>
<li class="chapter" data-level="7.3.8" data-path="regression.html"><a href="regression.html#omitted-variables"><i class="fa fa-check"></i><b>7.3.8</b> Omitted Variables</a></li>
<li class="chapter" data-level="7.3.9" data-path="regression.html"><a href="regression.html#overfitting"><i class="fa fa-check"></i><b>7.3.9</b> Overfitting</a></li>
<li class="chapter" data-level="7.3.10" data-path="regression.html"><a href="regression.html#variable-selection"><i class="fa fa-check"></i><b>7.3.10</b> Variable selection</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="regression.html"><a href="regression.html#categorical-predictors"><i class="fa fa-check"></i><b>7.4</b> Categorical predictors</a><ul>
<li class="chapter" data-level="7.4.1" data-path="regression.html"><a href="regression.html#two-categories"><i class="fa fa-check"></i><b>7.4.1</b> Two categories</a></li>
<li class="chapter" data-level="7.4.2" data-path="regression.html"><a href="regression.html#more-than-two-categories"><i class="fa fa-check"></i><b>7.4.2</b> More than two categories</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="regression.html"><a href="regression.html#extensions-of-the-linear-model"><i class="fa fa-check"></i><b>7.5</b> Extensions of the linear model</a><ul>
<li class="chapter" data-level="7.5.1" data-path="regression.html"><a href="regression.html#interaction-effects"><i class="fa fa-check"></i><b>7.5.1</b> Interaction effects</a></li>
<li class="chapter" data-level="7.5.2" data-path="regression.html"><a href="regression.html#non-linear-relationships"><i class="fa fa-check"></i><b>7.5.2</b> Non-linear relationships</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="regression.html"><a href="regression.html#logistic-regression"><i class="fa fa-check"></i><b>7.6</b> Logistic regression</a><ul>
<li class="chapter" data-level="7.6.1" data-path="regression.html"><a href="regression.html#motivation-and-intuition"><i class="fa fa-check"></i><b>7.6.1</b> Motivation and intuition</a></li>
<li class="chapter" data-level="7.6.2" data-path="regression.html"><a href="regression.html#technical-details-of-the-model"><i class="fa fa-check"></i><b>7.6.2</b> Technical details of the model</a></li>
<li class="chapter" data-level="7.6.3" data-path="regression.html"><a href="regression.html#estimation-in-r"><i class="fa fa-check"></i><b>7.6.3</b> Estimation in R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#learning-check-5"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#references-4"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html"><i class="fa fa-check"></i><b>8</b> Exploratory factor analysis</a><ul>
<li class="chapter" data-level="8.1" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#introduction-3"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#steps-in-factor-analysis"><i class="fa fa-check"></i><b>8.2</b> Steps in factor analysis</a><ul>
<li class="chapter" data-level="8.2.1" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#are-the-assumptions-satisfied"><i class="fa fa-check"></i><b>8.2.1</b> Are the assumptions satisfied?</a></li>
<li class="chapter" data-level="8.2.2" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#deriving-factors"><i class="fa fa-check"></i><b>8.2.2</b> Deriving factors</a></li>
<li class="chapter" data-level="8.2.3" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#factor-interpretation"><i class="fa fa-check"></i><b>8.2.3</b> Factor interpretation</a></li>
<li class="chapter" data-level="8.2.4" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#creating-new-variables"><i class="fa fa-check"></i><b>8.2.4</b> Creating new variables</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#reliability-analysis"><i class="fa fa-check"></i><b>8.3</b> Reliability analysis</a></li>
<li class="chapter" data-level="" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#learning-check-6"><i class="fa fa-check"></i>Learning check</a></li>
<li class="chapter" data-level="" data-path="exploratory-factor-analysis.html"><a href="exploratory-factor-analysis.html#references-5"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="part"><span><b>III Assignments</b></span></li>
<li class="chapter" data-level="9" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html"><i class="fa fa-check"></i><b>9</b> R Markdown &amp; assignments</a><ul>
<li class="chapter" data-level="9.1" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#introduction-to-r-markdown"><i class="fa fa-check"></i><b>9.1</b> Introduction to R Markdown</a><ul>
<li class="chapter" data-level="" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#creating-a-new-r-markdown-document"><i class="fa fa-check"></i>Creating a new R Markdown document</a></li>
<li class="chapter" data-level="" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#text-and-equations"><i class="fa fa-check"></i>Text and Equations</a></li>
<li class="chapter" data-level="" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#r-code"><i class="fa fa-check"></i>R-Code</a></li>
<li class="chapter" data-level="" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#latex-math"><i class="fa fa-check"></i>LaTeX Math</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#solution-assignment-2"><i class="fa fa-check"></i><b>9.2</b> Solution assignment 2</a></li>
<li class="chapter" data-level="9.3" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#solution-assignment-3"><i class="fa fa-check"></i><b>9.3</b> Solution assignment 3</a></li>
<li class="chapter" data-level="9.4" data-path="r-markdown-assignments.html"><a href="r-markdown-assignments.html#solution-assignment-4"><i class="fa fa-check"></i><b>9.4</b> Solution assignment 4</a></li>
</ul></li>
<li class="part"><span><b>IV Group project</b></span></li>
<li class="chapter" data-level="10" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html"><i class="fa fa-check"></i><b>10</b> Survey design &amp; analysis</a><ul>
<li class="chapter" data-level="10.1" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#your-tasks"><i class="fa fa-check"></i><b>10.1</b> Your tasks</a><ul>
<li class="chapter" data-level="10.1.1" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#topics-for-the-group-project"><i class="fa fa-check"></i><b>10.1.1</b> Topics for the group project</a></li>
<li class="chapter" data-level="10.1.2" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#guidelines"><i class="fa fa-check"></i><b>10.1.2</b> Guidelines</a></li>
<li class="chapter" data-level="10.1.3" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#timeline"><i class="fa fa-check"></i><b>10.1.3</b> Timeline</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#part-1-before-collecting-data"><i class="fa fa-check"></i><b>10.2</b> Part 1: Before collecting data</a><ul>
<li class="chapter" data-level="10.2.1" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#research-design"><i class="fa fa-check"></i><b>10.2.1</b> Research design</a></li>
<li class="chapter" data-level="10.2.2" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#survey-method"><i class="fa fa-check"></i><b>10.2.2</b> Survey method</a></li>
<li class="chapter" data-level="10.2.3" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#questionnaire"><i class="fa fa-check"></i><b>10.2.3</b> Questionnaire</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#part-2-collecting-data-and-analysis"><i class="fa fa-check"></i><b>10.3</b> Part 2: Collecting data and analysis</a><ul>
<li class="chapter" data-level="10.3.1" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#collecting-data-1"><i class="fa fa-check"></i><b>10.3.1</b> Collecting data</a></li>
<li class="chapter" data-level="10.3.2" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#data-analysis"><i class="fa fa-check"></i><b>10.3.2</b> Data analysis</a></li>
<li class="chapter" data-level="10.3.3" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#reporting"><i class="fa fa-check"></i><b>10.3.3</b> Reporting</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#frequently-asked-questions"><i class="fa fa-check"></i><b>10.4</b> Frequently asked questions</a><ul>
<li class="chapter" data-level="10.4.1" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#multiple-answers-stored-in-one-cell-in-csv"><i class="fa fa-check"></i><b>10.4.1</b> Multiple answers stored in one cell in CSV</a></li>
<li class="chapter" data-level="10.4.2" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#labels-for-numeric-values-in-csv-output"><i class="fa fa-check"></i><b>10.4.2</b> Labels for numeric values in CSV output</a></li>
<li class="chapter" data-level="10.4.3" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#bar-chart-for-multiple-choice-question-with-multiple-answers"><i class="fa fa-check"></i><b>10.4.3</b> Bar chart for multiple choice question with multiple answers</a></li>
<li class="chapter" data-level="10.4.4" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#how-to-create-a-radar-plot"><i class="fa fa-check"></i><b>10.4.4</b> How to create a radar plot?</a></li>
<li class="chapter" data-level="10.4.5" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#vertical-likert-line-chart"><i class="fa fa-check"></i><b>10.4.5</b> Vertical Likert line chart</a></li>
<li class="chapter" data-level="10.4.6" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#diverging-stacked-barchart"><i class="fa fa-check"></i><b>10.4.6</b> Diverging stacked barchart</a></li>
<li class="chapter" data-level="10.4.7" data-path="survey-design-analysis.html"><a href="survey-design-analysis.html#collapserecode-categories"><i class="fa fa-check"></i><b>10.4.7</b> Collapse/recode categories</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Marketing Research Design &amp; Analysis 2020</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="r-markdown-assignments" class="section level1">
<h1><span class="header-section-number">9</span> R Markdown &amp; assignments</h1>
<div id="introduction-to-r-markdown" class="section level2">
<h2><span class="header-section-number">9.1</span> Introduction to R Markdown</h2>
<div class="infobox download">
<p><a href="./Code/example_markdown.Rmd">You can download the example markdown file here</a></p>
</div>
<p>This page will guide you through creating and editing R Markdown documents. This is a useful tool for reporting your analysis (e.g. for homework assignments). Of course, there is also <a href="https://www.rstudio.org/links/r_markdown_cheat_sheet">a cheat sheet for R-Markdown</a> and <a href="https://bookdown.org/yihui/rmarkdown/">this book</a> contains a comprehensive discussion of the format.</p>
<p>The following video contains a short introduction to the R Markdown format.</p>
<br>
<div align="center">
<iframe width="560" height="315" src="https://www.youtube.com/embed/o8FdyMAR-g4" frameborder="0" allowfullscreen>
</iframe>
</div>
<p><br></p>
<div id="creating-a-new-r-markdown-document" class="section level3 unnumbered">
<h3>Creating a new R Markdown document</h3>
<p>In addition to the video, the following text contains a short description of the most important formatting options.</p>
<p>Let’s start to go through the steps of creating and .Rmd file and outputting the content to an HTML file.</p>
<ol start="0" style="list-style-type: decimal">
<li><p>If an R-Markdown file was provided to you, open it with R-Studio and skip to <a href="#step4">step 4</a> after adding your answers.</p></li>
<li><p>Open R-Studio</p></li>
<li><p>Create a new R-Markdown document
<img src="rmdExplain/start.PNG" />
<img src="rmdExplain/openDoc.PNG" />
<img src="rmdExplain/enterName.PNG" />
<img src="rmdExplain/template.PNG" /></p></li>
<li><p>Save with appropriate name
<img src="rmdExplain/saving.PNG" /></p>
<p>3.1. Add your answers</p>
<p>3.2. Save again</p></li>
</ol>
<p><a name="step4"></a></p>
<ol start="4" style="list-style-type: decimal">
<li><p>“Knit” to HTML
<img src="rmdExplain/knit.PNG" /></p></li>
<li><p>Hand in appropriate file (ending in <code>.html</code>) on learn@WU
<img src="rmdExplain/handin.PNG" /></p></li>
</ol>
</div>
<div id="text-and-equations" class="section level3 unnumbered">
<h3>Text and Equations</h3>
<p>R-Markdown documents are plain text files that include both text and R-code. Using RStudio they can be converted (‘knitted’) to HTML or PDF files that include both the text and the results of the R-code. In fact this website is written using R-Markdown and RStudio. In order for RStudio to be able to interpret the document you have to use certain characters or combinations of characters when formatting text and including R-code to be evaluated. By default the document starts with the options for the text part. You can change the title, date, author and a few more advanced options.</p>
<div class="figure">
<img src="rmdExplain/rmdHead.PNG" alt="" />
<p class="caption">First lines of an R-Markdown document</p>
</div>
<p>The default is text mode, meaning that lines in an Rmd document will be interpreted as text, unless specified otherwise.</p>
<div id="headings" class="section level4 unnumbered">
<h4>Headings</h4>
<p>Usually you want to include some kind of heading to structure your text. A heading is created using <code>#</code> signs. A single <code>#</code> creates a first level heading, two <code>##</code> a second level and so on.</p>
<p><img src="rmdExplain/headings.PNG" /></p>
<p>It is important to note here that the <code>#</code> symbol means something different within the code chunks as opposed to outside of them. If you continue to put a <code>#</code> in front of all your regular text, it will all be interpreted as a first level heading, making your text very large.</p>
</div>
<div id="lists" class="section level4 unnumbered">
<h4>Lists</h4>
<p>Bullet point lists are created using <code>*</code>, <code>+</code> or <code>-</code>. Sub-items are created by indenting the item using 4 spaces or 2 tabs.</p>
<pre><code>* First Item
* Second Item
    + first sub-item
        - first sub-sub-item
    + second sub-item</code></pre>
<ul>
<li>First Item</li>
<li>Second Item
<ul>
<li>first sub-item
<ul>
<li>first sub-sub-item</li>
</ul></li>
<li>second sub-item</li>
</ul></li>
</ul>
<p>Ordered lists can be created using numbers and letters. If you need sub-sub-items use <code>A)</code> instead of <code>A.</code> on the third level.</p>
<pre><code>1. First item
    a. first sub-item
        A) first sub-sub-item 
     b. second sub-item
2. Second item</code></pre>
<ol style="list-style-type: decimal">
<li>First item
<ol style="list-style-type: lower-alpha">
<li>first sub-item
<ol style="list-style-type: upper-alpha">
<li>first sub-sub-item</li>
</ol></li>
<li>second sub-item</li>
</ol></li>
<li>Second item</li>
</ol>
</div>
<div id="text-formatting" class="section level4 unnumbered">
<h4>Text formatting</h4>
<p>Text can be formatted in <em>italics</em> (<code>*italics*</code>) or <strong>bold</strong> (<code>**bold**</code>). In addition, you can ad block quotes with <code>&gt;</code></p>
<pre><code>&gt; Lorem ipsum dolor amet chillwave lomo ramps, four loko green juice messenger bag raclette forage offal shoreditch chartreuse austin. Slow-carb poutine meggings swag blog, pop-up salvia taxidermy bushwick freegan ugh poke.</code></pre>
<blockquote>
<p>Lorem ipsum dolor amet chillwave lomo ramps, four loko green juice messenger bag raclette forage offal shoreditch chartreuse austin. Slow-carb poutine meggings swag blog, pop-up salvia taxidermy bushwick freegan ugh poke.</p>
</blockquote>
</div>
</div>
<div id="r-code" class="section level3 unnumbered">
<h3>R-Code</h3>
<p>R-code is contained in so called “chunks”. These chunks always start with three backticks and <code>r</code> in curly braces (<code></code>{r} <code>) and end with three backticks (</code> <code></code>). Optionally, parameters can be added after the <code>r</code> to influence how a chunk behaves. Additionally, you can also give each chunk a name. Note that these have to be <strong>unique</strong>, otherwise R will refuse to knit your document.</p>
<div id="global-and-chunk-options" class="section level4 unnumbered">
<h4>Global and chunk options</h4>
<p>The first chunk always looks as follows</p>
<p><code>{r setup, include = FALSE}     knitr::opts_chunk$set(echo = TRUE)</code></p>
<p>It is added to the document automatically and sets options for all the following chunks. These options can be overwritten on a per-chunk basis.</p>
<p>Keep <code>knitr::opts_chunk$set(echo = TRUE)</code> to print your code to the document you will hand in. Changing it to <code>knitr::opts_chunk$set(echo = FALSE)</code> will not print your code by default. This can be changed on a per-chunk basis.</p>
<p>```{r cars, echo = FALSE}
summary(cars)</p>
<p>plot(dist~speed, cars)
```</p>
<pre><code>##      speed           dist       
##  Min.   : 4.0   Min.   :  2.00  
##  1st Qu.:12.0   1st Qu.: 26.00  
##  Median :15.0   Median : 36.00  
##  Mean   :15.4   Mean   : 42.98  
##  3rd Qu.:19.0   3rd Qu.: 56.00  
##  Max.   :25.0   Max.   :120.00</code></pre>
<p><img src="_main_files/figure-html/cars-1.png" width="672" /></p>
<p>```{r cars2, echo = TRUE}
summary(cars)</p>
<p>plot(dist~speed, cars)
```</p>
<div class="sourceCode" id="cb767"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb767-1"><a href="r-markdown-assignments.html#cb767-1"></a><span class="kw">summary</span>(cars)</span></code></pre></div>
<pre><code>##      speed           dist       
##  Min.   : 4.0   Min.   :  2.00  
##  1st Qu.:12.0   1st Qu.: 26.00  
##  Median :15.0   Median : 36.00  
##  Mean   :15.4   Mean   : 42.98  
##  3rd Qu.:19.0   3rd Qu.: 56.00  
##  Max.   :25.0   Max.   :120.00</code></pre>
<div class="sourceCode" id="cb769"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb769-1"><a href="r-markdown-assignments.html#cb769-1"></a><span class="kw">plot</span>(dist <span class="op">~</span><span class="st"> </span>speed, cars)</span></code></pre></div>
<p><img src="_main_files/figure-html/cars2-1.png" width="672" /></p>
<p>A good overview of all available global/chunk options can be found <a href="https://yihui.name/knitr/options/#chunk_options">here</a>.</p>
</div>
</div>
<div id="latex-math" class="section level3 unnumbered">
<h3>LaTeX Math</h3>
<p>Writing well formatted mathematical formulas is done the same way as in <a href="https://en.wikipedia.org/wiki/LaTeX">LaTeX</a>. Math mode is started and ended using <code>$$</code>.</p>
<pre><code>$$
 f_1(\omega) = \frac{\sigma^2}{2 \pi},\ \omega \in[-\pi, \pi]
$$</code></pre>
<p><span class="math display">\[
 f_1(\omega) = \frac{\sigma^2}{2 \pi},\ \omega \in[-\pi, \pi]
\]</span></p>
<p>(for those interested this is the spectral density of <a href="https://en.wikipedia.org/wiki/White_noise">white noise</a>)</p>
<p>Including inline mathematical notation is done with a single <code>$</code> symbol.</p>
<pre><code>${2\over3}$ of my code is inline.
</code></pre>
<p><span class="math inline">\({2\over3}\)</span> of my code is inline.</p>
<p><br></p>
<p>Take a look at <a href="https://en.wikibooks.org/wiki/LaTeX/Mathematics#Symbols">this wikibook on Mathematics in LaTeX</a> and <a href="https://www.sharelatex.com/learn/List_of_Greek_letters_and_math_symbols">this list of Greek letters and mathematical symbols</a> if you are not familiar with LaTeX.</p>
<p>In order to write multi-line equations in the same math environment, use <code>\\</code> after every line. In order to insert a space use a single <code>\</code>. To render text inside a math environment use <code>\text{here is the text}</code>. In order to align equations start with <code>\begin{align}</code> and place an <code>&amp;</code> in each line at the point around which it should be aligned. Finally end with <code>\end{align}</code></p>
<pre><code>$$
\begin{align}
\text{First equation: }\ Y &amp;= X \beta + \epsilon_y,\ \forall X \\
\text{Second equation: }\ X &amp;= Z \gamma + \epsilon_x
\end{align}
$$</code></pre>
<p><span class="math display">\[
\begin{align}
\text{First equation: }\ Y &amp;= X \beta + \epsilon_y,\ \forall X \\
\text{Second equation: }\ X &amp;= Z \gamma + \epsilon_x
\end{align}
\]</span></p>
<div id="important-symbols" class="section level4 unnumbered">
<h4>Important symbols</h4>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Symbol
</th>
<th style="text-align:left;">
Code
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a^{2} + b\)</span>
</td>
<td style="text-align:left;">
<code>a^{2} + b</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a^{2+b}\)</span>
</td>
<td style="text-align:left;">
<code>a^{2+b}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a_{1}\)</span>
</td>
<td style="text-align:left;">
<code>a_{1}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a \leq b\)</span>
</td>
<td style="text-align:left;">
<code>a \leq b</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a \geq b\)</span>
</td>
<td style="text-align:left;">
<code>a \geq b</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a \neq b\)</span>
</td>
<td style="text-align:left;">
<code>a \neq b</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a \approx b\)</span>
</td>
<td style="text-align:left;">
<code>a \approx b</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a \in (0,1)\)</span>
</td>
<td style="text-align:left;">
<code>a \in (0,1)</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a \rightarrow \infty\)</span>
</td>
<td style="text-align:left;">
<code>a \rightarrow \infty</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\frac{a}{b}\)</span>
</td>
<td style="text-align:left;">
<code>\frac{a}{b}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\frac{\partial a}{\partial b}\)</span>
</td>
<td style="text-align:left;">
<code>\frac{\partial a}{\partial b}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\sqrt{a}\)</span>
</td>
<td style="text-align:left;">
<code>\sqrt{a}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\sum_{i = 1}^{b} a_i\)</span>
</td>
<td style="text-align:left;">
<code>\sum_{i = 1}^{b} a_i</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\int_{a}^b f(c) dc\)</span>
</td>
<td style="text-align:left;">
<code>\int_{a}^b f(c) dc</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\prod_{i = 0}^b a_i\)</span>
</td>
<td style="text-align:left;">
<code>\prod_{i = 0}^b a_i</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(c \left( \sum_{i=1}^b a_i \right)\)</span>
</td>
<td style="text-align:left;">
<code>c \left( \sum_{i=1}^b a_i \right)</code>
</td>
</tr>
</tbody>
</table>
<p>The <code>{}</code> after <code>_</code> and <code>^</code> are not strictly necessary if there is only one character in the sub-/superscript. However, in order to place multiple characters in the sub-/superscript they are necessary.
e.g.</p>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Symbol
</th>
<th style="text-align:left;">
Code
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a^b = a^{b}\)</span>
</td>
<td style="text-align:left;">
<code>a^b = a^{b}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(a^b+c \neq a^{b+c}\)</span>
</td>
<td style="text-align:left;">
<code>a^b+c \neq a^{b+c}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\sum_i a_i = \sum_{i} a_{i}\)</span>
</td>
<td style="text-align:left;">
<code>\sum_i a_i = \sum_{i} a_{i}</code>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(\sum_{i=1}^{b+c} a_i \neq \sum_i=1^b+c a_i\)</span>
</td>
<td style="text-align:left;">
<code>\sum_{i=1}^{b+c} a_i \neq \sum_i=1^b+c a_i</code>
</td>
</tr>
</tbody>
</table>
</div>
<div id="greek-letters" class="section level4 unnumbered">
<h4>Greek letters</h4>
<p><a href="https://en.wikipedia.org/wiki/Greek_alphabet#Letters">Greek letters</a> are preceded by a <code>\</code> followed by their name (<code>$\beta$</code> = <span class="math inline">\(\beta\)</span>). In order to capitalize them simply capitalize the first letter of the name (<code>$\Gamma$</code> = <span class="math inline">\(\Gamma\)</span>).</p>
</div>
</div>
</div>
<div id="solution-assignment-2" class="section level2">
<h2><span class="header-section-number">9.2</span> Solution assignment 2</h2>
<p>As a marketing manager at a video streaming service, you are interested in the effect of online advertising on the number of streams that a movie receives. To test the effect of online advertising on streams, you select a representative sample of 200 movies and randomly assign 100 movies to be included in an online advertising campaign. The other half of the sample serves as the control group. You run the experiment for one week and collect data regarding the number of streams for each movie from this period. Overall, the data set includes the following variables:</p>
<ul>
<li>movieID: unique movie ID</li>
<li>streams_sd: number of streams in SD-quality</li>
<li>streams_hd: number of streams in HD-quality</li>
<li>online_advertising: indicator whether a movie was included in the online advertising campaign (0 = no, 1 = yes)</li>
</ul>
<p>Apply appropriate statistical methods to answer the following questions:</p>
<ol style="list-style-type: decimal">
<li>Compute the 95% confidence interval for the mean number of streams for movies in SD and HD quality and provide an interpretation of the interval<br />
</li>
<li>Your historical data tells you that the movies in SD and HD quality received 2,600 and 1,700 streams in the previous week, respectively. Please test if the number of streams that the movies received (irrespective of whether they were included in the experiment or not) in the week of the experiment is significantly different from the previous week for SD and HD movies.<br />
</li>
<li>Is there a significant difference in streams between movies that were included in the online advertising campaign and those that were not included? (Please conduct the test for SD and HD movies and also compute the effect size Cohen’s d)</li>
<li>Is there a significant difference in streams between movies in HD and SD quality? (Please also compute the effect size Cohen’s d)</li>
<li>Assume that you plan to run an experiment with two groups to test two different advertising strategies. You randomly assign movies to the control and experimental conditions and your goal is to test if there is a significant difference between the groups regarding the number of streams that the movies receive. How many movies would you need to include in each group of your experiment if you assume the effect size to be 0.3 for a significance level of 0.05 and power of 0.8?</li>
</ol>
<p>When answering the questions, please remember to address the following points, where appropriate:</p>
<ul>
<li>Formulate the corresponding hypotheses and choose an appropriate statistical test</li>
<li>Provide the reason for your choice and discuss if the assumptions of the test are met</li>
<li>Convert the variables to the appropriate type (e.g., factor variables)</li>
<li>Create appropriate graphs to explore the data (e.g., boxplot, bar chart, histogram)</li>
<li>Provide appropriate descriptive statistics for the variables</li>
<li>Report and interpret the test results accurately (including confidence intervals)<br />
</li>
<li>Finally, don’t forget to report your research conclusion in an appropriate way</li>
</ul>
<p>When you are done with your analysis, click on “Knit to HTML” button above the code editor. This will create a HTML document of your results in the folder where the “assignment.Rmd” file is stored. Open this file in your Internet browser to see if the output is correct. If the output is correct, submit the HTML file via Learn@WU. The file name should be “assignment2_studendID_name.html”.</p>
<p><strong>Load and inspect data</strong></p>
<p>Let´s load the data first and inspect the contained variables:</p>
<div class="sourceCode" id="cb773"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb773-1"><a href="r-markdown-assignments.html#cb773-1"></a>movie_data &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;https://raw.githubusercontent.com/IMSMWU/MRDA2018/master/data/assignment2.dat&quot;</span>, </span>
<span id="cb773-2"><a href="r-markdown-assignments.html#cb773-2"></a>    <span class="dt">sep =</span> <span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>, <span class="dt">header =</span> <span class="ot">TRUE</span>)  <span class="co">#read in data</span></span>
<span id="cb773-3"><a href="r-markdown-assignments.html#cb773-3"></a><span class="kw">head</span>(movie_data)</span></code></pre></div>
<pre><code>##   movieID online_advertising streams_sd streams_hd
## 1       1                  0       2365       1432
## 2       2                  0       1752       2305
## 3       3                  0       1351       1197
## 4       4                  0       2495       1112
## 5       5                  0       3883       1364
## 6       6                  1       3933       1202</code></pre>
<div class="sourceCode" id="cb775"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb775-1"><a href="r-markdown-assignments.html#cb775-1"></a><span class="kw">str</span>(movie_data)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    200 obs. of  4 variables:
##  $ movieID           : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ online_advertising: int  0 0 0 0 0 1 1 1 0 1 ...
##  $ streams_sd        : int  2365 1752 1351 2495 3883 3933 3849 2770 1146 3033 ...
##  $ streams_hd        : int  1432 2305 1197 1112 1364 1202 1363 3502 2047 1104 ...</code></pre>
<p><strong>Load packages</strong></p>
<p>Next, we load the packages that we will be using to answer the questions:</p>
<div class="sourceCode" id="cb777"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb777-1"><a href="r-markdown-assignments.html#cb777-1"></a><span class="kw">library</span>(pastecs)</span>
<span id="cb777-2"><a href="r-markdown-assignments.html#cb777-2"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb777-3"><a href="r-markdown-assignments.html#cb777-3"></a><span class="kw">library</span>(psych)</span>
<span id="cb777-4"><a href="r-markdown-assignments.html#cb777-4"></a><span class="kw">library</span>(pwr)</span>
<span id="cb777-5"><a href="r-markdown-assignments.html#cb777-5"></a><span class="kw">library</span>(lsr)</span>
<span id="cb777-6"><a href="r-markdown-assignments.html#cb777-6"></a><span class="kw">library</span>(reshape2)</span>
<span id="cb777-7"><a href="r-markdown-assignments.html#cb777-7"></a><span class="kw">library</span>(ggstatsplot)</span>
<span id="cb777-8"><a href="r-markdown-assignments.html#cb777-8"></a><span class="kw">library</span>(Rmisc)</span></code></pre></div>
<p><strong>Question 1</strong></p>
<p>To compute the confidence intervals for SD and HD streams we will need three things: 1) the mean <span class="math inline">\(\bar x\)</span>, 2) the standard error (<span class="math inline">\(s \over \sqrt{n}\)</span>), and 3) the critical value for a t-distribution (<span class="math inline">\(t_{crit}\)</span>; we will use a t-distribution, because we are not sure of the variance in the population).</p>
<div class="sourceCode" id="cb778"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb778-1"><a href="r-markdown-assignments.html#cb778-1"></a><span class="co"># Calculate components of confidence interval</span></span>
<span id="cb778-2"><a href="r-markdown-assignments.html#cb778-2"></a><span class="co"># formula</span></span>
<span id="cb778-3"><a href="r-markdown-assignments.html#cb778-3"></a>mean_sd &lt;-<span class="st"> </span><span class="kw">mean</span>(movie_data<span class="op">$</span>streams_sd)</span>
<span id="cb778-4"><a href="r-markdown-assignments.html#cb778-4"></a>mean_hd &lt;-<span class="st"> </span><span class="kw">mean</span>(movie_data<span class="op">$</span>streams_hd)</span>
<span id="cb778-5"><a href="r-markdown-assignments.html#cb778-5"></a></span>
<span id="cb778-6"><a href="r-markdown-assignments.html#cb778-6"></a>sd_sd &lt;-<span class="st"> </span><span class="kw">sd</span>(movie_data<span class="op">$</span>streams_sd)</span>
<span id="cb778-7"><a href="r-markdown-assignments.html#cb778-7"></a>sd_hd &lt;-<span class="st"> </span><span class="kw">sd</span>(movie_data<span class="op">$</span>streams_hd)</span>
<span id="cb778-8"><a href="r-markdown-assignments.html#cb778-8"></a></span>
<span id="cb778-9"><a href="r-markdown-assignments.html#cb778-9"></a>n &lt;-<span class="st"> </span><span class="kw">nrow</span>(movie_data)</span>
<span id="cb778-10"><a href="r-markdown-assignments.html#cb778-10"></a>se_sd &lt;-<span class="st"> </span>sd_sd<span class="op">/</span><span class="kw">sqrt</span>(n)</span>
<span id="cb778-11"><a href="r-markdown-assignments.html#cb778-11"></a>se_hd &lt;-<span class="st"> </span>sd_hd<span class="op">/</span><span class="kw">sqrt</span>(n)</span>
<span id="cb778-12"><a href="r-markdown-assignments.html#cb778-12"></a></span>
<span id="cb778-13"><a href="r-markdown-assignments.html#cb778-13"></a>df &lt;-<span class="st"> </span>n <span class="op">-</span><span class="st"> </span><span class="dv">1</span></span>
<span id="cb778-14"><a href="r-markdown-assignments.html#cb778-14"></a>t_crit &lt;-<span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.975</span>, df)</span></code></pre></div>
<p>Now the confidence intervals for streams in SD and HD quality can be computed as:</p>
<div class="sourceCode" id="cb779"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb779-1"><a href="r-markdown-assignments.html#cb779-1"></a><span class="co"># Interval for SD movies</span></span>
<span id="cb779-2"><a href="r-markdown-assignments.html#cb779-2"></a>ci_lower_sd &lt;-<span class="st"> </span>mean_sd <span class="op">-</span><span class="st"> </span>t_crit <span class="op">*</span><span class="st"> </span>se_sd</span>
<span id="cb779-3"><a href="r-markdown-assignments.html#cb779-3"></a>ci_upper_sd &lt;-<span class="st"> </span>mean_sd <span class="op">+</span><span class="st"> </span>t_crit <span class="op">*</span><span class="st"> </span>se_sd</span>
<span id="cb779-4"><a href="r-markdown-assignments.html#cb779-4"></a></span>
<span id="cb779-5"><a href="r-markdown-assignments.html#cb779-5"></a><span class="co"># Interval for HD movies</span></span>
<span id="cb779-6"><a href="r-markdown-assignments.html#cb779-6"></a>ci_lower_hd &lt;-<span class="st"> </span>mean_hd <span class="op">-</span><span class="st"> </span>t_crit <span class="op">*</span><span class="st"> </span>se_hd</span>
<span id="cb779-7"><a href="r-markdown-assignments.html#cb779-7"></a>ci_upper_hd &lt;-<span class="st"> </span>mean_hd <span class="op">+</span><span class="st"> </span>t_crit <span class="op">*</span><span class="st"> </span>se_hd</span></code></pre></div>
<p>Hence, the CI for SD movies is given by:</p>
<div class="sourceCode" id="cb780"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb780-1"><a href="r-markdown-assignments.html#cb780-1"></a>ci_lower_sd</span></code></pre></div>
<pre><code>## [1] 2527.979</code></pre>
<div class="sourceCode" id="cb782"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb782-1"><a href="r-markdown-assignments.html#cb782-1"></a>ci_upper_sd</span></code></pre></div>
<pre><code>## [1] 2827.851</code></pre>
<p><span class="math inline">\(CI_{SD} = [2527.97,2827.85]\)</span></p>
<p>Similarly, the CI for HD movies is given by</p>
<div class="sourceCode" id="cb784"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb784-1"><a href="r-markdown-assignments.html#cb784-1"></a>ci_lower_hd</span></code></pre></div>
<pre><code>## [1] 1728.51</code></pre>
<div class="sourceCode" id="cb786"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb786-1"><a href="r-markdown-assignments.html#cb786-1"></a>ci_upper_hd</span></code></pre></div>
<pre><code>## [1] 1940.52</code></pre>
<p><span class="math inline">\(CI_{HD} = [1728.51,1940.52]\)</span></p>
<p>The intervals can be interpreted as follows: If we would take 100 samples, calculate the mean and confidence interval for each of them, then the true population mean would be included in 95% of these intervals.</p>
<p><strong>Question 2</strong></p>
<p>To find out whether our data for SD and HD streams differs significantly from the previous week (2600 for SD; 1700 for HD), we will conduct a one sample t-test. This is appropriate, because 1) our data is on an interval scale, and 2) the sampling distribution can be considered as normally distributed due to the fairly large sample size (n=200; see central limit theorem).</p>
<p>Our null hypothesis states that there is no difference between the quantity of SD/HD streams watched in the current week, compared to the previous week. Rejecting the null hypotheses/accepting the alternative hypothesis would mean that there indeed was a difference between the two weeks.</p>
<p>So for our SD streams we could formulate our hypothesis as follows:</p>
<p><span class="math display">\[H_0: \mu_0 = 2600 \\ H_1: \mu_0 \neq 2600 \]</span></p>
<p>The same approach can be used for our HD streams:</p>
<p><span class="math display">\[H_0: \mu_0 = 1700 \\ H_1: \mu_0 \neq 1700 \]</span></p>
<p>We can first have a quick look at the descriptive statistics:</p>
<div class="sourceCode" id="cb788"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb788-1"><a href="r-markdown-assignments.html#cb788-1"></a><span class="kw">describe</span>(movie_data<span class="op">$</span>streams_sd)</span></code></pre></div>
<pre><code>##    vars   n    mean      sd median trimmed     mad min  max range skew kurtosis
## X1    1 200 2677.92 1075.28   2732 2653.68 1064.51 654 5709  5055  0.2    -0.41
##       se
## X1 76.03</code></pre>
<div class="sourceCode" id="cb790"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb790-1"><a href="r-markdown-assignments.html#cb790-1"></a><span class="kw">describe</span>(movie_data<span class="op">$</span>streams_hd)</span></code></pre></div>
<pre><code>##    vars   n    mean     sd median trimmed    mad min  max range skew kurtosis
## X1    1 200 1834.52 760.23 1668.5  1761.9 578.21 246 4305  4059 0.85     0.42
##       se
## X1 53.76</code></pre>
<p>As we can see, the differences between SD/HD and the week before don´t seem to be extraordinary high. To visualize the distribution of the data, we can create histograms:</p>
<div class="sourceCode" id="cb792"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb792-1"><a href="r-markdown-assignments.html#cb792-1"></a><span class="kw">ggplot</span>(movie_data, <span class="kw">aes</span>(streams_sd)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">col =</span> <span class="st">&quot;black&quot;</span>, </span>
<span id="cb792-2"><a href="r-markdown-assignments.html#cb792-2"></a>    <span class="dt">fill =</span> <span class="st">&quot;darkblue&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Number of SD stremas&quot;</span>, </span>
<span id="cb792-3"><a href="r-markdown-assignments.html#cb792-3"></a>    <span class="dt">y =</span> <span class="st">&quot;Frequency&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-463-1.png" width="672" /></p>
<div class="sourceCode" id="cb793"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb793-1"><a href="r-markdown-assignments.html#cb793-1"></a><span class="kw">ggplot</span>(movie_data, <span class="kw">aes</span>(streams_hd)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">col =</span> <span class="st">&quot;black&quot;</span>, </span>
<span id="cb793-2"><a href="r-markdown-assignments.html#cb793-2"></a>    <span class="dt">fill =</span> <span class="st">&quot;darkblue&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Number of HD streams&quot;</span>, </span>
<span id="cb793-3"><a href="r-markdown-assignments.html#cb793-3"></a>    <span class="dt">y =</span> <span class="st">&quot;Frequency&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-463-2.png" width="672" /></p>
<p>We can now conduct a one sample t-test to test for significance.</p>
<div class="sourceCode" id="cb794"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb794-1"><a href="r-markdown-assignments.html#cb794-1"></a><span class="kw">t.test</span>(movie_data<span class="op">$</span>streams_sd, <span class="dt">mu =</span> <span class="dv">2600</span>, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  movie_data$streams_sd
## t = 1.0247, df = 199, p-value = 0.3067
## alternative hypothesis: true mean is not equal to 2600
## 95 percent confidence interval:
##  2527.979 2827.851
## sample estimates:
## mean of x 
##  2677.915</code></pre>
<div class="sourceCode" id="cb796"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb796-1"><a href="r-markdown-assignments.html#cb796-1"></a><span class="kw">t.test</span>(movie_data<span class="op">$</span>streams_hd, <span class="dt">mu =</span> <span class="dv">1700</span>, <span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  movie_data$streams_hd
## t = 2.5023, df = 199, p-value = 0.01314
## alternative hypothesis: true mean is not equal to 1700
## 95 percent confidence interval:
##  1728.51 1940.52
## sample estimates:
## mean of x 
##  1834.515</code></pre>
<p>For SD streams, we can conclude that the average number of SD streams watched in this week (2677.92) were not significantly different from the 2600 streams watched in the previous week, t(199) = 1.025, p &gt; .05 (95% CI = [2528; 2828]). This can be seen from the fact that the p-value is larger than 0.05. This is also evidenced by the fact that the null hypothesis (2600) is included in the range of plausible values given by the confidence interval.</p>
<p>However for HD streams we see that the perceived mean in our sample (1834.52) is significantly higher compared to the previous week t(199) = 2.502, p &lt;.05 (95% CI = [1729; 1941]). This can be seen from the fact that the p-value is smaller than 0.05. This is also evidenced by the fact that the null hypothesis (1700) is not included in the range of plausible values given by the confidence interval.</p>
<p>Alternatively, you could also use the <code>ggstatsplot</code> package to conduct the tests:</p>
<div class="sourceCode" id="cb798"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb798-1"><a href="r-markdown-assignments.html#cb798-1"></a><span class="kw">gghistostats</span>(<span class="dt">data =</span> movie_data, <span class="dt">x =</span> streams_sd, <span class="dt">title =</span> <span class="st">&quot;Distribution of SD streams&quot;</span>, </span>
<span id="cb798-2"><a href="r-markdown-assignments.html#cb798-2"></a>    <span class="dt">type =</span> <span class="st">&quot;parametric&quot;</span>, <span class="dt">conf.level =</span> <span class="fl">0.95</span>, <span class="dt">bar.measure =</span> <span class="st">&quot;mix&quot;</span>, </span>
<span id="cb798-3"><a href="r-markdown-assignments.html#cb798-3"></a>    <span class="dt">test.value =</span> <span class="dv">2600</span>, <span class="dt">test.value.line =</span> <span class="ot">TRUE</span>, <span class="dt">effsize.type =</span> <span class="st">&quot;d&quot;</span>, </span>
<span id="cb798-4"><a href="r-markdown-assignments.html#cb798-4"></a>    <span class="dt">test.value.color =</span> <span class="st">&quot;#0072B2&quot;</span>, <span class="dt">centrality.para =</span> <span class="st">&quot;mean&quot;</span>, </span>
<span id="cb798-5"><a href="r-markdown-assignments.html#cb798-5"></a>    <span class="dt">centrality.color =</span> <span class="st">&quot;darkred&quot;</span>, <span class="dt">binwidth =</span> <span class="dv">300</span>, <span class="dt">messages =</span> <span class="ot">FALSE</span>, </span>
<span id="cb798-6"><a href="r-markdown-assignments.html#cb798-6"></a>    <span class="dt">bf.message =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-465-1.png" width="672" /></p>
<div class="sourceCode" id="cb799"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb799-1"><a href="r-markdown-assignments.html#cb799-1"></a><span class="kw">gghistostats</span>(<span class="dt">data =</span> movie_data, <span class="dt">x =</span> streams_hd, <span class="dt">title =</span> <span class="st">&quot;Distribution of HD streams&quot;</span>, </span>
<span id="cb799-2"><a href="r-markdown-assignments.html#cb799-2"></a>    <span class="dt">type =</span> <span class="st">&quot;parametric&quot;</span>, <span class="dt">conf.level =</span> <span class="fl">0.95</span>, <span class="dt">bar.measure =</span> <span class="st">&quot;mix&quot;</span>, </span>
<span id="cb799-3"><a href="r-markdown-assignments.html#cb799-3"></a>    <span class="dt">test.value =</span> <span class="dv">2600</span>, <span class="dt">test.value.line =</span> <span class="ot">TRUE</span>, <span class="dt">effsize.type =</span> <span class="st">&quot;d&quot;</span>, </span>
<span id="cb799-4"><a href="r-markdown-assignments.html#cb799-4"></a>    <span class="dt">test.value.color =</span> <span class="st">&quot;#0072B2&quot;</span>, <span class="dt">centrality.para =</span> <span class="st">&quot;mean&quot;</span>, </span>
<span id="cb799-5"><a href="r-markdown-assignments.html#cb799-5"></a>    <span class="dt">centrality.color =</span> <span class="st">&quot;darkred&quot;</span>, <span class="dt">binwidth =</span> <span class="dv">300</span>, <span class="dt">messages =</span> <span class="ot">FALSE</span>, </span>
<span id="cb799-6"><a href="r-markdown-assignments.html#cb799-6"></a>    <span class="dt">bf.message =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-466-1.png" width="672" /></p>
<p><strong>Question 3</strong></p>
<p>First we will analyze whether the advertising campaign had an effect on SD streams. We need to formulate a hypothesis which we can test. In this case, the null hypothesis is that the campaign had no effect on the mean number of streams, i.e. that there is no difference in the mean number of streams between the two populations. The alternative hypothesis states that the campaign <em>did</em> have an effect, meaning that there is a difference in the mean number of streams between the populations. In more formal notation this is:</p>
<p><span class="math display">\[H_0: \mu_0 = \mu_1 \\ H_1: \mu_0 \neq \mu_1\]</span></p>
<p>We need to transform the variable online_advertising into a factor variable for some of our analyses:</p>
<div class="sourceCode" id="cb800"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb800-1"><a href="r-markdown-assignments.html#cb800-1"></a><span class="co"># Transform into factor variable</span></span>
<span id="cb800-2"><a href="r-markdown-assignments.html#cb800-2"></a>movie_data<span class="op">$</span>online_advertising &lt;-<span class="st"> </span><span class="kw">factor</span>(movie_data<span class="op">$</span>online_advertising, </span>
<span id="cb800-3"><a href="r-markdown-assignments.html#cb800-3"></a>    <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;no&quot;</span>, <span class="st">&quot;yes&quot;</span>))</span></code></pre></div>
<p>A good way to get a feeling for the data is to compute descriptive statistics and create appropriate plots. Since we are testing differences in means, a plot of means (or a boxplot) would be appropriate.</p>
<div class="sourceCode" id="cb801"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb801-1"><a href="r-markdown-assignments.html#cb801-1"></a><span class="co"># Descriptive statistics for SD streams, split by</span></span>
<span id="cb801-2"><a href="r-markdown-assignments.html#cb801-2"></a><span class="co"># online advertising</span></span>
<span id="cb801-3"><a href="r-markdown-assignments.html#cb801-3"></a><span class="kw">describeBy</span>(movie_data<span class="op">$</span>streams_sd, movie_data<span class="op">$</span>online_advertising)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: no
##    vars   n    mean    sd median trimmed    mad min  max range skew kurtosis
## X1    1 100 2150.24 897.3 2088.5 2112.99 1188.3 705 4170  3465 0.25    -1.02
##       se
## X1 89.73
## ------------------------------------------------------------ 
## group: yes
##    vars   n    mean     sd median trimmed    mad min  max range skew kurtosis
## X1    1 100 3205.59 978.01   3147 3193.69 966.66 654 5709  5055 0.08     0.04
##      se
## X1 97.8</code></pre>
<div class="sourceCode" id="cb803"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb803-1"><a href="r-markdown-assignments.html#cb803-1"></a>mean_data &lt;-<span class="st"> </span><span class="kw">summarySE</span>(movie_data, <span class="dt">measurevar =</span> <span class="st">&quot;streams_sd&quot;</span>, </span>
<span id="cb803-2"><a href="r-markdown-assignments.html#cb803-2"></a>    <span class="dt">groupvars =</span> <span class="kw">c</span>(<span class="st">&quot;online_advertising&quot;</span>))</span>
<span id="cb803-3"><a href="r-markdown-assignments.html#cb803-3"></a></span>
<span id="cb803-4"><a href="r-markdown-assignments.html#cb803-4"></a><span class="co"># Plot of means</span></span>
<span id="cb803-5"><a href="r-markdown-assignments.html#cb803-5"></a><span class="kw">ggplot</span>(mean_data, <span class="kw">aes</span>(<span class="dt">x =</span> online_advertising, <span class="dt">y =</span> streams_sd)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb803-6"><a href="r-markdown-assignments.html#cb803-6"></a><span class="st">    </span><span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.9</span>), <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, </span>
<span id="cb803-7"><a href="r-markdown-assignments.html#cb803-7"></a>        <span class="dt">fill =</span> <span class="st">&quot;#CCCCCC&quot;</span>, <span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">width =</span> <span class="fl">0.65</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb803-8"><a href="r-markdown-assignments.html#cb803-8"></a><span class="st">    </span><span class="kw">geom_errorbar</span>(<span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.9</span>), <span class="dt">width =</span> <span class="fl">0.15</span>, </span>
<span id="cb803-9"><a href="r-markdown-assignments.html#cb803-9"></a>        <span class="kw">aes</span>(<span class="dt">ymin =</span> streams_sd <span class="op">-</span><span class="st"> </span>ci, <span class="dt">ymax =</span> streams_sd <span class="op">+</span><span class="st"> </span></span>
<span id="cb803-10"><a href="r-markdown-assignments.html#cb803-10"></a><span class="st">            </span>ci)) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Advertising&quot;</span>, </span>
<span id="cb803-11"><a href="r-markdown-assignments.html#cb803-11"></a>    <span class="dt">y =</span> <span class="st">&quot;Average number of SD streams&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Average number of SD streams by group&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb803-12"><a href="r-markdown-assignments.html#cb803-12"></a><span class="st">    </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>, </span>
<span id="cb803-13"><a href="r-markdown-assignments.html#cb803-13"></a>    <span class="dt">color =</span> <span class="st">&quot;#666666&quot;</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-468-1.png" width="672" /></p>
<p>As we can see in both the descriptive statistics and the plot, the mean of the number of streams is higher where online_advertising = “yes”, i.e. for the movies that were included in the marketing campaign. To test whether or not this difference is significant, we need to use a <strong>two sample t-test</strong>. We use an independent-means t-test because we have different movies in each group (i.e., the movies in one condition are <em>independent</em> of the movies in the other condition). The requirements are clearly met:</p>
<ul>
<li>Our dependent variable is on an interval scale</li>
<li>Since we have more than 30 observations per group we do not really have to concern ourselves with whether the data is normally distributed or not (see central limit theorem)</li>
<li>If a movie was included in the campaign or not was assigned randomly</li>
<li>R automatically performs Welch’s t-test, which corrects for unequal variance</li>
</ul>
<p>Thus we can perform the test in R</p>
<div class="sourceCode" id="cb804"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb804-1"><a href="r-markdown-assignments.html#cb804-1"></a><span class="kw">t.test</span>(streams_sd <span class="op">~</span><span class="st"> </span>online_advertising, <span class="dt">data =</span> movie_data)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  streams_sd by online_advertising
## t = -7.9513, df = 196.55, p-value = 0.0000000000001418
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1317.1019  -793.5981
## sample estimates:
##  mean in group no mean in group yes 
##           2150.24           3205.59</code></pre>
<p>The test is significant, since the p-value is smaller than 0.05, leading us to reject the null hypothesis that there is no difference in the mean number of streams. The p-value states the probability of finding a difference of the observed magnitude or higher, if the null hypothesis was in fact true (i.e., if there was in fact no difference between the populations). In effect, this means that the advertising campaign had an effect on the average number of times a video was streamed. Another thing we can extract from this test result is the confidence interval around the difference in means. Since 0 is not included in the interval, it is not a plausible value, confirming the conclusion to reject the null hypothesis.</p>
<p>The standardized effect size can be computed using the <code>cohensD</code> function:</p>
<div class="sourceCode" id="cb806"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb806-1"><a href="r-markdown-assignments.html#cb806-1"></a><span class="kw">cohensD</span>(streams_sd <span class="op">~</span><span class="st"> </span>online_advertising, <span class="dt">data =</span> movie_data)</span></code></pre></div>
<pre><code>## [1] 1.124481</code></pre>
<p>This magnitude of the effect size (1.12) suggests that the effect of online advertising on the number of SD streams is large.</p>
<p>The same can be done analogously for HD streams:</p>
<div class="sourceCode" id="cb808"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb808-1"><a href="r-markdown-assignments.html#cb808-1"></a><span class="co"># Descriptive statistics for HD streams, split by</span></span>
<span id="cb808-2"><a href="r-markdown-assignments.html#cb808-2"></a><span class="co"># online advertising</span></span>
<span id="cb808-3"><a href="r-markdown-assignments.html#cb808-3"></a>stats &lt;-<span class="st"> </span><span class="kw">describeBy</span>(movie_data<span class="op">$</span>streams_hd, movie_data<span class="op">$</span>online_advertising)</span>
<span id="cb808-4"><a href="r-markdown-assignments.html#cb808-4"></a><span class="kw">print</span>(stats)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: no
##    vars   n    mean     sd median trimmed    mad min  max range  skew kurtosis
## X1    1 100 1475.55 395.04   1483 1490.08 436.63 246 2305  2059 -0.34     -0.2
##      se
## X1 39.5
## ------------------------------------------------------------ 
## group: yes
##    vars   n    mean     sd median trimmed    mad min  max range skew kurtosis
## X1    1 100 2193.48 863.34   2133  2179.2 962.95 585 4305  3720 0.21    -0.73
##       se
## X1 86.33</code></pre>
<div class="sourceCode" id="cb810"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb810-1"><a href="r-markdown-assignments.html#cb810-1"></a>mean_data &lt;-<span class="st"> </span><span class="kw">summarySE</span>(movie_data, <span class="dt">measurevar =</span> <span class="st">&quot;streams_hd&quot;</span>, </span>
<span id="cb810-2"><a href="r-markdown-assignments.html#cb810-2"></a>    <span class="dt">groupvars =</span> <span class="kw">c</span>(<span class="st">&quot;online_advertising&quot;</span>))</span>
<span id="cb810-3"><a href="r-markdown-assignments.html#cb810-3"></a></span>
<span id="cb810-4"><a href="r-markdown-assignments.html#cb810-4"></a><span class="co"># Plot of means</span></span>
<span id="cb810-5"><a href="r-markdown-assignments.html#cb810-5"></a><span class="kw">ggplot</span>(mean_data, <span class="kw">aes</span>(<span class="dt">x =</span> online_advertising, <span class="dt">y =</span> streams_hd)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb810-6"><a href="r-markdown-assignments.html#cb810-6"></a><span class="st">    </span><span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.9</span>), <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, </span>
<span id="cb810-7"><a href="r-markdown-assignments.html#cb810-7"></a>        <span class="dt">fill =</span> <span class="st">&quot;#CCCCCC&quot;</span>, <span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">width =</span> <span class="fl">0.65</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb810-8"><a href="r-markdown-assignments.html#cb810-8"></a><span class="st">    </span><span class="kw">geom_errorbar</span>(<span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.9</span>), <span class="dt">width =</span> <span class="fl">0.15</span>, </span>
<span id="cb810-9"><a href="r-markdown-assignments.html#cb810-9"></a>        <span class="kw">aes</span>(<span class="dt">ymin =</span> streams_hd <span class="op">-</span><span class="st"> </span>ci, <span class="dt">ymax =</span> streams_hd <span class="op">+</span><span class="st"> </span></span>
<span id="cb810-10"><a href="r-markdown-assignments.html#cb810-10"></a><span class="st">            </span>ci)) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Advertising&quot;</span>, </span>
<span id="cb810-11"><a href="r-markdown-assignments.html#cb810-11"></a>    <span class="dt">y =</span> <span class="st">&quot;Average number of HD streams&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Average number of HD streams by group&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb810-12"><a href="r-markdown-assignments.html#cb810-12"></a><span class="st">    </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>, </span>
<span id="cb810-13"><a href="r-markdown-assignments.html#cb810-13"></a>    <span class="dt">color =</span> <span class="st">&quot;#666666&quot;</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-471-1.png" width="672" /></p>
<p>Again, the summary statistics and the plot seem to indicate that there is a difference in means. Using the same reasoning as before, we can conclude that we need a two sample t-test to determine whether this difference is significant (note that <em>two sample t-test</em> means the same as <em>independent-means t-test</em>).</p>
<div class="sourceCode" id="cb811"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb811-1"><a href="r-markdown-assignments.html#cb811-1"></a><span class="kw">t.test</span>(streams_hd <span class="op">~</span><span class="st"> </span>online_advertising, <span class="dt">data =</span> movie_data)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  streams_hd by online_advertising
## t = -7.5617, df = 138.71, p-value = 0.00000000000494
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -905.6522 -530.2078
## sample estimates:
##  mean in group no mean in group yes 
##           1475.55           2193.48</code></pre>
<p>Again, the p-value is so low that any sensible significance level would lead us to reject the null hypothesis, suggesting that there is a difference in mean the number of streams between videos included in the campaign and those that aren’t.</p>
<p>Calculate the standardized effect size:</p>
<div class="sourceCode" id="cb813"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb813-1"><a href="r-markdown-assignments.html#cb813-1"></a><span class="kw">cohensD</span>(streams_hd <span class="op">~</span><span class="st"> </span>online_advertising, <span class="dt">data =</span> movie_data)</span></code></pre></div>
<pre><code>## [1] 1.069388</code></pre>
<p>The magnitude of the effect size indicates again that this effect is large, although it is somewhat smaller than for SD streams.</p>
<p>Alternatively, you could also use the <code>ggstatsplot</code> package to conduct the tests:</p>
<div class="sourceCode" id="cb815"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb815-1"><a href="r-markdown-assignments.html#cb815-1"></a><span class="kw">ggbetweenstats</span>(</span>
<span id="cb815-2"><a href="r-markdown-assignments.html#cb815-2"></a>  <span class="dt">data =</span> movie_data,</span>
<span id="cb815-3"><a href="r-markdown-assignments.html#cb815-3"></a>  <span class="dt">plot.type =</span> <span class="st">&quot;box&quot;</span>,</span>
<span id="cb815-4"><a href="r-markdown-assignments.html#cb815-4"></a>  <span class="dt">x =</span> online_advertising, <span class="co"># 2 groups</span></span>
<span id="cb815-5"><a href="r-markdown-assignments.html#cb815-5"></a>  <span class="dt">y =</span> streams_sd ,</span>
<span id="cb815-6"><a href="r-markdown-assignments.html#cb815-6"></a>  <span class="dt">type =</span> <span class="st">&quot;p&quot;</span>, <span class="co"># default</span></span>
<span id="cb815-7"><a href="r-markdown-assignments.html#cb815-7"></a>  <span class="dt">effsize.type =</span> <span class="st">&quot;d&quot;</span>, <span class="co"># display effect size (Cohen&#39;s d in output)</span></span>
<span id="cb815-8"><a href="r-markdown-assignments.html#cb815-8"></a>  <span class="dt">messages =</span> <span class="ot">FALSE</span>,</span>
<span id="cb815-9"><a href="r-markdown-assignments.html#cb815-9"></a>  <span class="dt">bf.message =</span> <span class="ot">FALSE</span>,</span>
<span id="cb815-10"><a href="r-markdown-assignments.html#cb815-10"></a>  <span class="dt">mean.ci =</span> <span class="ot">TRUE</span>,</span>
<span id="cb815-11"><a href="r-markdown-assignments.html#cb815-11"></a>  <span class="dt">title =</span> <span class="st">&quot;SD streams&quot;</span></span>
<span id="cb815-12"><a href="r-markdown-assignments.html#cb815-12"></a>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-474-1.png" width="672" /></p>
<div class="sourceCode" id="cb816"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb816-1"><a href="r-markdown-assignments.html#cb816-1"></a><span class="kw">ggbetweenstats</span>(</span>
<span id="cb816-2"><a href="r-markdown-assignments.html#cb816-2"></a>  <span class="dt">data =</span> movie_data,</span>
<span id="cb816-3"><a href="r-markdown-assignments.html#cb816-3"></a>  <span class="dt">plot.type =</span> <span class="st">&quot;box&quot;</span>,</span>
<span id="cb816-4"><a href="r-markdown-assignments.html#cb816-4"></a>  <span class="dt">x =</span> online_advertising, <span class="co"># 2 groups</span></span>
<span id="cb816-5"><a href="r-markdown-assignments.html#cb816-5"></a>  <span class="dt">y =</span> streams_hd ,</span>
<span id="cb816-6"><a href="r-markdown-assignments.html#cb816-6"></a>  <span class="dt">type =</span> <span class="st">&quot;p&quot;</span>, <span class="co"># default</span></span>
<span id="cb816-7"><a href="r-markdown-assignments.html#cb816-7"></a>  <span class="dt">effsize.type =</span> <span class="st">&quot;d&quot;</span>, <span class="co"># display effect size (Cohen&#39;s d in output)</span></span>
<span id="cb816-8"><a href="r-markdown-assignments.html#cb816-8"></a>  <span class="dt">messages =</span> <span class="ot">FALSE</span>,</span>
<span id="cb816-9"><a href="r-markdown-assignments.html#cb816-9"></a>  <span class="dt">bf.message =</span> <span class="ot">FALSE</span>,</span>
<span id="cb816-10"><a href="r-markdown-assignments.html#cb816-10"></a>  <span class="dt">mean.ci =</span> <span class="ot">TRUE</span>,</span>
<span id="cb816-11"><a href="r-markdown-assignments.html#cb816-11"></a>  <span class="dt">title =</span> <span class="st">&quot;HD streams&quot;</span></span>
<span id="cb816-12"><a href="r-markdown-assignments.html#cb816-12"></a>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-475-1.png" width="672" /></p>
<p><strong>Question 4</strong></p>
<p>Next we want to examine whether HD and SD streams have similar numbers on average. The null hypothesis here is that there is no difference in the mean number of HD streams and the mean number of SD streams for the same movies. Because the observations come from the same population of movies, we refer to the difference in the means for the same population as <span class="math inline">\(\mu_D\)</span> when stating our hypotheses. The alternative hypothesis states that that there is a difference between the streams in HD and SD quality for the same movies. In mathematical notation this can be written as</p>
<p><span class="math display">\[H_0: \mu_D = 0 \\ H_1: \mu_D \neq 0\]</span></p>
<p>Again, we start with descriptive statistics to get a feel for the data.</p>
<div class="sourceCode" id="cb817"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb817-1"><a href="r-markdown-assignments.html#cb817-1"></a><span class="co"># Descriptive statistics for HD and SD streams</span></span>
<span id="cb817-2"><a href="r-markdown-assignments.html#cb817-2"></a>psych<span class="op">::</span><span class="kw">describe</span>(movie_data<span class="op">$</span>streams_sd)</span></code></pre></div>
<pre><code>##    vars   n    mean      sd median trimmed     mad min  max range skew kurtosis
## X1    1 200 2677.92 1075.28   2732 2653.68 1064.51 654 5709  5055  0.2    -0.41
##       se
## X1 76.03</code></pre>
<div class="sourceCode" id="cb819"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb819-1"><a href="r-markdown-assignments.html#cb819-1"></a>psych<span class="op">::</span><span class="kw">describe</span>(movie_data<span class="op">$</span>streams_hd)</span></code></pre></div>
<pre><code>##    vars   n    mean     sd median trimmed    mad min  max range skew kurtosis
## X1    1 200 1834.52 760.23 1668.5  1761.9 578.21 246 4305  4059 0.85     0.42
##       se
## X1 53.76</code></pre>
<div class="sourceCode" id="cb821"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb821-1"><a href="r-markdown-assignments.html#cb821-1"></a><span class="co"># Plot of means</span></span>
<span id="cb821-2"><a href="r-markdown-assignments.html#cb821-2"></a>movie_data_long &lt;-<span class="st"> </span><span class="kw">melt</span>(movie_data[, <span class="kw">c</span>(<span class="st">&quot;streams_sd&quot;</span>, </span>
<span id="cb821-3"><a href="r-markdown-assignments.html#cb821-3"></a>    <span class="st">&quot;streams_hd&quot;</span>)])</span>
<span id="cb821-4"><a href="r-markdown-assignments.html#cb821-4"></a><span class="kw">names</span>(movie_data_long) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;type&quot;</span>, <span class="st">&quot;streams&quot;</span>)</span>
<span id="cb821-5"><a href="r-markdown-assignments.html#cb821-5"></a></span>
<span id="cb821-6"><a href="r-markdown-assignments.html#cb821-6"></a>mean_data &lt;-<span class="st"> </span><span class="kw">summarySE</span>(movie_data_long, <span class="dt">measurevar =</span> <span class="st">&quot;streams&quot;</span>, </span>
<span id="cb821-7"><a href="r-markdown-assignments.html#cb821-7"></a>    <span class="dt">groupvars =</span> <span class="kw">c</span>(<span class="st">&quot;type&quot;</span>))</span>
<span id="cb821-8"><a href="r-markdown-assignments.html#cb821-8"></a></span>
<span id="cb821-9"><a href="r-markdown-assignments.html#cb821-9"></a><span class="co"># Plot of means</span></span>
<span id="cb821-10"><a href="r-markdown-assignments.html#cb821-10"></a><span class="kw">ggplot</span>(mean_data, <span class="kw">aes</span>(<span class="dt">x =</span> type, <span class="dt">y =</span> streams)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.9</span>), </span>
<span id="cb821-11"><a href="r-markdown-assignments.html#cb821-11"></a>    <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;#CCCCCC&quot;</span>, <span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, </span>
<span id="cb821-12"><a href="r-markdown-assignments.html#cb821-12"></a>    <span class="dt">width =</span> <span class="fl">0.65</span>) <span class="op">+</span><span class="st"> </span><span class="kw">geom_errorbar</span>(<span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.9</span>), </span>
<span id="cb821-13"><a href="r-markdown-assignments.html#cb821-13"></a>    <span class="dt">width =</span> <span class="fl">0.15</span>, <span class="kw">aes</span>(<span class="dt">ymin =</span> streams <span class="op">-</span><span class="st"> </span>ci, <span class="dt">ymax =</span> streams <span class="op">+</span><span class="st"> </span></span>
<span id="cb821-14"><a href="r-markdown-assignments.html#cb821-14"></a><span class="st">        </span>ci)) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Type&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Average number of streams&quot;</span>, </span>
<span id="cb821-15"><a href="r-markdown-assignments.html#cb821-15"></a>    <span class="dt">title =</span> <span class="st">&quot;Average number of streams by group&quot;</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb821-16"><a href="r-markdown-assignments.html#cb821-16"></a><span class="st">    </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>, </span>
<span id="cb821-17"><a href="r-markdown-assignments.html#cb821-17"></a>    <span class="dt">color =</span> <span class="st">&quot;#666666&quot;</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-477-1.png" width="672" /></p>
<p>It appears that there is a difference in the means. To test whether it is significant, we again need a t-test. However, this time we need a slightly different version of the t-test because the same movies are observed for HD and SD streams (i.e., the same movies are available in both formats). This means that we need a <strong>dependent means t-test</strong>. This test is also known as the <strong>paired samples t-test</strong>. The other assumptions are virtually identical to the independent-means t-test. The test can be executed in R by adding <code>paired = TRUE</code> to the code.</p>
<div class="sourceCode" id="cb822"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb822-1"><a href="r-markdown-assignments.html#cb822-1"></a><span class="kw">t.test</span>(<span class="dt">y =</span> movie_data<span class="op">$</span>streams_sd, <span class="dt">x =</span> movie_data<span class="op">$</span>streams_hd, </span>
<span id="cb822-2"><a href="r-markdown-assignments.html#cb822-2"></a>    <span class="dt">paired =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  movie_data$streams_hd and movie_data$streams_sd
## t = -11.214, df = 199, p-value &lt; 0.00000000000000022
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -991.7133 -695.0867
## sample estimates:
## mean of the differences 
##                  -843.4</code></pre>
<p>The p-value is again lower than the chosen significance level of 5% (i.e., p &lt; .05), which means that we reject the null hypothesis that there is no difference in the mean number of streams in HD and SD quality. Make sure you interpret the p-value correctly. It refers to the probability of observing a difference of the observed magnitude (or larger) between streams in HD and SD quality, assuming that there was in fact no difference between the formats. The confidence interval confirms the conclusion to reject the null hypothesis since <span class="math inline">\(0\)</span> is not contained in the range of plausible values.</p>
<p>Now let’s find out how strong this effect is.</p>
<div class="sourceCode" id="cb824"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb824-1"><a href="r-markdown-assignments.html#cb824-1"></a><span class="kw">cohensD</span>(movie_data<span class="op">$</span>streams_sd, movie_data<span class="op">$</span>streams_hd, </span>
<span id="cb824-2"><a href="r-markdown-assignments.html#cb824-2"></a>    <span class="dt">method =</span> <span class="st">&quot;paired&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 0.7929318</code></pre>
<p>A standardized effect size of approx. 0.79 tells us that this effect is large.</p>
<p>Alternatively, you could also use the <code>ggstatsplot</code> package to conduct the tests:</p>
<div class="sourceCode" id="cb826"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb826-1"><a href="r-markdown-assignments.html#cb826-1"></a><span class="kw">ggwithinstats</span>(</span>
<span id="cb826-2"><a href="r-markdown-assignments.html#cb826-2"></a>  <span class="dt">data =</span> movie_data_long,</span>
<span id="cb826-3"><a href="r-markdown-assignments.html#cb826-3"></a>  <span class="dt">x =</span> type,</span>
<span id="cb826-4"><a href="r-markdown-assignments.html#cb826-4"></a>  <span class="dt">y =</span> streams,</span>
<span id="cb826-5"><a href="r-markdown-assignments.html#cb826-5"></a>  <span class="dt">path.point =</span> <span class="ot">FALSE</span>,</span>
<span id="cb826-6"><a href="r-markdown-assignments.html#cb826-6"></a>  <span class="dt">path.mean =</span> <span class="ot">TRUE</span>,</span>
<span id="cb826-7"><a href="r-markdown-assignments.html#cb826-7"></a>  <span class="dt">sort =</span> <span class="st">&quot;descending&quot;</span>, <span class="co"># ordering groups along the x-axis based on</span></span>
<span id="cb826-8"><a href="r-markdown-assignments.html#cb826-8"></a>  <span class="dt">sort.fun =</span> mean, <span class="co"># values of `y` variable</span></span>
<span id="cb826-9"><a href="r-markdown-assignments.html#cb826-9"></a>  <span class="dt">title =</span> <span class="st">&quot;Number of streams for movies in SD and HD&quot;</span>,</span>
<span id="cb826-10"><a href="r-markdown-assignments.html#cb826-10"></a>  <span class="dt">messages =</span> <span class="ot">FALSE</span>,</span>
<span id="cb826-11"><a href="r-markdown-assignments.html#cb826-11"></a>  <span class="dt">bf.message =</span> <span class="ot">FALSE</span>,</span>
<span id="cb826-12"><a href="r-markdown-assignments.html#cb826-12"></a>  <span class="dt">mean.ci =</span> <span class="ot">TRUE</span>,</span>
<span id="cb826-13"><a href="r-markdown-assignments.html#cb826-13"></a>  <span class="dt">effsize.type =</span> <span class="st">&quot;d&quot;</span> <span class="co"># display effect size (Cohen&#39;s d in output)</span></span>
<span id="cb826-14"><a href="r-markdown-assignments.html#cb826-14"></a>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-481-1.png" width="672" /></p>
<p><strong>Question 5</strong></p>
<p>The question of how many movies we would need to include in each sample of our experiment can be answered quite comfortably with a power calculation function in R.</p>
<div class="sourceCode" id="cb827"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb827-1"><a href="r-markdown-assignments.html#cb827-1"></a><span class="kw">pwr.t.test</span>(<span class="dt">d =</span> <span class="fl">0.3</span>, <span class="dt">sig.level =</span> <span class="fl">0.05</span>, <span class="dt">power =</span> <span class="fl">0.8</span>, </span>
<span id="cb827-2"><a href="r-markdown-assignments.html#cb827-2"></a>    <span class="dt">type =</span> <span class="kw">c</span>(<span class="st">&quot;two.sample&quot;</span>), <span class="dt">alternative =</span> <span class="kw">c</span>(<span class="st">&quot;two.sided&quot;</span>))</span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 175.3847
##               d = 0.3
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<p>To achieve our desired effect size of 0.3, a significance level of 0.5 and a power of 0.8 we would need to include at least 175 movies per group in our sample.</p>
</div>
<div id="solution-assignment-3" class="section level2">
<h2><span class="header-section-number">9.3</span> Solution assignment 3</h2>
<p>The data file contains customer information from an online fashion shop. In an experiment, the customers were exposed to different types of online advertising over the past year (randomly assigned) and now you wish to analyze the results.</p>
<p>The following variables are included in the data set:</p>
<ul>
<li>customerID: unique customer ID</li>
<li>revenue: revenue per customer for the past year (in EUR)</li>
<li>gender: 0=male, 1=female</li>
<li>retargeting: type of online advertising that the customer was exposed to (3 levels: 1 = no advertising, 2 = generic retargeting, 3 = dynamic retargeting)</li>
<li>customerRank: ranking of customers according to their expenditure level (low rank = valuable customer, high rank = less valuable customer)</li>
<li>conversion: indicator variable, indicating if a customer converted in the previous campaign (0 = no conversion, 1 = conversion)</li>
</ul>
<p>Use R and appropriate analytical techniques to answer the following questions:</p>
<ol style="list-style-type: decimal">
<li>Has the types of online advertising an effect on revenue? Are there significant differences between the individual groups?</li>
<li>Is the customer ranking significantly influenced by the type of online advertising? Are there significant differences between the individual groups?</li>
<li>Does the conversion rate in the previous campaign differ between male and female customers?</li>
</ol>
<p>When answering the questions, please remember to address the following points, where appropriate:</p>
<ul>
<li>Formulate the corresponding hypotheses and choose an appropriate statistical test</li>
<li>Provide the reason for your choice and discuss if the assumptions of the test are met</li>
<li>Convert the variables to the appropriate type (e.g., factor variables)</li>
<li>Create appropriate graphs to explore the data (e.g., boxplot, bar chart, histogram)</li>
<li>Provide appropriate descriptive statistics for the variables</li>
<li>Report and interpret the test results accurately (including confidence intervals)<br />
</li>
<li>Finally, don’t forget to report your research conclusion in an appropriate way</li>
</ul>
<p>When you are done with your analysis, click on “Knit to HTML” button above the code editor. This will create a HTML document of your results in the folder where the “assignment3.Rmd” file is stored. Open this file in your Internet browser to see if the output is correct. If the output is correct, submit the HTML file via Learn@WU. The file name should be “assignment3_studendID_name.html”.</p>
<p><strong>Load data</strong></p>
<div class="sourceCode" id="cb829"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb829-1"><a href="r-markdown-assignments.html#cb829-1"></a><span class="kw">rm</span>(<span class="dt">list =</span> <span class="kw">ls</span>())</span>
<span id="cb829-2"><a href="r-markdown-assignments.html#cb829-2"></a>customer_data &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;https://raw.githubusercontent.com/IMSMWU/MRDA2018/master/data/assignment3.csv&quot;</span>, </span>
<span id="cb829-3"><a href="r-markdown-assignments.html#cb829-3"></a>    <span class="dt">sep =</span> <span class="st">&quot;;&quot;</span>, <span class="dt">header =</span> <span class="ot">TRUE</span>)  <span class="co">#read in data</span></span>
<span id="cb829-4"><a href="r-markdown-assignments.html#cb829-4"></a><span class="kw">head</span>(customer_data)</span></code></pre></div>
<pre><code>##   revenue gender retargeting customerID rank conversion
## 1    3866      1           3          2    1          1
## 2    1576      1           1          7  159          1
## 3    2667      1           1          8   37          0
## 4     772      1           1         12  259          1
## 5    2702      1           3         13   35          1
## 6    1277      1           2         14  203          1</code></pre>
<div class="sourceCode" id="cb831"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb831-1"><a href="r-markdown-assignments.html#cb831-1"></a><span class="kw">str</span>(customer_data)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    296 obs. of  6 variables:
##  $ revenue    : int  3866 1576 2667 772 2702 1277 2023 2170 3103 3067 ...
##  $ gender     : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ retargeting: int  3 1 1 1 3 2 1 3 3 1 ...
##  $ customerID : int  2 7 8 12 13 14 22 24 26 31 ...
##  $ rank       : int  1 159 37 259 35 203 103 87 17 19 ...
##  $ conversion : int  1 1 0 1 1 1 0 1 1 0 ...</code></pre>
<p><strong>Data Preparation</strong></p>
<p>As always, the first step is to load required packages (packages that have not been used as often in the course will be loaded as required to show which packages contain certain functions) and to load and inspect the data.</p>
<div class="sourceCode" id="cb833"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb833-1"><a href="r-markdown-assignments.html#cb833-1"></a><span class="kw">library</span>(plyr)</span>
<span id="cb833-2"><a href="r-markdown-assignments.html#cb833-2"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb833-3"><a href="r-markdown-assignments.html#cb833-3"></a><span class="kw">library</span>(psych)</span>
<span id="cb833-4"><a href="r-markdown-assignments.html#cb833-4"></a><span class="kw">library</span>(Hmisc)</span>
<span id="cb833-5"><a href="r-markdown-assignments.html#cb833-5"></a><span class="kw">library</span>(Rmisc)</span></code></pre></div>
<p>Next we are going to recode some of the variables into factors and give them more descriptive level names.</p>
<div class="sourceCode" id="cb834"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb834-1"><a href="r-markdown-assignments.html#cb834-1"></a>customer_data<span class="op">$</span>retargeting &lt;-<span class="st"> </span><span class="kw">factor</span>(customer_data<span class="op">$</span>retargeting, </span>
<span id="cb834-2"><a href="r-markdown-assignments.html#cb834-2"></a>    <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;no retargeting&quot;</span>, </span>
<span id="cb834-3"><a href="r-markdown-assignments.html#cb834-3"></a>        <span class="st">&quot;generic retargeting&quot;</span>, <span class="st">&quot;dynamic retargeting&quot;</span>))</span>
<span id="cb834-4"><a href="r-markdown-assignments.html#cb834-4"></a>customer_data<span class="op">$</span>gender &lt;-<span class="st"> </span><span class="kw">factor</span>(customer_data<span class="op">$</span>gender, </span>
<span id="cb834-5"><a href="r-markdown-assignments.html#cb834-5"></a>    <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;female&quot;</span>, <span class="st">&quot;male&quot;</span>))</span>
<span id="cb834-6"><a href="r-markdown-assignments.html#cb834-6"></a>customer_data<span class="op">$</span>conversion &lt;-<span class="st"> </span><span class="kw">factor</span>(customer_data<span class="op">$</span>conversion, </span>
<span id="cb834-7"><a href="r-markdown-assignments.html#cb834-7"></a>    <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;conversion&quot;</span>, <span class="st">&quot;no conversion&quot;</span>))</span></code></pre></div>
<p><strong>Question 1</strong></p>
<p>To answer whether the type of advertising has an effect on revenue we need to formulate a testable null hypothesis. In our case the null hypothesis is stating that the average level of sales is equal for all advertising types. In mathematical notation this implies:</p>
<p><span class="math display">\[H_0: \mu_1 = \mu_2 = \mu_3 \]</span></p>
<p>The alternate hypothesis is simply that the means are not all equal, i.e.,</p>
<p><span class="math display">\[H_1: \textrm{Means are not all equal}\]</span></p>
<p>If you wanted to put this in mathematical notation, you could also write:</p>
<p><span class="math display">\[H_1: \exists {i,j}: {\mu_i \ne \mu_j} \]</span></p>
<p>The appropriate test for such a hypothesis is one-way ANOVA since we have a metric scales dependent variable and a categorical independent variable with more than two levels.</p>
<p>Next we will calculate summary statistics for the data and produce an appropriate plot.</p>
<div class="sourceCode" id="cb835"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb835-1"><a href="r-markdown-assignments.html#cb835-1"></a><span class="kw">describeBy</span>(customer_data<span class="op">$</span>revenue, customer_data<span class="op">$</span>retargeting)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: no retargeting
##    vars   n    mean     sd median trimmed    mad min  max range skew kurtosis
## X1    1 106 1414.31 714.21 1437.5 1386.42 786.52 100 3356  3256 0.31    -0.53
##       se
## X1 69.37
## ------------------------------------------------------------ 
## group: generic retargeting
##    vars  n    mean    sd median trimmed    mad min  max range skew kurtosis
## X1    1 90 1502.63 681.3   1445 1491.79 729.44  78 2885  2807 0.12    -0.74
##       se
## X1 71.82
## ------------------------------------------------------------ 
## group: dynamic retargeting
##    vars   n    mean     sd median trimmed    mad min  max range  skew kurtosis
## X1    1 100 2208.28 796.85 2277.5 2218.12 735.37 145 3866  3721 -0.16    -0.51
##       se
## X1 79.68</code></pre>
<div class="sourceCode" id="cb837"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb837-1"><a href="r-markdown-assignments.html#cb837-1"></a>mean_data &lt;-<span class="st"> </span><span class="kw">summarySE</span>(customer_data, <span class="dt">measurevar =</span> <span class="st">&quot;revenue&quot;</span>, </span>
<span id="cb837-2"><a href="r-markdown-assignments.html#cb837-2"></a>    <span class="dt">groupvars =</span> <span class="kw">c</span>(<span class="st">&quot;retargeting&quot;</span>))</span>
<span id="cb837-3"><a href="r-markdown-assignments.html#cb837-3"></a><span class="kw">ggplot</span>(mean_data, <span class="kw">aes</span>(<span class="dt">x =</span> retargeting, <span class="dt">y =</span> revenue)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb837-4"><a href="r-markdown-assignments.html#cb837-4"></a><span class="st">    </span><span class="kw">geom_bar</span>(<span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="dv">1</span>), <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, </span>
<span id="cb837-5"><a href="r-markdown-assignments.html#cb837-5"></a>        <span class="dt">fill =</span> <span class="st">&quot;#CCCCCC&quot;</span>, <span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">width =</span> <span class="fl">0.65</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb837-6"><a href="r-markdown-assignments.html#cb837-6"></a><span class="st">    </span><span class="kw">geom_errorbar</span>(<span class="dt">position =</span> <span class="kw">position_dodge</span>(<span class="fl">0.9</span>), <span class="dt">width =</span> <span class="fl">0.15</span>, </span>
<span id="cb837-7"><a href="r-markdown-assignments.html#cb837-7"></a>        <span class="kw">aes</span>(<span class="dt">ymin =</span> revenue <span class="op">-</span><span class="st"> </span>ci, <span class="dt">ymax =</span> revenue <span class="op">+</span><span class="st"> </span>ci)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb837-8"><a href="r-markdown-assignments.html#cb837-8"></a><span class="st">    </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Group&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Average revenue&quot;</span>, </span>
<span id="cb837-9"><a href="r-markdown-assignments.html#cb837-9"></a>    <span class="dt">title =</span> <span class="st">&quot;Average revenue by group&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb837-10"><a href="r-markdown-assignments.html#cb837-10"></a><span class="st">    </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>, <span class="dt">color =</span> <span class="st">&quot;#666666&quot;</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-486-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Both the summary statistics and the plot hint at the fact that the means may not be equal. Especially the difference between dynamic retargeting and no retargeting/ generic regtargeting seem to be quite high. Before we move to the formal test, we need to see if a series of assumptions are met, namely:</p>
<ul>
<li>Distributional assumptions</li>
<li>Homogeneity of variances</li>
<li>Independence of observations</li>
</ul>
<p>The last assumption is satisfied due to the fact that the observations were randomly assigned to the advertisement groups. To see if we need to worry about distributional assumptions we first take a look at the number of observations in each advertising group.</p>
<div class="sourceCode" id="cb838"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb838-1"><a href="r-markdown-assignments.html#cb838-1"></a><span class="co"># check number of observations by group</span></span>
<span id="cb838-2"><a href="r-markdown-assignments.html#cb838-2"></a><span class="kw">table</span>(customer_data<span class="op">$</span>retargeting)</span></code></pre></div>
<pre><code>## 
##      no retargeting generic retargeting dynamic retargeting 
##                 106                  90                 100</code></pre>
<p>Due to the fact that there are always more than 30 observations in each group we can rely on the central limit theorem to satisfy the distributional assumptions.</p>
<p>Homogeneity of variances can be checked with Levene’s test (implemented as <code>leveneTest()</code> from the <code>car</code> package). The null hypothesis of this test is that the variances are equal, with the alternative hypothesis being that the variances are not all equal. Note that this step could also be skipped and replaced by the use of the robust ANOVA using the <code>oneway.test()</code> function.</p>
<div class="sourceCode" id="cb840"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb840-1"><a href="r-markdown-assignments.html#cb840-1"></a><span class="co"># Homogeneity of variances test:</span></span>
<span id="cb840-2"><a href="r-markdown-assignments.html#cb840-2"></a><span class="kw">library</span>(car)</span>
<span id="cb840-3"><a href="r-markdown-assignments.html#cb840-3"></a><span class="kw">leveneTest</span>(revenue <span class="op">~</span><span class="st"> </span>retargeting, <span class="dt">data =</span> customer_data, </span>
<span id="cb840-4"><a href="r-markdown-assignments.html#cb840-4"></a>    <span class="dt">center =</span> mean)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = mean)
##        Df F value Pr(&gt;F)
## group   2  1.2455 0.2893
##       293</code></pre>
<p>The test result is insignificant (for a significance level of 5 %), meaning that we do not reject the null hypothesis of equal variances and can operate under the assumption that the variances are equal.</p>
<p>Since all assumptions are fulfilled we can move on to conducting the actual ANOVA using the <code>aov()</code> function. As said above, it would also be possible to conduct the analysis using the robust ANOVA using the <code>oneway.test()</code> function:</p>
<div class="sourceCode" id="cb842"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb842-1"><a href="r-markdown-assignments.html#cb842-1"></a><span class="co"># Anova:</span></span>
<span id="cb842-2"><a href="r-markdown-assignments.html#cb842-2"></a>aov &lt;-<span class="st"> </span><span class="kw">aov</span>(revenue <span class="op">~</span><span class="st"> </span>retargeting, <span class="dt">data =</span> customer_data)</span>
<span id="cb842-3"><a href="r-markdown-assignments.html#cb842-3"></a><span class="kw">summary</span>(aov)</span></code></pre></div>
<pre><code>##              Df    Sum Sq  Mean Sq F value            Pr(&gt;F)    
## retargeting   2  37966043 18983022   35.26 0.000000000000019 ***
## Residuals   293 157734112   538342                              
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The p-value is smaller than 0.05, which we chose as our significance level, meaning that we reject the null hypothesis of the means being equal in the three advertising groups.</p>
<p>Next we will briefly inspect the residuals of the ANOVA to see if the assumptions of the test really are justified.</p>
<div class="sourceCode" id="cb844"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb844-1"><a href="r-markdown-assignments.html#cb844-1"></a><span class="co"># Inspect residuals</span></span>
<span id="cb844-2"><a href="r-markdown-assignments.html#cb844-2"></a><span class="kw">plot</span>(aov, <span class="dv">1</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-490-1.png" width="672" /></p>
<p>The first plot gives us a feel for the distribution of the residuals of the three groups. The residuals seem to be roughly equally distributed, which speaks for the fact that the homogeneity of variances assumptions is fulfilled.</p>
<div class="sourceCode" id="cb845"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb845-1"><a href="r-markdown-assignments.html#cb845-1"></a><span class="kw">plot</span>(aov, <span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-491-1.png" width="672" /></p>
<p>The second plot is a QQ-plot of the residuals, meant as a quick visual check to see if the normality assumption is fulfilled. Leading up to the test we only checked if there were more than 30 observations per group to satisfy the normality assumption but despite this being fulfilled it is still important to check the normality of the residuals, as any strange behavior here may indicate problems with the model specification.</p>
<p>To further confirm that the residuals are roughly normally distributed we employ the Shapiro-Wilk test. The null hypothesis is that the distribution of the data is normal, with the alternative hypothesis positing that the data is not normally distributed.</p>
<div class="sourceCode" id="cb846"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb846-1"><a href="r-markdown-assignments.html#cb846-1"></a><span class="kw">shapiro.test</span>(<span class="kw">resid</span>(aov))</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resid(aov)
## W = 0.99378, p-value = 0.2637</code></pre>
<p>The p value is far above any widely used significance level and thus we can not reject the null hypothesis of normal distribution, which further implies that the normality assumption is fulfilled.</p>
<p>The ANOVA result only tells us that the means of the three groups are not equal, but it does not tell us anything about <em>which</em> pairs of means are unequal. To find this out we need to conduct post hoc tests to test the following null hypotheses for the respective pairwise comparisons.</p>
<p><span class="math display">\[1) H_0: \mu_1 = \mu_2; H_1 = \mu_1 \neq \mu_2 \\
2) H_0: \mu_2 = \mu_3; H_1 = \mu_2 \neq \mu_3 \\
3) H_0: \mu_1 = \mu_3; H_1 = \mu_1 \neq \mu_3 \]</span></p>
<p>Here we will conduct both the Bonferroni correction as well as Tukey’s HSD test, however either would be sufficient for your homework. Bonferroni’s correction conducts multiple pairwise t-tests, with the null hypothesis being that of equal means in each case and the alternative hypothesis stating that the means are unequal.</p>
<div class="sourceCode" id="cb848"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb848-1"><a href="r-markdown-assignments.html#cb848-1"></a><span class="co"># bonferroni</span></span>
<span id="cb848-2"><a href="r-markdown-assignments.html#cb848-2"></a><span class="kw">pairwise.t.test</span>(customer_data<span class="op">$</span>revenue, customer_data<span class="op">$</span>retargeting, </span>
<span id="cb848-3"><a href="r-markdown-assignments.html#cb848-3"></a>    <span class="dt">data =</span> customer_data, <span class="dt">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  customer_data$revenue and customer_data$retargeting 
## 
##                     no retargeting   generic retargeting
## generic retargeting 1                -                  
## dynamic retargeting 0.00000000000042 0.00000000051570   
## 
## P value adjustment method: bonferroni</code></pre>
<p>The Bonferroni test reinforces what we saw in our plot earlier, namely that not all of the means might be significantly different from each other.</p>
<p>We can only reject the null hypothesis in the cases:<br />
dynamic regargeting vs. no retargeting<br />
dynamic regargeting vs. generig retargeting</p>
<p>But there seems to be no difference in the means of generic retargeting vs. no retargeting.</p>
<p>Alternatively, you could have also chosen to use Tukey’s HSD to conduct the post hoc test. Tukey’s HSD similarly compares pairwise means, corrected for family-wise errors (both of the post hoc tests would have been considered correct).</p>
<div class="sourceCode" id="cb850"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb850-1"><a href="r-markdown-assignments.html#cb850-1"></a><span class="co"># tukey correction using the mult-comp package</span></span>
<span id="cb850-2"><a href="r-markdown-assignments.html#cb850-2"></a><span class="kw">library</span>(multcomp)</span>
<span id="cb850-3"><a href="r-markdown-assignments.html#cb850-3"></a>tukeys &lt;-<span class="st"> </span><span class="kw">glht</span>(aov, <span class="dt">linfct =</span> <span class="kw">mcp</span>(<span class="dt">retargeting =</span> <span class="st">&quot;Tukey&quot;</span>))</span>
<span id="cb850-4"><a href="r-markdown-assignments.html#cb850-4"></a><span class="kw">summary</span>(tukeys)</span></code></pre></div>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Multiple Comparisons of Means: Tukey Contrasts
## 
## 
## Fit: aov(formula = revenue ~ retargeting, data = customer_data)
## 
## Linear Hypotheses:
##                                                Estimate Std. Error t value
## generic retargeting - no retargeting == 0         88.32     105.17   0.840
## dynamic retargeting - no retargeting == 0        793.97     102.28   7.762
## dynamic retargeting - generic retargeting == 0   705.65     106.61   6.619
##                                                Pr(&gt;|t|)    
## generic retargeting - no retargeting == 0         0.679    
## dynamic retargeting - no retargeting == 0      &lt;0.00001 ***
## dynamic retargeting - generic retargeting == 0 &lt;0.00001 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Adjusted p values reported -- single-step method)</code></pre>
<p>Tukey’s correction confirms the conclusion from the Bonferroni test from above. While there seems to be no difference in the means of generic retargeting vs. no retargeting, dynamic retargeting seems to differ significantly from both generic retargeting and no retargeting.</p>
<p>Tukey’s HSD further let’s us estimate the difference in means with corresponding confidence intervals.</p>
<div class="sourceCode" id="cb852"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb852-1"><a href="r-markdown-assignments.html#cb852-1"></a><span class="kw">confint</span>(tukeys)</span></code></pre></div>
<pre><code>## 
##   Simultaneous Confidence Intervals
## 
## Multiple Comparisons of Means: Tukey Contrasts
## 
## 
## Fit: aov(formula = revenue ~ retargeting, data = customer_data)
## 
## Quantile = 2.3554
## 95% family-wise confidence level
##  
## 
## Linear Hypotheses:
##                                                Estimate  lwr       upr      
## generic retargeting - no retargeting == 0        88.3220 -159.3887  336.0327
## dynamic retargeting - no retargeting == 0       793.9687  553.0494 1034.8880
## dynamic retargeting - generic retargeting == 0  705.6467  454.5468  956.7465</code></pre>
<div class="sourceCode" id="cb854"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb854-1"><a href="r-markdown-assignments.html#cb854-1"></a><span class="co"># The mar parameter changes the margins around</span></span>
<span id="cb854-2"><a href="r-markdown-assignments.html#cb854-2"></a><span class="co"># created plots. This is done so the labels on the</span></span>
<span id="cb854-3"><a href="r-markdown-assignments.html#cb854-3"></a><span class="co"># side of the Tukey plot are visible (however, this</span></span>
<span id="cb854-4"><a href="r-markdown-assignments.html#cb854-4"></a><span class="co"># was not expected).</span></span>
<span id="cb854-5"><a href="r-markdown-assignments.html#cb854-5"></a><span class="kw">par</span>(<span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">20</span>, <span class="dv">4</span>, <span class="dv">2</span>))</span>
<span id="cb854-6"><a href="r-markdown-assignments.html#cb854-6"></a><span class="kw">plot</span>(tukeys)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-495-1.png" width="672" /></p>
<p>It is clearly visible that just the CIs of generic retargetring vs. no retargeting cross the 0 bound, which further indicates that the differences in means are statistically not significantly different from 0.</p>
<p>From a reporting standpoint we can say that revenue is higher when using dynamic retargeting vs. no retargeting or generic retargeting, but there is no significant difference between the sales for products in the dynamic retargeting vs. no retargeting conditions. Managerially, this means that only dynamic retargetting helps us to increase sales.</p>
<p><strong>Question 2</strong></p>
<p>For this question we want to examine whether customer ranks are significantly different for different types of advertising. Because we are dealing with data on an ordinal scale, we can not use ANOVA for this type of question. The non-parametric counterpart is the Kruskal-Wallis test, which tests for differences in medians between groups. Hence, the null hypothesis is that the medians are equal in each group and the alternative hypothesis is that there is a difference between at least one pair of groups in terms of the median.</p>
<p><span class="math display">\[H_0: \bar{\mu}_1 =  \bar{\mu}_2 = \bar{\mu}_3 \]</span>
<span class="math display">\[H_1: \textrm{The meadians are not all equal} \]</span>
Or, alternatively</p>
<p><span class="math display">\[H_1: \exists {i,j}: {\bar \mu_i \ne \bar \mu_j} \]</span></p>
<p>A good way to visualize ordinal data is through a boxplot.</p>
<div class="sourceCode" id="cb855"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb855-1"><a href="r-markdown-assignments.html#cb855-1"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> customer_data, <span class="kw">aes</span>(<span class="dt">x =</span> retargeting, <span class="dt">y =</span> rank)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb855-2"><a href="r-markdown-assignments.html#cb855-2"></a><span class="st">    </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Rank&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-496-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The boxplot seems to indicate that the medians are unequal. At least for dynamic retargeting our customer ranks seem to be lower than the ones of no retargeting or generic retargeting.</p>
<p>The only assumption that we require for this test is that the dependent variable is at least ordinal, which is fulfilled for customer ranks. Hence we can move on to performing the test in R.</p>
<div class="sourceCode" id="cb856"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb856-1"><a href="r-markdown-assignments.html#cb856-1"></a><span class="co"># ordinal data so we use a non-parametric test</span></span>
<span id="cb856-2"><a href="r-markdown-assignments.html#cb856-2"></a><span class="kw">kruskal.test</span>(rank <span class="op">~</span><span class="st"> </span>retargeting, <span class="dt">data =</span> customer_data)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  rank by retargeting
## Kruskal-Wallis chi-squared = 54.163, df = 2, p-value =
## 0.000000000001732</code></pre>
<p>The p-value is below any sensible signifcance level and thus we reject the null hypothesis of equal medians. This means that the median rank of customers is different for different types of retargeting, implying that the type of retargeting has an effect on the customer rank.</p>
<p>To further see which of the medians are unequal we perform the Nemenyi post hoc test, which can be found in the <code>PCMCR</code> package in R. The null hypothesis is that the pairwise medians are equal, while the alternative hypothesis is that the pairwise medians are unequal.</p>
<div class="sourceCode" id="cb858"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb858-1"><a href="r-markdown-assignments.html#cb858-1"></a><span class="kw">library</span>(PMCMR)</span>
<span id="cb858-2"><a href="r-markdown-assignments.html#cb858-2"></a><span class="kw">posthoc.kruskal.nemenyi.test</span>(<span class="dt">x =</span> customer_data<span class="op">$</span>rank, </span>
<span id="cb858-3"><a href="r-markdown-assignments.html#cb858-3"></a>    <span class="dt">g =</span> customer_data<span class="op">$</span>retargeting, <span class="dt">dist =</span> <span class="st">&quot;Tukey&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using Tukey and Kramer (Nemenyi) test  
##                    with Tukey-Dist approximation for independent samples 
## 
## data:  customer_data$rank and customer_data$retargeting 
## 
##                     no retargeting generic retargeting
## generic retargeting 0.67           -                  
## dynamic retargeting 0.000000000022 0.000000030987     
## 
## P value adjustment method: none</code></pre>
<p>Similar to question 1 we can see that there seems to be no difference in (median) customer ranks of no retargeting vs. generic retargeting. On the other side ranks of dynamic retargeting seem to be significantly different from both no retargeting and generic retargeting. This implies that just dynamic retargeting leads to different customer ranks.</p>
<p><strong>Question 3</strong></p>
<p>To find out whether our conversion rate differs between our female and male customers, we can use a test for proportions instead of a test for mean differences. To test for the equality of proportions (and therefore no difference between them) we can use a <span class="math inline">\(\chi^2\)</span> test.</p>
<p>Our null hypothesis in this case states that the proportions of conversion are equal for females and males. Our alternative hypothesis states that these proportions are unequal.</p>
<p><span class="math display">\[H_0: \pi_1 = \pi_2 \\ H_1: \pi_1 \neq \pi_2\]</span></p>
<p>First let´s create a summary plot to get a feeling for the data.</p>
<div class="sourceCode" id="cb860"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb860-1"><a href="r-markdown-assignments.html#cb860-1"></a><span class="co">#conditional relative frequencies</span></span>
<span id="cb860-2"><a href="r-markdown-assignments.html#cb860-2"></a>rel_freq_table &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">prop.table</span>(<span class="kw">table</span>(customer_data<span class="op">$</span>gender, customer_data<span class="op">$</span>conversion), <span class="dv">1</span>))</span>
<span id="cb860-3"><a href="r-markdown-assignments.html#cb860-3"></a><span class="kw">names</span>(rel_freq_table) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;gender&quot;</span>, <span class="st">&quot;conversion&quot;</span>,<span class="st">&quot;freq&quot;</span>) <span class="co"># changing names of the columns</span></span>
<span id="cb860-4"><a href="r-markdown-assignments.html#cb860-4"></a>rel_freq_table</span></code></pre></div>
<pre><code>##   gender    conversion      freq
## 1 female    conversion 0.3851351
## 2   male    conversion 0.1283784
## 3 female no conversion 0.6148649
## 4   male no conversion 0.8716216</code></pre>
<div class="sourceCode" id="cb862"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb862-1"><a href="r-markdown-assignments.html#cb862-1"></a><span class="kw">ggplot</span>(rel_freq_table, <span class="kw">aes</span>(<span class="dt">x =</span> gender, <span class="dt">y =</span> freq, <span class="dt">fill =</span> conversion)) <span class="op">+</span><span class="st"> </span><span class="co">#plot data</span></span>
<span id="cb862-2"><a href="r-markdown-assignments.html#cb862-2"></a><span class="st">  </span><span class="kw">geom_col</span>(<span class="dt">width =</span> <span class="fl">.7</span>) <span class="op">+</span><span class="st"> </span><span class="co">#position</span></span>
<span id="cb862-3"><a href="r-markdown-assignments.html#cb862-3"></a><span class="st">  </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">label =</span> <span class="kw">paste0</span>(<span class="kw">round</span>(freq<span class="op">*</span><span class="dv">100</span>,<span class="dv">0</span>),<span class="st">&quot;%&quot;</span>)), <span class="dt">position =</span> <span class="kw">position_stack</span>(<span class="dt">vjust =</span> <span class="fl">0.5</span>), <span class="dt">size =</span> <span class="dv">4</span>) <span class="op">+</span><span class="st"> </span><span class="co">#add percentages</span></span>
<span id="cb862-4"><a href="r-markdown-assignments.html#cb862-4"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Proportion of conversions&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;gender&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="co"># specify axis labels</span></span>
<span id="cb862-5"><a href="r-markdown-assignments.html#cb862-5"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/question_3_1-1.png" width="672" /></p>
<p>We see that our conversion seems to be better for our female customers, but let´s check whether these proportions are significantly different.</p>
<div class="sourceCode" id="cb863"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb863-1"><a href="r-markdown-assignments.html#cb863-1"></a>n1 &lt;-<span class="st"> </span><span class="kw">nrow</span>(<span class="kw">subset</span>(customer_data, gender <span class="op">==</span><span class="st"> &quot;female&quot;</span>))  <span class="co">#number of observations for females</span></span>
<span id="cb863-2"><a href="r-markdown-assignments.html#cb863-2"></a>n2 &lt;-<span class="st"> </span><span class="kw">nrow</span>(<span class="kw">subset</span>(customer_data, gender <span class="op">==</span><span class="st"> &quot;male&quot;</span>))  <span class="co">#number of observations for males</span></span>
<span id="cb863-3"><a href="r-markdown-assignments.html#cb863-3"></a>n1_conv &lt;-<span class="st"> </span><span class="kw">nrow</span>(<span class="kw">subset</span>(customer_data, gender <span class="op">==</span><span class="st"> &quot;female&quot;</span> <span class="op">&amp;</span><span class="st"> </span></span>
<span id="cb863-4"><a href="r-markdown-assignments.html#cb863-4"></a><span class="st">    </span>conversion <span class="op">==</span><span class="st"> &quot;conversion&quot;</span>))  <span class="co">#number of conversions for females</span></span>
<span id="cb863-5"><a href="r-markdown-assignments.html#cb863-5"></a>n2_conv &lt;-<span class="st"> </span><span class="kw">nrow</span>(<span class="kw">subset</span>(customer_data, gender <span class="op">==</span><span class="st"> &quot;male&quot;</span> <span class="op">&amp;</span><span class="st"> </span></span>
<span id="cb863-6"><a href="r-markdown-assignments.html#cb863-6"></a><span class="st">    </span>conversion <span class="op">==</span><span class="st"> &quot;conversion&quot;</span>))  <span class="co">#number of conversions for males</span></span>
<span id="cb863-7"><a href="r-markdown-assignments.html#cb863-7"></a></span>
<span id="cb863-8"><a href="r-markdown-assignments.html#cb863-8"></a><span class="kw">prop.test</span>(<span class="dt">x =</span> <span class="kw">c</span>(n1_conv, n2_conv), <span class="dt">n =</span> <span class="kw">c</span>(n1, n2), <span class="dt">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  c(n1_conv, n2_conv) out of c(n1, n2)
## X-squared = 24.236, df = 1, p-value = 0.0000008523
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  0.1548639 0.3586496
## sample estimates:
##    prop 1    prop 2 
## 0.3851351 0.1283784</code></pre>
<p>The test showed that the conversion rate for females was 26% higher compared to male customers. This difference is highly significant <span class="math inline">\(\chi^2\)</span> (1) = 24.2, p &lt; .05 (95% CI = [0.16,0.36]), which means that we can reject our null hypothesis of equal probability and state that there indeed is a difference between our male and female customers respective their conversion rate.</p>
</div>
<div id="solution-assignment-4" class="section level2">
<h2><span class="header-section-number">9.4</span> Solution assignment 4</h2>
<p>As a marketing manager of a consumer electronics company, you are assigned the task to analyze the relative influence of different marketing activities. Specifically, you are supposed to analyse the effects of (1) TV advertising, (2) online advertising, and (3) radio advertising on the sales of fitness trackers (wristbands). Your data set consists of sales of the product in different markets (each line represents one market) from the past year, along with the advertising budgets for the product in each of those markets for three different media: TV, online, and radio.</p>
<p>The following variables are available to you:</p>
<ul>
<li>Sales (in thousands of units)</li>
<li>TV advertising budget (in thousands of Euros)</li>
<li>Online advertising budget (in thousands of Euros)</li>
<li>Radio advertising budget (in thousands of Euros)</li>
</ul>
<p>Please conduct the following analyses:</p>
<ol style="list-style-type: decimal">
<li>Formally state the regression equation, which you will use to determine the relative influence of the marketing activities on sales.</li>
<li>Describe the model variables using appropriate statistics and plots</li>
<li>Estimate a multiple linear regression model to determine the relative influence of each of the variables. Before you interpret the results, test if the model assumptions are fulfilled and use appropriate tests and plots to test the assumptions.</li>
<li>Interpret the model results:</li>
</ol>
<ul>
<li>Which variables have a significant influence on sales and what is the interpretation of the coefficients?</li>
<li>What is the relative importance of the predictor variables?</li>
<li>Interpret the F-test</li>
<li>How do you judge the fit of the model? Please also visualize the model fit using an appropriate graph.</li>
</ul>
<ol start="5" style="list-style-type: decimal">
<li>What sales quantity would you predict based on your model for a product when the marketing activities are planned as follows: TV: 150 thsd. €, Online: 26 thsd. €, Radio: 15 thsd. €? Please provide the equation you used to make the prediction.</li>
</ol>
<p>When you are done with your analysis, click on “Knit to HTML” button above the code editor. This will create a HTML document of your results in the folder where the “assignment4.Rmd” file is stored. Open this file in your Internet browser to see if the output is correct. If the output is correct, submit the HTML file via Learn@WU. The file name should be “assignment4_studendID_name.html”.</p>
<p><strong>Load data</strong></p>
<div class="sourceCode" id="cb865"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb865-1"><a href="r-markdown-assignments.html#cb865-1"></a>sales_data &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;https://raw.githubusercontent.com/IMSMWU/MRDA2018/master/data/assignment4.dat&quot;</span>, </span>
<span id="cb865-2"><a href="r-markdown-assignments.html#cb865-2"></a>    <span class="dt">sep =</span> <span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>, <span class="dt">header =</span> <span class="ot">TRUE</span>)  <span class="co">#read in data</span></span>
<span id="cb865-3"><a href="r-markdown-assignments.html#cb865-3"></a>sales_data<span class="op">$</span>market_id &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(sales_data)</span>
<span id="cb865-4"><a href="r-markdown-assignments.html#cb865-4"></a><span class="kw">head</span>(sales_data)</span></code></pre></div>
<pre><code>##   tv_adspend online_adspend radio_adspend sales market_id
## 1       68.6           10.3            24   8.6         1
## 2      136.6           29.0            40  15.8         2
## 3       14.5           44.3            25  11.8         3
## 4      214.6           26.2            40  17.1         4
## 5      285.0           13.9            31  17.4         5
## 6      139.6           74.9            24  24.4         6</code></pre>
<div class="sourceCode" id="cb867"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb867-1"><a href="r-markdown-assignments.html#cb867-1"></a><span class="kw">str</span>(sales_data)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    236 obs. of  5 variables:
##  $ tv_adspend    : num  68.6 136.6 14.5 214.6 285 ...
##  $ online_adspend: num  10.3 29 44.3 26.2 13.9 74.9 31.1 14.1 24.5 13.9 ...
##  $ radio_adspend : int  24 40 25 40 31 24 12 9 38 18 ...
##  $ sales         : num  8.6 15.8 11.8 17.1 17.4 24.4 19.5 4.7 20.7 19.5 ...
##  $ market_id     : int  1 2 3 4 5 6 7 8 9 10 ...</code></pre>
<p><strong>Question 1</strong></p>
<p>In a first step, we specify the regression equation. In this case, sales is the dependent variable which is regressed on the different types of advertising expenditures that represent the independent variables. Thus, the regression equation is:</p>
<p><span class="math display">\[Sales=\beta_0 + \beta_1 * tv\_adspend + \beta_2 * online\_adspend + \beta_3 * radio\_adspend + \epsilon\]</span></p>
<p><strong>Question 2</strong></p>
<p>The descriptive statistics can be checked using the <code>describe()</code> function:</p>
<div class="sourceCode" id="cb869"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb869-1"><a href="r-markdown-assignments.html#cb869-1"></a><span class="kw">library</span>(psych)</span>
<span id="cb869-2"><a href="r-markdown-assignments.html#cb869-2"></a>psych<span class="op">::</span><span class="kw">describe</span>(sales_data)</span></code></pre></div>
<pre><code>##                vars   n   mean    sd median trimmed    mad min   max range skew
## tv_adspend        1 236 148.65 89.77 141.85  147.45 117.27 1.1 299.6 298.5 0.12
## online_adspend    2 236  25.61 14.33  24.35   24.70  14.53 1.6  74.9  73.3 0.61
## radio_adspend     3 236  27.70 12.57  27.00   27.36  13.34 2.0  63.0  61.0 0.22
## sales             4 236  14.83  5.40  14.15   14.72   5.93 1.4  29.0  27.6 0.16
## market_id         5 236 118.50 68.27 118.50  118.50  87.47 1.0 236.0 235.0 0.00
##                kurtosis   se
## tv_adspend        -1.26 5.84
## online_adspend     0.08 0.93
## radio_adspend     -0.53 0.82
## sales             -0.57 0.35
## market_id         -1.22 4.44</code></pre>
<p>Since we have continuous variables, we use scatterplots to investigate the relationship between sales and each of the predictor variables.</p>
<div class="sourceCode" id="cb871"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb871-1"><a href="r-markdown-assignments.html#cb871-1"></a><span class="kw">library</span>(ggplot2)</span>
<span id="cb871-2"><a href="r-markdown-assignments.html#cb871-2"></a><span class="kw">ggplot</span>(sales_data, <span class="kw">aes</span>(<span class="dt">x =</span> tv_adspend, <span class="dt">y =</span> sales)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb871-3"><a href="r-markdown-assignments.html#cb871-3"></a><span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>, </span>
<span id="cb871-4"><a href="r-markdown-assignments.html#cb871-4"></a>    <span class="dt">alpha =</span> <span class="fl">0.1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-502-1.png" width="672" /></p>
<div class="sourceCode" id="cb872"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb872-1"><a href="r-markdown-assignments.html#cb872-1"></a><span class="kw">ggplot</span>(sales_data, <span class="kw">aes</span>(<span class="dt">x =</span> online_adspend, <span class="dt">y =</span> sales)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb872-2"><a href="r-markdown-assignments.html#cb872-2"></a><span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>, </span>
<span id="cb872-3"><a href="r-markdown-assignments.html#cb872-3"></a>    <span class="dt">alpha =</span> <span class="fl">0.1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-502-2.png" width="672" /></p>
<div class="sourceCode" id="cb873"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb873-1"><a href="r-markdown-assignments.html#cb873-1"></a><span class="kw">ggplot</span>(sales_data, <span class="kw">aes</span>(<span class="dt">x =</span> radio_adspend, <span class="dt">y =</span> sales)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb873-2"><a href="r-markdown-assignments.html#cb873-2"></a><span class="st">    </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.1</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb873-3"><a href="r-markdown-assignments.html#cb873-3"></a><span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-502-3.png" width="672" /></p>
<p>The plots including the fitted lines from a simple linear model already suggest that there might be a positive linear relationship between sales and TV- and online-advertising. However, there does not appear to be a strong relationship between sales and radio advertising.</p>
<p><strong>Question 3</strong></p>
<p>The estimate the model, we will use the <code>lm()</code> function:</p>
<div class="sourceCode" id="cb874"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb874-1"><a href="r-markdown-assignments.html#cb874-1"></a>linear_model &lt;-<span class="st"> </span><span class="kw">lm</span>(sales <span class="op">~</span><span class="st"> </span>tv_adspend <span class="op">+</span><span class="st"> </span>online_adspend <span class="op">+</span><span class="st"> </span></span>
<span id="cb874-2"><a href="r-markdown-assignments.html#cb874-2"></a><span class="st">    </span>radio_adspend, <span class="dt">data =</span> sales_data)</span></code></pre></div>
<p>Before we can inspect the results, we need to test if there might be potential problems with our model specification.</p>
<p><em>Outliers</em></p>
<p>The check for outliers, we extract the studentized residuals from our model and test if there are any absolute values larger than 3.</p>
<div class="sourceCode" id="cb875"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb875-1"><a href="r-markdown-assignments.html#cb875-1"></a>sales_data<span class="op">$</span>stud_resid &lt;-<span class="st"> </span><span class="kw">rstudent</span>(linear_model)</span>
<span id="cb875-2"><a href="r-markdown-assignments.html#cb875-2"></a><span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(sales_data), sales_data<span class="op">$</span>stud_resid, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">3.3</span>, </span>
<span id="cb875-3"><a href="r-markdown-assignments.html#cb875-3"></a>    <span class="fl">3.3</span>))  <span class="co">#create scatterplot </span></span>
<span id="cb875-4"><a href="r-markdown-assignments.html#cb875-4"></a><span class="kw">abline</span>(<span class="dt">h =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>), <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">lty =</span> <span class="dv">2</span>)  <span class="co">#add reference lines</span></span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-504-1.png" width="672" /></p>
<p>Since there are no residuals with absolute values larger than 3, we conclude that there are no severe outliers.</p>
<p><em>Influencial observations</em></p>
<p>To test for influential observations, we use Cook’s Distance. You may use the following two plots to verify if any Cook’s Distance values are larger than the cutoff of 1.</p>
<div class="sourceCode" id="cb876"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb876-1"><a href="r-markdown-assignments.html#cb876-1"></a><span class="kw">plot</span>(linear_model, <span class="dv">4</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-505-1.png" width="672" /></p>
<div class="sourceCode" id="cb877"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb877-1"><a href="r-markdown-assignments.html#cb877-1"></a><span class="kw">plot</span>(linear_model, <span class="dv">5</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-505-2.png" width="672" /></p>
<p>Since all values are well below the cutoff, we conclude that influential observations are not a problem in our model.</p>
<p><em>Non-linear relationships</em></p>
<p>Next, we test if a linear specification appears feasible. You could test this using the added variable plots:</p>
<div class="sourceCode" id="cb878"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb878-1"><a href="r-markdown-assignments.html#cb878-1"></a><span class="kw">library</span>(car)</span>
<span id="cb878-2"><a href="r-markdown-assignments.html#cb878-2"></a><span class="kw">avPlots</span>(linear_model)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-506-1.png" width="672" /></p>
<p>The plots suggest that the linear specification is appropriate. In addition, you could also use the residuals plot to see if the linear specification is appropriate. The red line is a smoothed curve through the residuals plot and if it deviates from the dashed grey horizontal line a lot, this would suggest that a linear specification is not appropriate.</p>
<div class="sourceCode" id="cb879"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb879-1"><a href="r-markdown-assignments.html#cb879-1"></a><span class="kw">plot</span>(linear_model, <span class="dv">1</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-507-1.png" width="672" /></p>
<p>In this example, the red line is close to the dashed grey line, so the linear specification appears reasonable.</p>
<p><em>Heteroscedasticity</em></p>
<p>Next, we test if the residual variance is approximately the same at all levels of the predicted outcome variables (i.e., homoscedasticity). To do this, we use the residuals plot again.</p>
<div class="sourceCode" id="cb880"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb880-1"><a href="r-markdown-assignments.html#cb880-1"></a><span class="kw">plot</span>(linear_model, <span class="dv">1</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-508-1.png" width="672" /></p>
<p>The spread of residuals at different levels of the predicted outcome does not appear to be very different. Thus, we can conclude that heteroscedasticity is unlikely to be a problem. We can also confirm this conclusion by using the Breusch-Pagan test, which shows an insignificant results, meaning that we cannot reject the Null Hypothesis of equal variances.</p>
<div class="sourceCode" id="cb881"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb881-1"><a href="r-markdown-assignments.html#cb881-1"></a><span class="kw">library</span>(lmtest)</span>
<span id="cb881-2"><a href="r-markdown-assignments.html#cb881-2"></a><span class="kw">bptest</span>(linear_model)</span></code></pre></div>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  linear_model
## BP = 1.7583, df = 3, p-value = 0.6241</code></pre>
<p><em>Non-normally distributed errors</em></p>
<p>Next, we test if the residuals are approximately normally distributed using the Q-Q plot from the output:</p>
<div class="sourceCode" id="cb883"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb883-1"><a href="r-markdown-assignments.html#cb883-1"></a><span class="kw">plot</span>(linear_model, <span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-510-1.png" width="672" /></p>
<p>The Q-Q plot does not suggest a severe deviation from a normal distribution. This could also be validated using the Shapiro test:</p>
<div class="sourceCode" id="cb884"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb884-1"><a href="r-markdown-assignments.html#cb884-1"></a><span class="kw">shapiro.test</span>(<span class="kw">resid</span>(linear_model))</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resid(linear_model)
## W = 0.99412, p-value = 0.4875</code></pre>
<p><em>Correlation of errors</em></p>
<p>We actually wouldn’t need to test this assumption here since there is not natural order in the data.</p>
<p><em>Multicollinearity</em></p>
<p>To test for linear dependence of the regressors, we first test the bivariate correlations for any extremely high correlations (i.e., &gt;0.8).</p>
<div class="sourceCode" id="cb886"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb886-1"><a href="r-markdown-assignments.html#cb886-1"></a><span class="kw">library</span>(<span class="st">&quot;Hmisc&quot;</span>)</span>
<span id="cb886-2"><a href="r-markdown-assignments.html#cb886-2"></a><span class="kw">rcorr</span>(<span class="kw">as.matrix</span>(sales_data[, <span class="kw">c</span>(<span class="st">&quot;tv_adspend&quot;</span>, <span class="st">&quot;online_adspend&quot;</span>, </span>
<span id="cb886-3"><a href="r-markdown-assignments.html#cb886-3"></a>    <span class="st">&quot;radio_adspend&quot;</span>)]))</span></code></pre></div>
<pre><code>##                tv_adspend online_adspend radio_adspend
## tv_adspend           1.00           0.05          0.03
## online_adspend       0.05           1.00         -0.07
## radio_adspend        0.03          -0.07          1.00
## 
## n= 236 
## 
## 
## P
##                tv_adspend online_adspend radio_adspend
## tv_adspend                0.4127         0.6735       
## online_adspend 0.4127                    0.2790       
## radio_adspend  0.6735     0.2790</code></pre>
<p>The results show that the bivariate correlations are rather low. This can also be shown in a plot:</p>
<div class="sourceCode" id="cb888"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb888-1"><a href="r-markdown-assignments.html#cb888-1"></a><span class="kw">plot</span>(sales_data[, <span class="kw">c</span>(<span class="st">&quot;tv_adspend&quot;</span>, <span class="st">&quot;online_adspend&quot;</span>, </span>
<span id="cb888-2"><a href="r-markdown-assignments.html#cb888-2"></a>    <span class="st">&quot;radio_adspend&quot;</span>)])</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-513-1.png" width="672" /></p>
<p>In a next step, we compute the variance inflation factor for each predictor variable. The values should be close to 1 and values larger than 4 indicate potential problems with the linear dependence of regressors.</p>
<div class="sourceCode" id="cb889"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb889-1"><a href="r-markdown-assignments.html#cb889-1"></a><span class="kw">library</span>(car)</span>
<span id="cb889-2"><a href="r-markdown-assignments.html#cb889-2"></a><span class="kw">vif</span>(linear_model)</span></code></pre></div>
<pre><code>##     tv_adspend online_adspend  radio_adspend 
##       1.003873       1.008157       1.006028</code></pre>
<p>Here, all vif values are well below the cutoff, indicating that there are no problems with multicollinearity.</p>
<p><strong>Question 4</strong></p>
<p>In a next step, we will investigate the results from the model using the <code>summary()</code> function.</p>
<div class="sourceCode" id="cb891"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb891-1"><a href="r-markdown-assignments.html#cb891-1"></a><span class="kw">summary</span>(linear_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sales ~ tv_adspend + online_adspend + radio_adspend, 
##     data = sales_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.1113 -1.4161 -0.0656  1.3233  5.5198 
## 
## Coefficients:
##                 Estimate Std. Error t value             Pr(&gt;|t|)    
## (Intercept)     3.604140   0.460057   7.834    0.000000000000169 ***
## tv_adspend      0.045480   0.001491  30.508 &lt; 0.0000000000000002 ***
## online_adspend  0.186859   0.009359  19.965 &lt; 0.0000000000000002 ***
## radio_adspend  -0.011469   0.010656  -1.076                0.283    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.048 on 232 degrees of freedom
## Multiple R-squared:  0.8582, Adjusted R-squared:  0.8564 
## F-statistic: 468.1 on 3 and 232 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>For each of the individual predictors, we test the following hypothesis:</p>
<p><span class="math display">\[H_0: \beta_k=0\]</span>
<span class="math display">\[H_1: \beta_k\ne0\]</span></p>
<p>where k denotes the number of the regression coefficient. In the present example, we reject the null hypothesis for the first two predictors, where we observe a significant effect (i.e., p &lt; 0.05 for “tv_adspend” and “online_adspend”). However, we fail to reject the null for the “radio_adspend” variable (i.e., the effect is insignificant).</p>
<p>The interpretation of the coefficients is as follows:</p>
<ul>
<li>tv_adspend (β<sub>1</sub>): when tv advertising expenditures increase by 1 Euro, sales will increase by 0.045 units</li>
<li>online_adspend (β<sub>2</sub>): when online advertising expenditures increase by 1 Euro, sales will increase by 0.187 units</li>
<li>radio_adspend (β<sub>3</sub>): when radio advertising expenditures increase by 1 Euro, sales will increase by -0.011 units</li>
</ul>
<p>You should always provide a measure of uncertainty that is associated with the estimates. You could compute the confidence intervals around the coefficients using the <code>confint()</code> function.</p>
<div class="sourceCode" id="cb893"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb893-1"><a href="r-markdown-assignments.html#cb893-1"></a><span class="kw">confint</span>(linear_model)</span></code></pre></div>
<pre><code>##                      2.5 %     97.5 %
## (Intercept)     2.69771633 4.51056393
## tv_adspend      0.04254244 0.04841668
## online_adspend  0.16841843 0.20529924
## radio_adspend  -0.03246402 0.00952540</code></pre>
<p>The results show that, for example, with a 95% probability the effect of online advertising will be between 0.172 and 0.211.</p>
<p>Although the variables are measured on the same scale, you should still test the relative influence by inspecting the standardized coefficients that express the effects in terms of standard deviations.</p>
<div class="sourceCode" id="cb895"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb895-1"><a href="r-markdown-assignments.html#cb895-1"></a><span class="kw">library</span>(lm.beta)</span>
<span id="cb895-2"><a href="r-markdown-assignments.html#cb895-2"></a><span class="kw">lm.beta</span>(linear_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sales ~ tv_adspend + online_adspend + radio_adspend, 
##     data = sales_data)
## 
## Standardized Coefficients::
##    (Intercept)     tv_adspend online_adspend  radio_adspend 
##     0.00000000     0.75566632     0.49556807    -0.02668878</code></pre>
<p>Here, we conclude that tv advertising has the largest ROI followed by online advertising and radio advertising.</p>
<p>Another significance test is the F-test. It tests the null hypothesis:</p>
<p><span class="math display">\[H_0: R^2=0\]</span></p>
<p>This is equivalent to the following null hypothesis:</p>
<p><span class="math display">\[H_0: \beta_1=\beta_2=\beta_3=\beta_k=0\]</span></p>
<p>The result of the test is provided in the output above (“F-statistic: 363.7 on 3 and 236 DF, p-value: &lt; 2.2e-16”). Since the p-value is smaller than 0.05, we reject the null hypothesis that all coefficients are zero.</p>
<p>Regarding the model fit, the R<sup>2</sup> statistic tells us that approximately 82% of the variance can be explained by the model. This can be visualized as follows:</p>
<div class="sourceCode" id="cb897"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb897-1"><a href="r-markdown-assignments.html#cb897-1"></a>sales_data<span class="op">$</span>yhat &lt;-<span class="st"> </span><span class="kw">predict</span>(linear_model)</span>
<span id="cb897-2"><a href="r-markdown-assignments.html#cb897-2"></a><span class="kw">ggplot</span>(sales_data,<span class="kw">aes</span>(yhat,sales)) <span class="op">+</span><span class="st">  </span></span>
<span id="cb897-3"><a href="r-markdown-assignments.html#cb897-3"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size=</span><span class="dv">2</span>,<span class="dt">shape=</span><span class="dv">1</span>) <span class="op">+</span><span class="st">  </span><span class="co">#Use hollow circles</span></span>
<span id="cb897-4"><a href="r-markdown-assignments.html#cb897-4"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">name=</span><span class="st">&quot;predicted values&quot;</span>) <span class="op">+</span></span>
<span id="cb897-5"><a href="r-markdown-assignments.html#cb897-5"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">name=</span><span class="st">&quot;observed values&quot;</span>) <span class="op">+</span></span>
<span id="cb897-6"><a href="r-markdown-assignments.html#cb897-6"></a><span class="st">  </span><span class="kw">geom_abline</span>(<span class="dt">intercept =</span> <span class="dv">0</span>, <span class="dt">slope =</span> <span class="dv">1</span>) <span class="op">+</span></span>
<span id="cb897-7"><a href="r-markdown-assignments.html#cb897-7"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-518-1.png" width="672" /></p>
<p>Of course, you could have also used the functions included in the ggstatsplot package to report the results from your regression model.</p>
<div class="sourceCode" id="cb898"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb898-1"><a href="r-markdown-assignments.html#cb898-1"></a><span class="kw">library</span>(ggstatsplot)</span>
<span id="cb898-2"><a href="r-markdown-assignments.html#cb898-2"></a><span class="kw">options</span>(<span class="dt">scipen =</span> <span class="dv">0</span>)</span>
<span id="cb898-3"><a href="r-markdown-assignments.html#cb898-3"></a><span class="co"># specify_decimal_p(0.00000000004, k = 3L, p.value</span></span>
<span id="cb898-4"><a href="r-markdown-assignments.html#cb898-4"></a><span class="co"># = TRUE)</span></span>
<span id="cb898-5"><a href="r-markdown-assignments.html#cb898-5"></a><span class="kw">ggcoefstats</span>(<span class="dt">x =</span> linear_model, <span class="dt">k =</span> <span class="dv">15</span>, <span class="dt">title =</span> <span class="st">&quot;Sales predicted by adspend, airplay, &amp; starpower&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-519-1.png" width="672" /></p>
<p><strong>Question 5</strong></p>
<p>Finally, we can predict the outcome for the given marketing mix using the following equation:</p>
<p><span class="math display">\[\hat{sales}= 0.045*150 + 0.192*26 + 0.007*15 = 14.623\]</span></p>
<div class="sourceCode" id="cb899"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb899-1"><a href="r-markdown-assignments.html#cb899-1"></a><span class="kw">summary</span>(linear_model)<span class="op">$</span>coefficients[<span class="dv">1</span>, <span class="dv">1</span>] <span class="op">+</span><span class="st"> </span><span class="kw">summary</span>(linear_model)<span class="op">$</span>coefficients[<span class="dv">2</span>, </span>
<span id="cb899-2"><a href="r-markdown-assignments.html#cb899-2"></a>    <span class="dv">1</span>] <span class="op">*</span><span class="st"> </span><span class="dv">150</span> <span class="op">+</span><span class="st"> </span><span class="kw">summary</span>(linear_model)<span class="op">$</span>coefficients[<span class="dv">3</span>, </span>
<span id="cb899-3"><a href="r-markdown-assignments.html#cb899-3"></a>    <span class="dv">1</span>] <span class="op">*</span><span class="st"> </span><span class="dv">26</span> <span class="op">+</span><span class="st"> </span><span class="kw">summary</span>(linear_model)<span class="op">$</span>coefficients[<span class="dv">4</span>, </span>
<span id="cb899-4"><a href="r-markdown-assignments.html#cb899-4"></a>    <span class="dv">1</span>] <span class="op">*</span><span class="st"> </span><span class="dv">15</span></span></code></pre></div>
<pre><code>## [1] 15.11236</code></pre>
<p>This means that given the planned marketing mix, we would expect to sell around 15,112 units (recall that the variables are measured in thousands of units).</p>

<p><link rel="stylesheet" type="text/css" media="all" href="style.css" /></p>
</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="exploratory-factor-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="survey-design-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
